ALTER TABLE T_CHARACTERISTIC_DESCRIPT_CODE	ADD DOC_CZ NVARCHAR2(100);
ALTER TABLE T_CHARACTERISTIC_DESCRIPT_CODE	ADD DOC_DE NVARCHAR2(100);
ALTER TABLE T_CHARACTERISTIC_DESCRIPT_CODE	ADD DOC_HU NVARCHAR2(100);
ALTER TABLE T_CHARACTERISTIC_DESCRIPT_CODE	ADD DOC_RUE NVARCHAR2(100);
	
	
ALTER TABLE T_COMMERCIAL_SERVICE_CODE	ADD DOC_CZ NVARCHAR2(100);
ALTER TABLE T_COMMERCIAL_SERVICE_CODE	ADD DOC_DE NVARCHAR2(100);
ALTER TABLE T_COMMERCIAL_SERVICE_CODE	ADD DOC_HU NVARCHAR2(100);
ALTER TABLE T_COMMERCIAL_SERVICE_CODE	ADD DOC_RUE NVARCHAR2(100);
	
	
ALTER TABLE T_FACILITY_TYPE_DESCRIPT_CODE	ADD DOC_CZ NVARCHAR2(100);
ALTER TABLE T_FACILITY_TYPE_DESCRIPT_CODE	ADD DOC_DE NVARCHAR2(100);
ALTER TABLE T_FACILITY_TYPE_DESCRIPT_CODE	ADD DOC_HU NVARCHAR2(100);
ALTER TABLE T_FACILITY_TYPE_DESCRIPT_CODE	ADD DOC_RUE NVARCHAR2(100);
	
ALTER TABLE T_INFORMATION_TO_BE_DISPLAYED	ADD DOC_CZ NVARCHAR2(100);
ALTER TABLE T_INFORMATION_TO_BE_DISPLAYED	ADD DOC_DE NVARCHAR2(100);
ALTER TABLE T_INFORMATION_TO_BE_DISPLAYED	ADD DOC_HU NVARCHAR2(100);
ALTER TABLE T_INFORMATION_TO_BE_DISPLAYED	ADD DOC_RUE NVARCHAR2(100);
	
ALTER TABLE T_INTERNAL_VEHICLE_FACILITY	ADD DOC_CZ NVARCHAR2(100);
ALTER TABLE T_INTERNAL_VEHICLE_FACILITY	ADD DOC_DE NVARCHAR2(100);
ALTER TABLE T_INTERNAL_VEHICLE_FACILITY	ADD DOC_HU NVARCHAR2(100);
ALTER TABLE T_INTERNAL_VEHICLE_FACILITY	ADD DOC_RUE NVARCHAR2(100);
	
	
ALTER TABLE T_SPECIAL_SERVICE_DESCR_CODE	ADD DOC_CZ NVARCHAR2(100);
ALTER TABLE T_SPECIAL_SERVICE_DESCR_CODE	ADD DOC_DE NVARCHAR2(100);
ALTER TABLE T_SPECIAL_SERVICE_DESCR_CODE	ADD DOC_HU NVARCHAR2(100);
ALTER TABLE T_SPECIAL_SERVICE_DESCR_CODE	ADD DOC_RUE NVARCHAR2(100);





