package sk.ditec.dao.meta;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Thu Jul 24 10:20:22 CEST 2025]
 * 
 * You should not use this class directly. It should not even be extended all references should be to CrdNenajdeneZaznamy
 */
public abstract class BaseCrdNenajdeneZaznamy extends BaseObject {
	/** Serial version */
	private static final long serialVersionUID = 1753345222773L;

	/** The Peer class */
	private static final CrdNenajdeneZaznamyPeer peer = new CrdNenajdeneZaznamyPeer();

	/** The value for the crdNenajdeneZaznamyId field */
	private Integer crdNenajdeneZaznamyId;

	/** The value for the idCrdSpracTabuliek field */
	private Integer idCrdSpracTabuliek;

	/** The value for the popis field */
	private String popis;

	/** The value for the chybovaSprava field */
	private String chybovaSprava;

	/** The value for the chyba field */
	private String chyba;

	/** The value for the varovanie field */
	private String varovanie;

	/**
	 * Get the CrdNenajdeneZaznamyId
	 * 
	 * @return Integer
	 */
	public Integer getCrdNenajdeneZaznamyId() {
		return crdNenajdeneZaznamyId;
	}

	/**
	 * Set the value of CrdNenajdeneZaznamyId
	 * 
	 * @param v
	 *            new value
	 */
	public void setCrdNenajdeneZaznamyId(Integer v) {

		if (!ObjectUtils.equals(this.crdNenajdeneZaznamyId, v)) {
			this.crdNenajdeneZaznamyId = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdCrdSpracTabuliek
	 * 
	 * @return Integer
	 */
	public Integer getIdCrdSpracTabuliek() {
		return idCrdSpracTabuliek;
	}

	/**
	 * Set the value of IdCrdSpracTabuliek
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdCrdSpracTabuliek(Integer v) {

		if (!ObjectUtils.equals(this.idCrdSpracTabuliek, v)) {
			this.idCrdSpracTabuliek = v;
			setModified(true);
		}

	}

	/**
	 * Get the Popis
	 * 
	 * @return String
	 */
	public String getPopis() {
		return popis;
	}

	/**
	 * Set the value of Popis
	 * 
	 * @param v
	 *            new value
	 */
	public void setPopis(String v) {

		if (!ObjectUtils.equals(this.popis, v)) {
			this.popis = v;
			setModified(true);
		}

	}

	/**
	 * Get the ChybovaSprava
	 * 
	 * @return String
	 */
	public String getChybovaSprava() {
		return chybovaSprava;
	}

	/**
	 * Set the value of ChybovaSprava
	 * 
	 * @param v
	 *            new value
	 */
	public void setChybovaSprava(String v) {

		if (!ObjectUtils.equals(this.chybovaSprava, v)) {
			this.chybovaSprava = v;
			setModified(true);
		}

	}

	/**
	 * Get the Chyba
	 * 
	 * @return String
	 */
	public String getChyba() {
		return chyba;
	}

	/**
	 * Set the value of Chyba
	 * 
	 * @param v
	 *            new value
	 */
	public void setChyba(String v) {

		if (!ObjectUtils.equals(this.chyba, v)) {
			this.chyba = v;
			setModified(true);
		}

	}

	/**
	 * Get the Varovanie
	 * 
	 * @return String
	 */
	public String getVarovanie() {
		return varovanie;
	}

	/**
	 * Set the value of Varovanie
	 * 
	 * @param v
	 *            new value
	 */
	public void setVarovanie(String v) {

		if (!ObjectUtils.equals(this.varovanie, v)) {
			this.varovanie = v;
			setModified(true);
		}

	}

	private static List fieldNames = null;

	/**
	 * Generate a list of field names.
	 * 
	 * @return a list of field names
	 */
	public static synchronized List getFieldNames() {
		if (fieldNames == null) {
			fieldNames = new ArrayList();
			fieldNames.add("CrdNenajdeneZaznamyId");
			fieldNames.add("IdCrdSpracTabuliek");
			fieldNames.add("Popis");
			fieldNames.add("ChybovaSprava");
			fieldNames.add("Chyba");
			fieldNames.add("Varovanie");
			fieldNames = Collections.unmodifiableList(fieldNames);
		}
		return fieldNames;
	}

	/**
	 * Retrieves a field from the object by field (Java) name passed in as a String.
	 * 
	 * @param name
	 *            field name
	 * @return value
	 */
	public Object getByName(String name) {
		if (name.equals("CrdNenajdeneZaznamyId")) {
			return getCrdNenajdeneZaznamyId();
		}
		if (name.equals("IdCrdSpracTabuliek")) {
			return getIdCrdSpracTabuliek();
		}
		if (name.equals("Popis")) {
			return getPopis();
		}
		if (name.equals("ChybovaSprava")) {
			return getChybovaSprava();
		}
		if (name.equals("Chyba")) {
			return getChyba();
		}
		if (name.equals("Varovanie")) {
			return getVarovanie();
		}
		return null;
	}

	/**
	 * Set a field in the object by field (Java) name.
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (name.equals("CrdNenajdeneZaznamyId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCrdNenajdeneZaznamyId((Integer) value);
			return true;
		}
		if (name.equals("IdCrdSpracTabuliek")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdCrdSpracTabuliek((Integer) value);
			return true;
		}
		if (name.equals("Popis")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPopis((String) value);
			return true;
		}
		if (name.equals("ChybovaSprava")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setChybovaSprava((String) value);
			return true;
		}
		if (name.equals("Chyba")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setChyba((String) value);
			return true;
		}
		if (name.equals("Varovanie")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setVarovanie((String) value);
			return true;
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by name passed in as a String. The String must be one of the static Strings defined in this Class' Peer.
	 * 
	 * @param name
	 *            peer name
	 * @return value
	 */
	public Object getByPeerName(String name) {
		if (name.equals(CrdNenajdeneZaznamyPeer.CRD_NENAJDENE_ZAZNAMY_ID)) {
			return getCrdNenajdeneZaznamyId();
		}
		if (name.equals(CrdNenajdeneZaznamyPeer.ID_CRD_SPRAC_TABULIEK)) {
			return getIdCrdSpracTabuliek();
		}
		if (name.equals(CrdNenajdeneZaznamyPeer.POPIS)) {
			return getPopis();
		}
		if (name.equals(CrdNenajdeneZaznamyPeer.CHYBOVA_SPRAVA)) {
			return getChybovaSprava();
		}
		if (name.equals(CrdNenajdeneZaznamyPeer.CHYBA)) {
			return getChyba();
		}
		if (name.equals(CrdNenajdeneZaznamyPeer.VAROVANIE)) {
			return getVarovanie();
		}
		return null;
	}

	/**
	 * Set field values by Peer Field Name
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPeerName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (CrdNenajdeneZaznamyPeer.CRD_NENAJDENE_ZAZNAMY_ID.equals(name)) {
			return setByName("CrdNenajdeneZaznamyId", value);
		}
		if (CrdNenajdeneZaznamyPeer.ID_CRD_SPRAC_TABULIEK.equals(name)) {
			return setByName("IdCrdSpracTabuliek", value);
		}
		if (CrdNenajdeneZaznamyPeer.POPIS.equals(name)) {
			return setByName("Popis", value);
		}
		if (CrdNenajdeneZaznamyPeer.CHYBOVA_SPRAVA.equals(name)) {
			return setByName("ChybovaSprava", value);
		}
		if (CrdNenajdeneZaznamyPeer.CHYBA.equals(name)) {
			return setByName("Chyba", value);
		}
		if (CrdNenajdeneZaznamyPeer.VAROVANIE.equals(name)) {
			return setByName("Varovanie", value);
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema. Zero-based.
	 * 
	 * @param pos
	 *            position in xml schema
	 * @return value
	 */
	public Object getByPosition(int pos) {
		if (pos == 0) {
			return getCrdNenajdeneZaznamyId();
		}
		if (pos == 1) {
			return getIdCrdSpracTabuliek();
		}
		if (pos == 2) {
			return getPopis();
		}
		if (pos == 3) {
			return getChybovaSprava();
		}
		if (pos == 4) {
			return getChyba();
		}
		if (pos == 5) {
			return getVarovanie();
		}
		return null;
	}

	/**
	 * Set field values by its position (zero based) in the XML schema.
	 * 
	 * @param position
	 *            The field position
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid position / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPosition(int position, Object value) throws TorqueException, IllegalArgumentException {
		if (position == 0) {
			return setByName("CrdNenajdeneZaznamyId", value);
		}
		if (position == 1) {
			return setByName("IdCrdSpracTabuliek", value);
		}
		if (position == 2) {
			return setByName("Popis", value);
		}
		if (position == 3) {
			return setByName("ChybovaSprava", value);
		}
		if (position == 4) {
			return setByName("Chyba", value);
		}
		if (position == 5) {
			return setByName("Varovanie", value);
		}
		return false;
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed.
	 * 
	 * @throws Exception
	 */
	public void save() throws Exception {
		save(CrdNenajdeneZaznamyPeer.DATABASE_NAME);
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. Note: this code is here because the method body is auto-generated
	 * conditionally and therefore needs to be in this file instead of in the super class, BaseObject.
	 * 
	 * @param dbName
	 * @throws TorqueException
	 */
	public void save(String dbName) throws TorqueException {
		Connection con = null;
		try {
			con = Transaction.begin(dbName);
			save(con);
			Transaction.commit(con);
		} catch (TorqueException e) {
			Transaction.safeRollback(con);
			throw e;
		}
	}

	/**
	 * flag to prevent endless save loop, if this object is referenced by another object which falls in this transaction.
	 */
	private boolean alreadyInSave = false;

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. This method is meant to be used as part of a transaction, otherwise
	 * use the save() method and the connection details will be handled internally
	 * 
	 * @param con
	 * @throws TorqueException
	 */
	public void save(Connection con) throws TorqueException {
		if (!alreadyInSave) {
			alreadyInSave = true;

			// If this object has been modified, then save it to the database.
			if (isModified()) {
				if (isNew()) {
					CrdNenajdeneZaznamyPeer.doInsert((CrdNenajdeneZaznamy) this, con);
					setNew(false);
				} else {
					CrdNenajdeneZaznamyPeer.doUpdate((CrdNenajdeneZaznamy) this, con);
				}
			}

			alreadyInSave = false;
		}
	}

	/**
	 * Set the PrimaryKey using ObjectKey.
	 * 
	 * @param key
	 *            crdNenajdeneZaznamyId ObjectKey
	 */
	public void setPrimaryKey(ObjectKey key)

	{
		setCrdNenajdeneZaznamyId(new Integer(((NumberKey) key).intValue()));
	}

	/**
	 * Set the PrimaryKey using a String.
	 * 
	 * @param key
	 */
	public void setPrimaryKey(String key) {
		setCrdNenajdeneZaznamyId(new Integer(key));
	}

	/**
	 * returns an id that differentiates this object from others of its class.
	 */
	public ObjectKey getPrimaryKey() {
		return SimpleKey.keyFor(getCrdNenajdeneZaznamyId());
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. It then fills all the association collections and sets the related objects to
	 * isNew=true.
	 */
	public CrdNenajdeneZaznamy copy() throws TorqueException {
		return copy(true);
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. If the parameter deepcopy is true, it then fills all the association collections and
	 * sets the related objects to isNew=true.
	 * 
	 * @param deepcopy
	 *            whether to copy the associated objects.
	 */
	public CrdNenajdeneZaznamy copy(boolean deepcopy) throws TorqueException {
		return copyInto(new CrdNenajdeneZaznamy(), deepcopy);
	}

	/**
	 * Fills the copyObj with the contents of this object. The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 */
	protected CrdNenajdeneZaznamy copyInto(CrdNenajdeneZaznamy copyObj) throws TorqueException {
		return copyInto(copyObj, true);
	}

	/**
	 * Fills the copyObj with the contents of this object. If deepcopy is true, The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 * @param deepcopy
	 *            whether the associated objects should be copied.
	 */
	protected CrdNenajdeneZaznamy copyInto(CrdNenajdeneZaznamy copyObj, boolean deepcopy) throws TorqueException {
		copyObj.setCrdNenajdeneZaznamyId(crdNenajdeneZaznamyId);
		copyObj.setIdCrdSpracTabuliek(idCrdSpracTabuliek);
		copyObj.setPopis(popis);
		copyObj.setChybovaSprava(chybovaSprava);
		copyObj.setChyba(chyba);
		copyObj.setVarovanie(varovanie);

		copyObj.setCrdNenajdeneZaznamyId((Integer) null);

		if (deepcopy) {
		}
		return copyObj;
	}

	/**
	 * returns a peer instance associated with this om. Since Peer classes are not to have any instance attributes, this method returns the same instance for all member of this
	 * class. The method could therefore be static, but this would prevent one from overriding the behavior.
	 */
	public CrdNenajdeneZaznamyPeer getPeer() {
		return peer;
	}

	/**
	 * Retrieves the TableMap object related to this Table data without compiler warnings of using getPeer().getTableMap().
	 * 
	 * @return The associated TableMap object.
	 */
	public TableMap getTableMap() throws TorqueException {
		return CrdNenajdeneZaznamyPeer.getTableMap();
	}

	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("CrdNenajdeneZaznamy:\n");
		str.append("CrdNenajdeneZaznamyId = ").append(getCrdNenajdeneZaznamyId()).append("\n");
		str.append("IdCrdSpracTabuliek = ").append(getIdCrdSpracTabuliek()).append("\n");
		str.append("Popis = ").append(getPopis()).append("\n");
		str.append("ChybovaSprava = ").append(getChybovaSprava()).append("\n");
		str.append("Chyba = ").append(getChyba()).append("\n");
		str.append("Varovanie = ").append(getVarovanie()).append("\n");
		return (str.toString());
	}
}
