package sk.ditec.dao.meta;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Thu Jul 24 10:20:22 CEST 2025]
 * 
 * You should not use this class directly. It should not even be extended all references should be to CudImportMsg
 */
public abstract class BaseCudImportMsg extends BaseObject {
	/** Serial version */
	private static final long serialVersionUID = 1753345222773L;

	/** The Peer class */
	private static final CudImportMsgPeer peer = new CudImportMsgPeer();

	/** The value for the importMsgId field */
	private Integer importMsgId;

	/** The value for the idImport field */
	private Integer idImport;

	/** The value for the idImportZmena field */
	private Integer idImportZmena;

	/** The value for the typ field */
	private String typ;

	/** The value for the msg field */
	private String msg;

	/** The value for the idTransakciaZapisane field */
	private Long idTransakciaZapisane;

	/**
	 * Get the ImportMsgId
	 * 
	 * @return Integer
	 */
	public Integer getImportMsgId() {
		return importMsgId;
	}

	/**
	 * Set the value of ImportMsgId
	 * 
	 * @param v
	 *            new value
	 */
	public void setImportMsgId(Integer v) {

		if (!ObjectUtils.equals(this.importMsgId, v)) {
			this.importMsgId = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdImport
	 * 
	 * @return Integer
	 */
	public Integer getIdImport() {
		return idImport;
	}

	/**
	 * Set the value of IdImport
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdImport(Integer v) {

		if (!ObjectUtils.equals(this.idImport, v)) {
			this.idImport = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdImportZmena
	 * 
	 * @return Integer
	 */
	public Integer getIdImportZmena() {
		return idImportZmena;
	}

	/**
	 * Set the value of IdImportZmena
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdImportZmena(Integer v) {

		if (!ObjectUtils.equals(this.idImportZmena, v)) {
			this.idImportZmena = v;
			setModified(true);
		}

	}

	/**
	 * Get the Typ
	 * 
	 * @return String
	 */
	public String getTyp() {
		return typ;
	}

	/**
	 * Set the value of Typ
	 * 
	 * @param v
	 *            new value
	 */
	public void setTyp(String v) {

		if (!ObjectUtils.equals(this.typ, v)) {
			this.typ = v;
			setModified(true);
		}

	}

	/**
	 * Get the Msg
	 * 
	 * @return String
	 */
	public String getMsg() {
		return msg;
	}

	/**
	 * Set the value of Msg
	 * 
	 * @param v
	 *            new value
	 */
	public void setMsg(String v) {

		if (!ObjectUtils.equals(this.msg, v)) {
			this.msg = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdTransakciaZapisane
	 * 
	 * @return Long
	 */
	public Long getIdTransakciaZapisane() {
		return idTransakciaZapisane;
	}

	/**
	 * Set the value of IdTransakciaZapisane
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdTransakciaZapisane(Long v) {

		if (!ObjectUtils.equals(this.idTransakciaZapisane, v)) {
			this.idTransakciaZapisane = v;
			setModified(true);
		}

	}

	private static List fieldNames = null;

	/**
	 * Generate a list of field names.
	 * 
	 * @return a list of field names
	 */
	public static synchronized List getFieldNames() {
		if (fieldNames == null) {
			fieldNames = new ArrayList();
			fieldNames.add("ImportMsgId");
			fieldNames.add("IdImport");
			fieldNames.add("IdImportZmena");
			fieldNames.add("Typ");
			fieldNames.add("Msg");
			fieldNames.add("IdTransakciaZapisane");
			fieldNames = Collections.unmodifiableList(fieldNames);
		}
		return fieldNames;
	}

	/**
	 * Retrieves a field from the object by field (Java) name passed in as a String.
	 * 
	 * @param name
	 *            field name
	 * @return value
	 */
	public Object getByName(String name) {
		if (name.equals("ImportMsgId")) {
			return getImportMsgId();
		}
		if (name.equals("IdImport")) {
			return getIdImport();
		}
		if (name.equals("IdImportZmena")) {
			return getIdImportZmena();
		}
		if (name.equals("Typ")) {
			return getTyp();
		}
		if (name.equals("Msg")) {
			return getMsg();
		}
		if (name.equals("IdTransakciaZapisane")) {
			return getIdTransakciaZapisane();
		}
		return null;
	}

	/**
	 * Set a field in the object by field (Java) name.
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (name.equals("ImportMsgId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setImportMsgId((Integer) value);
			return true;
		}
		if (name.equals("IdImport")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdImport((Integer) value);
			return true;
		}
		if (name.equals("IdImportZmena")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdImportZmena((Integer) value);
			return true;
		}
		if (name.equals("Typ")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setTyp((String) value);
			return true;
		}
		if (name.equals("Msg")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setMsg((String) value);
			return true;
		}
		if (name.equals("IdTransakciaZapisane")) {
			// Object fields can be null
			if (value != null && !Long.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdTransakciaZapisane((Long) value);
			return true;
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by name passed in as a String. The String must be one of the static Strings defined in this Class' Peer.
	 * 
	 * @param name
	 *            peer name
	 * @return value
	 */
	public Object getByPeerName(String name) {
		if (name.equals(CudImportMsgPeer.IMPORT_MSG_ID)) {
			return getImportMsgId();
		}
		if (name.equals(CudImportMsgPeer.ID_IMPORT)) {
			return getIdImport();
		}
		if (name.equals(CudImportMsgPeer.ID_IMPORT_ZMENA)) {
			return getIdImportZmena();
		}
		if (name.equals(CudImportMsgPeer.TYP)) {
			return getTyp();
		}
		if (name.equals(CudImportMsgPeer.MSG)) {
			return getMsg();
		}
		if (name.equals(CudImportMsgPeer.ID_TRANSAKCIA_ZAPISANE)) {
			return getIdTransakciaZapisane();
		}
		return null;
	}

	/**
	 * Set field values by Peer Field Name
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPeerName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (CudImportMsgPeer.IMPORT_MSG_ID.equals(name)) {
			return setByName("ImportMsgId", value);
		}
		if (CudImportMsgPeer.ID_IMPORT.equals(name)) {
			return setByName("IdImport", value);
		}
		if (CudImportMsgPeer.ID_IMPORT_ZMENA.equals(name)) {
			return setByName("IdImportZmena", value);
		}
		if (CudImportMsgPeer.TYP.equals(name)) {
			return setByName("Typ", value);
		}
		if (CudImportMsgPeer.MSG.equals(name)) {
			return setByName("Msg", value);
		}
		if (CudImportMsgPeer.ID_TRANSAKCIA_ZAPISANE.equals(name)) {
			return setByName("IdTransakciaZapisane", value);
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema. Zero-based.
	 * 
	 * @param pos
	 *            position in xml schema
	 * @return value
	 */
	public Object getByPosition(int pos) {
		if (pos == 0) {
			return getImportMsgId();
		}
		if (pos == 1) {
			return getIdImport();
		}
		if (pos == 2) {
			return getIdImportZmena();
		}
		if (pos == 3) {
			return getTyp();
		}
		if (pos == 4) {
			return getMsg();
		}
		if (pos == 5) {
			return getIdTransakciaZapisane();
		}
		return null;
	}

	/**
	 * Set field values by its position (zero based) in the XML schema.
	 * 
	 * @param position
	 *            The field position
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid position / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPosition(int position, Object value) throws TorqueException, IllegalArgumentException {
		if (position == 0) {
			return setByName("ImportMsgId", value);
		}
		if (position == 1) {
			return setByName("IdImport", value);
		}
		if (position == 2) {
			return setByName("IdImportZmena", value);
		}
		if (position == 3) {
			return setByName("Typ", value);
		}
		if (position == 4) {
			return setByName("Msg", value);
		}
		if (position == 5) {
			return setByName("IdTransakciaZapisane", value);
		}
		return false;
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed.
	 * 
	 * @throws Exception
	 */
	public void save() throws Exception {
		save(CudImportMsgPeer.DATABASE_NAME);
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. Note: this code is here because the method body is auto-generated
	 * conditionally and therefore needs to be in this file instead of in the super class, BaseObject.
	 * 
	 * @param dbName
	 * @throws TorqueException
	 */
	public void save(String dbName) throws TorqueException {
		Connection con = null;
		try {
			con = Transaction.begin(dbName);
			save(con);
			Transaction.commit(con);
		} catch (TorqueException e) {
			Transaction.safeRollback(con);
			throw e;
		}
	}

	/**
	 * flag to prevent endless save loop, if this object is referenced by another object which falls in this transaction.
	 */
	private boolean alreadyInSave = false;

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. This method is meant to be used as part of a transaction, otherwise
	 * use the save() method and the connection details will be handled internally
	 * 
	 * @param con
	 * @throws TorqueException
	 */
	public void save(Connection con) throws TorqueException {
		if (!alreadyInSave) {
			alreadyInSave = true;

			// If this object has been modified, then save it to the database.
			if (isModified()) {
				if (isNew()) {
					CudImportMsgPeer.doInsert((CudImportMsg) this, con);
					setNew(false);
				} else {
					CudImportMsgPeer.doUpdate((CudImportMsg) this, con);
				}
			}

			alreadyInSave = false;
		}
	}

	/**
	 * Set the PrimaryKey using ObjectKey.
	 * 
	 * @param key
	 *            importMsgId ObjectKey
	 */
	public void setPrimaryKey(ObjectKey key)

	{
		setImportMsgId(new Integer(((NumberKey) key).intValue()));
	}

	/**
	 * Set the PrimaryKey using a String.
	 * 
	 * @param key
	 */
	public void setPrimaryKey(String key) {
		setImportMsgId(new Integer(key));
	}

	/**
	 * returns an id that differentiates this object from others of its class.
	 */
	public ObjectKey getPrimaryKey() {
		return SimpleKey.keyFor(getImportMsgId());
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. It then fills all the association collections and sets the related objects to
	 * isNew=true.
	 */
	public CudImportMsg copy() throws TorqueException {
		return copy(true);
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. If the parameter deepcopy is true, it then fills all the association collections and
	 * sets the related objects to isNew=true.
	 * 
	 * @param deepcopy
	 *            whether to copy the associated objects.
	 */
	public CudImportMsg copy(boolean deepcopy) throws TorqueException {
		return copyInto(new CudImportMsg(), deepcopy);
	}

	/**
	 * Fills the copyObj with the contents of this object. The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 */
	protected CudImportMsg copyInto(CudImportMsg copyObj) throws TorqueException {
		return copyInto(copyObj, true);
	}

	/**
	 * Fills the copyObj with the contents of this object. If deepcopy is true, The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 * @param deepcopy
	 *            whether the associated objects should be copied.
	 */
	protected CudImportMsg copyInto(CudImportMsg copyObj, boolean deepcopy) throws TorqueException {
		copyObj.setImportMsgId(importMsgId);
		copyObj.setIdImport(idImport);
		copyObj.setIdImportZmena(idImportZmena);
		copyObj.setTyp(typ);
		copyObj.setMsg(msg);
		copyObj.setIdTransakciaZapisane(idTransakciaZapisane);

		copyObj.setImportMsgId((Integer) null);

		if (deepcopy) {
		}
		return copyObj;
	}

	/**
	 * returns a peer instance associated with this om. Since Peer classes are not to have any instance attributes, this method returns the same instance for all member of this
	 * class. The method could therefore be static, but this would prevent one from overriding the behavior.
	 */
	public CudImportMsgPeer getPeer() {
		return peer;
	}

	/**
	 * Retrieves the TableMap object related to this Table data without compiler warnings of using getPeer().getTableMap().
	 * 
	 * @return The associated TableMap object.
	 */
	public TableMap getTableMap() throws TorqueException {
		return CudImportMsgPeer.getTableMap();
	}

	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("CudImportMsg:\n");
		str.append("ImportMsgId = ").append(getImportMsgId()).append("\n");
		str.append("IdImport = ").append(getIdImport()).append("\n");
		str.append("IdImportZmena = ").append(getIdImportZmena()).append("\n");
		str.append("Typ = ").append(getTyp()).append("\n");
		str.append("Msg = ").append(getMsg()).append("\n");
		str.append("IdTransakciaZapisane = ").append(getIdTransakciaZapisane()).append("\n");
		return (str.toString());
	}
}
