package sk.ditec.dao.meta;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Thu Jul 24 10:20:22 CEST 2025]
 * 
 * You should not use this class directly. It should not even be extended all references should be to CudImportZmena
 */
public abstract class BaseCudImportZmena extends BaseObject {
	/** Serial version */
	private static final long serialVersionUID = 1753345222773L;

	/** The Peer class */
	private static final CudImportZmenaPeer peer = new CudImportZmenaPeer();

	/** The value for the importZmenaId field */
	private Integer importZmenaId;

	/** The value for the idImport field */
	private Integer idImport;

	/** The value for the rowId field */
	private Integer rowId;

	/** The value for the xlsRowId field */
	private Integer xlsRowId;

	/** The value for the operacia field */
	private String operacia;

	/** The value for the platnostOd field */
	private Date platnostOd;

	/** The value for the casSchvaleniaGr field */
	private Date casSchvaleniaGr;

	/** The value for the poznamka field */
	private String poznamka;

	/** The value for the spracovany field */
	private String spracovany;

	/** The value for the obnova field */
	private String obnova;

	/** The value for the idTransakciaZapisane field */
	private Long idTransakciaZapisane;

	/**
	 * Get the ImportZmenaId
	 * 
	 * @return Integer
	 */
	public Integer getImportZmenaId() {
		return importZmenaId;
	}

	/**
	 * Set the value of ImportZmenaId
	 * 
	 * @param v
	 *            new value
	 */
	public void setImportZmenaId(Integer v) {

		if (!ObjectUtils.equals(this.importZmenaId, v)) {
			this.importZmenaId = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdImport
	 * 
	 * @return Integer
	 */
	public Integer getIdImport() {
		return idImport;
	}

	/**
	 * Set the value of IdImport
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdImport(Integer v) {

		if (!ObjectUtils.equals(this.idImport, v)) {
			this.idImport = v;
			setModified(true);
		}

	}

	/**
	 * Get the RowId
	 * 
	 * @return Integer
	 */
	public Integer getRowId() {
		return rowId;
	}

	/**
	 * Set the value of RowId
	 * 
	 * @param v
	 *            new value
	 */
	public void setRowId(Integer v) {

		if (!ObjectUtils.equals(this.rowId, v)) {
			this.rowId = v;
			setModified(true);
		}

	}

	/**
	 * Get the XlsRowId
	 * 
	 * @return Integer
	 */
	public Integer getXlsRowId() {
		return xlsRowId;
	}

	/**
	 * Set the value of XlsRowId
	 * 
	 * @param v
	 *            new value
	 */
	public void setXlsRowId(Integer v) {

		if (!ObjectUtils.equals(this.xlsRowId, v)) {
			this.xlsRowId = v;
			setModified(true);
		}

	}

	/**
	 * Get the Operacia
	 * 
	 * @return String
	 */
	public String getOperacia() {
		return operacia;
	}

	/**
	 * Set the value of Operacia
	 * 
	 * @param v
	 *            new value
	 */
	public void setOperacia(String v) {

		if (!ObjectUtils.equals(this.operacia, v)) {
			this.operacia = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostOd
	 * 
	 * @return Date
	 */
	public Date getPlatnostOd() {
		return platnostOd;
	}

	/**
	 * Set the value of PlatnostOd
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostOd(Date v) {

		if (!ObjectUtils.equals(this.platnostOd, v)) {
			this.platnostOd = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasSchvaleniaGr
	 * 
	 * @return Date
	 */
	public Date getCasSchvaleniaGr() {
		return casSchvaleniaGr;
	}

	/**
	 * Set the value of CasSchvaleniaGr
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasSchvaleniaGr(Date v) {

		if (!ObjectUtils.equals(this.casSchvaleniaGr, v)) {
			this.casSchvaleniaGr = v;
			setModified(true);
		}

	}

	/**
	 * Get the Poznamka
	 * 
	 * @return String
	 */
	public String getPoznamka() {
		return poznamka;
	}

	/**
	 * Set the value of Poznamka
	 * 
	 * @param v
	 *            new value
	 */
	public void setPoznamka(String v) {

		if (!ObjectUtils.equals(this.poznamka, v)) {
			this.poznamka = v;
			setModified(true);
		}

	}

	/**
	 * Get the Spracovany
	 * 
	 * @return String
	 */
	public String getSpracovany() {
		return spracovany;
	}

	/**
	 * Set the value of Spracovany
	 * 
	 * @param v
	 *            new value
	 */
	public void setSpracovany(String v) {

		if (!ObjectUtils.equals(this.spracovany, v)) {
			this.spracovany = v;
			setModified(true);
		}

	}

	/**
	 * Get the Obnova
	 * 
	 * @return String
	 */
	public String getObnova() {
		return obnova;
	}

	/**
	 * Set the value of Obnova
	 * 
	 * @param v
	 *            new value
	 */
	public void setObnova(String v) {

		if (!ObjectUtils.equals(this.obnova, v)) {
			this.obnova = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdTransakciaZapisane
	 * 
	 * @return Long
	 */
	public Long getIdTransakciaZapisane() {
		return idTransakciaZapisane;
	}

	/**
	 * Set the value of IdTransakciaZapisane
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdTransakciaZapisane(Long v) {

		if (!ObjectUtils.equals(this.idTransakciaZapisane, v)) {
			this.idTransakciaZapisane = v;
			setModified(true);
		}

	}

	private static List fieldNames = null;

	/**
	 * Generate a list of field names.
	 * 
	 * @return a list of field names
	 */
	public static synchronized List getFieldNames() {
		if (fieldNames == null) {
			fieldNames = new ArrayList();
			fieldNames.add("ImportZmenaId");
			fieldNames.add("IdImport");
			fieldNames.add("RowId");
			fieldNames.add("XlsRowId");
			fieldNames.add("Operacia");
			fieldNames.add("PlatnostOd");
			fieldNames.add("CasSchvaleniaGr");
			fieldNames.add("Poznamka");
			fieldNames.add("Spracovany");
			fieldNames.add("Obnova");
			fieldNames.add("IdTransakciaZapisane");
			fieldNames = Collections.unmodifiableList(fieldNames);
		}
		return fieldNames;
	}

	/**
	 * Retrieves a field from the object by field (Java) name passed in as a String.
	 * 
	 * @param name
	 *            field name
	 * @return value
	 */
	public Object getByName(String name) {
		if (name.equals("ImportZmenaId")) {
			return getImportZmenaId();
		}
		if (name.equals("IdImport")) {
			return getIdImport();
		}
		if (name.equals("RowId")) {
			return getRowId();
		}
		if (name.equals("XlsRowId")) {
			return getXlsRowId();
		}
		if (name.equals("Operacia")) {
			return getOperacia();
		}
		if (name.equals("PlatnostOd")) {
			return getPlatnostOd();
		}
		if (name.equals("CasSchvaleniaGr")) {
			return getCasSchvaleniaGr();
		}
		if (name.equals("Poznamka")) {
			return getPoznamka();
		}
		if (name.equals("Spracovany")) {
			return getSpracovany();
		}
		if (name.equals("Obnova")) {
			return getObnova();
		}
		if (name.equals("IdTransakciaZapisane")) {
			return getIdTransakciaZapisane();
		}
		return null;
	}

	/**
	 * Set a field in the object by field (Java) name.
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (name.equals("ImportZmenaId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setImportZmenaId((Integer) value);
			return true;
		}
		if (name.equals("IdImport")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdImport((Integer) value);
			return true;
		}
		if (name.equals("RowId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setRowId((Integer) value);
			return true;
		}
		if (name.equals("XlsRowId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setXlsRowId((Integer) value);
			return true;
		}
		if (name.equals("Operacia")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setOperacia((String) value);
			return true;
		}
		if (name.equals("PlatnostOd")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostOd((Date) value);
			return true;
		}
		if (name.equals("CasSchvaleniaGr")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasSchvaleniaGr((Date) value);
			return true;
		}
		if (name.equals("Poznamka")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPoznamka((String) value);
			return true;
		}
		if (name.equals("Spracovany")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setSpracovany((String) value);
			return true;
		}
		if (name.equals("Obnova")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setObnova((String) value);
			return true;
		}
		if (name.equals("IdTransakciaZapisane")) {
			// Object fields can be null
			if (value != null && !Long.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdTransakciaZapisane((Long) value);
			return true;
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by name passed in as a String. The String must be one of the static Strings defined in this Class' Peer.
	 * 
	 * @param name
	 *            peer name
	 * @return value
	 */
	public Object getByPeerName(String name) {
		if (name.equals(CudImportZmenaPeer.IMPORT_ZMENA_ID)) {
			return getImportZmenaId();
		}
		if (name.equals(CudImportZmenaPeer.ID_IMPORT)) {
			return getIdImport();
		}
		if (name.equals(CudImportZmenaPeer.ROW_ID)) {
			return getRowId();
		}
		if (name.equals(CudImportZmenaPeer.XLS_ROW_ID)) {
			return getXlsRowId();
		}
		if (name.equals(CudImportZmenaPeer.OPERACIA)) {
			return getOperacia();
		}
		if (name.equals(CudImportZmenaPeer.PLATNOST_OD)) {
			return getPlatnostOd();
		}
		if (name.equals(CudImportZmenaPeer.CAS_SCHVALENIA_GR)) {
			return getCasSchvaleniaGr();
		}
		if (name.equals(CudImportZmenaPeer.POZNAMKA)) {
			return getPoznamka();
		}
		if (name.equals(CudImportZmenaPeer.SPRACOVANY)) {
			return getSpracovany();
		}
		if (name.equals(CudImportZmenaPeer.OBNOVA)) {
			return getObnova();
		}
		if (name.equals(CudImportZmenaPeer.ID_TRANSAKCIA_ZAPISANE)) {
			return getIdTransakciaZapisane();
		}
		return null;
	}

	/**
	 * Set field values by Peer Field Name
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPeerName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (CudImportZmenaPeer.IMPORT_ZMENA_ID.equals(name)) {
			return setByName("ImportZmenaId", value);
		}
		if (CudImportZmenaPeer.ID_IMPORT.equals(name)) {
			return setByName("IdImport", value);
		}
		if (CudImportZmenaPeer.ROW_ID.equals(name)) {
			return setByName("RowId", value);
		}
		if (CudImportZmenaPeer.XLS_ROW_ID.equals(name)) {
			return setByName("XlsRowId", value);
		}
		if (CudImportZmenaPeer.OPERACIA.equals(name)) {
			return setByName("Operacia", value);
		}
		if (CudImportZmenaPeer.PLATNOST_OD.equals(name)) {
			return setByName("PlatnostOd", value);
		}
		if (CudImportZmenaPeer.CAS_SCHVALENIA_GR.equals(name)) {
			return setByName("CasSchvaleniaGr", value);
		}
		if (CudImportZmenaPeer.POZNAMKA.equals(name)) {
			return setByName("Poznamka", value);
		}
		if (CudImportZmenaPeer.SPRACOVANY.equals(name)) {
			return setByName("Spracovany", value);
		}
		if (CudImportZmenaPeer.OBNOVA.equals(name)) {
			return setByName("Obnova", value);
		}
		if (CudImportZmenaPeer.ID_TRANSAKCIA_ZAPISANE.equals(name)) {
			return setByName("IdTransakciaZapisane", value);
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema. Zero-based.
	 * 
	 * @param pos
	 *            position in xml schema
	 * @return value
	 */
	public Object getByPosition(int pos) {
		if (pos == 0) {
			return getImportZmenaId();
		}
		if (pos == 1) {
			return getIdImport();
		}
		if (pos == 2) {
			return getRowId();
		}
		if (pos == 3) {
			return getXlsRowId();
		}
		if (pos == 4) {
			return getOperacia();
		}
		if (pos == 5) {
			return getPlatnostOd();
		}
		if (pos == 6) {
			return getCasSchvaleniaGr();
		}
		if (pos == 7) {
			return getPoznamka();
		}
		if (pos == 8) {
			return getSpracovany();
		}
		if (pos == 9) {
			return getObnova();
		}
		if (pos == 10) {
			return getIdTransakciaZapisane();
		}
		return null;
	}

	/**
	 * Set field values by its position (zero based) in the XML schema.
	 * 
	 * @param position
	 *            The field position
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid position / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPosition(int position, Object value) throws TorqueException, IllegalArgumentException {
		if (position == 0) {
			return setByName("ImportZmenaId", value);
		}
		if (position == 1) {
			return setByName("IdImport", value);
		}
		if (position == 2) {
			return setByName("RowId", value);
		}
		if (position == 3) {
			return setByName("XlsRowId", value);
		}
		if (position == 4) {
			return setByName("Operacia", value);
		}
		if (position == 5) {
			return setByName("PlatnostOd", value);
		}
		if (position == 6) {
			return setByName("CasSchvaleniaGr", value);
		}
		if (position == 7) {
			return setByName("Poznamka", value);
		}
		if (position == 8) {
			return setByName("Spracovany", value);
		}
		if (position == 9) {
			return setByName("Obnova", value);
		}
		if (position == 10) {
			return setByName("IdTransakciaZapisane", value);
		}
		return false;
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed.
	 * 
	 * @throws Exception
	 */
	public void save() throws Exception {
		save(CudImportZmenaPeer.DATABASE_NAME);
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. Note: this code is here because the method body is auto-generated
	 * conditionally and therefore needs to be in this file instead of in the super class, BaseObject.
	 * 
	 * @param dbName
	 * @throws TorqueException
	 */
	public void save(String dbName) throws TorqueException {
		Connection con = null;
		try {
			con = Transaction.begin(dbName);
			save(con);
			Transaction.commit(con);
		} catch (TorqueException e) {
			Transaction.safeRollback(con);
			throw e;
		}
	}

	/**
	 * flag to prevent endless save loop, if this object is referenced by another object which falls in this transaction.
	 */
	private boolean alreadyInSave = false;

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. This method is meant to be used as part of a transaction, otherwise
	 * use the save() method and the connection details will be handled internally
	 * 
	 * @param con
	 * @throws TorqueException
	 */
	public void save(Connection con) throws TorqueException {
		if (!alreadyInSave) {
			alreadyInSave = true;

			// If this object has been modified, then save it to the database.
			if (isModified()) {
				if (isNew()) {
					CudImportZmenaPeer.doInsert((CudImportZmena) this, con);
					setNew(false);
				} else {
					CudImportZmenaPeer.doUpdate((CudImportZmena) this, con);
				}
			}

			alreadyInSave = false;
		}
	}

	/**
	 * Set the PrimaryKey using ObjectKey.
	 * 
	 * @param key
	 *            importZmenaId ObjectKey
	 */
	public void setPrimaryKey(ObjectKey key)

	{
		setImportZmenaId(new Integer(((NumberKey) key).intValue()));
	}

	/**
	 * Set the PrimaryKey using a String.
	 * 
	 * @param key
	 */
	public void setPrimaryKey(String key) {
		setImportZmenaId(new Integer(key));
	}

	/**
	 * returns an id that differentiates this object from others of its class.
	 */
	public ObjectKey getPrimaryKey() {
		return SimpleKey.keyFor(getImportZmenaId());
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. It then fills all the association collections and sets the related objects to
	 * isNew=true.
	 */
	public CudImportZmena copy() throws TorqueException {
		return copy(true);
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. If the parameter deepcopy is true, it then fills all the association collections and
	 * sets the related objects to isNew=true.
	 * 
	 * @param deepcopy
	 *            whether to copy the associated objects.
	 */
	public CudImportZmena copy(boolean deepcopy) throws TorqueException {
		return copyInto(new CudImportZmena(), deepcopy);
	}

	/**
	 * Fills the copyObj with the contents of this object. The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 */
	protected CudImportZmena copyInto(CudImportZmena copyObj) throws TorqueException {
		return copyInto(copyObj, true);
	}

	/**
	 * Fills the copyObj with the contents of this object. If deepcopy is true, The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 * @param deepcopy
	 *            whether the associated objects should be copied.
	 */
	protected CudImportZmena copyInto(CudImportZmena copyObj, boolean deepcopy) throws TorqueException {
		copyObj.setImportZmenaId(importZmenaId);
		copyObj.setIdImport(idImport);
		copyObj.setRowId(rowId);
		copyObj.setXlsRowId(xlsRowId);
		copyObj.setOperacia(operacia);
		copyObj.setPlatnostOd(platnostOd);
		copyObj.setCasSchvaleniaGr(casSchvaleniaGr);
		copyObj.setPoznamka(poznamka);
		copyObj.setSpracovany(spracovany);
		copyObj.setObnova(obnova);
		copyObj.setIdTransakciaZapisane(idTransakciaZapisane);

		copyObj.setImportZmenaId((Integer) null);

		if (deepcopy) {
		}
		return copyObj;
	}

	/**
	 * returns a peer instance associated with this om. Since Peer classes are not to have any instance attributes, this method returns the same instance for all member of this
	 * class. The method could therefore be static, but this would prevent one from overriding the behavior.
	 */
	public CudImportZmenaPeer getPeer() {
		return peer;
	}

	/**
	 * Retrieves the TableMap object related to this Table data without compiler warnings of using getPeer().getTableMap().
	 * 
	 * @return The associated TableMap object.
	 */
	public TableMap getTableMap() throws TorqueException {
		return CudImportZmenaPeer.getTableMap();
	}

	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("CudImportZmena:\n");
		str.append("ImportZmenaId = ").append(getImportZmenaId()).append("\n");
		str.append("IdImport = ").append(getIdImport()).append("\n");
		str.append("RowId = ").append(getRowId()).append("\n");
		str.append("XlsRowId = ").append(getXlsRowId()).append("\n");
		str.append("Operacia = ").append(getOperacia()).append("\n");
		str.append("PlatnostOd = ").append(getPlatnostOd()).append("\n");
		str.append("CasSchvaleniaGr = ").append(getCasSchvaleniaGr()).append("\n");
		str.append("Poznamka = ").append(getPoznamka()).append("\n");
		str.append("Spracovany = ").append(getSpracovany()).append("\n");
		str.append("Obnova = ").append(getObnova()).append("\n");
		str.append("IdTransakciaZapisane = ").append(getIdTransakciaZapisane()).append("\n");
		return (str.toString());
	}
}
