package sk.ditec.dao.meta;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

import org.apache.torque.NoRowsException;
import org.apache.torque.TooManyRowsException;
import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.BasePeer;
import org.apache.torque.util.Criteria;

import sk.ditec.dao.meta.map.CudImportPrilohaMapBuilder;

import com.workingdogs.village.DataSetException;
import com.workingdogs.village.QueryDataSet;
import com.workingdogs.village.Record;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Thu Jul 24 10:20:22 CEST 2025]
 * 
 */
public abstract class BaseCudImportPrilohaPeer extends BasePeer {
	/** Serial version */
	private static final long serialVersionUID = 1753345222773L;

	/** the default database name for this class */
	public static final String DATABASE_NAME;

	/** the table name for this class */
	public static final String TABLE_NAME;

	/**
	 * @return the map builder for this peer
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static MapBuilder getMapBuilder() throws TorqueException {
		return getMapBuilder(CudImportPrilohaMapBuilder.CLASS_NAME);
	}

	/** the column name for the IMPORT_PRILOHA_ID field */
	public static final String IMPORT_PRILOHA_ID;
	/** the column name for the ID_IMPORT field */
	public static final String ID_IMPORT;
	/** the column name for the FILE_NAME field */
	public static final String FILE_NAME;
	/** the column name for the PRILOHA field */
	public static final String PRILOHA;
	/** the column name for the ID_TRANSAKCIA_ZAPISANE field */
	public static final String ID_TRANSAKCIA_ZAPISANE;

	static {
		DATABASE_NAME = "APP";
		TABLE_NAME = "CUD_IMPORT_PRILOHA";

		IMPORT_PRILOHA_ID = "CUD_IMPORT_PRILOHA.IMPORT_PRILOHA_ID";
		ID_IMPORT = "CUD_IMPORT_PRILOHA.ID_IMPORT";
		FILE_NAME = "CUD_IMPORT_PRILOHA.FILE_NAME";
		PRILOHA = "CUD_IMPORT_PRILOHA.PRILOHA";
		ID_TRANSAKCIA_ZAPISANE = "CUD_IMPORT_PRILOHA.ID_TRANSAKCIA_ZAPISANE";
		if (Torque.isInit()) {
			try {
				getMapBuilder(CudImportPrilohaMapBuilder.CLASS_NAME);
			} catch (Exception e) {
				log.error("Could not initialize Peer", e);
				throw new RuntimeException(e);
			}
		} else {
			Torque.registerMapBuilder(CudImportPrilohaMapBuilder.CLASS_NAME);
		}
	}

	/** number of columns for this peer */
	public static final int numColumns = 5;

	/** A class that can be returned by this peer. */
	protected static final String CLASSNAME_DEFAULT = "sk.ditec.dao.meta.CudImportPriloha";

	/** A class that can be returned by this peer. */
	protected static final Class CLASS_DEFAULT = initClass(CLASSNAME_DEFAULT);

	/**
	 * Class object initialization method.
	 * 
	 * @param className
	 *            name of the class to initialize
	 * @return the initialized class
	 */
	private static Class initClass(String className) {
		Class c = null;
		try {
			c = Class.forName(className);
		} catch (Throwable t) {
			log.error("A FATAL ERROR has occurred which should not " + "have happened under any circumstance.  Please notify " + "the Torque developers <torque-dev@db.apache.org> " + "and give as many details as possible (including the error " + "stack trace).", t);

			// Error objects should always be propogated.
			if (t instanceof Error) {
				throw (Error) t.fillInStackTrace();
			}
		}
		return c;
	}

	/**
	 * Get the list of objects for a ResultSet. Please not that your resultset MUST return columns in the right order. You can use getFieldNames() in BaseObject to get the correct
	 * sequence.
	 * 
	 * @param results
	 *            the ResultSet
	 * @return the list of objects
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static List resultSet2Objects(java.sql.ResultSet results) throws TorqueException {
		try {
			QueryDataSet qds = null;
			List rows = null;
			try {
				qds = new QueryDataSet(results);
				rows = getSelectResults(qds);
			} finally {
				if (qds != null) {
					qds.close();
				}
			}

			return populateObjects(rows);
		} catch (SQLException e) {
			throw new TorqueException(e);
		} catch (DataSetException e) {
			throw new TorqueException(e);
		}
	}

	/**
	 * Method to do inserts.
	 * 
	 * @param criteria
	 *            object used to create the INSERT statement.
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static ObjectKey doInsert(Criteria criteria) throws TorqueException {
		return BaseCudImportPrilohaPeer.doInsert(criteria, (Connection) null);
	}

	/**
	 * Method to do inserts. This method is to be used during a transaction, otherwise use the doInsert(Criteria) method. It will take care of the connection details internally.
	 * 
	 * @param criteria
	 *            object used to create the INSERT statement.
	 * @param con
	 *            the connection to use
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static ObjectKey doInsert(Criteria criteria, Connection con) throws TorqueException {
		correctBooleans(criteria);

		setDbName(criteria);

		if (con == null) {
			return BasePeer.doInsert(criteria);
		} else {
			return BasePeer.doInsert(criteria, con);
		}
	}

	/**
	 * Add all the columns needed to create a new object.
	 * 
	 * @param criteria
	 *            object containing the columns to add.
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void addSelectColumns(Criteria criteria) throws TorqueException {
		criteria.addSelectColumn(IMPORT_PRILOHA_ID);
		criteria.addSelectColumn(ID_IMPORT);
		criteria.addSelectColumn(FILE_NAME);
		criteria.addSelectColumn(PRILOHA);
		criteria.addSelectColumn(ID_TRANSAKCIA_ZAPISANE);
	}

	/**
	 * changes the boolean values in the criteria to the appropriate type, whenever a booleanchar or booleanint column is involved. This enables the user to create criteria using
	 * Boolean values for booleanchar or booleanint columns
	 * 
	 * @param criteria
	 *            the criteria in which the boolean values should be corrected
	 * @throws TorqueException
	 *             if the database map for the criteria cannot be obtained.
	 */
	public static void correctBooleans(Criteria criteria) throws TorqueException {
		correctBooleans(criteria, getTableMap());
	}

	/**
	 * Create a new object of type cls from a resultset row starting from a specified offset. This is done so that you can select other rows than just those needed for this object.
	 * You may for example want to create two objects from the same row.
	 * 
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static CudImportPriloha row2Object(Record row, int offset, Class cls) throws TorqueException {
		try {
			CudImportPriloha obj = (CudImportPriloha) cls.newInstance();
			CudImportPrilohaPeer.populateObject(row, offset, obj);
			obj.setModified(false);
			obj.setNew(false);

			return obj;
		} catch (InstantiationException e) {
			throw new TorqueException(e);
		} catch (IllegalAccessException e) {
			throw new TorqueException(e);
		}
	}

	/**
	 * Populates an object from a resultset row starting from a specified offset. This is done so that you can select other rows than just those needed for this object. You may for
	 * example want to create two objects from the same row.
	 * 
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void populateObject(Record row, int offset, CudImportPriloha obj) throws TorqueException {
		try {
			obj.setImportPrilohaId(row.getValue(offset + 0).asIntegerObj());
			obj.setIdImport(row.getValue(offset + 1).asIntegerObj());
			obj.setFileName(row.getValue(offset + 2).asString());
			obj.setPriloha(row.getValue(offset + 3).asBytes());
			obj.setIdTransakciaZapisane(row.getValue(offset + 4).asLongObj());
		} catch (DataSetException e) {
			throw new TorqueException(e);
		}
	}

	/**
	 * Method to do selects.
	 * 
	 * @param criteria
	 *            object used to create the SELECT statement.
	 * @return List of selected Objects
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static List doSelect(Criteria criteria) throws TorqueException {
		return populateObjects(doSelectVillageRecords(criteria));
	}

	/**
	 * Method to do selects within a transaction.
	 * 
	 * @param criteria
	 *            object used to create the SELECT statement.
	 * @param con
	 *            the connection to use
	 * @return List of selected Objects
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static List doSelect(Criteria criteria, Connection con) throws TorqueException {
		return populateObjects(doSelectVillageRecords(criteria, con));
	}

	/**
	 * Grabs the raw Village records to be formed into objects. This method handles connections internally. The Record objects returned by this method should be considered
	 * readonly. Do not alter the data and call save(), your results may vary, but are certainly likely to result in hard to track MT bugs.
	 * 
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static List doSelectVillageRecords(Criteria criteria) throws TorqueException {
		return BaseCudImportPrilohaPeer.doSelectVillageRecords(criteria, (Connection) null);
	}

	/**
	 * Grabs the raw Village records to be formed into objects. This method should be used for transactions
	 * 
	 * @param criteria
	 *            object used to create the SELECT statement.
	 * @param con
	 *            the connection to use
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static List doSelectVillageRecords(Criteria criteria, Connection con) throws TorqueException {
		if (criteria.getSelectColumns().size() == 0) {
			addSelectColumns(criteria);
		}
		correctBooleans(criteria);

		setDbName(criteria);

		// BasePeer returns a List of Value (Village) arrays. The array
		// order follows the order columns were placed in the Select clause.
		if (con == null) {
			return BasePeer.doSelect(criteria);
		} else {
			return BasePeer.doSelect(criteria, con);
		}
	}

	/**
	 * The returned List will contain objects of the default type or objects that inherit from the default.
	 * 
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static List populateObjects(List records) throws TorqueException {
		List results = new ArrayList(records.size());

		// populate the object(s)
		for (int i = 0; i < records.size(); i++) {
			Record row = (Record) records.get(i);
			results.add(CudImportPrilohaPeer.row2Object(row, 1, CudImportPrilohaPeer.getOMClass()));
		}
		return results;
	}

	/**
	 * The class that the Peer will make instances of. If the BO is abstract then you must implement this method in the BO.
	 * 
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static Class getOMClass() throws TorqueException {
		return CLASS_DEFAULT;
	}

	/**
	 * Method to do updates.
	 * 
	 * @param criteria
	 *            object containing data that is used to create the UPDATE statement.
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void doUpdate(Criteria criteria) throws TorqueException {
		BaseCudImportPrilohaPeer.doUpdate(criteria, (Connection) null);
	}

	/**
	 * Method to do updates. This method is to be used during a transaction, otherwise use the doUpdate(Criteria) method. It will take care of the connection details internally.
	 * 
	 * @param criteria
	 *            object containing data that is used to create the UPDATE statement.
	 * @param con
	 *            the connection to use
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void doUpdate(Criteria criteria, Connection con) throws TorqueException {
		Criteria selectCriteria = new Criteria(DATABASE_NAME, 2);
		correctBooleans(criteria);

		selectCriteria.put(IMPORT_PRILOHA_ID, criteria.remove(IMPORT_PRILOHA_ID));

		setDbName(criteria);

		if (con == null) {
			BasePeer.doUpdate(selectCriteria, criteria);
		} else {
			BasePeer.doUpdate(selectCriteria, criteria, con);
		}
	}

	/**
	 * Method to do deletes.
	 * 
	 * @param criteria
	 *            object containing data that is used DELETE from database.
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void doDelete(Criteria criteria) throws TorqueException {
		CudImportPrilohaPeer.doDelete(criteria, (Connection) null);
	}

	/**
	 * Method to do deletes. This method is to be used during a transaction, otherwise use the doDelete(Criteria) method. It will take care of the connection details internally.
	 * 
	 * @param criteria
	 *            object containing data that is used DELETE from database.
	 * @param con
	 *            the connection to use
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void doDelete(Criteria criteria, Connection con) throws TorqueException {
		correctBooleans(criteria);

		setDbName(criteria);

		if (con == null) {
			BasePeer.doDelete(criteria);
		} else {
			BasePeer.doDelete(criteria, con);
		}
	}

	/**
	 * Method to do selects
	 * 
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static List doSelect(CudImportPriloha obj) throws TorqueException {
		return doSelect(buildSelectCriteria(obj));
	}

	/**
	 * Method to do inserts
	 * 
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void doInsert(CudImportPriloha obj) throws TorqueException {
		obj.setPrimaryKey(doInsert(buildCriteria(obj)));
		obj.setNew(false);
		obj.setModified(false);
	}

	/**
	 * @param obj
	 *            the data object to update in the database.
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void doUpdate(CudImportPriloha obj) throws TorqueException {
		doUpdate(buildCriteria(obj));
		obj.setModified(false);
	}

	/**
	 * @param obj
	 *            the data object to delete in the database.
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void doDelete(CudImportPriloha obj) throws TorqueException {
		doDelete(buildSelectCriteria(obj));
	}

	/**
	 * Method to do inserts. This method is to be used during a transaction, otherwise use the doInsert(CudImportPriloha) method. It will take care of the connection details
	 * internally.
	 * 
	 * @param obj
	 *            the data object to insert into the database.
	 * @param con
	 *            the connection to use
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void doInsert(CudImportPriloha obj, Connection con) throws TorqueException {
		obj.setPrimaryKey(doInsert(buildCriteria(obj), con));
		obj.setNew(false);
		obj.setModified(false);
	}

	/**
	 * Method to do update. This method is to be used during a transaction, otherwise use the doUpdate(CudImportPriloha) method. It will take care of the connection details
	 * internally.
	 * 
	 * @param obj
	 *            the data object to update in the database.
	 * @param con
	 *            the connection to use
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void doUpdate(CudImportPriloha obj, Connection con) throws TorqueException {
		doUpdate(buildCriteria(obj), con);
		obj.setModified(false);
	}

	/**
	 * Method to delete. This method is to be used during a transaction, otherwise use the doDelete(CudImportPriloha) method. It will take care of the connection details
	 * internally.
	 * 
	 * @param obj
	 *            the data object to delete in the database.
	 * @param con
	 *            the connection to use
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void doDelete(CudImportPriloha obj, Connection con) throws TorqueException {
		doDelete(buildSelectCriteria(obj), con);
	}

	/**
	 * Method to do deletes.
	 * 
	 * @param pk
	 *            ObjectKey that is used DELETE from database.
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void doDelete(ObjectKey pk) throws TorqueException {
		BaseCudImportPrilohaPeer.doDelete(pk, (Connection) null);
	}

	/**
	 * Method to delete. This method is to be used during a transaction, otherwise use the doDelete(ObjectKey) method. It will take care of the connection details internally.
	 * 
	 * @param pk
	 *            the primary key for the object to delete in the database.
	 * @param con
	 *            the connection to use
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static void doDelete(ObjectKey pk, Connection con) throws TorqueException {
		doDelete(buildCriteria(pk), con);
	}

	/** Build a Criteria object from an ObjectKey */
	public static Criteria buildCriteria(ObjectKey pk) {
		Criteria criteria = new Criteria();
		criteria.add(IMPORT_PRILOHA_ID, pk);
		return criteria;
	}

	/** Build a Criteria object from the data object for this peer */
	public static Criteria buildCriteria(CudImportPriloha obj) {
		Criteria criteria = new Criteria(DATABASE_NAME);
		if (!obj.isNew())
			criteria.add(IMPORT_PRILOHA_ID, obj.getImportPrilohaId());
		criteria.add(ID_IMPORT, obj.getIdImport());
		criteria.add(FILE_NAME, obj.getFileName());
		criteria.add(PRILOHA, obj.getPriloha());
		criteria.add(ID_TRANSAKCIA_ZAPISANE, obj.getIdTransakciaZapisane());
		return criteria;
	}

	/** Build a Criteria object from the data object for this peer, skipping all binary columns */
	public static Criteria buildSelectCriteria(CudImportPriloha obj) {
		Criteria criteria = new Criteria(DATABASE_NAME);
		if (!obj.isNew()) {
			criteria.add(IMPORT_PRILOHA_ID, obj.getImportPrilohaId());
		}
		criteria.add(ID_IMPORT, obj.getIdImport());
		criteria.add(FILE_NAME, obj.getFileName());
		criteria.add(ID_TRANSAKCIA_ZAPISANE, obj.getIdTransakciaZapisane());
		return criteria;
	}

	/**
	 * Retrieve a single object by pk
	 * 
	 * @param pk
	 *            the primary key
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 * @throws NoRowsException
	 *             Primary key was not found in database.
	 * @throws TooManyRowsException
	 *             Primary key was not found in database.
	 */
	public static CudImportPriloha retrieveByPK(Integer pk) throws TorqueException, NoRowsException, TooManyRowsException {
		return retrieveByPK(SimpleKey.keyFor(pk));
	}

	/**
	 * Retrieve a single object by pk
	 * 
	 * @param pk
	 *            the primary key
	 * @param con
	 *            the connection to use
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 * @throws NoRowsException
	 *             Primary key was not found in database.
	 * @throws TooManyRowsException
	 *             Primary key was not found in database.
	 */
	public static CudImportPriloha retrieveByPK(Integer pk, Connection con) throws TorqueException, NoRowsException, TooManyRowsException {
		return retrieveByPK(SimpleKey.keyFor(pk), con);
	}

	/**
	 * Retrieve a single object by pk
	 * 
	 * @param pk
	 *            the primary key
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 * @throws NoRowsException
	 *             Primary key was not found in database.
	 * @throws TooManyRowsException
	 *             Primary key was not found in database.
	 */
	public static CudImportPriloha retrieveByPK(ObjectKey pk) throws TorqueException, NoRowsException, TooManyRowsException {
		Connection db = null;
		CudImportPriloha retVal = null;
		try {
			db = Torque.getConnection(DATABASE_NAME);
			retVal = retrieveByPK(pk, db);
		} finally {
			Torque.closeConnection(db);
		}
		return retVal;
	}

	/**
	 * Retrieve a single object by pk
	 * 
	 * @param pk
	 *            the primary key
	 * @param con
	 *            the connection to use
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 * @throws NoRowsException
	 *             Primary key was not found in database.
	 * @throws TooManyRowsException
	 *             Primary key was not found in database.
	 */
	public static CudImportPriloha retrieveByPK(ObjectKey pk, Connection con) throws TorqueException, NoRowsException, TooManyRowsException {
		Criteria criteria = buildCriteria(pk);
		List v = doSelect(criteria, con);
		if (v.size() == 0) {
			throw new NoRowsException("Failed to select a row.");
		} else if (v.size() > 1) {
			throw new TooManyRowsException("Failed to select only one row.");
		} else {
			return (CudImportPriloha) v.get(0);
		}
	}

	/**
	 * Retrieve a multiple objects by pk
	 * 
	 * @param pks
	 *            List of primary keys
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static List retrieveByPKs(List pks) throws TorqueException {
		Connection db = null;
		List retVal = null;
		try {
			db = Torque.getConnection(DATABASE_NAME);
			retVal = retrieveByPKs(pks, db);
		} finally {
			Torque.closeConnection(db);
		}
		return retVal;
	}

	/**
	 * Retrieve a multiple objects by pk
	 * 
	 * @param pks
	 *            List of primary keys
	 * @param dbcon
	 *            the connection to use
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static List retrieveByPKs(List pks, Connection dbcon) throws TorqueException {
		List objs = null;
		if (pks == null || pks.size() == 0) {
			objs = new LinkedList();
		} else {
			Criteria criteria = new Criteria();
			criteria.addIn(IMPORT_PRILOHA_ID, pks);
			objs = doSelect(criteria, dbcon);
		}
		return objs;
	}

	/**
	 * Returns the TableMap related to this peer.
	 * 
	 * @throws TorqueException
	 *             Any exceptions caught during processing will be rethrown wrapped into a TorqueException.
	 */
	public static TableMap getTableMap() throws TorqueException {
		return Torque.getDatabaseMap(DATABASE_NAME).getTable(TABLE_NAME);
	}

	private static void setDbName(Criteria crit) {
		// Set the correct dbName if it has not been overridden
		// crit.getDbName will return the same object if not set to
		// another value so == check is okay and faster
		if (crit.getDbName() == Torque.getDefaultDB()) {
			crit.setDbName(DATABASE_NAME);
		}
	}

}
