package sk.ditec.dao.meta;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Thu Jul 24 10:20:22 CEST 2025]
 * 
 * You should not use this class directly. It should not even be extended all references should be to CudObjektStlpec
 */
public abstract class BaseCudObjektStlpec extends BaseObject {
	/** Serial version */
	private static final long serialVersionUID = 1753345222773L;

	/** The Peer class */
	private static final CudObjektStlpecPeer peer = new CudObjektStlpecPeer();

	/** The value for the objektStlpecId field */
	private Integer objektStlpecId;

	/** The value for the idObjektCiselnik field */
	private Integer idObjektCiselnik;

	/** The value for the idCiselnikStlpec field */
	private Integer idCiselnikStlpec;

	/** The value for the zmena field */
	private String zmena;

	/** The value for the hodnota field */
	private String hodnota;

	/** The value for the casZmeny field */
	private Date casZmeny;

	/** The value for the idUcet field */
	private Integer idUcet;

	/** The value for the idTransakciaZapisane field */
	private Long idTransakciaZapisane;

	/** The value for the idTransakciaZrusene field */
	private Long idTransakciaZrusene;

	/**
	 * Get the ObjektStlpecId
	 * 
	 * @return Integer
	 */
	public Integer getObjektStlpecId() {
		return objektStlpecId;
	}

	/**
	 * Set the value of ObjektStlpecId
	 * 
	 * @param v
	 *            new value
	 */
	public void setObjektStlpecId(Integer v) {

		if (!ObjectUtils.equals(this.objektStlpecId, v)) {
			this.objektStlpecId = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdObjektCiselnik
	 * 
	 * @return Integer
	 */
	public Integer getIdObjektCiselnik() {
		return idObjektCiselnik;
	}

	/**
	 * Set the value of IdObjektCiselnik
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdObjektCiselnik(Integer v) {

		if (!ObjectUtils.equals(this.idObjektCiselnik, v)) {
			this.idObjektCiselnik = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdCiselnikStlpec
	 * 
	 * @return Integer
	 */
	public Integer getIdCiselnikStlpec() {
		return idCiselnikStlpec;
	}

	/**
	 * Set the value of IdCiselnikStlpec
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdCiselnikStlpec(Integer v) {

		if (!ObjectUtils.equals(this.idCiselnikStlpec, v)) {
			this.idCiselnikStlpec = v;
			setModified(true);
		}

	}

	/**
	 * Get the Zmena
	 * 
	 * @return String
	 */
	public String getZmena() {
		return zmena;
	}

	/**
	 * Set the value of Zmena
	 * 
	 * @param v
	 *            new value
	 */
	public void setZmena(String v) {

		if (!ObjectUtils.equals(this.zmena, v)) {
			this.zmena = v;
			setModified(true);
		}

	}

	/**
	 * Get the Hodnota
	 * 
	 * @return String
	 */
	public String getHodnota() {
		return hodnota;
	}

	/**
	 * Set the value of Hodnota
	 * 
	 * @param v
	 *            new value
	 */
	public void setHodnota(String v) {

		if (!ObjectUtils.equals(this.hodnota, v)) {
			this.hodnota = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasZmeny
	 * 
	 * @return Date
	 */
	public Date getCasZmeny() {
		return casZmeny;
	}

	/**
	 * Set the value of CasZmeny
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasZmeny(Date v) {

		if (!ObjectUtils.equals(this.casZmeny, v)) {
			this.casZmeny = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdUcet
	 * 
	 * @return Integer
	 */
	public Integer getIdUcet() {
		return idUcet;
	}

	/**
	 * Set the value of IdUcet
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdUcet(Integer v) {

		if (!ObjectUtils.equals(this.idUcet, v)) {
			this.idUcet = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdTransakciaZapisane
	 * 
	 * @return Long
	 */
	public Long getIdTransakciaZapisane() {
		return idTransakciaZapisane;
	}

	/**
	 * Set the value of IdTransakciaZapisane
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdTransakciaZapisane(Long v) {

		if (!ObjectUtils.equals(this.idTransakciaZapisane, v)) {
			this.idTransakciaZapisane = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdTransakciaZrusene
	 * 
	 * @return Long
	 */
	public Long getIdTransakciaZrusene() {
		return idTransakciaZrusene;
	}

	/**
	 * Set the value of IdTransakciaZrusene
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdTransakciaZrusene(Long v) {

		if (!ObjectUtils.equals(this.idTransakciaZrusene, v)) {
			this.idTransakciaZrusene = v;
			setModified(true);
		}

	}

	private static List fieldNames = null;

	/**
	 * Generate a list of field names.
	 * 
	 * @return a list of field names
	 */
	public static synchronized List getFieldNames() {
		if (fieldNames == null) {
			fieldNames = new ArrayList();
			fieldNames.add("ObjektStlpecId");
			fieldNames.add("IdObjektCiselnik");
			fieldNames.add("IdCiselnikStlpec");
			fieldNames.add("Zmena");
			fieldNames.add("Hodnota");
			fieldNames.add("CasZmeny");
			fieldNames.add("IdUcet");
			fieldNames.add("IdTransakciaZapisane");
			fieldNames.add("IdTransakciaZrusene");
			fieldNames = Collections.unmodifiableList(fieldNames);
		}
		return fieldNames;
	}

	/**
	 * Retrieves a field from the object by field (Java) name passed in as a String.
	 * 
	 * @param name
	 *            field name
	 * @return value
	 */
	public Object getByName(String name) {
		if (name.equals("ObjektStlpecId")) {
			return getObjektStlpecId();
		}
		if (name.equals("IdObjektCiselnik")) {
			return getIdObjektCiselnik();
		}
		if (name.equals("IdCiselnikStlpec")) {
			return getIdCiselnikStlpec();
		}
		if (name.equals("Zmena")) {
			return getZmena();
		}
		if (name.equals("Hodnota")) {
			return getHodnota();
		}
		if (name.equals("CasZmeny")) {
			return getCasZmeny();
		}
		if (name.equals("IdUcet")) {
			return getIdUcet();
		}
		if (name.equals("IdTransakciaZapisane")) {
			return getIdTransakciaZapisane();
		}
		if (name.equals("IdTransakciaZrusene")) {
			return getIdTransakciaZrusene();
		}
		return null;
	}

	/**
	 * Set a field in the object by field (Java) name.
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (name.equals("ObjektStlpecId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setObjektStlpecId((Integer) value);
			return true;
		}
		if (name.equals("IdObjektCiselnik")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdObjektCiselnik((Integer) value);
			return true;
		}
		if (name.equals("IdCiselnikStlpec")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdCiselnikStlpec((Integer) value);
			return true;
		}
		if (name.equals("Zmena")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setZmena((String) value);
			return true;
		}
		if (name.equals("Hodnota")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHodnota((String) value);
			return true;
		}
		if (name.equals("CasZmeny")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasZmeny((Date) value);
			return true;
		}
		if (name.equals("IdUcet")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdUcet((Integer) value);
			return true;
		}
		if (name.equals("IdTransakciaZapisane")) {
			// Object fields can be null
			if (value != null && !Long.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdTransakciaZapisane((Long) value);
			return true;
		}
		if (name.equals("IdTransakciaZrusene")) {
			// Object fields can be null
			if (value != null && !Long.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdTransakciaZrusene((Long) value);
			return true;
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by name passed in as a String. The String must be one of the static Strings defined in this Class' Peer.
	 * 
	 * @param name
	 *            peer name
	 * @return value
	 */
	public Object getByPeerName(String name) {
		if (name.equals(CudObjektStlpecPeer.OBJEKT_STLPEC_ID)) {
			return getObjektStlpecId();
		}
		if (name.equals(CudObjektStlpecPeer.ID_OBJEKT_CISELNIK)) {
			return getIdObjektCiselnik();
		}
		if (name.equals(CudObjektStlpecPeer.ID_CISELNIK_STLPEC)) {
			return getIdCiselnikStlpec();
		}
		if (name.equals(CudObjektStlpecPeer.ZMENA)) {
			return getZmena();
		}
		if (name.equals(CudObjektStlpecPeer.HODNOTA)) {
			return getHodnota();
		}
		if (name.equals(CudObjektStlpecPeer.CAS_ZMENY)) {
			return getCasZmeny();
		}
		if (name.equals(CudObjektStlpecPeer.ID_UCET)) {
			return getIdUcet();
		}
		if (name.equals(CudObjektStlpecPeer.ID_TRANSAKCIA_ZAPISANE)) {
			return getIdTransakciaZapisane();
		}
		if (name.equals(CudObjektStlpecPeer.ID_TRANSAKCIA_ZRUSENE)) {
			return getIdTransakciaZrusene();
		}
		return null;
	}

	/**
	 * Set field values by Peer Field Name
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPeerName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (CudObjektStlpecPeer.OBJEKT_STLPEC_ID.equals(name)) {
			return setByName("ObjektStlpecId", value);
		}
		if (CudObjektStlpecPeer.ID_OBJEKT_CISELNIK.equals(name)) {
			return setByName("IdObjektCiselnik", value);
		}
		if (CudObjektStlpecPeer.ID_CISELNIK_STLPEC.equals(name)) {
			return setByName("IdCiselnikStlpec", value);
		}
		if (CudObjektStlpecPeer.ZMENA.equals(name)) {
			return setByName("Zmena", value);
		}
		if (CudObjektStlpecPeer.HODNOTA.equals(name)) {
			return setByName("Hodnota", value);
		}
		if (CudObjektStlpecPeer.CAS_ZMENY.equals(name)) {
			return setByName("CasZmeny", value);
		}
		if (CudObjektStlpecPeer.ID_UCET.equals(name)) {
			return setByName("IdUcet", value);
		}
		if (CudObjektStlpecPeer.ID_TRANSAKCIA_ZAPISANE.equals(name)) {
			return setByName("IdTransakciaZapisane", value);
		}
		if (CudObjektStlpecPeer.ID_TRANSAKCIA_ZRUSENE.equals(name)) {
			return setByName("IdTransakciaZrusene", value);
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema. Zero-based.
	 * 
	 * @param pos
	 *            position in xml schema
	 * @return value
	 */
	public Object getByPosition(int pos) {
		if (pos == 0) {
			return getObjektStlpecId();
		}
		if (pos == 1) {
			return getIdObjektCiselnik();
		}
		if (pos == 2) {
			return getIdCiselnikStlpec();
		}
		if (pos == 3) {
			return getZmena();
		}
		if (pos == 4) {
			return getHodnota();
		}
		if (pos == 5) {
			return getCasZmeny();
		}
		if (pos == 6) {
			return getIdUcet();
		}
		if (pos == 7) {
			return getIdTransakciaZapisane();
		}
		if (pos == 8) {
			return getIdTransakciaZrusene();
		}
		return null;
	}

	/**
	 * Set field values by its position (zero based) in the XML schema.
	 * 
	 * @param position
	 *            The field position
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid position / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPosition(int position, Object value) throws TorqueException, IllegalArgumentException {
		if (position == 0) {
			return setByName("ObjektStlpecId", value);
		}
		if (position == 1) {
			return setByName("IdObjektCiselnik", value);
		}
		if (position == 2) {
			return setByName("IdCiselnikStlpec", value);
		}
		if (position == 3) {
			return setByName("Zmena", value);
		}
		if (position == 4) {
			return setByName("Hodnota", value);
		}
		if (position == 5) {
			return setByName("CasZmeny", value);
		}
		if (position == 6) {
			return setByName("IdUcet", value);
		}
		if (position == 7) {
			return setByName("IdTransakciaZapisane", value);
		}
		if (position == 8) {
			return setByName("IdTransakciaZrusene", value);
		}
		return false;
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed.
	 * 
	 * @throws Exception
	 */
	public void save() throws Exception {
		save(CudObjektStlpecPeer.DATABASE_NAME);
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. Note: this code is here because the method body is auto-generated
	 * conditionally and therefore needs to be in this file instead of in the super class, BaseObject.
	 * 
	 * @param dbName
	 * @throws TorqueException
	 */
	public void save(String dbName) throws TorqueException {
		Connection con = null;
		try {
			con = Transaction.begin(dbName);
			save(con);
			Transaction.commit(con);
		} catch (TorqueException e) {
			Transaction.safeRollback(con);
			throw e;
		}
	}

	/**
	 * flag to prevent endless save loop, if this object is referenced by another object which falls in this transaction.
	 */
	private boolean alreadyInSave = false;

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. This method is meant to be used as part of a transaction, otherwise
	 * use the save() method and the connection details will be handled internally
	 * 
	 * @param con
	 * @throws TorqueException
	 */
	public void save(Connection con) throws TorqueException {
		if (!alreadyInSave) {
			alreadyInSave = true;

			// If this object has been modified, then save it to the database.
			if (isModified()) {
				if (isNew()) {
					CudObjektStlpecPeer.doInsert((CudObjektStlpec) this, con);
					setNew(false);
				} else {
					CudObjektStlpecPeer.doUpdate((CudObjektStlpec) this, con);
				}
			}

			alreadyInSave = false;
		}
	}

	/**
	 * Set the PrimaryKey using ObjectKey.
	 * 
	 * @param key
	 *            objektStlpecId ObjectKey
	 */
	public void setPrimaryKey(ObjectKey key)

	{
		setObjektStlpecId(new Integer(((NumberKey) key).intValue()));
	}

	/**
	 * Set the PrimaryKey using a String.
	 * 
	 * @param key
	 */
	public void setPrimaryKey(String key) {
		setObjektStlpecId(new Integer(key));
	}

	/**
	 * returns an id that differentiates this object from others of its class.
	 */
	public ObjectKey getPrimaryKey() {
		return SimpleKey.keyFor(getObjektStlpecId());
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. It then fills all the association collections and sets the related objects to
	 * isNew=true.
	 */
	public CudObjektStlpec copy() throws TorqueException {
		return copy(true);
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. If the parameter deepcopy is true, it then fills all the association collections and
	 * sets the related objects to isNew=true.
	 * 
	 * @param deepcopy
	 *            whether to copy the associated objects.
	 */
	public CudObjektStlpec copy(boolean deepcopy) throws TorqueException {
		return copyInto(new CudObjektStlpec(), deepcopy);
	}

	/**
	 * Fills the copyObj with the contents of this object. The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 */
	protected CudObjektStlpec copyInto(CudObjektStlpec copyObj) throws TorqueException {
		return copyInto(copyObj, true);
	}

	/**
	 * Fills the copyObj with the contents of this object. If deepcopy is true, The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 * @param deepcopy
	 *            whether the associated objects should be copied.
	 */
	protected CudObjektStlpec copyInto(CudObjektStlpec copyObj, boolean deepcopy) throws TorqueException {
		copyObj.setObjektStlpecId(objektStlpecId);
		copyObj.setIdObjektCiselnik(idObjektCiselnik);
		copyObj.setIdCiselnikStlpec(idCiselnikStlpec);
		copyObj.setZmena(zmena);
		copyObj.setHodnota(hodnota);
		copyObj.setCasZmeny(casZmeny);
		copyObj.setIdUcet(idUcet);
		copyObj.setIdTransakciaZapisane(idTransakciaZapisane);
		copyObj.setIdTransakciaZrusene(idTransakciaZrusene);

		copyObj.setObjektStlpecId((Integer) null);

		if (deepcopy) {
		}
		return copyObj;
	}

	/**
	 * returns a peer instance associated with this om. Since Peer classes are not to have any instance attributes, this method returns the same instance for all member of this
	 * class. The method could therefore be static, but this would prevent one from overriding the behavior.
	 */
	public CudObjektStlpecPeer getPeer() {
		return peer;
	}

	/**
	 * Retrieves the TableMap object related to this Table data without compiler warnings of using getPeer().getTableMap().
	 * 
	 * @return The associated TableMap object.
	 */
	public TableMap getTableMap() throws TorqueException {
		return CudObjektStlpecPeer.getTableMap();
	}

	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("CudObjektStlpec:\n");
		str.append("ObjektStlpecId = ").append(getObjektStlpecId()).append("\n");
		str.append("IdObjektCiselnik = ").append(getIdObjektCiselnik()).append("\n");
		str.append("IdCiselnikStlpec = ").append(getIdCiselnikStlpec()).append("\n");
		str.append("Zmena = ").append(getZmena()).append("\n");
		str.append("Hodnota = ").append(getHodnota()).append("\n");
		str.append("CasZmeny = ").append(getCasZmeny()).append("\n");
		str.append("IdUcet = ").append(getIdUcet()).append("\n");
		str.append("IdTransakciaZapisane = ").append(getIdTransakciaZapisane()).append("\n");
		str.append("IdTransakciaZrusene = ").append(getIdTransakciaZrusene()).append("\n");
		return (str.toString());
	}
}
