package sk.ditec.dao.meta;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Thu Jul 24 10:20:22 CEST 2025]
 * 
 * You should not use this class directly. It should not even be extended all references should be to CudPrekladStlpec
 */
public abstract class BaseCudPrekladStlpec extends BaseObject {
	/** Serial version */
	private static final long serialVersionUID = 1753345222773L;

	/** The Peer class */
	private static final CudPrekladStlpecPeer peer = new CudPrekladStlpecPeer();

	/** The value for the prekladStlpecId field */
	private Integer prekladStlpecId;

	/** The value for the idPrekladTabulka field */
	private Integer idPrekladTabulka;

	/** The value for the nazovDb field */
	private String nazovDb;

	/** The value for the nadpis field */
	private String nadpis;

	/** The value for the idTransakciaZapisane field */
	private Long idTransakciaZapisane;

	/**
	 * Get the PrekladStlpecId
	 * 
	 * @return Integer
	 */
	public Integer getPrekladStlpecId() {
		return prekladStlpecId;
	}

	/**
	 * Set the value of PrekladStlpecId
	 * 
	 * @param v
	 *            new value
	 */
	public void setPrekladStlpecId(Integer v) {

		if (!ObjectUtils.equals(this.prekladStlpecId, v)) {
			this.prekladStlpecId = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdPrekladTabulka
	 * 
	 * @return Integer
	 */
	public Integer getIdPrekladTabulka() {
		return idPrekladTabulka;
	}

	/**
	 * Set the value of IdPrekladTabulka
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdPrekladTabulka(Integer v) {

		if (!ObjectUtils.equals(this.idPrekladTabulka, v)) {
			this.idPrekladTabulka = v;
			setModified(true);
		}

	}

	/**
	 * Get the NazovDb
	 * 
	 * @return String
	 */
	public String getNazovDb() {
		return nazovDb;
	}

	/**
	 * Set the value of NazovDb
	 * 
	 * @param v
	 *            new value
	 */
	public void setNazovDb(String v) {

		if (!ObjectUtils.equals(this.nazovDb, v)) {
			this.nazovDb = v;
			setModified(true);
		}

	}

	/**
	 * Get the Nadpis
	 * 
	 * @return String
	 */
	public String getNadpis() {
		return nadpis;
	}

	/**
	 * Set the value of Nadpis
	 * 
	 * @param v
	 *            new value
	 */
	public void setNadpis(String v) {

		if (!ObjectUtils.equals(this.nadpis, v)) {
			this.nadpis = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdTransakciaZapisane
	 * 
	 * @return Long
	 */
	public Long getIdTransakciaZapisane() {
		return idTransakciaZapisane;
	}

	/**
	 * Set the value of IdTransakciaZapisane
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdTransakciaZapisane(Long v) {

		if (!ObjectUtils.equals(this.idTransakciaZapisane, v)) {
			this.idTransakciaZapisane = v;
			setModified(true);
		}

	}

	private static List fieldNames = null;

	/**
	 * Generate a list of field names.
	 * 
	 * @return a list of field names
	 */
	public static synchronized List getFieldNames() {
		if (fieldNames == null) {
			fieldNames = new ArrayList();
			fieldNames.add("PrekladStlpecId");
			fieldNames.add("IdPrekladTabulka");
			fieldNames.add("NazovDb");
			fieldNames.add("Nadpis");
			fieldNames.add("IdTransakciaZapisane");
			fieldNames = Collections.unmodifiableList(fieldNames);
		}
		return fieldNames;
	}

	/**
	 * Retrieves a field from the object by field (Java) name passed in as a String.
	 * 
	 * @param name
	 *            field name
	 * @return value
	 */
	public Object getByName(String name) {
		if (name.equals("PrekladStlpecId")) {
			return getPrekladStlpecId();
		}
		if (name.equals("IdPrekladTabulka")) {
			return getIdPrekladTabulka();
		}
		if (name.equals("NazovDb")) {
			return getNazovDb();
		}
		if (name.equals("Nadpis")) {
			return getNadpis();
		}
		if (name.equals("IdTransakciaZapisane")) {
			return getIdTransakciaZapisane();
		}
		return null;
	}

	/**
	 * Set a field in the object by field (Java) name.
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (name.equals("PrekladStlpecId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPrekladStlpecId((Integer) value);
			return true;
		}
		if (name.equals("IdPrekladTabulka")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdPrekladTabulka((Integer) value);
			return true;
		}
		if (name.equals("NazovDb")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setNazovDb((String) value);
			return true;
		}
		if (name.equals("Nadpis")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setNadpis((String) value);
			return true;
		}
		if (name.equals("IdTransakciaZapisane")) {
			// Object fields can be null
			if (value != null && !Long.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdTransakciaZapisane((Long) value);
			return true;
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by name passed in as a String. The String must be one of the static Strings defined in this Class' Peer.
	 * 
	 * @param name
	 *            peer name
	 * @return value
	 */
	public Object getByPeerName(String name) {
		if (name.equals(CudPrekladStlpecPeer.PREKLAD_STLPEC_ID)) {
			return getPrekladStlpecId();
		}
		if (name.equals(CudPrekladStlpecPeer.ID_PREKLAD_TABULKA)) {
			return getIdPrekladTabulka();
		}
		if (name.equals(CudPrekladStlpecPeer.NAZOV_DB)) {
			return getNazovDb();
		}
		if (name.equals(CudPrekladStlpecPeer.NADPIS)) {
			return getNadpis();
		}
		if (name.equals(CudPrekladStlpecPeer.ID_TRANSAKCIA_ZAPISANE)) {
			return getIdTransakciaZapisane();
		}
		return null;
	}

	/**
	 * Set field values by Peer Field Name
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPeerName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (CudPrekladStlpecPeer.PREKLAD_STLPEC_ID.equals(name)) {
			return setByName("PrekladStlpecId", value);
		}
		if (CudPrekladStlpecPeer.ID_PREKLAD_TABULKA.equals(name)) {
			return setByName("IdPrekladTabulka", value);
		}
		if (CudPrekladStlpecPeer.NAZOV_DB.equals(name)) {
			return setByName("NazovDb", value);
		}
		if (CudPrekladStlpecPeer.NADPIS.equals(name)) {
			return setByName("Nadpis", value);
		}
		if (CudPrekladStlpecPeer.ID_TRANSAKCIA_ZAPISANE.equals(name)) {
			return setByName("IdTransakciaZapisane", value);
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema. Zero-based.
	 * 
	 * @param pos
	 *            position in xml schema
	 * @return value
	 */
	public Object getByPosition(int pos) {
		if (pos == 0) {
			return getPrekladStlpecId();
		}
		if (pos == 1) {
			return getIdPrekladTabulka();
		}
		if (pos == 2) {
			return getNazovDb();
		}
		if (pos == 3) {
			return getNadpis();
		}
		if (pos == 4) {
			return getIdTransakciaZapisane();
		}
		return null;
	}

	/**
	 * Set field values by its position (zero based) in the XML schema.
	 * 
	 * @param position
	 *            The field position
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid position / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPosition(int position, Object value) throws TorqueException, IllegalArgumentException {
		if (position == 0) {
			return setByName("PrekladStlpecId", value);
		}
		if (position == 1) {
			return setByName("IdPrekladTabulka", value);
		}
		if (position == 2) {
			return setByName("NazovDb", value);
		}
		if (position == 3) {
			return setByName("Nadpis", value);
		}
		if (position == 4) {
			return setByName("IdTransakciaZapisane", value);
		}
		return false;
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed.
	 * 
	 * @throws Exception
	 */
	public void save() throws Exception {
		save(CudPrekladStlpecPeer.DATABASE_NAME);
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. Note: this code is here because the method body is auto-generated
	 * conditionally and therefore needs to be in this file instead of in the super class, BaseObject.
	 * 
	 * @param dbName
	 * @throws TorqueException
	 */
	public void save(String dbName) throws TorqueException {
		Connection con = null;
		try {
			con = Transaction.begin(dbName);
			save(con);
			Transaction.commit(con);
		} catch (TorqueException e) {
			Transaction.safeRollback(con);
			throw e;
		}
	}

	/**
	 * flag to prevent endless save loop, if this object is referenced by another object which falls in this transaction.
	 */
	private boolean alreadyInSave = false;

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. This method is meant to be used as part of a transaction, otherwise
	 * use the save() method and the connection details will be handled internally
	 * 
	 * @param con
	 * @throws TorqueException
	 */
	public void save(Connection con) throws TorqueException {
		if (!alreadyInSave) {
			alreadyInSave = true;

			// If this object has been modified, then save it to the database.
			if (isModified()) {
				if (isNew()) {
					CudPrekladStlpecPeer.doInsert((CudPrekladStlpec) this, con);
					setNew(false);
				} else {
					CudPrekladStlpecPeer.doUpdate((CudPrekladStlpec) this, con);
				}
			}

			alreadyInSave = false;
		}
	}

	/**
	 * Set the PrimaryKey using ObjectKey.
	 * 
	 * @param key
	 *            prekladStlpecId ObjectKey
	 */
	public void setPrimaryKey(ObjectKey key)

	{
		setPrekladStlpecId(new Integer(((NumberKey) key).intValue()));
	}

	/**
	 * Set the PrimaryKey using a String.
	 * 
	 * @param key
	 */
	public void setPrimaryKey(String key) {
		setPrekladStlpecId(new Integer(key));
	}

	/**
	 * returns an id that differentiates this object from others of its class.
	 */
	public ObjectKey getPrimaryKey() {
		return SimpleKey.keyFor(getPrekladStlpecId());
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. It then fills all the association collections and sets the related objects to
	 * isNew=true.
	 */
	public CudPrekladStlpec copy() throws TorqueException {
		return copy(true);
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. If the parameter deepcopy is true, it then fills all the association collections and
	 * sets the related objects to isNew=true.
	 * 
	 * @param deepcopy
	 *            whether to copy the associated objects.
	 */
	public CudPrekladStlpec copy(boolean deepcopy) throws TorqueException {
		return copyInto(new CudPrekladStlpec(), deepcopy);
	}

	/**
	 * Fills the copyObj with the contents of this object. The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 */
	protected CudPrekladStlpec copyInto(CudPrekladStlpec copyObj) throws TorqueException {
		return copyInto(copyObj, true);
	}

	/**
	 * Fills the copyObj with the contents of this object. If deepcopy is true, The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 * @param deepcopy
	 *            whether the associated objects should be copied.
	 */
	protected CudPrekladStlpec copyInto(CudPrekladStlpec copyObj, boolean deepcopy) throws TorqueException {
		copyObj.setPrekladStlpecId(prekladStlpecId);
		copyObj.setIdPrekladTabulka(idPrekladTabulka);
		copyObj.setNazovDb(nazovDb);
		copyObj.setNadpis(nadpis);
		copyObj.setIdTransakciaZapisane(idTransakciaZapisane);

		copyObj.setPrekladStlpecId((Integer) null);

		if (deepcopy) {
		}
		return copyObj;
	}

	/**
	 * returns a peer instance associated with this om. Since Peer classes are not to have any instance attributes, this method returns the same instance for all member of this
	 * class. The method could therefore be static, but this would prevent one from overriding the behavior.
	 */
	public CudPrekladStlpecPeer getPeer() {
		return peer;
	}

	/**
	 * Retrieves the TableMap object related to this Table data without compiler warnings of using getPeer().getTableMap().
	 * 
	 * @return The associated TableMap object.
	 */
	public TableMap getTableMap() throws TorqueException {
		return CudPrekladStlpecPeer.getTableMap();
	}

	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("CudPrekladStlpec:\n");
		str.append("PrekladStlpecId = ").append(getPrekladStlpecId()).append("\n");
		str.append("IdPrekladTabulka = ").append(getIdPrekladTabulka()).append("\n");
		str.append("NazovDb = ").append(getNazovDb()).append("\n");
		str.append("Nadpis = ").append(getNadpis()).append("\n");
		str.append("IdTransakciaZapisane = ").append(getIdTransakciaZapisane()).append("\n");
		return (str.toString());
	}
}
