package sk.ditec.dao.meta;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Thu Jul 24 10:20:22 CEST 2025]
 * 
 * You should not use this class directly. It should not even be extended all references should be to CrdSpracovanie
 */
public abstract class BaseCrdSpracovanie extends BaseObject {
	/** Serial version */
	private static final long serialVersionUID = 1753345222773L;

	/** The Peer class */
	private static final CrdSpracovaniePeer peer = new CrdSpracovaniePeer();

	/** The value for the crdSpracovanieId field */
	private Integer crdSpracovanieId;

	/** The value for the datumVolania field */
	private Date datumVolania;

	/** The value for the kodSpracovania field */
	private String kodSpracovania;

	/** The value for the posledneUspesneSpracovanie field */
	private Date posledneUspesneSpracovanie;

	/**
	 * Get the CrdSpracovanieId
	 * 
	 * @return Integer
	 */
	public Integer getCrdSpracovanieId() {
		return crdSpracovanieId;
	}

	/**
	 * Set the value of CrdSpracovanieId
	 * 
	 * @param v
	 *            new value
	 */
	public void setCrdSpracovanieId(Integer v) {

		if (!ObjectUtils.equals(this.crdSpracovanieId, v)) {
			this.crdSpracovanieId = v;
			setModified(true);
		}

	}

	/**
	 * Get the DatumVolania
	 * 
	 * @return Date
	 */
	public Date getDatumVolania() {
		return datumVolania;
	}

	/**
	 * Set the value of DatumVolania
	 * 
	 * @param v
	 *            new value
	 */
	public void setDatumVolania(Date v) {

		if (!ObjectUtils.equals(this.datumVolania, v)) {
			this.datumVolania = v;
			setModified(true);
		}

	}

	/**
	 * Get the KodSpracovania
	 * 
	 * @return String
	 */
	public String getKodSpracovania() {
		return kodSpracovania;
	}

	/**
	 * Set the value of KodSpracovania
	 * 
	 * @param v
	 *            new value
	 */
	public void setKodSpracovania(String v) {

		if (!ObjectUtils.equals(this.kodSpracovania, v)) {
			this.kodSpracovania = v;
			setModified(true);
		}

	}

	/**
	 * Get the PosledneUspesneSpracovanie
	 * 
	 * @return Date
	 */
	public Date getPosledneUspesneSpracovanie() {
		return posledneUspesneSpracovanie;
	}

	/**
	 * Set the value of PosledneUspesneSpracovanie
	 * 
	 * @param v
	 *            new value
	 */
	public void setPosledneUspesneSpracovanie(Date v) {

		if (!ObjectUtils.equals(this.posledneUspesneSpracovanie, v)) {
			this.posledneUspesneSpracovanie = v;
			setModified(true);
		}

	}

	private static List fieldNames = null;

	/**
	 * Generate a list of field names.
	 * 
	 * @return a list of field names
	 */
	public static synchronized List getFieldNames() {
		if (fieldNames == null) {
			fieldNames = new ArrayList();
			fieldNames.add("CrdSpracovanieId");
			fieldNames.add("DatumVolania");
			fieldNames.add("KodSpracovania");
			fieldNames.add("PosledneUspesneSpracovanie");
			fieldNames = Collections.unmodifiableList(fieldNames);
		}
		return fieldNames;
	}

	/**
	 * Retrieves a field from the object by field (Java) name passed in as a String.
	 * 
	 * @param name
	 *            field name
	 * @return value
	 */
	public Object getByName(String name) {
		if (name.equals("CrdSpracovanieId")) {
			return getCrdSpracovanieId();
		}
		if (name.equals("DatumVolania")) {
			return getDatumVolania();
		}
		if (name.equals("KodSpracovania")) {
			return getKodSpracovania();
		}
		if (name.equals("PosledneUspesneSpracovanie")) {
			return getPosledneUspesneSpracovanie();
		}
		return null;
	}

	/**
	 * Set a field in the object by field (Java) name.
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (name.equals("CrdSpracovanieId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCrdSpracovanieId((Integer) value);
			return true;
		}
		if (name.equals("DatumVolania")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setDatumVolania((Date) value);
			return true;
		}
		if (name.equals("KodSpracovania")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setKodSpracovania((String) value);
			return true;
		}
		if (name.equals("PosledneUspesneSpracovanie")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPosledneUspesneSpracovanie((Date) value);
			return true;
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by name passed in as a String. The String must be one of the static Strings defined in this Class' Peer.
	 * 
	 * @param name
	 *            peer name
	 * @return value
	 */
	public Object getByPeerName(String name) {
		if (name.equals(CrdSpracovaniePeer.CRD_SPRACOVANIE_ID)) {
			return getCrdSpracovanieId();
		}
		if (name.equals(CrdSpracovaniePeer.DATUM_VOLANIA)) {
			return getDatumVolania();
		}
		if (name.equals(CrdSpracovaniePeer.KOD_SPRACOVANIA)) {
			return getKodSpracovania();
		}
		if (name.equals(CrdSpracovaniePeer.POSLEDNE_USPESNE_SPRACOVANIE)) {
			return getPosledneUspesneSpracovanie();
		}
		return null;
	}

	/**
	 * Set field values by Peer Field Name
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPeerName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (CrdSpracovaniePeer.CRD_SPRACOVANIE_ID.equals(name)) {
			return setByName("CrdSpracovanieId", value);
		}
		if (CrdSpracovaniePeer.DATUM_VOLANIA.equals(name)) {
			return setByName("DatumVolania", value);
		}
		if (CrdSpracovaniePeer.KOD_SPRACOVANIA.equals(name)) {
			return setByName("KodSpracovania", value);
		}
		if (CrdSpracovaniePeer.POSLEDNE_USPESNE_SPRACOVANIE.equals(name)) {
			return setByName("PosledneUspesneSpracovanie", value);
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema. Zero-based.
	 * 
	 * @param pos
	 *            position in xml schema
	 * @return value
	 */
	public Object getByPosition(int pos) {
		if (pos == 0) {
			return getCrdSpracovanieId();
		}
		if (pos == 1) {
			return getDatumVolania();
		}
		if (pos == 2) {
			return getKodSpracovania();
		}
		if (pos == 3) {
			return getPosledneUspesneSpracovanie();
		}
		return null;
	}

	/**
	 * Set field values by its position (zero based) in the XML schema.
	 * 
	 * @param position
	 *            The field position
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid position / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPosition(int position, Object value) throws TorqueException, IllegalArgumentException {
		if (position == 0) {
			return setByName("CrdSpracovanieId", value);
		}
		if (position == 1) {
			return setByName("DatumVolania", value);
		}
		if (position == 2) {
			return setByName("KodSpracovania", value);
		}
		if (position == 3) {
			return setByName("PosledneUspesneSpracovanie", value);
		}
		return false;
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed.
	 * 
	 * @throws Exception
	 */
	public void save() throws Exception {
		save(CrdSpracovaniePeer.DATABASE_NAME);
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. Note: this code is here because the method body is auto-generated
	 * conditionally and therefore needs to be in this file instead of in the super class, BaseObject.
	 * 
	 * @param dbName
	 * @throws TorqueException
	 */
	public void save(String dbName) throws TorqueException {
		Connection con = null;
		try {
			con = Transaction.begin(dbName);
			save(con);
			Transaction.commit(con);
		} catch (TorqueException e) {
			Transaction.safeRollback(con);
			throw e;
		}
	}

	/**
	 * flag to prevent endless save loop, if this object is referenced by another object which falls in this transaction.
	 */
	private boolean alreadyInSave = false;

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. This method is meant to be used as part of a transaction, otherwise
	 * use the save() method and the connection details will be handled internally
	 * 
	 * @param con
	 * @throws TorqueException
	 */
	public void save(Connection con) throws TorqueException {
		if (!alreadyInSave) {
			alreadyInSave = true;

			// If this object has been modified, then save it to the database.
			if (isModified()) {
				if (isNew()) {
					CrdSpracovaniePeer.doInsert((CrdSpracovanie) this, con);
					setNew(false);
				} else {
					CrdSpracovaniePeer.doUpdate((CrdSpracovanie) this, con);
				}
			}

			alreadyInSave = false;
		}
	}

	/**
	 * Set the PrimaryKey using ObjectKey.
	 * 
	 * @param key
	 *            crdSpracovanieId ObjectKey
	 */
	public void setPrimaryKey(ObjectKey key)

	{
		setCrdSpracovanieId(new Integer(((NumberKey) key).intValue()));
	}

	/**
	 * Set the PrimaryKey using a String.
	 * 
	 * @param key
	 */
	public void setPrimaryKey(String key) {
		setCrdSpracovanieId(new Integer(key));
	}

	/**
	 * returns an id that differentiates this object from others of its class.
	 */
	public ObjectKey getPrimaryKey() {
		return SimpleKey.keyFor(getCrdSpracovanieId());
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. It then fills all the association collections and sets the related objects to
	 * isNew=true.
	 */
	public CrdSpracovanie copy() throws TorqueException {
		return copy(true);
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. If the parameter deepcopy is true, it then fills all the association collections and
	 * sets the related objects to isNew=true.
	 * 
	 * @param deepcopy
	 *            whether to copy the associated objects.
	 */
	public CrdSpracovanie copy(boolean deepcopy) throws TorqueException {
		return copyInto(new CrdSpracovanie(), deepcopy);
	}

	/**
	 * Fills the copyObj with the contents of this object. The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 */
	protected CrdSpracovanie copyInto(CrdSpracovanie copyObj) throws TorqueException {
		return copyInto(copyObj, true);
	}

	/**
	 * Fills the copyObj with the contents of this object. If deepcopy is true, The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 * @param deepcopy
	 *            whether the associated objects should be copied.
	 */
	protected CrdSpracovanie copyInto(CrdSpracovanie copyObj, boolean deepcopy) throws TorqueException {
		copyObj.setCrdSpracovanieId(crdSpracovanieId);
		copyObj.setDatumVolania(datumVolania);
		copyObj.setKodSpracovania(kodSpracovania);
		copyObj.setPosledneUspesneSpracovanie(posledneUspesneSpracovanie);

		copyObj.setCrdSpracovanieId((Integer) null);

		if (deepcopy) {
		}
		return copyObj;
	}

	/**
	 * returns a peer instance associated with this om. Since Peer classes are not to have any instance attributes, this method returns the same instance for all member of this
	 * class. The method could therefore be static, but this would prevent one from overriding the behavior.
	 */
	public CrdSpracovaniePeer getPeer() {
		return peer;
	}

	/**
	 * Retrieves the TableMap object related to this Table data without compiler warnings of using getPeer().getTableMap().
	 * 
	 * @return The associated TableMap object.
	 */
	public TableMap getTableMap() throws TorqueException {
		return CrdSpracovaniePeer.getTableMap();
	}

	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("CrdSpracovanie:\n");
		str.append("CrdSpracovanieId = ").append(getCrdSpracovanieId()).append("\n");
		str.append("DatumVolania = ").append(getDatumVolania()).append("\n");
		str.append("KodSpracovania = ").append(getKodSpracovania()).append("\n");
		str.append("PosledneUspesneSpracovanie = ").append(getPosledneUspesneSpracovanie()).append("\n");
		return (str.toString());
	}
}
