package sk.ditec.dao.meta;

/**
 * The skeleton for this class was autogenerated by Torque on:
 * 
 * [Mon Oct 20 12:40:10 CEST 2025]
 * 
 * You should add additional methods to this class to meet the application requirements. This class will only be generated as long as it does not already exist in the output
 * directory.
 */
public class CudWfDefPeer extends sk.ditec.dao.meta.BaseCudWfDefPeer {
	/** Serial version */
	private static final long serialVersionUID = 1760956810281L;

}
