ALTER TABLE T_ZAKLADNE_INFORMACIE_O_PRM ADD PSC NUMBER(5);
ALTER TABLE T_ZAKLADNE_INFORMACIE_O_PRM ADD ID_OBEC NUMBER(10);
ALTER TABLE T_ZAKLADNE_INFORMACIE_O_PRM ADD ULICA NVARCHAR2(50);
ALTER TABLE T_ZAKLADNE_INFORMACIE_O_PRM ADD CISLO NVARCHAR2(10);
