
-- update dat


UPDATE cud_wf_def
SET  email_send = 'T'
WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka in ('T_CHARACTERISTIC_DESCRIPT_CODE', 'T_COMMERCIAL_SERVICE_CODE', 'T_FACILITY_TYPE_DESCRIPT_CODE', 'T_INFORMATION_TO_BE_DISPLAYED', 'T_INTERNAL_VEHICLE_FACILITY', 'T_SPECIAL_SERVICE_DESCR_CODE'));
COMMIT;
