package sk.ditec.dao.meta.map;

import java.util.Date;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.ColumnMap;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.TableMap;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Thu Jul 24 10:20:22 CEST 2025]
 * 
 */
public class CrdSpracTabuliekMapBuilder implements MapBuilder {
	/**
	 * The name of this class
	 */
	public static final String CLASS_NAME = "sk.ditec.dao.meta.map.CrdSpracTabuliekMapBuilder";

	/**
	 * The database map.
	 */
	private DatabaseMap dbMap = null;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we don't have to re-build it every time.
	 * 
	 * @return true if this DatabaseMapBuilder is built
	 */
	public boolean isBuilt() {
		return (dbMap != null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 * 
	 * @return the databasemap
	 */
	public DatabaseMap getDatabaseMap() {
		return this.dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 * 
	 * @throws TorqueException
	 */
	public synchronized void doBuild() throws TorqueException {
		if (isBuilt()) {
			return;
		}
		dbMap = Torque.getDatabaseMap("APP");

		dbMap.addTable("CRD_SPRAC_TABULIEK");
		TableMap tMap = dbMap.getTable("CRD_SPRAC_TABULIEK");
		tMap.setJavaName("CrdSpracTabuliek");
		tMap.setOMClass(sk.ditec.dao.meta.CrdSpracTabuliek.class);
		tMap.setPeerClass(sk.ditec.dao.meta.CrdSpracTabuliekPeer.class);
		tMap.setPrimaryKeyMethod(TableMap.NATIVE);
		tMap.setPrimaryKeyMethodInfo("CRD_SPRAC_TABULIEK_SEQ");

		ColumnMap cMap = null;

		// ------------- Column: CRD_SPRAC_TABULIEK_ID --------------------
		cMap = new ColumnMap("CRD_SPRAC_TABULIEK_ID", tMap);
		cMap.setType(new Integer(0));
		cMap.setTorqueType("INTEGER");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(true);
		cMap.setNotNull(true);
		cMap.setJavaName("CrdSpracTabuliekId");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setSize(10);
		cMap.setScale(0);
		cMap.setPosition(1);
		tMap.addColumn(cMap);
		// ------------- Column: ID_CRD_SPRACOVANIE --------------------
		cMap = new ColumnMap("ID_CRD_SPRACOVANIE", tMap);
		cMap.setType(new Integer(0));
		cMap.setTorqueType("INTEGER");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(true);
		cMap.setJavaName("IdCrdSpracovanie");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setSize(10);
		cMap.setScale(0);
		cMap.setPosition(2);
		tMap.addColumn(cMap);
		// ------------- Column: ID_CISELNIK --------------------
		cMap = new ColumnMap("ID_CISELNIK", tMap);
		cMap.setType(new Integer(0));
		cMap.setTorqueType("INTEGER");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(true);
		cMap.setJavaName("IdCiselnik");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setSize(10);
		cMap.setScale(0);
		cMap.setPosition(3);
		tMap.addColumn(cMap);
		// ------------- Column: DATE_FILTER_FOR_DELETED --------------------
		cMap = new ColumnMap("DATE_FILTER_FOR_DELETED", tMap);
		cMap.setType(new Date());
		cMap.setTorqueType("TIMESTAMP");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(true);
		cMap.setJavaName("DateFilterForDeleted");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setPosition(4);
		tMap.addColumn(cMap);
		// ------------- Column: REPLICATE_FROM_DATE --------------------
		cMap = new ColumnMap("REPLICATE_FROM_DATE", tMap);
		cMap.setType(new Date());
		cMap.setTorqueType("TIMESTAMP");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(true);
		cMap.setJavaName("ReplicateFromDate");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setPosition(5);
		tMap.addColumn(cMap);
		// ------------- Column: REPLICATE_ALL --------------------
		cMap = new ColumnMap("REPLICATE_ALL", tMap);
		cMap.setType("");
		cMap.setTorqueType("VARCHAR");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(true);
		cMap.setJavaName("ReplicateAll");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setSize(20);
		cMap.setPosition(6);
		tMap.addColumn(cMap);
		// ------------- Column: NAVRATOVY_KOD --------------------
		cMap = new ColumnMap("NAVRATOVY_KOD", tMap);
		cMap.setType(new Integer(0));
		cMap.setTorqueType("INTEGER");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(false);
		cMap.setJavaName("NavratovyKod");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setSize(3);
		cMap.setScale(0);
		cMap.setPosition(7);
		tMap.addColumn(cMap);
		// ------------- Column: POPIS_SPRACOVANIA --------------------
		cMap = new ColumnMap("POPIS_SPRACOVANIA", tMap);
		cMap.setType("");
		cMap.setTorqueType("VARCHAR");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(false);
		cMap.setJavaName("PopisSpracovania");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setSize(500);
		cMap.setPosition(8);
		tMap.addColumn(cMap);
		// ------------- Column: VSTUPNE_XML --------------------
		cMap = new ColumnMap("VSTUPNE_XML", tMap);
		cMap.setType("");
		cMap.setTorqueType("VARCHAR");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(false);
		cMap.setJavaName("VstupneXml");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setPosition(9);
		tMap.addColumn(cMap);
		// ------------- Column: VYSTUPNE_XML --------------------
		cMap = new ColumnMap("VYSTUPNE_XML", tMap);
		cMap.setType("");
		cMap.setTorqueType("VARCHAR");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(false);
		cMap.setJavaName("VystupneXml");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setPosition(10);
		tMap.addColumn(cMap);
		// ------------- Column: ZMENOVE_XML_VSTUP --------------------
		cMap = new ColumnMap("ZMENOVE_XML_VSTUP", tMap);
		cMap.setType("");
		cMap.setTorqueType("VARCHAR");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(false);
		cMap.setJavaName("ZmenoveXmlVstup");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setPosition(11);
		tMap.addColumn(cMap);
		// ------------- Column: ZMENOVE_XML_VYSTUP --------------------
		cMap = new ColumnMap("ZMENOVE_XML_VYSTUP", tMap);
		cMap.setType("");
		cMap.setTorqueType("VARCHAR");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(false);
		cMap.setJavaName("ZmenoveXmlVystup");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setPosition(12);
		tMap.addColumn(cMap);
		tMap.setUseInheritance(false);
	}
}
