package sk.ditec.dao.meta.map;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.ColumnMap;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.TableMap;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Thu Jul 24 10:20:22 CEST 2025]
 * 
 */
public class CudPrekladStlpecMapBuilder implements MapBuilder {
	/**
	 * The name of this class
	 */
	public static final String CLASS_NAME = "sk.ditec.dao.meta.map.CudPrekladStlpecMapBuilder";

	/**
	 * The database map.
	 */
	private DatabaseMap dbMap = null;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we don't have to re-build it every time.
	 * 
	 * @return true if this DatabaseMapBuilder is built
	 */
	public boolean isBuilt() {
		return (dbMap != null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 * 
	 * @return the databasemap
	 */
	public DatabaseMap getDatabaseMap() {
		return this.dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 * 
	 * @throws TorqueException
	 */
	public synchronized void doBuild() throws TorqueException {
		if (isBuilt()) {
			return;
		}
		dbMap = Torque.getDatabaseMap("APP");

		dbMap.addTable("CUD_PREKLAD_STLPEC");
		TableMap tMap = dbMap.getTable("CUD_PREKLAD_STLPEC");
		tMap.setJavaName("CudPrekladStlpec");
		tMap.setOMClass(sk.ditec.dao.meta.CudPrekladStlpec.class);
		tMap.setPeerClass(sk.ditec.dao.meta.CudPrekladStlpecPeer.class);
		tMap.setPrimaryKeyMethod(TableMap.NATIVE);
		tMap.setPrimaryKeyMethodInfo("CUD_PREKLAD_STLPEC_SEQ");

		ColumnMap cMap = null;

		// ------------- Column: PREKLAD_STLPEC_ID --------------------
		cMap = new ColumnMap("PREKLAD_STLPEC_ID", tMap);
		cMap.setType(new Integer(0));
		cMap.setTorqueType("INTEGER");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(true);
		cMap.setNotNull(true);
		cMap.setJavaName("PrekladStlpecId");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setSize(10);
		cMap.setScale(0);
		cMap.setPosition(1);
		tMap.addColumn(cMap);
		// ------------- Column: ID_PREKLAD_TABULKA --------------------
		cMap = new ColumnMap("ID_PREKLAD_TABULKA", tMap);
		cMap.setType(new Integer(0));
		cMap.setTorqueType("INTEGER");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(true);
		cMap.setJavaName("IdPrekladTabulka");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setSize(10);
		cMap.setScale(0);
		cMap.setPosition(2);
		tMap.addColumn(cMap);
		// ------------- Column: NAZOV_DB --------------------
		cMap = new ColumnMap("NAZOV_DB", tMap);
		cMap.setType("");
		cMap.setTorqueType("VARCHAR");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(true);
		cMap.setJavaName("NazovDb");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setPosition(3);
		tMap.addColumn(cMap);
		// ------------- Column: NADPIS --------------------
		cMap = new ColumnMap("NADPIS", tMap);
		cMap.setType("");
		cMap.setTorqueType("VARCHAR");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(true);
		cMap.setJavaName("Nadpis");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setPosition(4);
		tMap.addColumn(cMap);
		// ------------- Column: ID_TRANSAKCIA_ZAPISANE --------------------
		cMap = new ColumnMap("ID_TRANSAKCIA_ZAPISANE", tMap);
		cMap.setType(new Long(0));
		cMap.setTorqueType("BIGINT");
		cMap.setUsePrimitive(false);
		cMap.setPrimaryKey(false);
		cMap.setNotNull(true);
		cMap.setJavaName("IdTransakciaZapisane");
		cMap.setAutoIncrement(false);
		cMap.setProtected(false);
		cMap.setInheritance("false");
		cMap.setSize(20);
		cMap.setScale(0);
		cMap.setPosition(5);
		tMap.addColumn(cMap);
		tMap.setUseInheritance(false);
	}
}
