-- CR 55523: D_CR_CUD_20240419_01-DB_STRING

ALTER TABLE CUD.CUD_CISELNIK_STLPEC ADD (JE_DB_STRING NVARCHAR2(1) NULL);

COMMENT ON COLUMN CUD.CUD_CISELNIK_STLPEC.JE_DB_STRING IS 'Ak je true znamená že natívna reprezentácia na databáze je string';
