DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_DESCRIPTION_MANNER' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_UNIT_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_DANGER_LABEL' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_STATUS_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_IMHARMONIZATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_JOURNEY_LOCATION_TYPE_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_CONSIGNMENT_TYPE_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ACTION_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_RESTRICTION_CODES' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_PROCEDURE_UPD_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_CC_SYSTEM_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_REMOVABLE_ACCESSORIES' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INTERNAL_FITTING_DEFECT_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_DIRECTION_OF_DESCRIPTION' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_REQUEST_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAINSET_ORIENTATION' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_RUHARMONIZATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ERROR_TYPE_OF_ERROR' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_ACTIVITY_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_BRAKING_POWER_VARIATION_DEV' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_SPECIAL_SERVICE_DESCR_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INFO_GOODS_SHAPE_TYPE_DANGER' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_MESSAGE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_NORMAL_LOADING_GAUGE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_CC_SYST' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_PACKING_GROUP' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_REFUSAL_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_RUNNING_STATUS' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_INFORMATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INTEROP_CAPABILITY' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_OBJECT_INFO_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRANSPORT_RESTRICTION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_HAND_BRAKE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_HEATING' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_IRN_EVENT_CAUSE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_WHEEL_SET_TRANSFORM_METHOD' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ERROR_SEVERITY' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_RADIO_SYSTEM' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_MRN_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_wf_todo WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_BRAKE_TYPE' AND id_transakcia_zrusene IS NULL );
commit;

DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_RADIO_SYSTEM' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_IMHARMONIZATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRANSPORT_RESTRICTION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_REQUEST_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_INFORMATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ERROR_TYPE_OF_ERROR' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_HAND_BRAKE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_WHEEL_SET_TRANSFORM_METHOD' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_CC_SYST' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_OBJECT_INFO_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_PACKING_GROUP' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_RUHARMONIZATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INFO_GOODS_SHAPE_TYPE_DANGER' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_HEATING' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_DIRECTION_OF_DESCRIPTION' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INTEROP_CAPABILITY' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ERROR_SEVERITY' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_REFUSAL_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_CONSIGNMENT_TYPE_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_JOURNEY_LOCATION_TYPE_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_REMOVABLE_ACCESSORIES' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_STATUS_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_DESCRIPTION_MANNER' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_MESSAGE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_RUNNING_STATUS' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_UNIT_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_IRN_EVENT_CAUSE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAINSET_ORIENTATION' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INTERNAL_FITTING_DEFECT_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_DANGER_LABEL' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_CC_SYSTEM_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_SPECIAL_SERVICE_DESCR_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_PROCEDURE_UPD_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_ACTIVITY_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ACTION_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_BRAKING_POWER_VARIATION_DEV' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_RESTRICTION_CODES' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_BRAKE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_NORMAL_LOADING_GAUGE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stav_hist WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_MRN_TYPE' AND id_transakcia_zrusene IS NULL );
commit;

DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_IRN_EVENT_CAUSE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_REQUEST_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_BRAKE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_WHEEL_SET_TRANSFORM_METHOD' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_RADIO_SYSTEM' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INTERNAL_FITTING_DEFECT_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_UNIT_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_REMOVABLE_ACCESSORIES' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_BRAKING_POWER_VARIATION_DEV' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_MESSAGE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ERROR_SEVERITY' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_REFUSAL_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_CONSIGNMENT_TYPE_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INFO_GOODS_SHAPE_TYPE_DANGER' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_ACTIVITY_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_INFORMATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_RESTRICTION_CODES' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_RUNNING_STATUS' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_SPECIAL_SERVICE_DESCR_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INTEROP_CAPABILITY' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ERROR_TYPE_OF_ERROR' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_IMHARMONIZATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRANSPORT_RESTRICTION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_JOURNEY_LOCATION_TYPE_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_RUHARMONIZATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_CC_SYST' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_DIRECTION_OF_DESCRIPTION' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_DESCRIPTION_MANNER' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_PACKING_GROUP' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAINSET_ORIENTATION' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_CC_SYSTEM_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_OBJECT_INFO_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_HEATING' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_NORMAL_LOADING_GAUGE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_PROCEDURE_UPD_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_HAND_BRAKE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_MRN_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ACTION_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_DANGER_LABEL' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_eskalacia WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_STATUS_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
commit;

DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ERROR_TYPE_OF_ERROR' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_IRN_EVENT_CAUSE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ERROR_SEVERITY' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_WHEEL_SET_TRANSFORM_METHOD' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_ACTIVITY_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_HEATING' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ACTION_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_BRAKING_POWER_VARIATION_DEV' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_MESSAGE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_RUHARMONIZATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_MRN_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_UNIT_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_DANGER_LABEL' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_BRAKE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_IMHARMONIZATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAINSET_ORIENTATION' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_DIRECTION_OF_DESCRIPTION' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INTEROP_CAPABILITY' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_CONSIGNMENT_TYPE_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INTERNAL_FITTING_DEFECT_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_DESCRIPTION_MANNER' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_CC_SYST' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_REFUSAL_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_SPECIAL_SERVICE_DESCR_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_PACKING_GROUP' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_REMOVABLE_ACCESSORIES' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_HAND_BRAKE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_OBJECT_INFO_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_PROCEDURE_UPD_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_RUNNING_STATUS' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INFO_GOODS_SHAPE_TYPE_DANGER' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_JOURNEY_LOCATION_TYPE_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_NORMAL_LOADING_GAUGE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_REQUEST_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_RESTRICTION_CODES' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRANSPORT_RESTRICTION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_RADIO_SYSTEM' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_STATUS_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_INFORMATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena_stlpec WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_CC_SYSTEM_CODE' AND id_transakcia_zrusene IS NULL );
commit;

DELETE FROM T_ACTION_UPDATE_LINK_FRAMEWORK;
DELETE FROM T_PROCEDURE_UPD_LINK_FRAMEWORK;
DELETE FROM T_BRAKING_POWER_VARIATION_DEV;
DELETE FROM T_REFUSAL_CODE;
DELETE FROM T_OBJECT_INFO_TYPE;
DELETE FROM T_TRAIN_ACTIVITY_TYPE;
DELETE FROM T_TYPE_OF_RUHARMONIZATION_CODE;
DELETE FROM T_DIRECTION_OF_DESCRIPTION;
DELETE FROM T_SPECIAL_SERVICE_DESCR_CODE;
DELETE FROM T_RESTRICTION_CODES;
DELETE FROM T_DANGER_LABEL;
DELETE FROM T_MRN_TYPE;
DELETE FROM T_HAND_BRAKE_TYPE;
DELETE FROM T_ERROR_TYPE_OF_ERROR;
DELETE FROM T_IRN_EVENT_CAUSE;
DELETE FROM T_WHEEL_SET_TRANSFORM_METHOD;
DELETE FROM T_TRAIN_CC_SYSTEM_CODE;
DELETE FROM T_RUNNING_STATUS;
DELETE FROM T_TRANSPORT_RESTRICTION_CODE;
DELETE FROM T_UNIT_TYPE;
DELETE FROM T_INTEROP_CAPABILITY;
DELETE FROM T_ERROR_SEVERITY;
DELETE FROM T_BRAKE_TYPE;
DELETE FROM T_PACKING_GROUP;
DELETE FROM T_TRAIN_TYPE;
DELETE FROM T_STATUS_UPDATE_LINK_FRAMEWORK;
DELETE FROM T_INTERNAL_FITTING_DEFECT_CODE;
DELETE FROM T_JOURNEY_LOCATION_TYPE_CODE;
DELETE FROM T_TYPE_OF_REQUEST_CODE;
DELETE FROM T_TRAIN_DESCRIPTION_MANNER;
DELETE FROM T_TYPE_OF_IMHARMONIZATION_CODE;
DELETE FROM T_INFO_GOODS_SHAPE_TYPE_DANGER;
DELETE FROM T_MESSAGE_TYPE;
DELETE FROM T_TRAIN_CC_SYST;
DELETE FROM T_CONSIGNMENT_TYPE_CODE;
DELETE FROM T_TRAINSET_ORIENTATION;
DELETE FROM T_TYPE_UPDATE_LINK_FRAMEWORK;
DELETE FROM T_TYPE_REMOVABLE_ACCESSORIES;
DELETE FROM T_TYPE_OF_INFORMATION_CODE;
DELETE FROM T_TRAIN_RADIO_SYSTEM;
DELETE FROM T_TYPE_OF_HEATING;
DELETE FROM T_NORMAL_LOADING_GAUGE;
commit;

DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_BRAKE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_IRN_EVENT_CAUSE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_INFORMATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_CC_SYSTEM_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_HAND_BRAKE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_REQUEST_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_REMOVABLE_ACCESSORIES' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_PROCEDURE_UPD_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_JOURNEY_LOCATION_TYPE_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_NORMAL_LOADING_GAUGE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_PACKING_GROUP' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_RADIO_SYSTEM' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_OBJECT_INFO_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ERROR_SEVERITY' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_ACTIVITY_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_STATUS_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INTERNAL_FITTING_DEFECT_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_MRN_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_MESSAGE_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_BRAKING_POWER_VARIATION_DEV' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_HEATING' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_CC_SYST' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INFO_GOODS_SHAPE_TYPE_DANGER' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_CONSIGNMENT_TYPE_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_RUHARMONIZATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_RESTRICTION_CODES' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_DESCRIPTION_MANNER' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ACTION_UPDATE_LINK_FRAMEWORK' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAINSET_ORIENTATION' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_DIRECTION_OF_DESCRIPTION' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_REFUSAL_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TYPE_OF_IMHARMONIZATION_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_DANGER_LABEL' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_ERROR_TYPE_OF_ERROR' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRAIN_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_UNIT_TYPE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_RUNNING_STATUS' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_WHEEL_SET_TRANSFORM_METHOD' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_INTEROP_CAPABILITY' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_SPECIAL_SERVICE_DESCR_CODE' AND id_transakcia_zrusene IS NULL );
DELETE FROM cud_zmena WHERE id_ciselnik IN ( SELECT ciselnik_id FROM cud_ciselnik WHERE tabulka = 'T_TRANSPORT_RESTRICTION_CODE' AND id_transakcia_zrusene IS NULL );
commit;