package sk.ditec.dao.master;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Fri Jul 25 14:44:46 CEST 2025]
 * 
 * You should not use this class directly. It should not even be extended all references should be to TVozenUcelenejJednotky
 */
public abstract class BaseTVozenUcelenejJednotky extends BaseObject {
	/** Serial version */
	private static final long serialVersionUID = 1753447486539L;

	/** The Peer class */
	private static final TVozenUcelenejJednotkyPeer peer = new TVozenUcelenejJednotkyPeer();

	/** The value for the histId field */
	private Integer histId;

	/** The value for the platnostOd field */
	private Date platnostOd;

	/** The value for the platnostDo field */
	private Date platnostDo;

	/** The value for the casVytvorenia field */
	private Date casVytvorenia;

	/** The value for the casZmeny field */
	private Date casZmeny;

	/** The value for the idZmena field */
	private Integer idZmena;

	/** The value for the zmaz field */
	private String zmaz;

	/** The value for the vozenUcelenejJednotkyId field */
	private Integer vozenUcelenejJednotkyId;

	/** The value for the cislo field */
	private String cislo;

	/** The value for the dlzka field */
	private Integer dlzka;

	/** The value for the napravy field */
	private Integer napravy;

	/** The value for the hmotnost field */
	private Integer hmotnost;

	/** The value for the hmotnostPrazdneho field */
	private Integer hmotnostPrazdneho;

	/** The value for the rad field */
	private String rad;

	/** The value for the pismenoveOznacenieVozna field */
	private String pismenoveOznacenieVozna;

	/** The value for the poznamka field */
	private String poznamka;

	/** The value for the idUcelenaJednotka field */
	private Integer idUcelenaJednotka;

	/**
	 * Get the HistId
	 * 
	 * @return Integer
	 */
	public Integer getHistId() {
		return histId;
	}

	/**
	 * Set the value of HistId
	 * 
	 * @param v
	 *            new value
	 */
	public void setHistId(Integer v) {

		if (!ObjectUtils.equals(this.histId, v)) {
			this.histId = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostOd
	 * 
	 * @return Date
	 */
	public Date getPlatnostOd() {
		return platnostOd;
	}

	/**
	 * Set the value of PlatnostOd
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostOd(Date v) {

		if (!ObjectUtils.equals(this.platnostOd, v)) {
			this.platnostOd = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostDo
	 * 
	 * @return Date
	 */
	public Date getPlatnostDo() {
		return platnostDo;
	}

	/**
	 * Set the value of PlatnostDo
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostDo(Date v) {

		if (!ObjectUtils.equals(this.platnostDo, v)) {
			this.platnostDo = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasVytvorenia
	 * 
	 * @return Date
	 */
	public Date getCasVytvorenia() {
		return casVytvorenia;
	}

	/**
	 * Set the value of CasVytvorenia
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasVytvorenia(Date v) {

		if (!ObjectUtils.equals(this.casVytvorenia, v)) {
			this.casVytvorenia = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasZmeny
	 * 
	 * @return Date
	 */
	public Date getCasZmeny() {
		return casZmeny;
	}

	/**
	 * Set the value of CasZmeny
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasZmeny(Date v) {

		if (!ObjectUtils.equals(this.casZmeny, v)) {
			this.casZmeny = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdZmena
	 * 
	 * @return Integer
	 */
	public Integer getIdZmena() {
		return idZmena;
	}

	/**
	 * Set the value of IdZmena
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdZmena(Integer v) {

		if (!ObjectUtils.equals(this.idZmena, v)) {
			this.idZmena = v;
			setModified(true);
		}

	}

	/**
	 * Get the Zmaz
	 * 
	 * @return String
	 */
	public String getZmaz() {
		return zmaz;
	}

	/**
	 * Set the value of Zmaz
	 * 
	 * @param v
	 *            new value
	 */
	public void setZmaz(String v) {

		if (!ObjectUtils.equals(this.zmaz, v)) {
			this.zmaz = v;
			setModified(true);
		}

	}

	/**
	 * Get the VozenUcelenejJednotkyId
	 * 
	 * @return Integer
	 */
	public Integer getVozenUcelenejJednotkyId() {
		return vozenUcelenejJednotkyId;
	}

	/**
	 * Set the value of VozenUcelenejJednotkyId
	 * 
	 * @param v
	 *            new value
	 */
	public void setVozenUcelenejJednotkyId(Integer v) {

		if (!ObjectUtils.equals(this.vozenUcelenejJednotkyId, v)) {
			this.vozenUcelenejJednotkyId = v;
			setModified(true);
		}

	}

	/**
	 * Get the Cislo
	 * 
	 * @return String
	 */
	public String getCislo() {
		return cislo;
	}

	/**
	 * Set the value of Cislo
	 * 
	 * @param v
	 *            new value
	 */
	public void setCislo(String v) {

		if (!ObjectUtils.equals(this.cislo, v)) {
			this.cislo = v;
			setModified(true);
		}

	}

	/**
	 * Get the Dlzka
	 * 
	 * @return Integer
	 */
	public Integer getDlzka() {
		return dlzka;
	}

	/**
	 * Set the value of Dlzka
	 * 
	 * @param v
	 *            new value
	 */
	public void setDlzka(Integer v) {

		if (!ObjectUtils.equals(this.dlzka, v)) {
			this.dlzka = v;
			setModified(true);
		}

	}

	/**
	 * Get the Napravy
	 * 
	 * @return Integer
	 */
	public Integer getNapravy() {
		return napravy;
	}

	/**
	 * Set the value of Napravy
	 * 
	 * @param v
	 *            new value
	 */
	public void setNapravy(Integer v) {

		if (!ObjectUtils.equals(this.napravy, v)) {
			this.napravy = v;
			setModified(true);
		}

	}

	/**
	 * Get the Hmotnost
	 * 
	 * @return Integer
	 */
	public Integer getHmotnost() {
		return hmotnost;
	}

	/**
	 * Set the value of Hmotnost
	 * 
	 * @param v
	 *            new value
	 */
	public void setHmotnost(Integer v) {

		if (!ObjectUtils.equals(this.hmotnost, v)) {
			this.hmotnost = v;
			setModified(true);
		}

	}

	/**
	 * Get the HmotnostPrazdneho
	 * 
	 * @return Integer
	 */
	public Integer getHmotnostPrazdneho() {
		return hmotnostPrazdneho;
	}

	/**
	 * Set the value of HmotnostPrazdneho
	 * 
	 * @param v
	 *            new value
	 */
	public void setHmotnostPrazdneho(Integer v) {

		if (!ObjectUtils.equals(this.hmotnostPrazdneho, v)) {
			this.hmotnostPrazdneho = v;
			setModified(true);
		}

	}

	/**
	 * Get the Rad
	 * 
	 * @return String
	 */
	public String getRad() {
		return rad;
	}

	/**
	 * Set the value of Rad
	 * 
	 * @param v
	 *            new value
	 */
	public void setRad(String v) {

		if (!ObjectUtils.equals(this.rad, v)) {
			this.rad = v;
			setModified(true);
		}

	}

	/**
	 * Get the PismenoveOznacenieVozna
	 * 
	 * @return String
	 */
	public String getPismenoveOznacenieVozna() {
		return pismenoveOznacenieVozna;
	}

	/**
	 * Set the value of PismenoveOznacenieVozna
	 * 
	 * @param v
	 *            new value
	 */
	public void setPismenoveOznacenieVozna(String v) {

		if (!ObjectUtils.equals(this.pismenoveOznacenieVozna, v)) {
			this.pismenoveOznacenieVozna = v;
			setModified(true);
		}

	}

	/**
	 * Get the Poznamka
	 * 
	 * @return String
	 */
	public String getPoznamka() {
		return poznamka;
	}

	/**
	 * Set the value of Poznamka
	 * 
	 * @param v
	 *            new value
	 */
	public void setPoznamka(String v) {

		if (!ObjectUtils.equals(this.poznamka, v)) {
			this.poznamka = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdUcelenaJednotka
	 * 
	 * @return Integer
	 */
	public Integer getIdUcelenaJednotka() {
		return idUcelenaJednotka;
	}

	/**
	 * Set the value of IdUcelenaJednotka
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdUcelenaJednotka(Integer v) {

		if (!ObjectUtils.equals(this.idUcelenaJednotka, v)) {
			this.idUcelenaJednotka = v;
			setModified(true);
		}

	}

	private static List fieldNames = null;

	/**
	 * Generate a list of field names.
	 * 
	 * @return a list of field names
	 */
	public static synchronized List getFieldNames() {
		if (fieldNames == null) {
			fieldNames = new ArrayList();
			fieldNames.add("HistId");
			fieldNames.add("PlatnostOd");
			fieldNames.add("PlatnostDo");
			fieldNames.add("CasVytvorenia");
			fieldNames.add("CasZmeny");
			fieldNames.add("IdZmena");
			fieldNames.add("Zmaz");
			fieldNames.add("VozenUcelenejJednotkyId");
			fieldNames.add("Cislo");
			fieldNames.add("Dlzka");
			fieldNames.add("Napravy");
			fieldNames.add("Hmotnost");
			fieldNames.add("HmotnostPrazdneho");
			fieldNames.add("Rad");
			fieldNames.add("PismenoveOznacenieVozna");
			fieldNames.add("Poznamka");
			fieldNames.add("IdUcelenaJednotka");
			fieldNames = Collections.unmodifiableList(fieldNames);
		}
		return fieldNames;
	}

	/**
	 * Retrieves a field from the object by field (Java) name passed in as a String.
	 * 
	 * @param name
	 *            field name
	 * @return value
	 */
	public Object getByName(String name) {
		if (name.equals("HistId")) {
			return getHistId();
		}
		if (name.equals("PlatnostOd")) {
			return getPlatnostOd();
		}
		if (name.equals("PlatnostDo")) {
			return getPlatnostDo();
		}
		if (name.equals("CasVytvorenia")) {
			return getCasVytvorenia();
		}
		if (name.equals("CasZmeny")) {
			return getCasZmeny();
		}
		if (name.equals("IdZmena")) {
			return getIdZmena();
		}
		if (name.equals("Zmaz")) {
			return getZmaz();
		}
		if (name.equals("VozenUcelenejJednotkyId")) {
			return getVozenUcelenejJednotkyId();
		}
		if (name.equals("Cislo")) {
			return getCislo();
		}
		if (name.equals("Dlzka")) {
			return getDlzka();
		}
		if (name.equals("Napravy")) {
			return getNapravy();
		}
		if (name.equals("Hmotnost")) {
			return getHmotnost();
		}
		if (name.equals("HmotnostPrazdneho")) {
			return getHmotnostPrazdneho();
		}
		if (name.equals("Rad")) {
			return getRad();
		}
		if (name.equals("PismenoveOznacenieVozna")) {
			return getPismenoveOznacenieVozna();
		}
		if (name.equals("Poznamka")) {
			return getPoznamka();
		}
		if (name.equals("IdUcelenaJednotka")) {
			return getIdUcelenaJednotka();
		}
		return null;
	}

	/**
	 * Set a field in the object by field (Java) name.
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (name.equals("HistId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHistId((Integer) value);
			return true;
		}
		if (name.equals("PlatnostOd")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostOd((Date) value);
			return true;
		}
		if (name.equals("PlatnostDo")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostDo((Date) value);
			return true;
		}
		if (name.equals("CasVytvorenia")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasVytvorenia((Date) value);
			return true;
		}
		if (name.equals("CasZmeny")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasZmeny((Date) value);
			return true;
		}
		if (name.equals("IdZmena")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdZmena((Integer) value);
			return true;
		}
		if (name.equals("Zmaz")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setZmaz((String) value);
			return true;
		}
		if (name.equals("VozenUcelenejJednotkyId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setVozenUcelenejJednotkyId((Integer) value);
			return true;
		}
		if (name.equals("Cislo")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCislo((String) value);
			return true;
		}
		if (name.equals("Dlzka")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setDlzka((Integer) value);
			return true;
		}
		if (name.equals("Napravy")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setNapravy((Integer) value);
			return true;
		}
		if (name.equals("Hmotnost")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHmotnost((Integer) value);
			return true;
		}
		if (name.equals("HmotnostPrazdneho")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHmotnostPrazdneho((Integer) value);
			return true;
		}
		if (name.equals("Rad")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setRad((String) value);
			return true;
		}
		if (name.equals("PismenoveOznacenieVozna")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPismenoveOznacenieVozna((String) value);
			return true;
		}
		if (name.equals("Poznamka")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPoznamka((String) value);
			return true;
		}
		if (name.equals("IdUcelenaJednotka")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdUcelenaJednotka((Integer) value);
			return true;
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by name passed in as a String. The String must be one of the static Strings defined in this Class' Peer.
	 * 
	 * @param name
	 *            peer name
	 * @return value
	 */
	public Object getByPeerName(String name) {
		if (name.equals(TVozenUcelenejJednotkyPeer.HIST_ID)) {
			return getHistId();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.PLATNOST_OD)) {
			return getPlatnostOd();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.PLATNOST_DO)) {
			return getPlatnostDo();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.CAS_VYTVORENIA)) {
			return getCasVytvorenia();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.CAS_ZMENY)) {
			return getCasZmeny();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.ID_ZMENA)) {
			return getIdZmena();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.ZMAZ)) {
			return getZmaz();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.VOZEN_UCELENEJ_JEDNOTKY_ID)) {
			return getVozenUcelenejJednotkyId();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.CISLO)) {
			return getCislo();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.DLZKA)) {
			return getDlzka();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.NAPRAVY)) {
			return getNapravy();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.HMOTNOST)) {
			return getHmotnost();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.HMOTNOST_PRAZDNEHO)) {
			return getHmotnostPrazdneho();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.RAD)) {
			return getRad();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.PISMENOVE_OZNACENIE_VOZNA)) {
			return getPismenoveOznacenieVozna();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.POZNAMKA)) {
			return getPoznamka();
		}
		if (name.equals(TVozenUcelenejJednotkyPeer.ID_UCELENA_JEDNOTKA)) {
			return getIdUcelenaJednotka();
		}
		return null;
	}

	/**
	 * Set field values by Peer Field Name
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPeerName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (TVozenUcelenejJednotkyPeer.HIST_ID.equals(name)) {
			return setByName("HistId", value);
		}
		if (TVozenUcelenejJednotkyPeer.PLATNOST_OD.equals(name)) {
			return setByName("PlatnostOd", value);
		}
		if (TVozenUcelenejJednotkyPeer.PLATNOST_DO.equals(name)) {
			return setByName("PlatnostDo", value);
		}
		if (TVozenUcelenejJednotkyPeer.CAS_VYTVORENIA.equals(name)) {
			return setByName("CasVytvorenia", value);
		}
		if (TVozenUcelenejJednotkyPeer.CAS_ZMENY.equals(name)) {
			return setByName("CasZmeny", value);
		}
		if (TVozenUcelenejJednotkyPeer.ID_ZMENA.equals(name)) {
			return setByName("IdZmena", value);
		}
		if (TVozenUcelenejJednotkyPeer.ZMAZ.equals(name)) {
			return setByName("Zmaz", value);
		}
		if (TVozenUcelenejJednotkyPeer.VOZEN_UCELENEJ_JEDNOTKY_ID.equals(name)) {
			return setByName("VozenUcelenejJednotkyId", value);
		}
		if (TVozenUcelenejJednotkyPeer.CISLO.equals(name)) {
			return setByName("Cislo", value);
		}
		if (TVozenUcelenejJednotkyPeer.DLZKA.equals(name)) {
			return setByName("Dlzka", value);
		}
		if (TVozenUcelenejJednotkyPeer.NAPRAVY.equals(name)) {
			return setByName("Napravy", value);
		}
		if (TVozenUcelenejJednotkyPeer.HMOTNOST.equals(name)) {
			return setByName("Hmotnost", value);
		}
		if (TVozenUcelenejJednotkyPeer.HMOTNOST_PRAZDNEHO.equals(name)) {
			return setByName("HmotnostPrazdneho", value);
		}
		if (TVozenUcelenejJednotkyPeer.RAD.equals(name)) {
			return setByName("Rad", value);
		}
		if (TVozenUcelenejJednotkyPeer.PISMENOVE_OZNACENIE_VOZNA.equals(name)) {
			return setByName("PismenoveOznacenieVozna", value);
		}
		if (TVozenUcelenejJednotkyPeer.POZNAMKA.equals(name)) {
			return setByName("Poznamka", value);
		}
		if (TVozenUcelenejJednotkyPeer.ID_UCELENA_JEDNOTKA.equals(name)) {
			return setByName("IdUcelenaJednotka", value);
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema. Zero-based.
	 * 
	 * @param pos
	 *            position in xml schema
	 * @return value
	 */
	public Object getByPosition(int pos) {
		if (pos == 0) {
			return getHistId();
		}
		if (pos == 1) {
			return getPlatnostOd();
		}
		if (pos == 2) {
			return getPlatnostDo();
		}
		if (pos == 3) {
			return getCasVytvorenia();
		}
		if (pos == 4) {
			return getCasZmeny();
		}
		if (pos == 5) {
			return getIdZmena();
		}
		if (pos == 6) {
			return getZmaz();
		}
		if (pos == 7) {
			return getVozenUcelenejJednotkyId();
		}
		if (pos == 8) {
			return getCislo();
		}
		if (pos == 9) {
			return getDlzka();
		}
		if (pos == 10) {
			return getNapravy();
		}
		if (pos == 11) {
			return getHmotnost();
		}
		if (pos == 12) {
			return getHmotnostPrazdneho();
		}
		if (pos == 13) {
			return getRad();
		}
		if (pos == 14) {
			return getPismenoveOznacenieVozna();
		}
		if (pos == 15) {
			return getPoznamka();
		}
		if (pos == 16) {
			return getIdUcelenaJednotka();
		}
		return null;
	}

	/**
	 * Set field values by its position (zero based) in the XML schema.
	 * 
	 * @param position
	 *            The field position
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid position / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPosition(int position, Object value) throws TorqueException, IllegalArgumentException {
		if (position == 0) {
			return setByName("HistId", value);
		}
		if (position == 1) {
			return setByName("PlatnostOd", value);
		}
		if (position == 2) {
			return setByName("PlatnostDo", value);
		}
		if (position == 3) {
			return setByName("CasVytvorenia", value);
		}
		if (position == 4) {
			return setByName("CasZmeny", value);
		}
		if (position == 5) {
			return setByName("IdZmena", value);
		}
		if (position == 6) {
			return setByName("Zmaz", value);
		}
		if (position == 7) {
			return setByName("VozenUcelenejJednotkyId", value);
		}
		if (position == 8) {
			return setByName("Cislo", value);
		}
		if (position == 9) {
			return setByName("Dlzka", value);
		}
		if (position == 10) {
			return setByName("Napravy", value);
		}
		if (position == 11) {
			return setByName("Hmotnost", value);
		}
		if (position == 12) {
			return setByName("HmotnostPrazdneho", value);
		}
		if (position == 13) {
			return setByName("Rad", value);
		}
		if (position == 14) {
			return setByName("PismenoveOznacenieVozna", value);
		}
		if (position == 15) {
			return setByName("Poznamka", value);
		}
		if (position == 16) {
			return setByName("IdUcelenaJednotka", value);
		}
		return false;
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed.
	 * 
	 * @throws Exception
	 */
	public void save() throws Exception {
		save(TVozenUcelenejJednotkyPeer.DATABASE_NAME);
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. Note: this code is here because the method body is auto-generated
	 * conditionally and therefore needs to be in this file instead of in the super class, BaseObject.
	 * 
	 * @param dbName
	 * @throws TorqueException
	 */
	public void save(String dbName) throws TorqueException {
		Connection con = null;
		try {
			con = Transaction.begin(dbName);
			save(con);
			Transaction.commit(con);
		} catch (TorqueException e) {
			Transaction.safeRollback(con);
			throw e;
		}
	}

	/**
	 * flag to prevent endless save loop, if this object is referenced by another object which falls in this transaction.
	 */
	private boolean alreadyInSave = false;

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. This method is meant to be used as part of a transaction, otherwise
	 * use the save() method and the connection details will be handled internally
	 * 
	 * @param con
	 * @throws TorqueException
	 */
	public void save(Connection con) throws TorqueException {
		if (!alreadyInSave) {
			alreadyInSave = true;

			// If this object has been modified, then save it to the database.
			if (isModified()) {
				if (isNew()) {
					TVozenUcelenejJednotkyPeer.doInsert((TVozenUcelenejJednotky) this, con);
					setNew(false);
				} else {
					TVozenUcelenejJednotkyPeer.doUpdate((TVozenUcelenejJednotky) this, con);
				}
			}

			alreadyInSave = false;
		}
	}

	/**
	 * Set the PrimaryKey using ObjectKey.
	 * 
	 * @param key
	 *            histId ObjectKey
	 */
	public void setPrimaryKey(ObjectKey key)

	{
		setHistId(new Integer(((NumberKey) key).intValue()));
	}

	/**
	 * Set the PrimaryKey using a String.
	 * 
	 * @param key
	 */
	public void setPrimaryKey(String key) {
		setHistId(new Integer(key));
	}

	/**
	 * returns an id that differentiates this object from others of its class.
	 */
	public ObjectKey getPrimaryKey() {
		return SimpleKey.keyFor(getHistId());
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. It then fills all the association collections and sets the related objects to
	 * isNew=true.
	 */
	public TVozenUcelenejJednotky copy() throws TorqueException {
		return copy(true);
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. If the parameter deepcopy is true, it then fills all the association collections and
	 * sets the related objects to isNew=true.
	 * 
	 * @param deepcopy
	 *            whether to copy the associated objects.
	 */
	public TVozenUcelenejJednotky copy(boolean deepcopy) throws TorqueException {
		return copyInto(new TVozenUcelenejJednotky(), deepcopy);
	}

	/**
	 * Fills the copyObj with the contents of this object. The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 */
	protected TVozenUcelenejJednotky copyInto(TVozenUcelenejJednotky copyObj) throws TorqueException {
		return copyInto(copyObj, true);
	}

	/**
	 * Fills the copyObj with the contents of this object. If deepcopy is true, The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 * @param deepcopy
	 *            whether the associated objects should be copied.
	 */
	protected TVozenUcelenejJednotky copyInto(TVozenUcelenejJednotky copyObj, boolean deepcopy) throws TorqueException {
		copyObj.setHistId(histId);
		copyObj.setPlatnostOd(platnostOd);
		copyObj.setPlatnostDo(platnostDo);
		copyObj.setCasVytvorenia(casVytvorenia);
		copyObj.setCasZmeny(casZmeny);
		copyObj.setIdZmena(idZmena);
		copyObj.setZmaz(zmaz);
		copyObj.setVozenUcelenejJednotkyId(vozenUcelenejJednotkyId);
		copyObj.setCislo(cislo);
		copyObj.setDlzka(dlzka);
		copyObj.setNapravy(napravy);
		copyObj.setHmotnost(hmotnost);
		copyObj.setHmotnostPrazdneho(hmotnostPrazdneho);
		copyObj.setRad(rad);
		copyObj.setPismenoveOznacenieVozna(pismenoveOznacenieVozna);
		copyObj.setPoznamka(poznamka);
		copyObj.setIdUcelenaJednotka(idUcelenaJednotka);

		copyObj.setHistId((Integer) null);

		if (deepcopy) {
		}
		return copyObj;
	}

	/**
	 * returns a peer instance associated with this om. Since Peer classes are not to have any instance attributes, this method returns the same instance for all member of this
	 * class. The method could therefore be static, but this would prevent one from overriding the behavior.
	 */
	public TVozenUcelenejJednotkyPeer getPeer() {
		return peer;
	}

	/**
	 * Retrieves the TableMap object related to this Table data without compiler warnings of using getPeer().getTableMap().
	 * 
	 * @return The associated TableMap object.
	 */
	public TableMap getTableMap() throws TorqueException {
		return TVozenUcelenejJednotkyPeer.getTableMap();
	}

	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("TVozenUcelenejJednotky:\n");
		str.append("HistId = ").append(getHistId()).append("\n");
		str.append("PlatnostOd = ").append(getPlatnostOd()).append("\n");
		str.append("PlatnostDo = ").append(getPlatnostDo()).append("\n");
		str.append("CasVytvorenia = ").append(getCasVytvorenia()).append("\n");
		str.append("CasZmeny = ").append(getCasZmeny()).append("\n");
		str.append("IdZmena = ").append(getIdZmena()).append("\n");
		str.append("Zmaz = ").append(getZmaz()).append("\n");
		str.append("VozenUcelenejJednotkyId = ").append(getVozenUcelenejJednotkyId()).append("\n");
		str.append("Cislo = ").append(getCislo()).append("\n");
		str.append("Dlzka = ").append(getDlzka()).append("\n");
		str.append("Napravy = ").append(getNapravy()).append("\n");
		str.append("Hmotnost = ").append(getHmotnost()).append("\n");
		str.append("HmotnostPrazdneho = ").append(getHmotnostPrazdneho()).append("\n");
		str.append("Rad = ").append(getRad()).append("\n");
		str.append("PismenoveOznacenieVozna = ").append(getPismenoveOznacenieVozna()).append("\n");
		str.append("Poznamka = ").append(getPoznamka()).append("\n");
		str.append("IdUcelenaJednotka = ").append(getIdUcelenaJednotka()).append("\n");
		return (str.toString());
	}
}
