package sk.ditec.dao.master;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Fri Jul 25 14:44:46 CEST 2025]
 * 
 * You should not use this class directly. It should not even be extended all references should be to THnacieDrahoveVozidlo
 */
public abstract class BaseTHnacieDrahoveVozidlo extends BaseObject {
	/** Serial version */
	private static final long serialVersionUID = 1753447486539L;

	/** The Peer class */
	private static final THnacieDrahoveVozidloPeer peer = new THnacieDrahoveVozidloPeer();

	/** The value for the histId field */
	private Integer histId;

	/** The value for the platnostOd field */
	private Date platnostOd;

	/** The value for the platnostDo field */
	private Date platnostDo;

	/** The value for the casVytvorenia field */
	private Date casVytvorenia;

	/** The value for the casZmeny field */
	private Date casZmeny;

	/** The value for the idZmena field */
	private Integer idZmena;

	/** The value for the zmaz field */
	private String zmaz;

	/** The value for the hnacieDrahoveVozidloId field */
	private Integer hnacieDrahoveVozidloId;

	/** The value for the cislo7 field */
	private String cislo7;

	/** The value for the cislo12 field */
	private String cislo12;

	/** The value for the nestandardne field */
	private String nestandardne;

	/** The value for the idRadHdv field */
	private Integer idRadHdv;

	/** The value for the dlzka field */
	private Double dlzka;

	/** The value for the pocetNaprav field */
	private Integer pocetNaprav;

	/** The value for the hmotnost field */
	private Double hmotnost;

	/** The value for the brzdiacaHmotnostG field */
	private String brzdiacaHmotnostG;

	/** The value for the brzdiacaHmotnostP field */
	private String brzdiacaHmotnostP;

	/** The value for the brzdiacaHmotnostR field */
	private String brzdiacaHmotnostR;

	/** The value for the brzdiacaHmotnostGe field */
	private String brzdiacaHmotnostGe;

	/** The value for the brzdiacaHmotnostPe field */
	private String brzdiacaHmotnostPe;

	/** The value for the brzdiacaHmotnostRe field */
	private String brzdiacaHmotnostRe;

	/** The value for the idTrakciaHdv field */
	private Integer idTrakciaHdv;

	/** The value for the idVlastnickaZeleznica field */
	private Integer idVlastnickaZeleznica;

	/** The value for the idVlastnikHdv field */
	private Integer idVlastnikHdv;

	/** The value for the poznamka field */
	private String poznamka;

	/** The value for the hmotnostPrazdnejJednotky field */
	private Double hmotnostPrazdnejJednotky;

	/** The value for the telefonHkv field */
	private String telefonHkv;

	/** The value for the idUcelenaJednotka field */
	private Integer idUcelenaJednotka;

	/**
	 * Get the HistId
	 * 
	 * @return Integer
	 */
	public Integer getHistId() {
		return histId;
	}

	/**
	 * Set the value of HistId
	 * 
	 * @param v
	 *            new value
	 */
	public void setHistId(Integer v) {

		if (!ObjectUtils.equals(this.histId, v)) {
			this.histId = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostOd
	 * 
	 * @return Date
	 */
	public Date getPlatnostOd() {
		return platnostOd;
	}

	/**
	 * Set the value of PlatnostOd
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostOd(Date v) {

		if (!ObjectUtils.equals(this.platnostOd, v)) {
			this.platnostOd = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostDo
	 * 
	 * @return Date
	 */
	public Date getPlatnostDo() {
		return platnostDo;
	}

	/**
	 * Set the value of PlatnostDo
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostDo(Date v) {

		if (!ObjectUtils.equals(this.platnostDo, v)) {
			this.platnostDo = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasVytvorenia
	 * 
	 * @return Date
	 */
	public Date getCasVytvorenia() {
		return casVytvorenia;
	}

	/**
	 * Set the value of CasVytvorenia
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasVytvorenia(Date v) {

		if (!ObjectUtils.equals(this.casVytvorenia, v)) {
			this.casVytvorenia = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasZmeny
	 * 
	 * @return Date
	 */
	public Date getCasZmeny() {
		return casZmeny;
	}

	/**
	 * Set the value of CasZmeny
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasZmeny(Date v) {

		if (!ObjectUtils.equals(this.casZmeny, v)) {
			this.casZmeny = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdZmena
	 * 
	 * @return Integer
	 */
	public Integer getIdZmena() {
		return idZmena;
	}

	/**
	 * Set the value of IdZmena
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdZmena(Integer v) {

		if (!ObjectUtils.equals(this.idZmena, v)) {
			this.idZmena = v;
			setModified(true);
		}

	}

	/**
	 * Get the Zmaz
	 * 
	 * @return String
	 */
	public String getZmaz() {
		return zmaz;
	}

	/**
	 * Set the value of Zmaz
	 * 
	 * @param v
	 *            new value
	 */
	public void setZmaz(String v) {

		if (!ObjectUtils.equals(this.zmaz, v)) {
			this.zmaz = v;
			setModified(true);
		}

	}

	/**
	 * Get the HnacieDrahoveVozidloId
	 * 
	 * @return Integer
	 */
	public Integer getHnacieDrahoveVozidloId() {
		return hnacieDrahoveVozidloId;
	}

	/**
	 * Set the value of HnacieDrahoveVozidloId
	 * 
	 * @param v
	 *            new value
	 */
	public void setHnacieDrahoveVozidloId(Integer v) {

		if (!ObjectUtils.equals(this.hnacieDrahoveVozidloId, v)) {
			this.hnacieDrahoveVozidloId = v;
			setModified(true);
		}

	}

	/**
	 * Get the Cislo7
	 * 
	 * @return String
	 */
	public String getCislo7() {
		return cislo7;
	}

	/**
	 * Set the value of Cislo7
	 * 
	 * @param v
	 *            new value
	 */
	public void setCislo7(String v) {

		if (!ObjectUtils.equals(this.cislo7, v)) {
			this.cislo7 = v;
			setModified(true);
		}

	}

	/**
	 * Get the Cislo12
	 * 
	 * @return String
	 */
	public String getCislo12() {
		return cislo12;
	}

	/**
	 * Set the value of Cislo12
	 * 
	 * @param v
	 *            new value
	 */
	public void setCislo12(String v) {

		if (!ObjectUtils.equals(this.cislo12, v)) {
			this.cislo12 = v;
			setModified(true);
		}

	}

	/**
	 * Get the Nestandardne
	 * 
	 * @return String
	 */
	public String getNestandardne() {
		return nestandardne;
	}

	/**
	 * Set the value of Nestandardne
	 * 
	 * @param v
	 *            new value
	 */
	public void setNestandardne(String v) {

		if (!ObjectUtils.equals(this.nestandardne, v)) {
			this.nestandardne = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdRadHdv
	 * 
	 * @return Integer
	 */
	public Integer getIdRadHdv() {
		return idRadHdv;
	}

	/**
	 * Set the value of IdRadHdv
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdRadHdv(Integer v) {

		if (!ObjectUtils.equals(this.idRadHdv, v)) {
			this.idRadHdv = v;
			setModified(true);
		}

	}

	/**
	 * Get the Dlzka
	 * 
	 * @return Double
	 */
	public Double getDlzka() {
		return dlzka;
	}

	/**
	 * Set the value of Dlzka
	 * 
	 * @param v
	 *            new value
	 */
	public void setDlzka(Double v) {

		if (!ObjectUtils.equals(this.dlzka, v)) {
			this.dlzka = v;
			setModified(true);
		}

	}

	/**
	 * Get the PocetNaprav
	 * 
	 * @return Integer
	 */
	public Integer getPocetNaprav() {
		return pocetNaprav;
	}

	/**
	 * Set the value of PocetNaprav
	 * 
	 * @param v
	 *            new value
	 */
	public void setPocetNaprav(Integer v) {

		if (!ObjectUtils.equals(this.pocetNaprav, v)) {
			this.pocetNaprav = v;
			setModified(true);
		}

	}

	/**
	 * Get the Hmotnost
	 * 
	 * @return Double
	 */
	public Double getHmotnost() {
		return hmotnost;
	}

	/**
	 * Set the value of Hmotnost
	 * 
	 * @param v
	 *            new value
	 */
	public void setHmotnost(Double v) {

		if (!ObjectUtils.equals(this.hmotnost, v)) {
			this.hmotnost = v;
			setModified(true);
		}

	}

	/**
	 * Get the BrzdiacaHmotnostG
	 * 
	 * @return String
	 */
	public String getBrzdiacaHmotnostG() {
		return brzdiacaHmotnostG;
	}

	/**
	 * Set the value of BrzdiacaHmotnostG
	 * 
	 * @param v
	 *            new value
	 */
	public void setBrzdiacaHmotnostG(String v) {

		if (!ObjectUtils.equals(this.brzdiacaHmotnostG, v)) {
			this.brzdiacaHmotnostG = v;
			setModified(true);
		}

	}

	/**
	 * Get the BrzdiacaHmotnostP
	 * 
	 * @return String
	 */
	public String getBrzdiacaHmotnostP() {
		return brzdiacaHmotnostP;
	}

	/**
	 * Set the value of BrzdiacaHmotnostP
	 * 
	 * @param v
	 *            new value
	 */
	public void setBrzdiacaHmotnostP(String v) {

		if (!ObjectUtils.equals(this.brzdiacaHmotnostP, v)) {
			this.brzdiacaHmotnostP = v;
			setModified(true);
		}

	}

	/**
	 * Get the BrzdiacaHmotnostR
	 * 
	 * @return String
	 */
	public String getBrzdiacaHmotnostR() {
		return brzdiacaHmotnostR;
	}

	/**
	 * Set the value of BrzdiacaHmotnostR
	 * 
	 * @param v
	 *            new value
	 */
	public void setBrzdiacaHmotnostR(String v) {

		if (!ObjectUtils.equals(this.brzdiacaHmotnostR, v)) {
			this.brzdiacaHmotnostR = v;
			setModified(true);
		}

	}

	/**
	 * Get the BrzdiacaHmotnostGe
	 * 
	 * @return String
	 */
	public String getBrzdiacaHmotnostGe() {
		return brzdiacaHmotnostGe;
	}

	/**
	 * Set the value of BrzdiacaHmotnostGe
	 * 
	 * @param v
	 *            new value
	 */
	public void setBrzdiacaHmotnostGe(String v) {

		if (!ObjectUtils.equals(this.brzdiacaHmotnostGe, v)) {
			this.brzdiacaHmotnostGe = v;
			setModified(true);
		}

	}

	/**
	 * Get the BrzdiacaHmotnostPe
	 * 
	 * @return String
	 */
	public String getBrzdiacaHmotnostPe() {
		return brzdiacaHmotnostPe;
	}

	/**
	 * Set the value of BrzdiacaHmotnostPe
	 * 
	 * @param v
	 *            new value
	 */
	public void setBrzdiacaHmotnostPe(String v) {

		if (!ObjectUtils.equals(this.brzdiacaHmotnostPe, v)) {
			this.brzdiacaHmotnostPe = v;
			setModified(true);
		}

	}

	/**
	 * Get the BrzdiacaHmotnostRe
	 * 
	 * @return String
	 */
	public String getBrzdiacaHmotnostRe() {
		return brzdiacaHmotnostRe;
	}

	/**
	 * Set the value of BrzdiacaHmotnostRe
	 * 
	 * @param v
	 *            new value
	 */
	public void setBrzdiacaHmotnostRe(String v) {

		if (!ObjectUtils.equals(this.brzdiacaHmotnostRe, v)) {
			this.brzdiacaHmotnostRe = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdTrakciaHdv
	 * 
	 * @return Integer
	 */
	public Integer getIdTrakciaHdv() {
		return idTrakciaHdv;
	}

	/**
	 * Set the value of IdTrakciaHdv
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdTrakciaHdv(Integer v) {

		if (!ObjectUtils.equals(this.idTrakciaHdv, v)) {
			this.idTrakciaHdv = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdVlastnickaZeleznica
	 * 
	 * @return Integer
	 */
	public Integer getIdVlastnickaZeleznica() {
		return idVlastnickaZeleznica;
	}

	/**
	 * Set the value of IdVlastnickaZeleznica
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdVlastnickaZeleznica(Integer v) {

		if (!ObjectUtils.equals(this.idVlastnickaZeleznica, v)) {
			this.idVlastnickaZeleznica = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdVlastnikHdv
	 * 
	 * @return Integer
	 */
	public Integer getIdVlastnikHdv() {
		return idVlastnikHdv;
	}

	/**
	 * Set the value of IdVlastnikHdv
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdVlastnikHdv(Integer v) {

		if (!ObjectUtils.equals(this.idVlastnikHdv, v)) {
			this.idVlastnikHdv = v;
			setModified(true);
		}

	}

	/**
	 * Get the Poznamka
	 * 
	 * @return String
	 */
	public String getPoznamka() {
		return poznamka;
	}

	/**
	 * Set the value of Poznamka
	 * 
	 * @param v
	 *            new value
	 */
	public void setPoznamka(String v) {

		if (!ObjectUtils.equals(this.poznamka, v)) {
			this.poznamka = v;
			setModified(true);
		}

	}

	/**
	 * Get the HmotnostPrazdnejJednotky
	 * 
	 * @return Double
	 */
	public Double getHmotnostPrazdnejJednotky() {
		return hmotnostPrazdnejJednotky;
	}

	/**
	 * Set the value of HmotnostPrazdnejJednotky
	 * 
	 * @param v
	 *            new value
	 */
	public void setHmotnostPrazdnejJednotky(Double v) {

		if (!ObjectUtils.equals(this.hmotnostPrazdnejJednotky, v)) {
			this.hmotnostPrazdnejJednotky = v;
			setModified(true);
		}

	}

	/**
	 * Get the TelefonHkv
	 * 
	 * @return String
	 */
	public String getTelefonHkv() {
		return telefonHkv;
	}

	/**
	 * Set the value of TelefonHkv
	 * 
	 * @param v
	 *            new value
	 */
	public void setTelefonHkv(String v) {

		if (!ObjectUtils.equals(this.telefonHkv, v)) {
			this.telefonHkv = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdUcelenaJednotka
	 * 
	 * @return Integer
	 */
	public Integer getIdUcelenaJednotka() {
		return idUcelenaJednotka;
	}

	/**
	 * Set the value of IdUcelenaJednotka
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdUcelenaJednotka(Integer v) {

		if (!ObjectUtils.equals(this.idUcelenaJednotka, v)) {
			this.idUcelenaJednotka = v;
			setModified(true);
		}

	}

	private static List fieldNames = null;

	/**
	 * Generate a list of field names.
	 * 
	 * @return a list of field names
	 */
	public static synchronized List getFieldNames() {
		if (fieldNames == null) {
			fieldNames = new ArrayList();
			fieldNames.add("HistId");
			fieldNames.add("PlatnostOd");
			fieldNames.add("PlatnostDo");
			fieldNames.add("CasVytvorenia");
			fieldNames.add("CasZmeny");
			fieldNames.add("IdZmena");
			fieldNames.add("Zmaz");
			fieldNames.add("HnacieDrahoveVozidloId");
			fieldNames.add("Cislo7");
			fieldNames.add("Cislo12");
			fieldNames.add("Nestandardne");
			fieldNames.add("IdRadHdv");
			fieldNames.add("Dlzka");
			fieldNames.add("PocetNaprav");
			fieldNames.add("Hmotnost");
			fieldNames.add("BrzdiacaHmotnostG");
			fieldNames.add("BrzdiacaHmotnostP");
			fieldNames.add("BrzdiacaHmotnostR");
			fieldNames.add("BrzdiacaHmotnostGe");
			fieldNames.add("BrzdiacaHmotnostPe");
			fieldNames.add("BrzdiacaHmotnostRe");
			fieldNames.add("IdTrakciaHdv");
			fieldNames.add("IdVlastnickaZeleznica");
			fieldNames.add("IdVlastnikHdv");
			fieldNames.add("Poznamka");
			fieldNames.add("HmotnostPrazdnejJednotky");
			fieldNames.add("TelefonHkv");
			fieldNames.add("IdUcelenaJednotka");
			fieldNames = Collections.unmodifiableList(fieldNames);
		}
		return fieldNames;
	}

	/**
	 * Retrieves a field from the object by field (Java) name passed in as a String.
	 * 
	 * @param name
	 *            field name
	 * @return value
	 */
	public Object getByName(String name) {
		if (name.equals("HistId")) {
			return getHistId();
		}
		if (name.equals("PlatnostOd")) {
			return getPlatnostOd();
		}
		if (name.equals("PlatnostDo")) {
			return getPlatnostDo();
		}
		if (name.equals("CasVytvorenia")) {
			return getCasVytvorenia();
		}
		if (name.equals("CasZmeny")) {
			return getCasZmeny();
		}
		if (name.equals("IdZmena")) {
			return getIdZmena();
		}
		if (name.equals("Zmaz")) {
			return getZmaz();
		}
		if (name.equals("HnacieDrahoveVozidloId")) {
			return getHnacieDrahoveVozidloId();
		}
		if (name.equals("Cislo7")) {
			return getCislo7();
		}
		if (name.equals("Cislo12")) {
			return getCislo12();
		}
		if (name.equals("Nestandardne")) {
			return getNestandardne();
		}
		if (name.equals("IdRadHdv")) {
			return getIdRadHdv();
		}
		if (name.equals("Dlzka")) {
			return getDlzka();
		}
		if (name.equals("PocetNaprav")) {
			return getPocetNaprav();
		}
		if (name.equals("Hmotnost")) {
			return getHmotnost();
		}
		if (name.equals("BrzdiacaHmotnostG")) {
			return getBrzdiacaHmotnostG();
		}
		if (name.equals("BrzdiacaHmotnostP")) {
			return getBrzdiacaHmotnostP();
		}
		if (name.equals("BrzdiacaHmotnostR")) {
			return getBrzdiacaHmotnostR();
		}
		if (name.equals("BrzdiacaHmotnostGe")) {
			return getBrzdiacaHmotnostGe();
		}
		if (name.equals("BrzdiacaHmotnostPe")) {
			return getBrzdiacaHmotnostPe();
		}
		if (name.equals("BrzdiacaHmotnostRe")) {
			return getBrzdiacaHmotnostRe();
		}
		if (name.equals("IdTrakciaHdv")) {
			return getIdTrakciaHdv();
		}
		if (name.equals("IdVlastnickaZeleznica")) {
			return getIdVlastnickaZeleznica();
		}
		if (name.equals("IdVlastnikHdv")) {
			return getIdVlastnikHdv();
		}
		if (name.equals("Poznamka")) {
			return getPoznamka();
		}
		if (name.equals("HmotnostPrazdnejJednotky")) {
			return getHmotnostPrazdnejJednotky();
		}
		if (name.equals("TelefonHkv")) {
			return getTelefonHkv();
		}
		if (name.equals("IdUcelenaJednotka")) {
			return getIdUcelenaJednotka();
		}
		return null;
	}

	/**
	 * Set a field in the object by field (Java) name.
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (name.equals("HistId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHistId((Integer) value);
			return true;
		}
		if (name.equals("PlatnostOd")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostOd((Date) value);
			return true;
		}
		if (name.equals("PlatnostDo")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostDo((Date) value);
			return true;
		}
		if (name.equals("CasVytvorenia")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasVytvorenia((Date) value);
			return true;
		}
		if (name.equals("CasZmeny")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasZmeny((Date) value);
			return true;
		}
		if (name.equals("IdZmena")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdZmena((Integer) value);
			return true;
		}
		if (name.equals("Zmaz")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setZmaz((String) value);
			return true;
		}
		if (name.equals("HnacieDrahoveVozidloId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHnacieDrahoveVozidloId((Integer) value);
			return true;
		}
		if (name.equals("Cislo7")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCislo7((String) value);
			return true;
		}
		if (name.equals("Cislo12")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCislo12((String) value);
			return true;
		}
		if (name.equals("Nestandardne")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setNestandardne((String) value);
			return true;
		}
		if (name.equals("IdRadHdv")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdRadHdv((Integer) value);
			return true;
		}
		if (name.equals("Dlzka")) {
			// Object fields can be null
			if (value != null && !Double.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setDlzka((Double) value);
			return true;
		}
		if (name.equals("PocetNaprav")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPocetNaprav((Integer) value);
			return true;
		}
		if (name.equals("Hmotnost")) {
			// Object fields can be null
			if (value != null && !Double.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHmotnost((Double) value);
			return true;
		}
		if (name.equals("BrzdiacaHmotnostG")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setBrzdiacaHmotnostG((String) value);
			return true;
		}
		if (name.equals("BrzdiacaHmotnostP")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setBrzdiacaHmotnostP((String) value);
			return true;
		}
		if (name.equals("BrzdiacaHmotnostR")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setBrzdiacaHmotnostR((String) value);
			return true;
		}
		if (name.equals("BrzdiacaHmotnostGe")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setBrzdiacaHmotnostGe((String) value);
			return true;
		}
		if (name.equals("BrzdiacaHmotnostPe")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setBrzdiacaHmotnostPe((String) value);
			return true;
		}
		if (name.equals("BrzdiacaHmotnostRe")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setBrzdiacaHmotnostRe((String) value);
			return true;
		}
		if (name.equals("IdTrakciaHdv")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdTrakciaHdv((Integer) value);
			return true;
		}
		if (name.equals("IdVlastnickaZeleznica")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdVlastnickaZeleznica((Integer) value);
			return true;
		}
		if (name.equals("IdVlastnikHdv")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdVlastnikHdv((Integer) value);
			return true;
		}
		if (name.equals("Poznamka")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPoznamka((String) value);
			return true;
		}
		if (name.equals("HmotnostPrazdnejJednotky")) {
			// Object fields can be null
			if (value != null && !Double.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHmotnostPrazdnejJednotky((Double) value);
			return true;
		}
		if (name.equals("TelefonHkv")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setTelefonHkv((String) value);
			return true;
		}
		if (name.equals("IdUcelenaJednotka")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdUcelenaJednotka((Integer) value);
			return true;
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by name passed in as a String. The String must be one of the static Strings defined in this Class' Peer.
	 * 
	 * @param name
	 *            peer name
	 * @return value
	 */
	public Object getByPeerName(String name) {
		if (name.equals(THnacieDrahoveVozidloPeer.HIST_ID)) {
			return getHistId();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.PLATNOST_OD)) {
			return getPlatnostOd();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.PLATNOST_DO)) {
			return getPlatnostDo();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.CAS_VYTVORENIA)) {
			return getCasVytvorenia();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.CAS_ZMENY)) {
			return getCasZmeny();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.ID_ZMENA)) {
			return getIdZmena();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.ZMAZ)) {
			return getZmaz();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.HNACIE_DRAHOVE_VOZIDLO_ID)) {
			return getHnacieDrahoveVozidloId();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.CISLO_7)) {
			return getCislo7();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.CISLO_12)) {
			return getCislo12();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.NESTANDARDNE)) {
			return getNestandardne();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.ID_RAD_HDV)) {
			return getIdRadHdv();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.DLZKA)) {
			return getDlzka();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.POCET_NAPRAV)) {
			return getPocetNaprav();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.HMOTNOST)) {
			return getHmotnost();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.BRZDIACA_HMOTNOST_G)) {
			return getBrzdiacaHmotnostG();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.BRZDIACA_HMOTNOST_P)) {
			return getBrzdiacaHmotnostP();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.BRZDIACA_HMOTNOST_R)) {
			return getBrzdiacaHmotnostR();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.BRZDIACA_HMOTNOST_GE)) {
			return getBrzdiacaHmotnostGe();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.BRZDIACA_HMOTNOST_PE)) {
			return getBrzdiacaHmotnostPe();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.BRZDIACA_HMOTNOST_RE)) {
			return getBrzdiacaHmotnostRe();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.ID_TRAKCIA_HDV)) {
			return getIdTrakciaHdv();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.ID_VLASTNICKA_ZELEZNICA)) {
			return getIdVlastnickaZeleznica();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.ID_VLASTNIK_HDV)) {
			return getIdVlastnikHdv();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.POZNAMKA)) {
			return getPoznamka();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.HMOTNOST_PRAZDNEJ_JEDNOTKY)) {
			return getHmotnostPrazdnejJednotky();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.TELEFON_HKV)) {
			return getTelefonHkv();
		}
		if (name.equals(THnacieDrahoveVozidloPeer.ID_UCELENA_JEDNOTKA)) {
			return getIdUcelenaJednotka();
		}
		return null;
	}

	/**
	 * Set field values by Peer Field Name
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPeerName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (THnacieDrahoveVozidloPeer.HIST_ID.equals(name)) {
			return setByName("HistId", value);
		}
		if (THnacieDrahoveVozidloPeer.PLATNOST_OD.equals(name)) {
			return setByName("PlatnostOd", value);
		}
		if (THnacieDrahoveVozidloPeer.PLATNOST_DO.equals(name)) {
			return setByName("PlatnostDo", value);
		}
		if (THnacieDrahoveVozidloPeer.CAS_VYTVORENIA.equals(name)) {
			return setByName("CasVytvorenia", value);
		}
		if (THnacieDrahoveVozidloPeer.CAS_ZMENY.equals(name)) {
			return setByName("CasZmeny", value);
		}
		if (THnacieDrahoveVozidloPeer.ID_ZMENA.equals(name)) {
			return setByName("IdZmena", value);
		}
		if (THnacieDrahoveVozidloPeer.ZMAZ.equals(name)) {
			return setByName("Zmaz", value);
		}
		if (THnacieDrahoveVozidloPeer.HNACIE_DRAHOVE_VOZIDLO_ID.equals(name)) {
			return setByName("HnacieDrahoveVozidloId", value);
		}
		if (THnacieDrahoveVozidloPeer.CISLO_7.equals(name)) {
			return setByName("Cislo7", value);
		}
		if (THnacieDrahoveVozidloPeer.CISLO_12.equals(name)) {
			return setByName("Cislo12", value);
		}
		if (THnacieDrahoveVozidloPeer.NESTANDARDNE.equals(name)) {
			return setByName("Nestandardne", value);
		}
		if (THnacieDrahoveVozidloPeer.ID_RAD_HDV.equals(name)) {
			return setByName("IdRadHdv", value);
		}
		if (THnacieDrahoveVozidloPeer.DLZKA.equals(name)) {
			return setByName("Dlzka", value);
		}
		if (THnacieDrahoveVozidloPeer.POCET_NAPRAV.equals(name)) {
			return setByName("PocetNaprav", value);
		}
		if (THnacieDrahoveVozidloPeer.HMOTNOST.equals(name)) {
			return setByName("Hmotnost", value);
		}
		if (THnacieDrahoveVozidloPeer.BRZDIACA_HMOTNOST_G.equals(name)) {
			return setByName("BrzdiacaHmotnostG", value);
		}
		if (THnacieDrahoveVozidloPeer.BRZDIACA_HMOTNOST_P.equals(name)) {
			return setByName("BrzdiacaHmotnostP", value);
		}
		if (THnacieDrahoveVozidloPeer.BRZDIACA_HMOTNOST_R.equals(name)) {
			return setByName("BrzdiacaHmotnostR", value);
		}
		if (THnacieDrahoveVozidloPeer.BRZDIACA_HMOTNOST_GE.equals(name)) {
			return setByName("BrzdiacaHmotnostGe", value);
		}
		if (THnacieDrahoveVozidloPeer.BRZDIACA_HMOTNOST_PE.equals(name)) {
			return setByName("BrzdiacaHmotnostPe", value);
		}
		if (THnacieDrahoveVozidloPeer.BRZDIACA_HMOTNOST_RE.equals(name)) {
			return setByName("BrzdiacaHmotnostRe", value);
		}
		if (THnacieDrahoveVozidloPeer.ID_TRAKCIA_HDV.equals(name)) {
			return setByName("IdTrakciaHdv", value);
		}
		if (THnacieDrahoveVozidloPeer.ID_VLASTNICKA_ZELEZNICA.equals(name)) {
			return setByName("IdVlastnickaZeleznica", value);
		}
		if (THnacieDrahoveVozidloPeer.ID_VLASTNIK_HDV.equals(name)) {
			return setByName("IdVlastnikHdv", value);
		}
		if (THnacieDrahoveVozidloPeer.POZNAMKA.equals(name)) {
			return setByName("Poznamka", value);
		}
		if (THnacieDrahoveVozidloPeer.HMOTNOST_PRAZDNEJ_JEDNOTKY.equals(name)) {
			return setByName("HmotnostPrazdnejJednotky", value);
		}
		if (THnacieDrahoveVozidloPeer.TELEFON_HKV.equals(name)) {
			return setByName("TelefonHkv", value);
		}
		if (THnacieDrahoveVozidloPeer.ID_UCELENA_JEDNOTKA.equals(name)) {
			return setByName("IdUcelenaJednotka", value);
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema. Zero-based.
	 * 
	 * @param pos
	 *            position in xml schema
	 * @return value
	 */
	public Object getByPosition(int pos) {
		if (pos == 0) {
			return getHistId();
		}
		if (pos == 1) {
			return getPlatnostOd();
		}
		if (pos == 2) {
			return getPlatnostDo();
		}
		if (pos == 3) {
			return getCasVytvorenia();
		}
		if (pos == 4) {
			return getCasZmeny();
		}
		if (pos == 5) {
			return getIdZmena();
		}
		if (pos == 6) {
			return getZmaz();
		}
		if (pos == 7) {
			return getHnacieDrahoveVozidloId();
		}
		if (pos == 8) {
			return getCislo7();
		}
		if (pos == 9) {
			return getCislo12();
		}
		if (pos == 10) {
			return getNestandardne();
		}
		if (pos == 11) {
			return getIdRadHdv();
		}
		if (pos == 12) {
			return getDlzka();
		}
		if (pos == 13) {
			return getPocetNaprav();
		}
		if (pos == 14) {
			return getHmotnost();
		}
		if (pos == 15) {
			return getBrzdiacaHmotnostG();
		}
		if (pos == 16) {
			return getBrzdiacaHmotnostP();
		}
		if (pos == 17) {
			return getBrzdiacaHmotnostR();
		}
		if (pos == 18) {
			return getBrzdiacaHmotnostGe();
		}
		if (pos == 19) {
			return getBrzdiacaHmotnostPe();
		}
		if (pos == 20) {
			return getBrzdiacaHmotnostRe();
		}
		if (pos == 21) {
			return getIdTrakciaHdv();
		}
		if (pos == 22) {
			return getIdVlastnickaZeleznica();
		}
		if (pos == 23) {
			return getIdVlastnikHdv();
		}
		if (pos == 24) {
			return getPoznamka();
		}
		if (pos == 25) {
			return getHmotnostPrazdnejJednotky();
		}
		if (pos == 26) {
			return getTelefonHkv();
		}
		if (pos == 27) {
			return getIdUcelenaJednotka();
		}
		return null;
	}

	/**
	 * Set field values by its position (zero based) in the XML schema.
	 * 
	 * @param position
	 *            The field position
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid position / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPosition(int position, Object value) throws TorqueException, IllegalArgumentException {
		if (position == 0) {
			return setByName("HistId", value);
		}
		if (position == 1) {
			return setByName("PlatnostOd", value);
		}
		if (position == 2) {
			return setByName("PlatnostDo", value);
		}
		if (position == 3) {
			return setByName("CasVytvorenia", value);
		}
		if (position == 4) {
			return setByName("CasZmeny", value);
		}
		if (position == 5) {
			return setByName("IdZmena", value);
		}
		if (position == 6) {
			return setByName("Zmaz", value);
		}
		if (position == 7) {
			return setByName("HnacieDrahoveVozidloId", value);
		}
		if (position == 8) {
			return setByName("Cislo7", value);
		}
		if (position == 9) {
			return setByName("Cislo12", value);
		}
		if (position == 10) {
			return setByName("Nestandardne", value);
		}
		if (position == 11) {
			return setByName("IdRadHdv", value);
		}
		if (position == 12) {
			return setByName("Dlzka", value);
		}
		if (position == 13) {
			return setByName("PocetNaprav", value);
		}
		if (position == 14) {
			return setByName("Hmotnost", value);
		}
		if (position == 15) {
			return setByName("BrzdiacaHmotnostG", value);
		}
		if (position == 16) {
			return setByName("BrzdiacaHmotnostP", value);
		}
		if (position == 17) {
			return setByName("BrzdiacaHmotnostR", value);
		}
		if (position == 18) {
			return setByName("BrzdiacaHmotnostGe", value);
		}
		if (position == 19) {
			return setByName("BrzdiacaHmotnostPe", value);
		}
		if (position == 20) {
			return setByName("BrzdiacaHmotnostRe", value);
		}
		if (position == 21) {
			return setByName("IdTrakciaHdv", value);
		}
		if (position == 22) {
			return setByName("IdVlastnickaZeleznica", value);
		}
		if (position == 23) {
			return setByName("IdVlastnikHdv", value);
		}
		if (position == 24) {
			return setByName("Poznamka", value);
		}
		if (position == 25) {
			return setByName("HmotnostPrazdnejJednotky", value);
		}
		if (position == 26) {
			return setByName("TelefonHkv", value);
		}
		if (position == 27) {
			return setByName("IdUcelenaJednotka", value);
		}
		return false;
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed.
	 * 
	 * @throws Exception
	 */
	public void save() throws Exception {
		save(THnacieDrahoveVozidloPeer.DATABASE_NAME);
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. Note: this code is here because the method body is auto-generated
	 * conditionally and therefore needs to be in this file instead of in the super class, BaseObject.
	 * 
	 * @param dbName
	 * @throws TorqueException
	 */
	public void save(String dbName) throws TorqueException {
		Connection con = null;
		try {
			con = Transaction.begin(dbName);
			save(con);
			Transaction.commit(con);
		} catch (TorqueException e) {
			Transaction.safeRollback(con);
			throw e;
		}
	}

	/**
	 * flag to prevent endless save loop, if this object is referenced by another object which falls in this transaction.
	 */
	private boolean alreadyInSave = false;

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. This method is meant to be used as part of a transaction, otherwise
	 * use the save() method and the connection details will be handled internally
	 * 
	 * @param con
	 * @throws TorqueException
	 */
	public void save(Connection con) throws TorqueException {
		if (!alreadyInSave) {
			alreadyInSave = true;

			// If this object has been modified, then save it to the database.
			if (isModified()) {
				if (isNew()) {
					THnacieDrahoveVozidloPeer.doInsert((THnacieDrahoveVozidlo) this, con);
					setNew(false);
				} else {
					THnacieDrahoveVozidloPeer.doUpdate((THnacieDrahoveVozidlo) this, con);
				}
			}

			alreadyInSave = false;
		}
	}

	/**
	 * Set the PrimaryKey using ObjectKey.
	 * 
	 * @param key
	 *            histId ObjectKey
	 */
	public void setPrimaryKey(ObjectKey key)

	{
		setHistId(new Integer(((NumberKey) key).intValue()));
	}

	/**
	 * Set the PrimaryKey using a String.
	 * 
	 * @param key
	 */
	public void setPrimaryKey(String key) {
		setHistId(new Integer(key));
	}

	/**
	 * returns an id that differentiates this object from others of its class.
	 */
	public ObjectKey getPrimaryKey() {
		return SimpleKey.keyFor(getHistId());
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. It then fills all the association collections and sets the related objects to
	 * isNew=true.
	 */
	public THnacieDrahoveVozidlo copy() throws TorqueException {
		return copy(true);
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. If the parameter deepcopy is true, it then fills all the association collections and
	 * sets the related objects to isNew=true.
	 * 
	 * @param deepcopy
	 *            whether to copy the associated objects.
	 */
	public THnacieDrahoveVozidlo copy(boolean deepcopy) throws TorqueException {
		return copyInto(new THnacieDrahoveVozidlo(), deepcopy);
	}

	/**
	 * Fills the copyObj with the contents of this object. The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 */
	protected THnacieDrahoveVozidlo copyInto(THnacieDrahoveVozidlo copyObj) throws TorqueException {
		return copyInto(copyObj, true);
	}

	/**
	 * Fills the copyObj with the contents of this object. If deepcopy is true, The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 * @param deepcopy
	 *            whether the associated objects should be copied.
	 */
	protected THnacieDrahoveVozidlo copyInto(THnacieDrahoveVozidlo copyObj, boolean deepcopy) throws TorqueException {
		copyObj.setHistId(histId);
		copyObj.setPlatnostOd(platnostOd);
		copyObj.setPlatnostDo(platnostDo);
		copyObj.setCasVytvorenia(casVytvorenia);
		copyObj.setCasZmeny(casZmeny);
		copyObj.setIdZmena(idZmena);
		copyObj.setZmaz(zmaz);
		copyObj.setHnacieDrahoveVozidloId(hnacieDrahoveVozidloId);
		copyObj.setCislo7(cislo7);
		copyObj.setCislo12(cislo12);
		copyObj.setNestandardne(nestandardne);
		copyObj.setIdRadHdv(idRadHdv);
		copyObj.setDlzka(dlzka);
		copyObj.setPocetNaprav(pocetNaprav);
		copyObj.setHmotnost(hmotnost);
		copyObj.setBrzdiacaHmotnostG(brzdiacaHmotnostG);
		copyObj.setBrzdiacaHmotnostP(brzdiacaHmotnostP);
		copyObj.setBrzdiacaHmotnostR(brzdiacaHmotnostR);
		copyObj.setBrzdiacaHmotnostGe(brzdiacaHmotnostGe);
		copyObj.setBrzdiacaHmotnostPe(brzdiacaHmotnostPe);
		copyObj.setBrzdiacaHmotnostRe(brzdiacaHmotnostRe);
		copyObj.setIdTrakciaHdv(idTrakciaHdv);
		copyObj.setIdVlastnickaZeleznica(idVlastnickaZeleznica);
		copyObj.setIdVlastnikHdv(idVlastnikHdv);
		copyObj.setPoznamka(poznamka);
		copyObj.setHmotnostPrazdnejJednotky(hmotnostPrazdnejJednotky);
		copyObj.setTelefonHkv(telefonHkv);
		copyObj.setIdUcelenaJednotka(idUcelenaJednotka);

		copyObj.setHistId((Integer) null);

		if (deepcopy) {
		}
		return copyObj;
	}

	/**
	 * returns a peer instance associated with this om. Since Peer classes are not to have any instance attributes, this method returns the same instance for all member of this
	 * class. The method could therefore be static, but this would prevent one from overriding the behavior.
	 */
	public THnacieDrahoveVozidloPeer getPeer() {
		return peer;
	}

	/**
	 * Retrieves the TableMap object related to this Table data without compiler warnings of using getPeer().getTableMap().
	 * 
	 * @return The associated TableMap object.
	 */
	public TableMap getTableMap() throws TorqueException {
		return THnacieDrahoveVozidloPeer.getTableMap();
	}

	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("THnacieDrahoveVozidlo:\n");
		str.append("HistId = ").append(getHistId()).append("\n");
		str.append("PlatnostOd = ").append(getPlatnostOd()).append("\n");
		str.append("PlatnostDo = ").append(getPlatnostDo()).append("\n");
		str.append("CasVytvorenia = ").append(getCasVytvorenia()).append("\n");
		str.append("CasZmeny = ").append(getCasZmeny()).append("\n");
		str.append("IdZmena = ").append(getIdZmena()).append("\n");
		str.append("Zmaz = ").append(getZmaz()).append("\n");
		str.append("HnacieDrahoveVozidloId = ").append(getHnacieDrahoveVozidloId()).append("\n");
		str.append("Cislo7 = ").append(getCislo7()).append("\n");
		str.append("Cislo12 = ").append(getCislo12()).append("\n");
		str.append("Nestandardne = ").append(getNestandardne()).append("\n");
		str.append("IdRadHdv = ").append(getIdRadHdv()).append("\n");
		str.append("Dlzka = ").append(getDlzka()).append("\n");
		str.append("PocetNaprav = ").append(getPocetNaprav()).append("\n");
		str.append("Hmotnost = ").append(getHmotnost()).append("\n");
		str.append("BrzdiacaHmotnostG = ").append(getBrzdiacaHmotnostG()).append("\n");
		str.append("BrzdiacaHmotnostP = ").append(getBrzdiacaHmotnostP()).append("\n");
		str.append("BrzdiacaHmotnostR = ").append(getBrzdiacaHmotnostR()).append("\n");
		str.append("BrzdiacaHmotnostGe = ").append(getBrzdiacaHmotnostGe()).append("\n");
		str.append("BrzdiacaHmotnostPe = ").append(getBrzdiacaHmotnostPe()).append("\n");
		str.append("BrzdiacaHmotnostRe = ").append(getBrzdiacaHmotnostRe()).append("\n");
		str.append("IdTrakciaHdv = ").append(getIdTrakciaHdv()).append("\n");
		str.append("IdVlastnickaZeleznica = ").append(getIdVlastnickaZeleznica()).append("\n");
		str.append("IdVlastnikHdv = ").append(getIdVlastnikHdv()).append("\n");
		str.append("Poznamka = ").append(getPoznamka()).append("\n");
		str.append("HmotnostPrazdnejJednotky = ").append(getHmotnostPrazdnejJednotky()).append("\n");
		str.append("TelefonHkv = ").append(getTelefonHkv()).append("\n");
		str.append("IdUcelenaJednotka = ").append(getIdUcelenaJednotka()).append("\n");
		return (str.toString());
	}
}
