package sk.ditec.dao.master;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Fri Jul 25 14:44:46 CEST 2025]
 * 
 * You should not use this class directly. It should not even be extended all references should be to TKategoriaZatazenia
 */
public abstract class BaseTKategoriaZatazenia extends BaseObject {
	/** Serial version */
	private static final long serialVersionUID = 1753447486539L;

	/** The Peer class */
	private static final TKategoriaZatazeniaPeer peer = new TKategoriaZatazeniaPeer();

	/** The value for the histId field */
	private Integer histId;

	/** The value for the platnostOd field */
	private Date platnostOd;

	/** The value for the platnostDo field */
	private Date platnostDo;

	/** The value for the casVytvorenia field */
	private Date casVytvorenia;

	/** The value for the casZmeny field */
	private Date casZmeny;

	/** The value for the idZmena field */
	private Integer idZmena;

	/** The value for the zmaz field */
	private String zmaz;

	/** The value for the kategoriaZatazeniaId field */
	private Integer kategoriaZatazeniaId;

	/** The value for the oznacenie field */
	private String oznacenie;

	/** The value for the hmotnostNaNapravu field */
	private Double hmotnostNaNapravu;

	/** The value for the hmotnostNa1mKolaje field */
	private Double hmotnostNa1mKolaje;

	/** The value for the nazov field */
	private String nazov;

	/** The value for the vzdialNapravM field */
	private Double vzdialNapravM;

	/** The value for the vzdial1NapravOdNaraz field */
	private Double vzdial1NapravOdNaraz;

	/** The value for the vzdialVnutNaprav field */
	private Double vzdialVnutNaprav;

	/** The value for the dlzkaVozna field */
	private Double dlzkaVozna;

	/**
	 * Get the HistId
	 * 
	 * @return Integer
	 */
	public Integer getHistId() {
		return histId;
	}

	/**
	 * Set the value of HistId
	 * 
	 * @param v
	 *            new value
	 */
	public void setHistId(Integer v) {

		if (!ObjectUtils.equals(this.histId, v)) {
			this.histId = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostOd
	 * 
	 * @return Date
	 */
	public Date getPlatnostOd() {
		return platnostOd;
	}

	/**
	 * Set the value of PlatnostOd
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostOd(Date v) {

		if (!ObjectUtils.equals(this.platnostOd, v)) {
			this.platnostOd = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostDo
	 * 
	 * @return Date
	 */
	public Date getPlatnostDo() {
		return platnostDo;
	}

	/**
	 * Set the value of PlatnostDo
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostDo(Date v) {

		if (!ObjectUtils.equals(this.platnostDo, v)) {
			this.platnostDo = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasVytvorenia
	 * 
	 * @return Date
	 */
	public Date getCasVytvorenia() {
		return casVytvorenia;
	}

	/**
	 * Set the value of CasVytvorenia
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasVytvorenia(Date v) {

		if (!ObjectUtils.equals(this.casVytvorenia, v)) {
			this.casVytvorenia = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasZmeny
	 * 
	 * @return Date
	 */
	public Date getCasZmeny() {
		return casZmeny;
	}

	/**
	 * Set the value of CasZmeny
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasZmeny(Date v) {

		if (!ObjectUtils.equals(this.casZmeny, v)) {
			this.casZmeny = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdZmena
	 * 
	 * @return Integer
	 */
	public Integer getIdZmena() {
		return idZmena;
	}

	/**
	 * Set the value of IdZmena
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdZmena(Integer v) {

		if (!ObjectUtils.equals(this.idZmena, v)) {
			this.idZmena = v;
			setModified(true);
		}

	}

	/**
	 * Get the Zmaz
	 * 
	 * @return String
	 */
	public String getZmaz() {
		return zmaz;
	}

	/**
	 * Set the value of Zmaz
	 * 
	 * @param v
	 *            new value
	 */
	public void setZmaz(String v) {

		if (!ObjectUtils.equals(this.zmaz, v)) {
			this.zmaz = v;
			setModified(true);
		}

	}

	/**
	 * Get the KategoriaZatazeniaId
	 * 
	 * @return Integer
	 */
	public Integer getKategoriaZatazeniaId() {
		return kategoriaZatazeniaId;
	}

	/**
	 * Set the value of KategoriaZatazeniaId
	 * 
	 * @param v
	 *            new value
	 */
	public void setKategoriaZatazeniaId(Integer v) {

		if (!ObjectUtils.equals(this.kategoriaZatazeniaId, v)) {
			this.kategoriaZatazeniaId = v;
			setModified(true);
		}

	}

	/**
	 * Get the Oznacenie
	 * 
	 * @return String
	 */
	public String getOznacenie() {
		return oznacenie;
	}

	/**
	 * Set the value of Oznacenie
	 * 
	 * @param v
	 *            new value
	 */
	public void setOznacenie(String v) {

		if (!ObjectUtils.equals(this.oznacenie, v)) {
			this.oznacenie = v;
			setModified(true);
		}

	}

	/**
	 * Get the HmotnostNaNapravu
	 * 
	 * @return Double
	 */
	public Double getHmotnostNaNapravu() {
		return hmotnostNaNapravu;
	}

	/**
	 * Set the value of HmotnostNaNapravu
	 * 
	 * @param v
	 *            new value
	 */
	public void setHmotnostNaNapravu(Double v) {

		if (!ObjectUtils.equals(this.hmotnostNaNapravu, v)) {
			this.hmotnostNaNapravu = v;
			setModified(true);
		}

	}

	/**
	 * Get the HmotnostNa1mKolaje
	 * 
	 * @return Double
	 */
	public Double getHmotnostNa1mKolaje() {
		return hmotnostNa1mKolaje;
	}

	/**
	 * Set the value of HmotnostNa1mKolaje
	 * 
	 * @param v
	 *            new value
	 */
	public void setHmotnostNa1mKolaje(Double v) {

		if (!ObjectUtils.equals(this.hmotnostNa1mKolaje, v)) {
			this.hmotnostNa1mKolaje = v;
			setModified(true);
		}

	}

	/**
	 * Get the Nazov
	 * 
	 * @return String
	 */
	public String getNazov() {
		return nazov;
	}

	/**
	 * Set the value of Nazov
	 * 
	 * @param v
	 *            new value
	 */
	public void setNazov(String v) {

		if (!ObjectUtils.equals(this.nazov, v)) {
			this.nazov = v;
			setModified(true);
		}

	}

	/**
	 * Get the VzdialNapravM
	 * 
	 * @return Double
	 */
	public Double getVzdialNapravM() {
		return vzdialNapravM;
	}

	/**
	 * Set the value of VzdialNapravM
	 * 
	 * @param v
	 *            new value
	 */
	public void setVzdialNapravM(Double v) {

		if (!ObjectUtils.equals(this.vzdialNapravM, v)) {
			this.vzdialNapravM = v;
			setModified(true);
		}

	}

	/**
	 * Get the Vzdial1NapravOdNaraz
	 * 
	 * @return Double
	 */
	public Double getVzdial1NapravOdNaraz() {
		return vzdial1NapravOdNaraz;
	}

	/**
	 * Set the value of Vzdial1NapravOdNaraz
	 * 
	 * @param v
	 *            new value
	 */
	public void setVzdial1NapravOdNaraz(Double v) {

		if (!ObjectUtils.equals(this.vzdial1NapravOdNaraz, v)) {
			this.vzdial1NapravOdNaraz = v;
			setModified(true);
		}

	}

	/**
	 * Get the VzdialVnutNaprav
	 * 
	 * @return Double
	 */
	public Double getVzdialVnutNaprav() {
		return vzdialVnutNaprav;
	}

	/**
	 * Set the value of VzdialVnutNaprav
	 * 
	 * @param v
	 *            new value
	 */
	public void setVzdialVnutNaprav(Double v) {

		if (!ObjectUtils.equals(this.vzdialVnutNaprav, v)) {
			this.vzdialVnutNaprav = v;
			setModified(true);
		}

	}

	/**
	 * Get the DlzkaVozna
	 * 
	 * @return Double
	 */
	public Double getDlzkaVozna() {
		return dlzkaVozna;
	}

	/**
	 * Set the value of DlzkaVozna
	 * 
	 * @param v
	 *            new value
	 */
	public void setDlzkaVozna(Double v) {

		if (!ObjectUtils.equals(this.dlzkaVozna, v)) {
			this.dlzkaVozna = v;
			setModified(true);
		}

	}

	private static List fieldNames = null;

	/**
	 * Generate a list of field names.
	 * 
	 * @return a list of field names
	 */
	public static synchronized List getFieldNames() {
		if (fieldNames == null) {
			fieldNames = new ArrayList();
			fieldNames.add("HistId");
			fieldNames.add("PlatnostOd");
			fieldNames.add("PlatnostDo");
			fieldNames.add("CasVytvorenia");
			fieldNames.add("CasZmeny");
			fieldNames.add("IdZmena");
			fieldNames.add("Zmaz");
			fieldNames.add("KategoriaZatazeniaId");
			fieldNames.add("Oznacenie");
			fieldNames.add("HmotnostNaNapravu");
			fieldNames.add("HmotnostNa1mKolaje");
			fieldNames.add("Nazov");
			fieldNames.add("VzdialNapravM");
			fieldNames.add("Vzdial1NapravOdNaraz");
			fieldNames.add("VzdialVnutNaprav");
			fieldNames.add("DlzkaVozna");
			fieldNames = Collections.unmodifiableList(fieldNames);
		}
		return fieldNames;
	}

	/**
	 * Retrieves a field from the object by field (Java) name passed in as a String.
	 * 
	 * @param name
	 *            field name
	 * @return value
	 */
	public Object getByName(String name) {
		if (name.equals("HistId")) {
			return getHistId();
		}
		if (name.equals("PlatnostOd")) {
			return getPlatnostOd();
		}
		if (name.equals("PlatnostDo")) {
			return getPlatnostDo();
		}
		if (name.equals("CasVytvorenia")) {
			return getCasVytvorenia();
		}
		if (name.equals("CasZmeny")) {
			return getCasZmeny();
		}
		if (name.equals("IdZmena")) {
			return getIdZmena();
		}
		if (name.equals("Zmaz")) {
			return getZmaz();
		}
		if (name.equals("KategoriaZatazeniaId")) {
			return getKategoriaZatazeniaId();
		}
		if (name.equals("Oznacenie")) {
			return getOznacenie();
		}
		if (name.equals("HmotnostNaNapravu")) {
			return getHmotnostNaNapravu();
		}
		if (name.equals("HmotnostNa1mKolaje")) {
			return getHmotnostNa1mKolaje();
		}
		if (name.equals("Nazov")) {
			return getNazov();
		}
		if (name.equals("VzdialNapravM")) {
			return getVzdialNapravM();
		}
		if (name.equals("Vzdial1NapravOdNaraz")) {
			return getVzdial1NapravOdNaraz();
		}
		if (name.equals("VzdialVnutNaprav")) {
			return getVzdialVnutNaprav();
		}
		if (name.equals("DlzkaVozna")) {
			return getDlzkaVozna();
		}
		return null;
	}

	/**
	 * Set a field in the object by field (Java) name.
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (name.equals("HistId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHistId((Integer) value);
			return true;
		}
		if (name.equals("PlatnostOd")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostOd((Date) value);
			return true;
		}
		if (name.equals("PlatnostDo")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostDo((Date) value);
			return true;
		}
		if (name.equals("CasVytvorenia")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasVytvorenia((Date) value);
			return true;
		}
		if (name.equals("CasZmeny")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasZmeny((Date) value);
			return true;
		}
		if (name.equals("IdZmena")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdZmena((Integer) value);
			return true;
		}
		if (name.equals("Zmaz")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setZmaz((String) value);
			return true;
		}
		if (name.equals("KategoriaZatazeniaId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setKategoriaZatazeniaId((Integer) value);
			return true;
		}
		if (name.equals("Oznacenie")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setOznacenie((String) value);
			return true;
		}
		if (name.equals("HmotnostNaNapravu")) {
			// Object fields can be null
			if (value != null && !Double.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHmotnostNaNapravu((Double) value);
			return true;
		}
		if (name.equals("HmotnostNa1mKolaje")) {
			// Object fields can be null
			if (value != null && !Double.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHmotnostNa1mKolaje((Double) value);
			return true;
		}
		if (name.equals("Nazov")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setNazov((String) value);
			return true;
		}
		if (name.equals("VzdialNapravM")) {
			// Object fields can be null
			if (value != null && !Double.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setVzdialNapravM((Double) value);
			return true;
		}
		if (name.equals("Vzdial1NapravOdNaraz")) {
			// Object fields can be null
			if (value != null && !Double.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setVzdial1NapravOdNaraz((Double) value);
			return true;
		}
		if (name.equals("VzdialVnutNaprav")) {
			// Object fields can be null
			if (value != null && !Double.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setVzdialVnutNaprav((Double) value);
			return true;
		}
		if (name.equals("DlzkaVozna")) {
			// Object fields can be null
			if (value != null && !Double.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setDlzkaVozna((Double) value);
			return true;
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by name passed in as a String. The String must be one of the static Strings defined in this Class' Peer.
	 * 
	 * @param name
	 *            peer name
	 * @return value
	 */
	public Object getByPeerName(String name) {
		if (name.equals(TKategoriaZatazeniaPeer.HIST_ID)) {
			return getHistId();
		}
		if (name.equals(TKategoriaZatazeniaPeer.PLATNOST_OD)) {
			return getPlatnostOd();
		}
		if (name.equals(TKategoriaZatazeniaPeer.PLATNOST_DO)) {
			return getPlatnostDo();
		}
		if (name.equals(TKategoriaZatazeniaPeer.CAS_VYTVORENIA)) {
			return getCasVytvorenia();
		}
		if (name.equals(TKategoriaZatazeniaPeer.CAS_ZMENY)) {
			return getCasZmeny();
		}
		if (name.equals(TKategoriaZatazeniaPeer.ID_ZMENA)) {
			return getIdZmena();
		}
		if (name.equals(TKategoriaZatazeniaPeer.ZMAZ)) {
			return getZmaz();
		}
		if (name.equals(TKategoriaZatazeniaPeer.KATEGORIA_ZATAZENIA_ID)) {
			return getKategoriaZatazeniaId();
		}
		if (name.equals(TKategoriaZatazeniaPeer.OZNACENIE)) {
			return getOznacenie();
		}
		if (name.equals(TKategoriaZatazeniaPeer.HMOTNOST_NA_NAPRAVU)) {
			return getHmotnostNaNapravu();
		}
		if (name.equals(TKategoriaZatazeniaPeer.HMOTNOST_NA_1M_KOLAJE)) {
			return getHmotnostNa1mKolaje();
		}
		if (name.equals(TKategoriaZatazeniaPeer.NAZOV)) {
			return getNazov();
		}
		if (name.equals(TKategoriaZatazeniaPeer.VZDIAL_NAPRAV_M)) {
			return getVzdialNapravM();
		}
		if (name.equals(TKategoriaZatazeniaPeer.VZDIAL_1_NAPRAV_OD_NARAZ)) {
			return getVzdial1NapravOdNaraz();
		}
		if (name.equals(TKategoriaZatazeniaPeer.VZDIAL_VNUT_NAPRAV)) {
			return getVzdialVnutNaprav();
		}
		if (name.equals(TKategoriaZatazeniaPeer.DLZKA_VOZNA)) {
			return getDlzkaVozna();
		}
		return null;
	}

	/**
	 * Set field values by Peer Field Name
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPeerName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (TKategoriaZatazeniaPeer.HIST_ID.equals(name)) {
			return setByName("HistId", value);
		}
		if (TKategoriaZatazeniaPeer.PLATNOST_OD.equals(name)) {
			return setByName("PlatnostOd", value);
		}
		if (TKategoriaZatazeniaPeer.PLATNOST_DO.equals(name)) {
			return setByName("PlatnostDo", value);
		}
		if (TKategoriaZatazeniaPeer.CAS_VYTVORENIA.equals(name)) {
			return setByName("CasVytvorenia", value);
		}
		if (TKategoriaZatazeniaPeer.CAS_ZMENY.equals(name)) {
			return setByName("CasZmeny", value);
		}
		if (TKategoriaZatazeniaPeer.ID_ZMENA.equals(name)) {
			return setByName("IdZmena", value);
		}
		if (TKategoriaZatazeniaPeer.ZMAZ.equals(name)) {
			return setByName("Zmaz", value);
		}
		if (TKategoriaZatazeniaPeer.KATEGORIA_ZATAZENIA_ID.equals(name)) {
			return setByName("KategoriaZatazeniaId", value);
		}
		if (TKategoriaZatazeniaPeer.OZNACENIE.equals(name)) {
			return setByName("Oznacenie", value);
		}
		if (TKategoriaZatazeniaPeer.HMOTNOST_NA_NAPRAVU.equals(name)) {
			return setByName("HmotnostNaNapravu", value);
		}
		if (TKategoriaZatazeniaPeer.HMOTNOST_NA_1M_KOLAJE.equals(name)) {
			return setByName("HmotnostNa1mKolaje", value);
		}
		if (TKategoriaZatazeniaPeer.NAZOV.equals(name)) {
			return setByName("Nazov", value);
		}
		if (TKategoriaZatazeniaPeer.VZDIAL_NAPRAV_M.equals(name)) {
			return setByName("VzdialNapravM", value);
		}
		if (TKategoriaZatazeniaPeer.VZDIAL_1_NAPRAV_OD_NARAZ.equals(name)) {
			return setByName("Vzdial1NapravOdNaraz", value);
		}
		if (TKategoriaZatazeniaPeer.VZDIAL_VNUT_NAPRAV.equals(name)) {
			return setByName("VzdialVnutNaprav", value);
		}
		if (TKategoriaZatazeniaPeer.DLZKA_VOZNA.equals(name)) {
			return setByName("DlzkaVozna", value);
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema. Zero-based.
	 * 
	 * @param pos
	 *            position in xml schema
	 * @return value
	 */
	public Object getByPosition(int pos) {
		if (pos == 0) {
			return getHistId();
		}
		if (pos == 1) {
			return getPlatnostOd();
		}
		if (pos == 2) {
			return getPlatnostDo();
		}
		if (pos == 3) {
			return getCasVytvorenia();
		}
		if (pos == 4) {
			return getCasZmeny();
		}
		if (pos == 5) {
			return getIdZmena();
		}
		if (pos == 6) {
			return getZmaz();
		}
		if (pos == 7) {
			return getKategoriaZatazeniaId();
		}
		if (pos == 8) {
			return getOznacenie();
		}
		if (pos == 9) {
			return getHmotnostNaNapravu();
		}
		if (pos == 10) {
			return getHmotnostNa1mKolaje();
		}
		if (pos == 11) {
			return getNazov();
		}
		if (pos == 12) {
			return getVzdialNapravM();
		}
		if (pos == 13) {
			return getVzdial1NapravOdNaraz();
		}
		if (pos == 14) {
			return getVzdialVnutNaprav();
		}
		if (pos == 15) {
			return getDlzkaVozna();
		}
		return null;
	}

	/**
	 * Set field values by its position (zero based) in the XML schema.
	 * 
	 * @param position
	 *            The field position
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid position / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPosition(int position, Object value) throws TorqueException, IllegalArgumentException {
		if (position == 0) {
			return setByName("HistId", value);
		}
		if (position == 1) {
			return setByName("PlatnostOd", value);
		}
		if (position == 2) {
			return setByName("PlatnostDo", value);
		}
		if (position == 3) {
			return setByName("CasVytvorenia", value);
		}
		if (position == 4) {
			return setByName("CasZmeny", value);
		}
		if (position == 5) {
			return setByName("IdZmena", value);
		}
		if (position == 6) {
			return setByName("Zmaz", value);
		}
		if (position == 7) {
			return setByName("KategoriaZatazeniaId", value);
		}
		if (position == 8) {
			return setByName("Oznacenie", value);
		}
		if (position == 9) {
			return setByName("HmotnostNaNapravu", value);
		}
		if (position == 10) {
			return setByName("HmotnostNa1mKolaje", value);
		}
		if (position == 11) {
			return setByName("Nazov", value);
		}
		if (position == 12) {
			return setByName("VzdialNapravM", value);
		}
		if (position == 13) {
			return setByName("Vzdial1NapravOdNaraz", value);
		}
		if (position == 14) {
			return setByName("VzdialVnutNaprav", value);
		}
		if (position == 15) {
			return setByName("DlzkaVozna", value);
		}
		return false;
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed.
	 * 
	 * @throws Exception
	 */
	public void save() throws Exception {
		save(TKategoriaZatazeniaPeer.DATABASE_NAME);
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. Note: this code is here because the method body is auto-generated
	 * conditionally and therefore needs to be in this file instead of in the super class, BaseObject.
	 * 
	 * @param dbName
	 * @throws TorqueException
	 */
	public void save(String dbName) throws TorqueException {
		Connection con = null;
		try {
			con = Transaction.begin(dbName);
			save(con);
			Transaction.commit(con);
		} catch (TorqueException e) {
			Transaction.safeRollback(con);
			throw e;
		}
	}

	/**
	 * flag to prevent endless save loop, if this object is referenced by another object which falls in this transaction.
	 */
	private boolean alreadyInSave = false;

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. This method is meant to be used as part of a transaction, otherwise
	 * use the save() method and the connection details will be handled internally
	 * 
	 * @param con
	 * @throws TorqueException
	 */
	public void save(Connection con) throws TorqueException {
		if (!alreadyInSave) {
			alreadyInSave = true;

			// If this object has been modified, then save it to the database.
			if (isModified()) {
				if (isNew()) {
					TKategoriaZatazeniaPeer.doInsert((TKategoriaZatazenia) this, con);
					setNew(false);
				} else {
					TKategoriaZatazeniaPeer.doUpdate((TKategoriaZatazenia) this, con);
				}
			}

			alreadyInSave = false;
		}
	}

	/**
	 * Set the PrimaryKey using ObjectKey.
	 * 
	 * @param key
	 *            histId ObjectKey
	 */
	public void setPrimaryKey(ObjectKey key)

	{
		setHistId(new Integer(((NumberKey) key).intValue()));
	}

	/**
	 * Set the PrimaryKey using a String.
	 * 
	 * @param key
	 */
	public void setPrimaryKey(String key) {
		setHistId(new Integer(key));
	}

	/**
	 * returns an id that differentiates this object from others of its class.
	 */
	public ObjectKey getPrimaryKey() {
		return SimpleKey.keyFor(getHistId());
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. It then fills all the association collections and sets the related objects to
	 * isNew=true.
	 */
	public TKategoriaZatazenia copy() throws TorqueException {
		return copy(true);
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. If the parameter deepcopy is true, it then fills all the association collections and
	 * sets the related objects to isNew=true.
	 * 
	 * @param deepcopy
	 *            whether to copy the associated objects.
	 */
	public TKategoriaZatazenia copy(boolean deepcopy) throws TorqueException {
		return copyInto(new TKategoriaZatazenia(), deepcopy);
	}

	/**
	 * Fills the copyObj with the contents of this object. The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 */
	protected TKategoriaZatazenia copyInto(TKategoriaZatazenia copyObj) throws TorqueException {
		return copyInto(copyObj, true);
	}

	/**
	 * Fills the copyObj with the contents of this object. If deepcopy is true, The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 * @param deepcopy
	 *            whether the associated objects should be copied.
	 */
	protected TKategoriaZatazenia copyInto(TKategoriaZatazenia copyObj, boolean deepcopy) throws TorqueException {
		copyObj.setHistId(histId);
		copyObj.setPlatnostOd(platnostOd);
		copyObj.setPlatnostDo(platnostDo);
		copyObj.setCasVytvorenia(casVytvorenia);
		copyObj.setCasZmeny(casZmeny);
		copyObj.setIdZmena(idZmena);
		copyObj.setZmaz(zmaz);
		copyObj.setKategoriaZatazeniaId(kategoriaZatazeniaId);
		copyObj.setOznacenie(oznacenie);
		copyObj.setHmotnostNaNapravu(hmotnostNaNapravu);
		copyObj.setHmotnostNa1mKolaje(hmotnostNa1mKolaje);
		copyObj.setNazov(nazov);
		copyObj.setVzdialNapravM(vzdialNapravM);
		copyObj.setVzdial1NapravOdNaraz(vzdial1NapravOdNaraz);
		copyObj.setVzdialVnutNaprav(vzdialVnutNaprav);
		copyObj.setDlzkaVozna(dlzkaVozna);

		copyObj.setHistId((Integer) null);

		if (deepcopy) {
		}
		return copyObj;
	}

	/**
	 * returns a peer instance associated with this om. Since Peer classes are not to have any instance attributes, this method returns the same instance for all member of this
	 * class. The method could therefore be static, but this would prevent one from overriding the behavior.
	 */
	public TKategoriaZatazeniaPeer getPeer() {
		return peer;
	}

	/**
	 * Retrieves the TableMap object related to this Table data without compiler warnings of using getPeer().getTableMap().
	 * 
	 * @return The associated TableMap object.
	 */
	public TableMap getTableMap() throws TorqueException {
		return TKategoriaZatazeniaPeer.getTableMap();
	}

	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("TKategoriaZatazenia:\n");
		str.append("HistId = ").append(getHistId()).append("\n");
		str.append("PlatnostOd = ").append(getPlatnostOd()).append("\n");
		str.append("PlatnostDo = ").append(getPlatnostDo()).append("\n");
		str.append("CasVytvorenia = ").append(getCasVytvorenia()).append("\n");
		str.append("CasZmeny = ").append(getCasZmeny()).append("\n");
		str.append("IdZmena = ").append(getIdZmena()).append("\n");
		str.append("Zmaz = ").append(getZmaz()).append("\n");
		str.append("KategoriaZatazeniaId = ").append(getKategoriaZatazeniaId()).append("\n");
		str.append("Oznacenie = ").append(getOznacenie()).append("\n");
		str.append("HmotnostNaNapravu = ").append(getHmotnostNaNapravu()).append("\n");
		str.append("HmotnostNa1mKolaje = ").append(getHmotnostNa1mKolaje()).append("\n");
		str.append("Nazov = ").append(getNazov()).append("\n");
		str.append("VzdialNapravM = ").append(getVzdialNapravM()).append("\n");
		str.append("Vzdial1NapravOdNaraz = ").append(getVzdial1NapravOdNaraz()).append("\n");
		str.append("VzdialVnutNaprav = ").append(getVzdialVnutNaprav()).append("\n");
		str.append("DlzkaVozna = ").append(getDlzkaVozna()).append("\n");
		return (str.toString());
	}
}
