package sk.ditec.dao.master;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;

import org.apache.torque.NoRowsException;
import org.apache.torque.TooManyRowsException;
import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.BasePeer;
import org.apache.torque.util.Criteria;

import com.workingdogs.village.DataSetException;
import com.workingdogs.village.QueryDataSet;
import com.workingdogs.village.Record;

// Local classes
import sk.ditec.dao.master.map.*;



/**
 * This class was autogenerated by Torque on:
 *
 * [Fri Mar 20 13:51:25 CET 2026]
 *
 */
public abstract class BaseTPrimaryLocationPeer
    extends BasePeer
{
    /** Serial version */
    private static final long serialVersionUID = 1774011085524L;


    /** the default database name for this class */
    public static final String DATABASE_NAME;

     /** the table name for this class */
    public static final String TABLE_NAME;

    /**
     * @return the map builder for this peer
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static MapBuilder getMapBuilder()
        throws TorqueException
    {
        return getMapBuilder(TPrimaryLocationMapBuilder.CLASS_NAME);
    }

      /** the column name for the HIST_ID field */
    public static final String HIST_ID;
      /** the column name for the PLATNOST_OD field */
    public static final String PLATNOST_OD;
      /** the column name for the PLATNOST_DO field */
    public static final String PLATNOST_DO;
      /** the column name for the CAS_VYTVORENIA field */
    public static final String CAS_VYTVORENIA;
      /** the column name for the CAS_ZMENY field */
    public static final String CAS_ZMENY;
      /** the column name for the ID_ZMENA field */
    public static final String ID_ZMENA;
      /** the column name for the ZMAZ field */
    public static final String ZMAZ;
      /** the column name for the PRIMARY_LOCATION_ID field */
    public static final String PRIMARY_LOCATION_ID;
      /** the column name for the ID_COUNTRY field */
    public static final String ID_COUNTRY;
      /** the column name for the LOCATION_CODE field */
    public static final String LOCATION_CODE;
      /** the column name for the START_VALIDITY field */
    public static final String START_VALIDITY;
      /** the column name for the END_VALIDITY field */
    public static final String END_VALIDITY;
      /** the column name for the ID_COMPANY field */
    public static final String ID_COMPANY;
      /** the column name for the LOCATION_NAME field */
    public static final String LOCATION_NAME;
      /** the column name for the LOCATION_NAME_ASCII field */
    public static final String LOCATION_NAME_ASCII;
      /** the column name for the NUTS_CODE field */
    public static final String NUTS_CODE;
      /** the column name for the CONTAINER_HANDLING_FLAG field */
    public static final String CONTAINER_HANDLING_FLAG;
      /** the column name for the HANDOVER_POINT_FLAG field */
    public static final String HANDOVER_POINT_FLAG;
      /** the column name for the FREIGHT_POSSIBLE_FLAG field */
    public static final String FREIGHT_POSSIBLE_FLAG;
      /** the column name for the FREIGHT_START_VALIDITY field */
    public static final String FREIGHT_START_VALIDITY;
      /** the column name for the FREIGHT_END_VALIDITY field */
    public static final String FREIGHT_END_VALIDITY;
      /** the column name for the PASSENGER_POSSIBLE_FLAG field */
    public static final String PASSENGER_POSSIBLE_FLAG;
      /** the column name for the PASSENGER_START_VALIDITY field */
    public static final String PASSENGER_START_VALIDITY;
      /** the column name for the PASSENGER_END_VALIDITY field */
    public static final String PASSENGER_END_VALIDITY;
      /** the column name for the LONGITUDE field */
    public static final String LONGITUDE;
      /** the column name for the LATITUDE field */
    public static final String LATITUDE;
      /** the column name for the FREE_TEXT field */
    public static final String FREE_TEXT;
      /** the column name for the ACTIVE_FLAG field */
    public static final String ACTIVE_FLAG;
  
    static
    {
        DATABASE_NAME = "APP";
        TABLE_NAME = "T_PRIMARY_LOCATION";

              HIST_ID = "T_PRIMARY_LOCATION.HIST_ID";
                  PLATNOST_OD = "T_PRIMARY_LOCATION.PLATNOST_OD";
                  PLATNOST_DO = "T_PRIMARY_LOCATION.PLATNOST_DO";
                  CAS_VYTVORENIA = "T_PRIMARY_LOCATION.CAS_VYTVORENIA";
                  CAS_ZMENY = "T_PRIMARY_LOCATION.CAS_ZMENY";
                  ID_ZMENA = "T_PRIMARY_LOCATION.ID_ZMENA";
                  ZMAZ = "T_PRIMARY_LOCATION.ZMAZ";
                  PRIMARY_LOCATION_ID = "T_PRIMARY_LOCATION.PRIMARY_LOCATION_ID";
                  ID_COUNTRY = "T_PRIMARY_LOCATION.ID_COUNTRY";
                  LOCATION_CODE = "T_PRIMARY_LOCATION.LOCATION_CODE";
                  START_VALIDITY = "T_PRIMARY_LOCATION.START_VALIDITY";
                  END_VALIDITY = "T_PRIMARY_LOCATION.END_VALIDITY";
                  ID_COMPANY = "T_PRIMARY_LOCATION.ID_COMPANY";
                  LOCATION_NAME = "T_PRIMARY_LOCATION.LOCATION_NAME";
                  LOCATION_NAME_ASCII = "T_PRIMARY_LOCATION.LOCATION_NAME_ASCII";
                  NUTS_CODE = "T_PRIMARY_LOCATION.NUTS_CODE";
                  CONTAINER_HANDLING_FLAG = "T_PRIMARY_LOCATION.CONTAINER_HANDLING_FLAG";
                  HANDOVER_POINT_FLAG = "T_PRIMARY_LOCATION.HANDOVER_POINT_FLAG";
                  FREIGHT_POSSIBLE_FLAG = "T_PRIMARY_LOCATION.FREIGHT_POSSIBLE_FLAG";
                  FREIGHT_START_VALIDITY = "T_PRIMARY_LOCATION.FREIGHT_START_VALIDITY";
                  FREIGHT_END_VALIDITY = "T_PRIMARY_LOCATION.FREIGHT_END_VALIDITY";
                  PASSENGER_POSSIBLE_FLAG = "T_PRIMARY_LOCATION.PASSENGER_POSSIBLE_FLAG";
                  PASSENGER_START_VALIDITY = "T_PRIMARY_LOCATION.PASSENGER_START_VALIDITY";
                  PASSENGER_END_VALIDITY = "T_PRIMARY_LOCATION.PASSENGER_END_VALIDITY";
                  LONGITUDE = "T_PRIMARY_LOCATION.LONGITUDE";
                  LATITUDE = "T_PRIMARY_LOCATION.LATITUDE";
                  FREE_TEXT = "T_PRIMARY_LOCATION.FREE_TEXT";
                  ACTIVE_FLAG = "T_PRIMARY_LOCATION.ACTIVE_FLAG";
              if (Torque.isInit())
        {
            try
            {
                getMapBuilder(TPrimaryLocationMapBuilder.CLASS_NAME);
            }
            catch (Exception e)
            {
                log.error("Could not initialize Peer", e);
                throw new RuntimeException(e);
            }
        }
        else
        {
            Torque.registerMapBuilder(TPrimaryLocationMapBuilder.CLASS_NAME);
        }
    }
 
    /** number of columns for this peer */
    public static final int numColumns =  28;

    /** A class that can be returned by this peer. */
    protected static final String CLASSNAME_DEFAULT =
        "sk.ditec.dao.master.TPrimaryLocation";

    /** A class that can be returned by this peer. */
    protected static final Class CLASS_DEFAULT = initClass(CLASSNAME_DEFAULT);

    /**
     * Class object initialization method.
     *
     * @param className name of the class to initialize
     * @return the initialized class
     */
    private static Class initClass(String className)
    {
        Class c = null;
        try
        {
            c = Class.forName(className);
        }
        catch (Throwable t)
        {
            log.error("A FATAL ERROR has occurred which should not "
                + "have happened under any circumstance.  Please notify "
                + "the Torque developers <torque-dev@db.apache.org> "
                + "and give as many details as possible (including the error "
                + "stack trace).", t);

            // Error objects should always be propogated.
            if (t instanceof Error)
            {
                throw (Error) t.fillInStackTrace();
            }
        }
        return c;
    }

    /**
     * Get the list of objects for a ResultSet.  Please not that your
     * resultset MUST return columns in the right order.  You can use
     * getFieldNames() in BaseObject to get the correct sequence.
     *
     * @param results the ResultSet
     * @return the list of objects
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List resultSet2Objects(java.sql.ResultSet results)
            throws TorqueException
    {
        try
        {
            QueryDataSet qds = null;
            List rows = null;
            try
            {
                qds = new QueryDataSet(results);
                rows = getSelectResults(qds);
            }
            finally
            {
                if (qds != null)
                {
                    qds.close();
                }
            }

            return populateObjects(rows);
        }
        catch (SQLException e)
        {
            throw new TorqueException(e);
        }
        catch (DataSetException e)
        {
            throw new TorqueException(e);
        }
    }


  
    /**
     * Method to do inserts.
     *
     * @param criteria object used to create the INSERT statement.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static ObjectKey doInsert(Criteria criteria)
        throws TorqueException
    {
        return BaseTPrimaryLocationPeer
            .doInsert(criteria, (Connection) null);
    }

    /**
     * Method to do inserts.  This method is to be used during a transaction,
     * otherwise use the doInsert(Criteria) method.  It will take care of
     * the connection details internally.
     *
     * @param criteria object used to create the INSERT statement.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static ObjectKey doInsert(Criteria criteria, Connection con)
        throws TorqueException
    {
        correctBooleans(criteria);

        setDbName(criteria);

        if (con == null)
        {
            return BasePeer.doInsert(criteria);
        }
        else
        {
            return BasePeer.doInsert(criteria, con);
        }
    }

    /**
     * Add all the columns needed to create a new object.
     *
     * @param criteria object containing the columns to add.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void addSelectColumns(Criteria criteria)
            throws TorqueException
    {
          criteria.addSelectColumn(HIST_ID);
          criteria.addSelectColumn(PLATNOST_OD);
          criteria.addSelectColumn(PLATNOST_DO);
          criteria.addSelectColumn(CAS_VYTVORENIA);
          criteria.addSelectColumn(CAS_ZMENY);
          criteria.addSelectColumn(ID_ZMENA);
          criteria.addSelectColumn(ZMAZ);
          criteria.addSelectColumn(PRIMARY_LOCATION_ID);
          criteria.addSelectColumn(ID_COUNTRY);
          criteria.addSelectColumn(LOCATION_CODE);
          criteria.addSelectColumn(START_VALIDITY);
          criteria.addSelectColumn(END_VALIDITY);
          criteria.addSelectColumn(ID_COMPANY);
          criteria.addSelectColumn(LOCATION_NAME);
          criteria.addSelectColumn(LOCATION_NAME_ASCII);
          criteria.addSelectColumn(NUTS_CODE);
          criteria.addSelectColumn(CONTAINER_HANDLING_FLAG);
          criteria.addSelectColumn(HANDOVER_POINT_FLAG);
          criteria.addSelectColumn(FREIGHT_POSSIBLE_FLAG);
          criteria.addSelectColumn(FREIGHT_START_VALIDITY);
          criteria.addSelectColumn(FREIGHT_END_VALIDITY);
          criteria.addSelectColumn(PASSENGER_POSSIBLE_FLAG);
          criteria.addSelectColumn(PASSENGER_START_VALIDITY);
          criteria.addSelectColumn(PASSENGER_END_VALIDITY);
          criteria.addSelectColumn(LONGITUDE);
          criteria.addSelectColumn(LATITUDE);
          criteria.addSelectColumn(FREE_TEXT);
          criteria.addSelectColumn(ACTIVE_FLAG);
      }

    /**
     * changes the boolean values in the criteria to the appropriate type,
     * whenever a booleanchar or booleanint column is involved.
     * This enables the user to create criteria using Boolean values
     * for booleanchar or booleanint columns
     * @param criteria the criteria in which the boolean values should be corrected
     * @throws TorqueException if the database map for the criteria cannot be 
               obtained.
     */
    public static void correctBooleans(Criteria criteria) throws TorqueException
    {
        correctBooleans(criteria, getTableMap());
    }

    /**
     * Create a new object of type cls from a resultset row starting
     * from a specified offset.  This is done so that you can select
     * other rows than just those needed for this object.  You may
     * for example want to create two objects from the same row.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static TPrimaryLocation row2Object(Record row,
                                             int offset,
                                             Class cls)
        throws TorqueException
    {
        try
        {
            TPrimaryLocation obj = (TPrimaryLocation) cls.newInstance();
            TPrimaryLocationPeer.populateObject(row, offset, obj);
                  obj.setModified(false);
              obj.setNew(false);

            return obj;
        }
        catch (InstantiationException e)
        {
            throw new TorqueException(e);
        }
        catch (IllegalAccessException e)
        {
            throw new TorqueException(e);
        }
    }

    /**
     * Populates an object from a resultset row starting
     * from a specified offset.  This is done so that you can select
     * other rows than just those needed for this object.  You may
     * for example want to create two objects from the same row.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void populateObject(Record row,
                                      int offset,
                                      TPrimaryLocation obj)
        throws TorqueException
    {
        try
        {
                obj.setHistId(row.getValue(offset + 0).asIntegerObj());
                  obj.setPlatnostOd(row.getValue(offset + 1).asUtilDate());
                  obj.setPlatnostDo(row.getValue(offset + 2).asUtilDate());
                  obj.setCasVytvorenia(row.getValue(offset + 3).asUtilDate());
                  obj.setCasZmeny(row.getValue(offset + 4).asUtilDate());
                  obj.setIdZmena(row.getValue(offset + 5).asIntegerObj());
                  obj.setZmaz(row.getValue(offset + 6).asString());
                  obj.setPrimaryLocationId(row.getValue(offset + 7).asIntegerObj());
                  obj.setIdCountry(row.getValue(offset + 8).asIntegerObj());
                  obj.setLocationCode(row.getValue(offset + 9).asString());
                  obj.setStartValidity(row.getValue(offset + 10).asUtilDate());
                  obj.setEndValidity(row.getValue(offset + 11).asUtilDate());
                  obj.setIdCompany(row.getValue(offset + 12).asIntegerObj());
                  obj.setLocationName(row.getValue(offset + 13).asString());
                  obj.setLocationNameAscii(row.getValue(offset + 14).asString());
                  obj.setNutsCode(row.getValue(offset + 15).asString());
                  obj.setContainerHandlingFlag(row.getValue(offset + 16).asString());
                  obj.setHandoverPointFlag(row.getValue(offset + 17).asString());
                  obj.setFreightPossibleFlag(row.getValue(offset + 18).asString());
                  obj.setFreightStartValidity(row.getValue(offset + 19).asUtilDate());
                  obj.setFreightEndValidity(row.getValue(offset + 20).asUtilDate());
                  obj.setPassengerPossibleFlag(row.getValue(offset + 21).asString());
                  obj.setPassengerStartValidity(row.getValue(offset + 22).asUtilDate());
                  obj.setPassengerEndValidity(row.getValue(offset + 23).asUtilDate());
                  obj.setLongitude(row.getValue(offset + 24).asDoubleObj());
                  obj.setLatitude(row.getValue(offset + 25).asDoubleObj());
                  obj.setFreeText(row.getValue(offset + 26).asString());
                  obj.setActiveFlag(row.getValue(offset + 27).asString());
              }
        catch (DataSetException e)
        {
            throw new TorqueException(e);
        }
    }

    /**
     * Method to do selects.
     *
     * @param criteria object used to create the SELECT statement.
     * @return List of selected Objects
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelect(Criteria criteria) throws TorqueException
    {
        return populateObjects(doSelectVillageRecords(criteria));
    }

    /**
     * Method to do selects within a transaction.
     *
     * @param criteria object used to create the SELECT statement.
     * @param con the connection to use
     * @return List of selected Objects
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelect(Criteria criteria, Connection con)
        throws TorqueException
    {
        return populateObjects(doSelectVillageRecords(criteria, con));
    }

    /**
     * Grabs the raw Village records to be formed into objects.
     * This method handles connections internally.  The Record objects
     * returned by this method should be considered readonly.  Do not
     * alter the data and call save(), your results may vary, but are
     * certainly likely to result in hard to track MT bugs.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelectVillageRecords(Criteria criteria)
        throws TorqueException
    {
        return BaseTPrimaryLocationPeer
            .doSelectVillageRecords(criteria, (Connection) null);
    }

    /**
     * Grabs the raw Village records to be formed into objects.
     * This method should be used for transactions
     *
     * @param criteria object used to create the SELECT statement.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelectVillageRecords(Criteria criteria, Connection con)
        throws TorqueException
    {
        if (criteria.getSelectColumns().size() == 0)
        {
            addSelectColumns(criteria);
        }
        correctBooleans(criteria);

        setDbName(criteria);

        // BasePeer returns a List of Value (Village) arrays.  The array
        // order follows the order columns were placed in the Select clause.
        if (con == null)
        {
            return BasePeer.doSelect(criteria);
        }
        else
        {
            return BasePeer.doSelect(criteria, con);
        }
    }

    /**
     * The returned List will contain objects of the default type or
     * objects that inherit from the default.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List populateObjects(List records)
        throws TorqueException
    {
        List results = new ArrayList(records.size());

        // populate the object(s)
        for (int i = 0; i < records.size(); i++)
        {
            Record row = (Record) records.get(i);
              results.add(TPrimaryLocationPeer.row2Object(row, 1,
                TPrimaryLocationPeer.getOMClass()));
          }
        return results;
    }
 

    /**
     * The class that the Peer will make instances of.
     * If the BO is abstract then you must implement this method
     * in the BO.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static Class getOMClass()
        throws TorqueException
    {
        return CLASS_DEFAULT;
    }

    /**
     * Method to do updates.
     *
     * @param criteria object containing data that is used to create the UPDATE
     *        statement.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doUpdate(Criteria criteria) throws TorqueException
    {
         BaseTPrimaryLocationPeer
            .doUpdate(criteria, (Connection) null);
    }

    /**
     * Method to do updates.  This method is to be used during a transaction,
     * otherwise use the doUpdate(Criteria) method.  It will take care of
     * the connection details internally.
     *
     * @param criteria object containing data that is used to create the UPDATE
     *        statement.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doUpdate(Criteria criteria, Connection con)
        throws TorqueException
    {
        Criteria selectCriteria = new Criteria(DATABASE_NAME, 2);
        correctBooleans(criteria);

  
             selectCriteria.put(HIST_ID, criteria.remove(HIST_ID));
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
        setDbName(criteria);

        if (con == null)
        {
            BasePeer.doUpdate(selectCriteria, criteria);
        }
        else
        {
            BasePeer.doUpdate(selectCriteria, criteria, con);
        }
    }

    /**
     * Method to do deletes.
     *
     * @param criteria object containing data that is used DELETE from database.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
     public static void doDelete(Criteria criteria) throws TorqueException
     {
         TPrimaryLocationPeer
            .doDelete(criteria, (Connection) null);
     }

    /**
     * Method to do deletes.  This method is to be used during a transaction,
     * otherwise use the doDelete(Criteria) method.  It will take care of
     * the connection details internally.
     *
     * @param criteria object containing data that is used DELETE from database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
     public static void doDelete(Criteria criteria, Connection con)
        throws TorqueException
     {
        correctBooleans(criteria);

        setDbName(criteria);

        if (con == null)
        {
            BasePeer.doDelete(criteria);
        }
        else
        {
            BasePeer.doDelete(criteria, con);
        }
     }

    /**
     * Method to do selects
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelect(TPrimaryLocation obj) throws TorqueException
    {
        return doSelect(buildSelectCriteria(obj));
    }

    /**
     * Method to do inserts
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doInsert(TPrimaryLocation obj) throws TorqueException
    {
          obj.setPrimaryKey(doInsert(buildCriteria(obj)));
          obj.setNew(false);
        obj.setModified(false);
    }

    /**
     * @param obj the data object to update in the database.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doUpdate(TPrimaryLocation obj) throws TorqueException
    {
        doUpdate(buildCriteria(obj));
        obj.setModified(false);
    }

    /**
     * @param obj the data object to delete in the database.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doDelete(TPrimaryLocation obj) throws TorqueException
    {
        doDelete(buildSelectCriteria(obj));
    }

    /**
     * Method to do inserts.  This method is to be used during a transaction,
     * otherwise use the doInsert(TPrimaryLocation) method.  It will take
     * care of the connection details internally.
     *
     * @param obj the data object to insert into the database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doInsert(TPrimaryLocation obj, Connection con)
        throws TorqueException
    {
          obj.setPrimaryKey(doInsert(buildCriteria(obj), con));
          obj.setNew(false);
        obj.setModified(false);
    }

    /**
     * Method to do update.  This method is to be used during a transaction,
     * otherwise use the doUpdate(TPrimaryLocation) method.  It will take
     * care of the connection details internally.
     *
     * @param obj the data object to update in the database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doUpdate(TPrimaryLocation obj, Connection con)
        throws TorqueException
    {
        doUpdate(buildCriteria(obj), con);
        obj.setModified(false);
    }

    /**
     * Method to delete.  This method is to be used during a transaction,
     * otherwise use the doDelete(TPrimaryLocation) method.  It will take
     * care of the connection details internally.
     *
     * @param obj the data object to delete in the database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doDelete(TPrimaryLocation obj, Connection con)
        throws TorqueException
    {
        doDelete(buildSelectCriteria(obj), con);
    }

    /**
     * Method to do deletes.
     *
     * @param pk ObjectKey that is used DELETE from database.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doDelete(ObjectKey pk) throws TorqueException
    {
        BaseTPrimaryLocationPeer
           .doDelete(pk, (Connection) null);
    }

    /**
     * Method to delete.  This method is to be used during a transaction,
     * otherwise use the doDelete(ObjectKey) method.  It will take
     * care of the connection details internally.
     *
     * @param pk the primary key for the object to delete in the database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doDelete(ObjectKey pk, Connection con)
        throws TorqueException
    {
        doDelete(buildCriteria(pk), con);
    }

    /** Build a Criteria object from an ObjectKey */
    public static Criteria buildCriteria( ObjectKey pk )
    {
        Criteria criteria = new Criteria();
              criteria.add(HIST_ID, pk);
          return criteria;
     }

    /** Build a Criteria object from the data object for this peer */
    public static Criteria buildCriteria( TPrimaryLocation obj )
    {
        Criteria criteria = new Criteria(DATABASE_NAME);
              if (!obj.isNew())
            criteria.add(HIST_ID, obj.getHistId());
              criteria.add(PLATNOST_OD, obj.getPlatnostOd());
              criteria.add(PLATNOST_DO, obj.getPlatnostDo());
              criteria.add(CAS_VYTVORENIA, obj.getCasVytvorenia());
              criteria.add(CAS_ZMENY, obj.getCasZmeny());
              criteria.add(ID_ZMENA, obj.getIdZmena());
              criteria.add(ZMAZ, obj.getZmaz());
              criteria.add(PRIMARY_LOCATION_ID, obj.getPrimaryLocationId());
              criteria.add(ID_COUNTRY, obj.getIdCountry());
              criteria.add(LOCATION_CODE, obj.getLocationCode());
              criteria.add(START_VALIDITY, obj.getStartValidity());
              criteria.add(END_VALIDITY, obj.getEndValidity());
              criteria.add(ID_COMPANY, obj.getIdCompany());
              criteria.add(LOCATION_NAME, obj.getLocationName());
              criteria.add(LOCATION_NAME_ASCII, obj.getLocationNameAscii());
              criteria.add(NUTS_CODE, obj.getNutsCode());
              criteria.add(CONTAINER_HANDLING_FLAG, obj.getContainerHandlingFlag());
              criteria.add(HANDOVER_POINT_FLAG, obj.getHandoverPointFlag());
              criteria.add(FREIGHT_POSSIBLE_FLAG, obj.getFreightPossibleFlag());
              criteria.add(FREIGHT_START_VALIDITY, obj.getFreightStartValidity());
              criteria.add(FREIGHT_END_VALIDITY, obj.getFreightEndValidity());
              criteria.add(PASSENGER_POSSIBLE_FLAG, obj.getPassengerPossibleFlag());
              criteria.add(PASSENGER_START_VALIDITY, obj.getPassengerStartValidity());
              criteria.add(PASSENGER_END_VALIDITY, obj.getPassengerEndValidity());
              criteria.add(LONGITUDE, obj.getLongitude());
              criteria.add(LATITUDE, obj.getLatitude());
              criteria.add(FREE_TEXT, obj.getFreeText());
              criteria.add(ACTIVE_FLAG, obj.getActiveFlag());
          return criteria;
    }

    /** Build a Criteria object from the data object for this peer, skipping all binary columns */
    public static Criteria buildSelectCriteria( TPrimaryLocation obj )
    {
        Criteria criteria = new Criteria(DATABASE_NAME);
              if (!obj.isNew())
        {
                    criteria.add(HIST_ID, obj.getHistId());
                }
                          criteria.add(PLATNOST_OD, obj.getPlatnostOd());
                              criteria.add(PLATNOST_DO, obj.getPlatnostDo());
                              criteria.add(CAS_VYTVORENIA, obj.getCasVytvorenia());
                              criteria.add(CAS_ZMENY, obj.getCasZmeny());
                              criteria.add(ID_ZMENA, obj.getIdZmena());
                              criteria.add(ZMAZ, obj.getZmaz());
                              criteria.add(PRIMARY_LOCATION_ID, obj.getPrimaryLocationId());
                              criteria.add(ID_COUNTRY, obj.getIdCountry());
                              criteria.add(LOCATION_CODE, obj.getLocationCode());
                              criteria.add(START_VALIDITY, obj.getStartValidity());
                              criteria.add(END_VALIDITY, obj.getEndValidity());
                              criteria.add(ID_COMPANY, obj.getIdCompany());
                              criteria.add(LOCATION_NAME, obj.getLocationName());
                              criteria.add(LOCATION_NAME_ASCII, obj.getLocationNameAscii());
                              criteria.add(NUTS_CODE, obj.getNutsCode());
                              criteria.add(CONTAINER_HANDLING_FLAG, obj.getContainerHandlingFlag());
                              criteria.add(HANDOVER_POINT_FLAG, obj.getHandoverPointFlag());
                              criteria.add(FREIGHT_POSSIBLE_FLAG, obj.getFreightPossibleFlag());
                              criteria.add(FREIGHT_START_VALIDITY, obj.getFreightStartValidity());
                              criteria.add(FREIGHT_END_VALIDITY, obj.getFreightEndValidity());
                              criteria.add(PASSENGER_POSSIBLE_FLAG, obj.getPassengerPossibleFlag());
                              criteria.add(PASSENGER_START_VALIDITY, obj.getPassengerStartValidity());
                              criteria.add(PASSENGER_END_VALIDITY, obj.getPassengerEndValidity());
                              criteria.add(LONGITUDE, obj.getLongitude());
                              criteria.add(LATITUDE, obj.getLatitude());
                              criteria.add(FREE_TEXT, obj.getFreeText());
                              criteria.add(ACTIVE_FLAG, obj.getActiveFlag());
                  return criteria;
    }
 
    
        /**
     * Retrieve a single object by pk
     *
     * @param pk the primary key
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     * @throws NoRowsException Primary key was not found in database.
     * @throws TooManyRowsException Primary key was not found in database.
     */
    public static TPrimaryLocation retrieveByPK(Integer pk)
        throws TorqueException, NoRowsException, TooManyRowsException
    {
        return retrieveByPK(SimpleKey.keyFor(pk));
    }

    /**
     * Retrieve a single object by pk
     *
     * @param pk the primary key
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     * @throws NoRowsException Primary key was not found in database.
     * @throws TooManyRowsException Primary key was not found in database.
     */
    public static TPrimaryLocation retrieveByPK(Integer pk, Connection con)
        throws TorqueException, NoRowsException, TooManyRowsException
    {
        return retrieveByPK(SimpleKey.keyFor(pk), con);
    }
  
    /**
     * Retrieve a single object by pk
     *
     * @param pk the primary key
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     * @throws NoRowsException Primary key was not found in database.
     * @throws TooManyRowsException Primary key was not found in database.
     */
    public static TPrimaryLocation retrieveByPK(ObjectKey pk)
        throws TorqueException, NoRowsException, TooManyRowsException
    {
        Connection db = null;
        TPrimaryLocation retVal = null;
        try
        {
            db = Torque.getConnection(DATABASE_NAME);
            retVal = retrieveByPK(pk, db);
        }
        finally
        {
            Torque.closeConnection(db);
        }
        return retVal;
    }

    /**
     * Retrieve a single object by pk
     *
     * @param pk the primary key
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     * @throws NoRowsException Primary key was not found in database.
     * @throws TooManyRowsException Primary key was not found in database.
     */
    public static TPrimaryLocation retrieveByPK(ObjectKey pk, Connection con)
        throws TorqueException, NoRowsException, TooManyRowsException
    {
        Criteria criteria = buildCriteria(pk);
        List v = doSelect(criteria, con);
        if (v.size() == 0)
        {
            throw new NoRowsException("Failed to select a row.");
        }
        else if (v.size() > 1)
        {
            throw new TooManyRowsException("Failed to select only one row.");
        }
        else
        {
            return (TPrimaryLocation)v.get(0);
        }
    }

    /**
     * Retrieve a multiple objects by pk
     *
     * @param pks List of primary keys
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List retrieveByPKs(List pks)
        throws TorqueException
    {
        Connection db = null;
        List retVal = null;
        try
        {
           db = Torque.getConnection(DATABASE_NAME);
           retVal = retrieveByPKs(pks, db);
        }
        finally
        {
            Torque.closeConnection(db);
        }
        return retVal;
    }

    /**
     * Retrieve a multiple objects by pk
     *
     * @param pks List of primary keys
     * @param dbcon the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List retrieveByPKs( List pks, Connection dbcon )
        throws TorqueException
    {
        List objs = null;
        if (pks == null || pks.size() == 0)
        {
            objs = new LinkedList();
        }
        else
        {
            Criteria criteria = new Criteria();
              criteria.addIn( HIST_ID, pks );
          objs = doSelect(criteria, dbcon);
        }
        return objs;
    }

 



        
  
  
    
  
      /**
     * Returns the TableMap related to this peer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static TableMap getTableMap()
        throws TorqueException
    {
        return Torque.getDatabaseMap(DATABASE_NAME).getTable(TABLE_NAME);
    }
   
    private static void setDbName(Criteria crit)
    {
        // Set the correct dbName if it has not been overridden
        // crit.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (crit.getDbName() == Torque.getDefaultDB())
        {
            crit.setDbName(DATABASE_NAME);
        }
    }
    

}
