package sk.ditec.dao.master;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Fri Jul 25 14:44:46 CEST 2025]
 * 
 * You should not use this class directly. It should not even be extended all references should be to TRestrictionCodes
 */
public abstract class BaseTRestrictionCodes extends BaseObject {
	/** Serial version */
	private static final long serialVersionUID = 1753447486539L;

	/** The Peer class */
	private static final TRestrictionCodesPeer peer = new TRestrictionCodesPeer();

	/** The value for the histId field */
	private Integer histId;

	/** The value for the platnostOd field */
	private Date platnostOd;

	/** The value for the platnostDo field */
	private Date platnostDo;

	/** The value for the casVytvorenia field */
	private Date casVytvorenia;

	/** The value for the casZmeny field */
	private Date casZmeny;

	/** The value for the idZmena field */
	private Integer idZmena;

	/** The value for the zmaz field */
	private String zmaz;

	/** The value for the restrictionCodesId field */
	private Integer restrictionCodesId;

	/** The value for the enumKod field */
	private String enumKod;

	/** The value for the freighten field */
	private String freighten;

	/** The value for the passenger field */
	private String passenger;

	/** The value for the docEn field */
	private String docEn;

	/** The value for the docSk field */
	private String docSk;

	/**
	 * Get the HistId
	 * 
	 * @return Integer
	 */
	public Integer getHistId() {
		return histId;
	}

	/**
	 * Set the value of HistId
	 * 
	 * @param v
	 *            new value
	 */
	public void setHistId(Integer v) {

		if (!ObjectUtils.equals(this.histId, v)) {
			this.histId = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostOd
	 * 
	 * @return Date
	 */
	public Date getPlatnostOd() {
		return platnostOd;
	}

	/**
	 * Set the value of PlatnostOd
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostOd(Date v) {

		if (!ObjectUtils.equals(this.platnostOd, v)) {
			this.platnostOd = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostDo
	 * 
	 * @return Date
	 */
	public Date getPlatnostDo() {
		return platnostDo;
	}

	/**
	 * Set the value of PlatnostDo
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostDo(Date v) {

		if (!ObjectUtils.equals(this.platnostDo, v)) {
			this.platnostDo = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasVytvorenia
	 * 
	 * @return Date
	 */
	public Date getCasVytvorenia() {
		return casVytvorenia;
	}

	/**
	 * Set the value of CasVytvorenia
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasVytvorenia(Date v) {

		if (!ObjectUtils.equals(this.casVytvorenia, v)) {
			this.casVytvorenia = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasZmeny
	 * 
	 * @return Date
	 */
	public Date getCasZmeny() {
		return casZmeny;
	}

	/**
	 * Set the value of CasZmeny
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasZmeny(Date v) {

		if (!ObjectUtils.equals(this.casZmeny, v)) {
			this.casZmeny = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdZmena
	 * 
	 * @return Integer
	 */
	public Integer getIdZmena() {
		return idZmena;
	}

	/**
	 * Set the value of IdZmena
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdZmena(Integer v) {

		if (!ObjectUtils.equals(this.idZmena, v)) {
			this.idZmena = v;
			setModified(true);
		}

	}

	/**
	 * Get the Zmaz
	 * 
	 * @return String
	 */
	public String getZmaz() {
		return zmaz;
	}

	/**
	 * Set the value of Zmaz
	 * 
	 * @param v
	 *            new value
	 */
	public void setZmaz(String v) {

		if (!ObjectUtils.equals(this.zmaz, v)) {
			this.zmaz = v;
			setModified(true);
		}

	}

	/**
	 * Get the RestrictionCodesId
	 * 
	 * @return Integer
	 */
	public Integer getRestrictionCodesId() {
		return restrictionCodesId;
	}

	/**
	 * Set the value of RestrictionCodesId
	 * 
	 * @param v
	 *            new value
	 */
	public void setRestrictionCodesId(Integer v) {

		if (!ObjectUtils.equals(this.restrictionCodesId, v)) {
			this.restrictionCodesId = v;
			setModified(true);
		}

	}

	/**
	 * Get the EnumKod
	 * 
	 * @return String
	 */
	public String getEnumKod() {
		return enumKod;
	}

	/**
	 * Set the value of EnumKod
	 * 
	 * @param v
	 *            new value
	 */
	public void setEnumKod(String v) {

		if (!ObjectUtils.equals(this.enumKod, v)) {
			this.enumKod = v;
			setModified(true);
		}

	}

	/**
	 * Get the Freighten
	 * 
	 * @return String
	 */
	public String getFreighten() {
		return freighten;
	}

	/**
	 * Set the value of Freighten
	 * 
	 * @param v
	 *            new value
	 */
	public void setFreighten(String v) {

		if (!ObjectUtils.equals(this.freighten, v)) {
			this.freighten = v;
			setModified(true);
		}

	}

	/**
	 * Get the Passenger
	 * 
	 * @return String
	 */
	public String getPassenger() {
		return passenger;
	}

	/**
	 * Set the value of Passenger
	 * 
	 * @param v
	 *            new value
	 */
	public void setPassenger(String v) {

		if (!ObjectUtils.equals(this.passenger, v)) {
			this.passenger = v;
			setModified(true);
		}

	}

	/**
	 * Get the DocEn
	 * 
	 * @return String
	 */
	public String getDocEn() {
		return docEn;
	}

	/**
	 * Set the value of DocEn
	 * 
	 * @param v
	 *            new value
	 */
	public void setDocEn(String v) {

		if (!ObjectUtils.equals(this.docEn, v)) {
			this.docEn = v;
			setModified(true);
		}

	}

	/**
	 * Get the DocSk
	 * 
	 * @return String
	 */
	public String getDocSk() {
		return docSk;
	}

	/**
	 * Set the value of DocSk
	 * 
	 * @param v
	 *            new value
	 */
	public void setDocSk(String v) {

		if (!ObjectUtils.equals(this.docSk, v)) {
			this.docSk = v;
			setModified(true);
		}

	}

	private static List fieldNames = null;

	/**
	 * Generate a list of field names.
	 * 
	 * @return a list of field names
	 */
	public static synchronized List getFieldNames() {
		if (fieldNames == null) {
			fieldNames = new ArrayList();
			fieldNames.add("HistId");
			fieldNames.add("PlatnostOd");
			fieldNames.add("PlatnostDo");
			fieldNames.add("CasVytvorenia");
			fieldNames.add("CasZmeny");
			fieldNames.add("IdZmena");
			fieldNames.add("Zmaz");
			fieldNames.add("RestrictionCodesId");
			fieldNames.add("EnumKod");
			fieldNames.add("Freighten");
			fieldNames.add("Passenger");
			fieldNames.add("DocEn");
			fieldNames.add("DocSk");
			fieldNames = Collections.unmodifiableList(fieldNames);
		}
		return fieldNames;
	}

	/**
	 * Retrieves a field from the object by field (Java) name passed in as a String.
	 * 
	 * @param name
	 *            field name
	 * @return value
	 */
	public Object getByName(String name) {
		if (name.equals("HistId")) {
			return getHistId();
		}
		if (name.equals("PlatnostOd")) {
			return getPlatnostOd();
		}
		if (name.equals("PlatnostDo")) {
			return getPlatnostDo();
		}
		if (name.equals("CasVytvorenia")) {
			return getCasVytvorenia();
		}
		if (name.equals("CasZmeny")) {
			return getCasZmeny();
		}
		if (name.equals("IdZmena")) {
			return getIdZmena();
		}
		if (name.equals("Zmaz")) {
			return getZmaz();
		}
		if (name.equals("RestrictionCodesId")) {
			return getRestrictionCodesId();
		}
		if (name.equals("EnumKod")) {
			return getEnumKod();
		}
		if (name.equals("Freighten")) {
			return getFreighten();
		}
		if (name.equals("Passenger")) {
			return getPassenger();
		}
		if (name.equals("DocEn")) {
			return getDocEn();
		}
		if (name.equals("DocSk")) {
			return getDocSk();
		}
		return null;
	}

	/**
	 * Set a field in the object by field (Java) name.
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (name.equals("HistId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHistId((Integer) value);
			return true;
		}
		if (name.equals("PlatnostOd")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostOd((Date) value);
			return true;
		}
		if (name.equals("PlatnostDo")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostDo((Date) value);
			return true;
		}
		if (name.equals("CasVytvorenia")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasVytvorenia((Date) value);
			return true;
		}
		if (name.equals("CasZmeny")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasZmeny((Date) value);
			return true;
		}
		if (name.equals("IdZmena")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdZmena((Integer) value);
			return true;
		}
		if (name.equals("Zmaz")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setZmaz((String) value);
			return true;
		}
		if (name.equals("RestrictionCodesId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setRestrictionCodesId((Integer) value);
			return true;
		}
		if (name.equals("EnumKod")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setEnumKod((String) value);
			return true;
		}
		if (name.equals("Freighten")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setFreighten((String) value);
			return true;
		}
		if (name.equals("Passenger")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPassenger((String) value);
			return true;
		}
		if (name.equals("DocEn")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setDocEn((String) value);
			return true;
		}
		if (name.equals("DocSk")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setDocSk((String) value);
			return true;
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by name passed in as a String. The String must be one of the static Strings defined in this Class' Peer.
	 * 
	 * @param name
	 *            peer name
	 * @return value
	 */
	public Object getByPeerName(String name) {
		if (name.equals(TRestrictionCodesPeer.HIST_ID)) {
			return getHistId();
		}
		if (name.equals(TRestrictionCodesPeer.PLATNOST_OD)) {
			return getPlatnostOd();
		}
		if (name.equals(TRestrictionCodesPeer.PLATNOST_DO)) {
			return getPlatnostDo();
		}
		if (name.equals(TRestrictionCodesPeer.CAS_VYTVORENIA)) {
			return getCasVytvorenia();
		}
		if (name.equals(TRestrictionCodesPeer.CAS_ZMENY)) {
			return getCasZmeny();
		}
		if (name.equals(TRestrictionCodesPeer.ID_ZMENA)) {
			return getIdZmena();
		}
		if (name.equals(TRestrictionCodesPeer.ZMAZ)) {
			return getZmaz();
		}
		if (name.equals(TRestrictionCodesPeer.RESTRICTION_CODES_ID)) {
			return getRestrictionCodesId();
		}
		if (name.equals(TRestrictionCodesPeer.ENUM_KOD)) {
			return getEnumKod();
		}
		if (name.equals(TRestrictionCodesPeer.FREIGHTEN)) {
			return getFreighten();
		}
		if (name.equals(TRestrictionCodesPeer.PASSENGER)) {
			return getPassenger();
		}
		if (name.equals(TRestrictionCodesPeer.DOC_EN)) {
			return getDocEn();
		}
		if (name.equals(TRestrictionCodesPeer.DOC_SK)) {
			return getDocSk();
		}
		return null;
	}

	/**
	 * Set field values by Peer Field Name
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPeerName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (TRestrictionCodesPeer.HIST_ID.equals(name)) {
			return setByName("HistId", value);
		}
		if (TRestrictionCodesPeer.PLATNOST_OD.equals(name)) {
			return setByName("PlatnostOd", value);
		}
		if (TRestrictionCodesPeer.PLATNOST_DO.equals(name)) {
			return setByName("PlatnostDo", value);
		}
		if (TRestrictionCodesPeer.CAS_VYTVORENIA.equals(name)) {
			return setByName("CasVytvorenia", value);
		}
		if (TRestrictionCodesPeer.CAS_ZMENY.equals(name)) {
			return setByName("CasZmeny", value);
		}
		if (TRestrictionCodesPeer.ID_ZMENA.equals(name)) {
			return setByName("IdZmena", value);
		}
		if (TRestrictionCodesPeer.ZMAZ.equals(name)) {
			return setByName("Zmaz", value);
		}
		if (TRestrictionCodesPeer.RESTRICTION_CODES_ID.equals(name)) {
			return setByName("RestrictionCodesId", value);
		}
		if (TRestrictionCodesPeer.ENUM_KOD.equals(name)) {
			return setByName("EnumKod", value);
		}
		if (TRestrictionCodesPeer.FREIGHTEN.equals(name)) {
			return setByName("Freighten", value);
		}
		if (TRestrictionCodesPeer.PASSENGER.equals(name)) {
			return setByName("Passenger", value);
		}
		if (TRestrictionCodesPeer.DOC_EN.equals(name)) {
			return setByName("DocEn", value);
		}
		if (TRestrictionCodesPeer.DOC_SK.equals(name)) {
			return setByName("DocSk", value);
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema. Zero-based.
	 * 
	 * @param pos
	 *            position in xml schema
	 * @return value
	 */
	public Object getByPosition(int pos) {
		if (pos == 0) {
			return getHistId();
		}
		if (pos == 1) {
			return getPlatnostOd();
		}
		if (pos == 2) {
			return getPlatnostDo();
		}
		if (pos == 3) {
			return getCasVytvorenia();
		}
		if (pos == 4) {
			return getCasZmeny();
		}
		if (pos == 5) {
			return getIdZmena();
		}
		if (pos == 6) {
			return getZmaz();
		}
		if (pos == 7) {
			return getRestrictionCodesId();
		}
		if (pos == 8) {
			return getEnumKod();
		}
		if (pos == 9) {
			return getFreighten();
		}
		if (pos == 10) {
			return getPassenger();
		}
		if (pos == 11) {
			return getDocEn();
		}
		if (pos == 12) {
			return getDocSk();
		}
		return null;
	}

	/**
	 * Set field values by its position (zero based) in the XML schema.
	 * 
	 * @param position
	 *            The field position
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid position / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPosition(int position, Object value) throws TorqueException, IllegalArgumentException {
		if (position == 0) {
			return setByName("HistId", value);
		}
		if (position == 1) {
			return setByName("PlatnostOd", value);
		}
		if (position == 2) {
			return setByName("PlatnostDo", value);
		}
		if (position == 3) {
			return setByName("CasVytvorenia", value);
		}
		if (position == 4) {
			return setByName("CasZmeny", value);
		}
		if (position == 5) {
			return setByName("IdZmena", value);
		}
		if (position == 6) {
			return setByName("Zmaz", value);
		}
		if (position == 7) {
			return setByName("RestrictionCodesId", value);
		}
		if (position == 8) {
			return setByName("EnumKod", value);
		}
		if (position == 9) {
			return setByName("Freighten", value);
		}
		if (position == 10) {
			return setByName("Passenger", value);
		}
		if (position == 11) {
			return setByName("DocEn", value);
		}
		if (position == 12) {
			return setByName("DocSk", value);
		}
		return false;
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed.
	 * 
	 * @throws Exception
	 */
	public void save() throws Exception {
		save(TRestrictionCodesPeer.DATABASE_NAME);
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. Note: this code is here because the method body is auto-generated
	 * conditionally and therefore needs to be in this file instead of in the super class, BaseObject.
	 * 
	 * @param dbName
	 * @throws TorqueException
	 */
	public void save(String dbName) throws TorqueException {
		Connection con = null;
		try {
			con = Transaction.begin(dbName);
			save(con);
			Transaction.commit(con);
		} catch (TorqueException e) {
			Transaction.safeRollback(con);
			throw e;
		}
	}

	/**
	 * flag to prevent endless save loop, if this object is referenced by another object which falls in this transaction.
	 */
	private boolean alreadyInSave = false;

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. This method is meant to be used as part of a transaction, otherwise
	 * use the save() method and the connection details will be handled internally
	 * 
	 * @param con
	 * @throws TorqueException
	 */
	public void save(Connection con) throws TorqueException {
		if (!alreadyInSave) {
			alreadyInSave = true;

			// If this object has been modified, then save it to the database.
			if (isModified()) {
				if (isNew()) {
					TRestrictionCodesPeer.doInsert((TRestrictionCodes) this, con);
					setNew(false);
				} else {
					TRestrictionCodesPeer.doUpdate((TRestrictionCodes) this, con);
				}
			}

			alreadyInSave = false;
		}
	}

	/**
	 * Set the PrimaryKey using ObjectKey.
	 * 
	 * @param key
	 *            histId ObjectKey
	 */
	public void setPrimaryKey(ObjectKey key)

	{
		setHistId(new Integer(((NumberKey) key).intValue()));
	}

	/**
	 * Set the PrimaryKey using a String.
	 * 
	 * @param key
	 */
	public void setPrimaryKey(String key) {
		setHistId(new Integer(key));
	}

	/**
	 * returns an id that differentiates this object from others of its class.
	 */
	public ObjectKey getPrimaryKey() {
		return SimpleKey.keyFor(getHistId());
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. It then fills all the association collections and sets the related objects to
	 * isNew=true.
	 */
	public TRestrictionCodes copy() throws TorqueException {
		return copy(true);
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. If the parameter deepcopy is true, it then fills all the association collections and
	 * sets the related objects to isNew=true.
	 * 
	 * @param deepcopy
	 *            whether to copy the associated objects.
	 */
	public TRestrictionCodes copy(boolean deepcopy) throws TorqueException {
		return copyInto(new TRestrictionCodes(), deepcopy);
	}

	/**
	 * Fills the copyObj with the contents of this object. The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 */
	protected TRestrictionCodes copyInto(TRestrictionCodes copyObj) throws TorqueException {
		return copyInto(copyObj, true);
	}

	/**
	 * Fills the copyObj with the contents of this object. If deepcopy is true, The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 * @param deepcopy
	 *            whether the associated objects should be copied.
	 */
	protected TRestrictionCodes copyInto(TRestrictionCodes copyObj, boolean deepcopy) throws TorqueException {
		copyObj.setHistId(histId);
		copyObj.setPlatnostOd(platnostOd);
		copyObj.setPlatnostDo(platnostDo);
		copyObj.setCasVytvorenia(casVytvorenia);
		copyObj.setCasZmeny(casZmeny);
		copyObj.setIdZmena(idZmena);
		copyObj.setZmaz(zmaz);
		copyObj.setRestrictionCodesId(restrictionCodesId);
		copyObj.setEnumKod(enumKod);
		copyObj.setFreighten(freighten);
		copyObj.setPassenger(passenger);
		copyObj.setDocEn(docEn);
		copyObj.setDocSk(docSk);

		copyObj.setHistId((Integer) null);

		if (deepcopy) {
		}
		return copyObj;
	}

	/**
	 * returns a peer instance associated with this om. Since Peer classes are not to have any instance attributes, this method returns the same instance for all member of this
	 * class. The method could therefore be static, but this would prevent one from overriding the behavior.
	 */
	public TRestrictionCodesPeer getPeer() {
		return peer;
	}

	/**
	 * Retrieves the TableMap object related to this Table data without compiler warnings of using getPeer().getTableMap().
	 * 
	 * @return The associated TableMap object.
	 */
	public TableMap getTableMap() throws TorqueException {
		return TRestrictionCodesPeer.getTableMap();
	}

	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("TRestrictionCodes:\n");
		str.append("HistId = ").append(getHistId()).append("\n");
		str.append("PlatnostOd = ").append(getPlatnostOd()).append("\n");
		str.append("PlatnostDo = ").append(getPlatnostDo()).append("\n");
		str.append("CasVytvorenia = ").append(getCasVytvorenia()).append("\n");
		str.append("CasZmeny = ").append(getCasZmeny()).append("\n");
		str.append("IdZmena = ").append(getIdZmena()).append("\n");
		str.append("Zmaz = ").append(getZmaz()).append("\n");
		str.append("RestrictionCodesId = ").append(getRestrictionCodesId()).append("\n");
		str.append("EnumKod = ").append(getEnumKod()).append("\n");
		str.append("Freighten = ").append(getFreighten()).append("\n");
		str.append("Passenger = ").append(getPassenger()).append("\n");
		str.append("DocEn = ").append(getDocEn()).append("\n");
		str.append("DocSk = ").append(getDocSk()).append("\n");
		return (str.toString());
	}
}
