package sk.ditec.dao.master;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Fri Jul 25 14:44:46 CEST 2025]
 * 
 * You should not use this class directly. It should not even be extended all references should be to TTrat
 */
public abstract class BaseTTrat extends BaseObject {
	/** Serial version */
	private static final long serialVersionUID = 1753447486539L;

	/** The Peer class */
	private static final TTratPeer peer = new TTratPeer();

	/** The value for the histId field */
	private Integer histId;

	/** The value for the platnostOd field */
	private Date platnostOd;

	/** The value for the platnostDo field */
	private Date platnostDo;

	/** The value for the casVytvorenia field */
	private Date casVytvorenia;

	/** The value for the casZmeny field */
	private Date casZmeny;

	/** The value for the idZmena field */
	private Integer idZmena;

	/** The value for the zmaz field */
	private String zmaz;

	/** The value for the tratId field */
	private Integer tratId;

	/** The value for the cislo field */
	private String cislo;

	/** The value for the kategoria field */
	private Integer kategoria;

	/** The value for the idDopravnyBodOd field */
	private Integer idDopravnyBodOd;

	/** The value for the idDopravnyBodDo field */
	private Integer idDopravnyBodDo;

	/** The value for the dlzkaM field */
	private Double dlzkaM;

	/** The value for the dlzkaKm field */
	private Integer dlzkaKm;

	/**
	 * Get the HistId
	 * 
	 * @return Integer
	 */
	public Integer getHistId() {
		return histId;
	}

	/**
	 * Set the value of HistId
	 * 
	 * @param v
	 *            new value
	 */
	public void setHistId(Integer v) {

		if (!ObjectUtils.equals(this.histId, v)) {
			this.histId = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostOd
	 * 
	 * @return Date
	 */
	public Date getPlatnostOd() {
		return platnostOd;
	}

	/**
	 * Set the value of PlatnostOd
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostOd(Date v) {

		if (!ObjectUtils.equals(this.platnostOd, v)) {
			this.platnostOd = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostDo
	 * 
	 * @return Date
	 */
	public Date getPlatnostDo() {
		return platnostDo;
	}

	/**
	 * Set the value of PlatnostDo
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostDo(Date v) {

		if (!ObjectUtils.equals(this.platnostDo, v)) {
			this.platnostDo = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasVytvorenia
	 * 
	 * @return Date
	 */
	public Date getCasVytvorenia() {
		return casVytvorenia;
	}

	/**
	 * Set the value of CasVytvorenia
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasVytvorenia(Date v) {

		if (!ObjectUtils.equals(this.casVytvorenia, v)) {
			this.casVytvorenia = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasZmeny
	 * 
	 * @return Date
	 */
	public Date getCasZmeny() {
		return casZmeny;
	}

	/**
	 * Set the value of CasZmeny
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasZmeny(Date v) {

		if (!ObjectUtils.equals(this.casZmeny, v)) {
			this.casZmeny = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdZmena
	 * 
	 * @return Integer
	 */
	public Integer getIdZmena() {
		return idZmena;
	}

	/**
	 * Set the value of IdZmena
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdZmena(Integer v) {

		if (!ObjectUtils.equals(this.idZmena, v)) {
			this.idZmena = v;
			setModified(true);
		}

	}

	/**
	 * Get the Zmaz
	 * 
	 * @return String
	 */
	public String getZmaz() {
		return zmaz;
	}

	/**
	 * Set the value of Zmaz
	 * 
	 * @param v
	 *            new value
	 */
	public void setZmaz(String v) {

		if (!ObjectUtils.equals(this.zmaz, v)) {
			this.zmaz = v;
			setModified(true);
		}

	}

	/**
	 * Get the TratId
	 * 
	 * @return Integer
	 */
	public Integer getTratId() {
		return tratId;
	}

	/**
	 * Set the value of TratId
	 * 
	 * @param v
	 *            new value
	 */
	public void setTratId(Integer v) {

		if (!ObjectUtils.equals(this.tratId, v)) {
			this.tratId = v;
			setModified(true);
		}

	}

	/**
	 * Get the Cislo
	 * 
	 * @return String
	 */
	public String getCislo() {
		return cislo;
	}

	/**
	 * Set the value of Cislo
	 * 
	 * @param v
	 *            new value
	 */
	public void setCislo(String v) {

		if (!ObjectUtils.equals(this.cislo, v)) {
			this.cislo = v;
			setModified(true);
		}

	}

	/**
	 * Get the Kategoria
	 * 
	 * @return Integer
	 */
	public Integer getKategoria() {
		return kategoria;
	}

	/**
	 * Set the value of Kategoria
	 * 
	 * @param v
	 *            new value
	 */
	public void setKategoria(Integer v) {

		if (!ObjectUtils.equals(this.kategoria, v)) {
			this.kategoria = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdDopravnyBodOd
	 * 
	 * @return Integer
	 */
	public Integer getIdDopravnyBodOd() {
		return idDopravnyBodOd;
	}

	/**
	 * Set the value of IdDopravnyBodOd
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdDopravnyBodOd(Integer v) {

		if (!ObjectUtils.equals(this.idDopravnyBodOd, v)) {
			this.idDopravnyBodOd = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdDopravnyBodDo
	 * 
	 * @return Integer
	 */
	public Integer getIdDopravnyBodDo() {
		return idDopravnyBodDo;
	}

	/**
	 * Set the value of IdDopravnyBodDo
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdDopravnyBodDo(Integer v) {

		if (!ObjectUtils.equals(this.idDopravnyBodDo, v)) {
			this.idDopravnyBodDo = v;
			setModified(true);
		}

	}

	/**
	 * Get the DlzkaM
	 * 
	 * @return Double
	 */
	public Double getDlzkaM() {
		return dlzkaM;
	}

	/**
	 * Set the value of DlzkaM
	 * 
	 * @param v
	 *            new value
	 */
	public void setDlzkaM(Double v) {

		if (!ObjectUtils.equals(this.dlzkaM, v)) {
			this.dlzkaM = v;
			setModified(true);
		}

	}

	/**
	 * Get the DlzkaKm
	 * 
	 * @return Integer
	 */
	public Integer getDlzkaKm() {
		return dlzkaKm;
	}

	/**
	 * Set the value of DlzkaKm
	 * 
	 * @param v
	 *            new value
	 */
	public void setDlzkaKm(Integer v) {

		if (!ObjectUtils.equals(this.dlzkaKm, v)) {
			this.dlzkaKm = v;
			setModified(true);
		}

	}

	private static List fieldNames = null;

	/**
	 * Generate a list of field names.
	 * 
	 * @return a list of field names
	 */
	public static synchronized List getFieldNames() {
		if (fieldNames == null) {
			fieldNames = new ArrayList();
			fieldNames.add("HistId");
			fieldNames.add("PlatnostOd");
			fieldNames.add("PlatnostDo");
			fieldNames.add("CasVytvorenia");
			fieldNames.add("CasZmeny");
			fieldNames.add("IdZmena");
			fieldNames.add("Zmaz");
			fieldNames.add("TratId");
			fieldNames.add("Cislo");
			fieldNames.add("Kategoria");
			fieldNames.add("IdDopravnyBodOd");
			fieldNames.add("IdDopravnyBodDo");
			fieldNames.add("DlzkaM");
			fieldNames.add("DlzkaKm");
			fieldNames = Collections.unmodifiableList(fieldNames);
		}
		return fieldNames;
	}

	/**
	 * Retrieves a field from the object by field (Java) name passed in as a String.
	 * 
	 * @param name
	 *            field name
	 * @return value
	 */
	public Object getByName(String name) {
		if (name.equals("HistId")) {
			return getHistId();
		}
		if (name.equals("PlatnostOd")) {
			return getPlatnostOd();
		}
		if (name.equals("PlatnostDo")) {
			return getPlatnostDo();
		}
		if (name.equals("CasVytvorenia")) {
			return getCasVytvorenia();
		}
		if (name.equals("CasZmeny")) {
			return getCasZmeny();
		}
		if (name.equals("IdZmena")) {
			return getIdZmena();
		}
		if (name.equals("Zmaz")) {
			return getZmaz();
		}
		if (name.equals("TratId")) {
			return getTratId();
		}
		if (name.equals("Cislo")) {
			return getCislo();
		}
		if (name.equals("Kategoria")) {
			return getKategoria();
		}
		if (name.equals("IdDopravnyBodOd")) {
			return getIdDopravnyBodOd();
		}
		if (name.equals("IdDopravnyBodDo")) {
			return getIdDopravnyBodDo();
		}
		if (name.equals("DlzkaM")) {
			return getDlzkaM();
		}
		if (name.equals("DlzkaKm")) {
			return getDlzkaKm();
		}
		return null;
	}

	/**
	 * Set a field in the object by field (Java) name.
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (name.equals("HistId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHistId((Integer) value);
			return true;
		}
		if (name.equals("PlatnostOd")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostOd((Date) value);
			return true;
		}
		if (name.equals("PlatnostDo")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostDo((Date) value);
			return true;
		}
		if (name.equals("CasVytvorenia")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasVytvorenia((Date) value);
			return true;
		}
		if (name.equals("CasZmeny")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasZmeny((Date) value);
			return true;
		}
		if (name.equals("IdZmena")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdZmena((Integer) value);
			return true;
		}
		if (name.equals("Zmaz")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setZmaz((String) value);
			return true;
		}
		if (name.equals("TratId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setTratId((Integer) value);
			return true;
		}
		if (name.equals("Cislo")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCislo((String) value);
			return true;
		}
		if (name.equals("Kategoria")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setKategoria((Integer) value);
			return true;
		}
		if (name.equals("IdDopravnyBodOd")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdDopravnyBodOd((Integer) value);
			return true;
		}
		if (name.equals("IdDopravnyBodDo")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdDopravnyBodDo((Integer) value);
			return true;
		}
		if (name.equals("DlzkaM")) {
			// Object fields can be null
			if (value != null && !Double.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setDlzkaM((Double) value);
			return true;
		}
		if (name.equals("DlzkaKm")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setDlzkaKm((Integer) value);
			return true;
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by name passed in as a String. The String must be one of the static Strings defined in this Class' Peer.
	 * 
	 * @param name
	 *            peer name
	 * @return value
	 */
	public Object getByPeerName(String name) {
		if (name.equals(TTratPeer.HIST_ID)) {
			return getHistId();
		}
		if (name.equals(TTratPeer.PLATNOST_OD)) {
			return getPlatnostOd();
		}
		if (name.equals(TTratPeer.PLATNOST_DO)) {
			return getPlatnostDo();
		}
		if (name.equals(TTratPeer.CAS_VYTVORENIA)) {
			return getCasVytvorenia();
		}
		if (name.equals(TTratPeer.CAS_ZMENY)) {
			return getCasZmeny();
		}
		if (name.equals(TTratPeer.ID_ZMENA)) {
			return getIdZmena();
		}
		if (name.equals(TTratPeer.ZMAZ)) {
			return getZmaz();
		}
		if (name.equals(TTratPeer.TRAT_ID)) {
			return getTratId();
		}
		if (name.equals(TTratPeer.CISLO)) {
			return getCislo();
		}
		if (name.equals(TTratPeer.KATEGORIA)) {
			return getKategoria();
		}
		if (name.equals(TTratPeer.ID_DOPRAVNY_BOD_OD)) {
			return getIdDopravnyBodOd();
		}
		if (name.equals(TTratPeer.ID_DOPRAVNY_BOD_DO)) {
			return getIdDopravnyBodDo();
		}
		if (name.equals(TTratPeer.DLZKA_M)) {
			return getDlzkaM();
		}
		if (name.equals(TTratPeer.DLZKA_KM)) {
			return getDlzkaKm();
		}
		return null;
	}

	/**
	 * Set field values by Peer Field Name
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPeerName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (TTratPeer.HIST_ID.equals(name)) {
			return setByName("HistId", value);
		}
		if (TTratPeer.PLATNOST_OD.equals(name)) {
			return setByName("PlatnostOd", value);
		}
		if (TTratPeer.PLATNOST_DO.equals(name)) {
			return setByName("PlatnostDo", value);
		}
		if (TTratPeer.CAS_VYTVORENIA.equals(name)) {
			return setByName("CasVytvorenia", value);
		}
		if (TTratPeer.CAS_ZMENY.equals(name)) {
			return setByName("CasZmeny", value);
		}
		if (TTratPeer.ID_ZMENA.equals(name)) {
			return setByName("IdZmena", value);
		}
		if (TTratPeer.ZMAZ.equals(name)) {
			return setByName("Zmaz", value);
		}
		if (TTratPeer.TRAT_ID.equals(name)) {
			return setByName("TratId", value);
		}
		if (TTratPeer.CISLO.equals(name)) {
			return setByName("Cislo", value);
		}
		if (TTratPeer.KATEGORIA.equals(name)) {
			return setByName("Kategoria", value);
		}
		if (TTratPeer.ID_DOPRAVNY_BOD_OD.equals(name)) {
			return setByName("IdDopravnyBodOd", value);
		}
		if (TTratPeer.ID_DOPRAVNY_BOD_DO.equals(name)) {
			return setByName("IdDopravnyBodDo", value);
		}
		if (TTratPeer.DLZKA_M.equals(name)) {
			return setByName("DlzkaM", value);
		}
		if (TTratPeer.DLZKA_KM.equals(name)) {
			return setByName("DlzkaKm", value);
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema. Zero-based.
	 * 
	 * @param pos
	 *            position in xml schema
	 * @return value
	 */
	public Object getByPosition(int pos) {
		if (pos == 0) {
			return getHistId();
		}
		if (pos == 1) {
			return getPlatnostOd();
		}
		if (pos == 2) {
			return getPlatnostDo();
		}
		if (pos == 3) {
			return getCasVytvorenia();
		}
		if (pos == 4) {
			return getCasZmeny();
		}
		if (pos == 5) {
			return getIdZmena();
		}
		if (pos == 6) {
			return getZmaz();
		}
		if (pos == 7) {
			return getTratId();
		}
		if (pos == 8) {
			return getCislo();
		}
		if (pos == 9) {
			return getKategoria();
		}
		if (pos == 10) {
			return getIdDopravnyBodOd();
		}
		if (pos == 11) {
			return getIdDopravnyBodDo();
		}
		if (pos == 12) {
			return getDlzkaM();
		}
		if (pos == 13) {
			return getDlzkaKm();
		}
		return null;
	}

	/**
	 * Set field values by its position (zero based) in the XML schema.
	 * 
	 * @param position
	 *            The field position
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid position / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPosition(int position, Object value) throws TorqueException, IllegalArgumentException {
		if (position == 0) {
			return setByName("HistId", value);
		}
		if (position == 1) {
			return setByName("PlatnostOd", value);
		}
		if (position == 2) {
			return setByName("PlatnostDo", value);
		}
		if (position == 3) {
			return setByName("CasVytvorenia", value);
		}
		if (position == 4) {
			return setByName("CasZmeny", value);
		}
		if (position == 5) {
			return setByName("IdZmena", value);
		}
		if (position == 6) {
			return setByName("Zmaz", value);
		}
		if (position == 7) {
			return setByName("TratId", value);
		}
		if (position == 8) {
			return setByName("Cislo", value);
		}
		if (position == 9) {
			return setByName("Kategoria", value);
		}
		if (position == 10) {
			return setByName("IdDopravnyBodOd", value);
		}
		if (position == 11) {
			return setByName("IdDopravnyBodDo", value);
		}
		if (position == 12) {
			return setByName("DlzkaM", value);
		}
		if (position == 13) {
			return setByName("DlzkaKm", value);
		}
		return false;
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed.
	 * 
	 * @throws Exception
	 */
	public void save() throws Exception {
		save(TTratPeer.DATABASE_NAME);
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. Note: this code is here because the method body is auto-generated
	 * conditionally and therefore needs to be in this file instead of in the super class, BaseObject.
	 * 
	 * @param dbName
	 * @throws TorqueException
	 */
	public void save(String dbName) throws TorqueException {
		Connection con = null;
		try {
			con = Transaction.begin(dbName);
			save(con);
			Transaction.commit(con);
		} catch (TorqueException e) {
			Transaction.safeRollback(con);
			throw e;
		}
	}

	/**
	 * flag to prevent endless save loop, if this object is referenced by another object which falls in this transaction.
	 */
	private boolean alreadyInSave = false;

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. This method is meant to be used as part of a transaction, otherwise
	 * use the save() method and the connection details will be handled internally
	 * 
	 * @param con
	 * @throws TorqueException
	 */
	public void save(Connection con) throws TorqueException {
		if (!alreadyInSave) {
			alreadyInSave = true;

			// If this object has been modified, then save it to the database.
			if (isModified()) {
				if (isNew()) {
					TTratPeer.doInsert((TTrat) this, con);
					setNew(false);
				} else {
					TTratPeer.doUpdate((TTrat) this, con);
				}
			}

			alreadyInSave = false;
		}
	}

	/**
	 * Set the PrimaryKey using ObjectKey.
	 * 
	 * @param key
	 *            histId ObjectKey
	 */
	public void setPrimaryKey(ObjectKey key)

	{
		setHistId(new Integer(((NumberKey) key).intValue()));
	}

	/**
	 * Set the PrimaryKey using a String.
	 * 
	 * @param key
	 */
	public void setPrimaryKey(String key) {
		setHistId(new Integer(key));
	}

	/**
	 * returns an id that differentiates this object from others of its class.
	 */
	public ObjectKey getPrimaryKey() {
		return SimpleKey.keyFor(getHistId());
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. It then fills all the association collections and sets the related objects to
	 * isNew=true.
	 */
	public TTrat copy() throws TorqueException {
		return copy(true);
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. If the parameter deepcopy is true, it then fills all the association collections and
	 * sets the related objects to isNew=true.
	 * 
	 * @param deepcopy
	 *            whether to copy the associated objects.
	 */
	public TTrat copy(boolean deepcopy) throws TorqueException {
		return copyInto(new TTrat(), deepcopy);
	}

	/**
	 * Fills the copyObj with the contents of this object. The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 */
	protected TTrat copyInto(TTrat copyObj) throws TorqueException {
		return copyInto(copyObj, true);
	}

	/**
	 * Fills the copyObj with the contents of this object. If deepcopy is true, The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 * @param deepcopy
	 *            whether the associated objects should be copied.
	 */
	protected TTrat copyInto(TTrat copyObj, boolean deepcopy) throws TorqueException {
		copyObj.setHistId(histId);
		copyObj.setPlatnostOd(platnostOd);
		copyObj.setPlatnostDo(platnostDo);
		copyObj.setCasVytvorenia(casVytvorenia);
		copyObj.setCasZmeny(casZmeny);
		copyObj.setIdZmena(idZmena);
		copyObj.setZmaz(zmaz);
		copyObj.setTratId(tratId);
		copyObj.setCislo(cislo);
		copyObj.setKategoria(kategoria);
		copyObj.setIdDopravnyBodOd(idDopravnyBodOd);
		copyObj.setIdDopravnyBodDo(idDopravnyBodDo);
		copyObj.setDlzkaM(dlzkaM);
		copyObj.setDlzkaKm(dlzkaKm);

		copyObj.setHistId((Integer) null);

		if (deepcopy) {
		}
		return copyObj;
	}

	/**
	 * returns a peer instance associated with this om. Since Peer classes are not to have any instance attributes, this method returns the same instance for all member of this
	 * class. The method could therefore be static, but this would prevent one from overriding the behavior.
	 */
	public TTratPeer getPeer() {
		return peer;
	}

	/**
	 * Retrieves the TableMap object related to this Table data without compiler warnings of using getPeer().getTableMap().
	 * 
	 * @return The associated TableMap object.
	 */
	public TableMap getTableMap() throws TorqueException {
		return TTratPeer.getTableMap();
	}

	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("TTrat:\n");
		str.append("HistId = ").append(getHistId()).append("\n");
		str.append("PlatnostOd = ").append(getPlatnostOd()).append("\n");
		str.append("PlatnostDo = ").append(getPlatnostDo()).append("\n");
		str.append("CasVytvorenia = ").append(getCasVytvorenia()).append("\n");
		str.append("CasZmeny = ").append(getCasZmeny()).append("\n");
		str.append("IdZmena = ").append(getIdZmena()).append("\n");
		str.append("Zmaz = ").append(getZmaz()).append("\n");
		str.append("TratId = ").append(getTratId()).append("\n");
		str.append("Cislo = ").append(getCislo()).append("\n");
		str.append("Kategoria = ").append(getKategoria()).append("\n");
		str.append("IdDopravnyBodOd = ").append(getIdDopravnyBodOd()).append("\n");
		str.append("IdDopravnyBodDo = ").append(getIdDopravnyBodDo()).append("\n");
		str.append("DlzkaM = ").append(getDlzkaM()).append("\n");
		str.append("DlzkaKm = ").append(getDlzkaKm()).append("\n");
		return (str.toString());
	}
}
