package sk.ditec.dao.master;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Fri Jul 25 14:44:46 CEST 2025]
 * 
 * You should not use this class directly. It should not even be extended all references should be to TNastupistePrm
 */
public abstract class BaseTNastupistePrm extends BaseObject {
	/** Serial version */
	private static final long serialVersionUID = 1753447486539L;

	/** The Peer class */
	private static final TNastupistePrmPeer peer = new TNastupistePrmPeer();

	/** The value for the histId field */
	private Integer histId;

	/** The value for the platnostOd field */
	private Date platnostOd;

	/** The value for the platnostDo field */
	private Date platnostDo;

	/** The value for the casVytvorenia field */
	private Date casVytvorenia;

	/** The value for the casZmeny field */
	private Date casZmeny;

	/** The value for the idZmena field */
	private Integer idZmena;

	/** The value for the zmaz field */
	private String zmaz;

	/** The value for the nastupistePrmId field */
	private Integer nastupistePrmId;

	/** The value for the nastupisteCislo field */
	private String nastupisteCislo;

	/** The value for the prisupBezSchodZRefer field */
	private String prisupBezSchodZRefer;

	/** The value for the hmatovaCestaZRefer field */
	private String hmatovaCestaZRefer;

	/** The value for the kontrastneSchodyZRefer field */
	private String kontrastneSchodyZRefer;

	/** The value for the zvyrazneniePrekazokZRefer field */
	private String zvyrazneniePrekazokZRefer;

	/** The value for the podlahoveIndikatoryNastup field */
	private String podlahoveIndikatoryNastup;

	/** The value for the barieryNaKontroluClNastupistia field */
	private String barieryNaKontroluClNastupistia;

	/** The value for the barieryNaKontroluClVozik field */
	private String barieryNaKontroluClVozik;

	/** The value for the doplnInfOPristupnosti field */
	private String doplnInfOPristupnosti;

	/** The value for the urovnovyPristupVozik field */
	private String urovnovyPristupVozik;

	/** The value for the pomocneZarNastupVystup field */
	private String pomocneZarNastupVystup;

	/** The value for the doplnInfOPristupnostiPomZar field */
	private String doplnInfOPristupnostiPomZar;

	/** The value for the pomocPriPristupe field */
	private String pomocPriPristupe;

	/** The value for the podmienkyPomoci field */
	private String podmienkyPomoci;

	/** The value for the pomocBezOznamenia field */
	private String pomocBezOznamenia;

	/** The value for the moznostNadZssk field */
	private String moznostNadZssk;

	/** The value for the podmienkyNadZssk field */
	private String podmienkyNadZssk;

	/** The value for the idDopravnyBod field */
	private Integer idDopravnyBod;

	/**
	 * Get the HistId
	 * 
	 * @return Integer
	 */
	public Integer getHistId() {
		return histId;
	}

	/**
	 * Set the value of HistId
	 * 
	 * @param v
	 *            new value
	 */
	public void setHistId(Integer v) {

		if (!ObjectUtils.equals(this.histId, v)) {
			this.histId = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostOd
	 * 
	 * @return Date
	 */
	public Date getPlatnostOd() {
		return platnostOd;
	}

	/**
	 * Set the value of PlatnostOd
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostOd(Date v) {

		if (!ObjectUtils.equals(this.platnostOd, v)) {
			this.platnostOd = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostDo
	 * 
	 * @return Date
	 */
	public Date getPlatnostDo() {
		return platnostDo;
	}

	/**
	 * Set the value of PlatnostDo
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostDo(Date v) {

		if (!ObjectUtils.equals(this.platnostDo, v)) {
			this.platnostDo = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasVytvorenia
	 * 
	 * @return Date
	 */
	public Date getCasVytvorenia() {
		return casVytvorenia;
	}

	/**
	 * Set the value of CasVytvorenia
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasVytvorenia(Date v) {

		if (!ObjectUtils.equals(this.casVytvorenia, v)) {
			this.casVytvorenia = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasZmeny
	 * 
	 * @return Date
	 */
	public Date getCasZmeny() {
		return casZmeny;
	}

	/**
	 * Set the value of CasZmeny
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasZmeny(Date v) {

		if (!ObjectUtils.equals(this.casZmeny, v)) {
			this.casZmeny = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdZmena
	 * 
	 * @return Integer
	 */
	public Integer getIdZmena() {
		return idZmena;
	}

	/**
	 * Set the value of IdZmena
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdZmena(Integer v) {

		if (!ObjectUtils.equals(this.idZmena, v)) {
			this.idZmena = v;
			setModified(true);
		}

	}

	/**
	 * Get the Zmaz
	 * 
	 * @return String
	 */
	public String getZmaz() {
		return zmaz;
	}

	/**
	 * Set the value of Zmaz
	 * 
	 * @param v
	 *            new value
	 */
	public void setZmaz(String v) {

		if (!ObjectUtils.equals(this.zmaz, v)) {
			this.zmaz = v;
			setModified(true);
		}

	}

	/**
	 * Get the NastupistePrmId
	 * 
	 * @return Integer
	 */
	public Integer getNastupistePrmId() {
		return nastupistePrmId;
	}

	/**
	 * Set the value of NastupistePrmId
	 * 
	 * @param v
	 *            new value
	 */
	public void setNastupistePrmId(Integer v) {

		if (!ObjectUtils.equals(this.nastupistePrmId, v)) {
			this.nastupistePrmId = v;
			setModified(true);
		}

	}

	/**
	 * Get the NastupisteCislo
	 * 
	 * @return String
	 */
	public String getNastupisteCislo() {
		return nastupisteCislo;
	}

	/**
	 * Set the value of NastupisteCislo
	 * 
	 * @param v
	 *            new value
	 */
	public void setNastupisteCislo(String v) {

		if (!ObjectUtils.equals(this.nastupisteCislo, v)) {
			this.nastupisteCislo = v;
			setModified(true);
		}

	}

	/**
	 * Get the PrisupBezSchodZRefer
	 * 
	 * @return String
	 */
	public String getPrisupBezSchodZRefer() {
		return prisupBezSchodZRefer;
	}

	/**
	 * Set the value of PrisupBezSchodZRefer
	 * 
	 * @param v
	 *            new value
	 */
	public void setPrisupBezSchodZRefer(String v) {

		if (!ObjectUtils.equals(this.prisupBezSchodZRefer, v)) {
			this.prisupBezSchodZRefer = v;
			setModified(true);
		}

	}

	/**
	 * Get the HmatovaCestaZRefer
	 * 
	 * @return String
	 */
	public String getHmatovaCestaZRefer() {
		return hmatovaCestaZRefer;
	}

	/**
	 * Set the value of HmatovaCestaZRefer
	 * 
	 * @param v
	 *            new value
	 */
	public void setHmatovaCestaZRefer(String v) {

		if (!ObjectUtils.equals(this.hmatovaCestaZRefer, v)) {
			this.hmatovaCestaZRefer = v;
			setModified(true);
		}

	}

	/**
	 * Get the KontrastneSchodyZRefer
	 * 
	 * @return String
	 */
	public String getKontrastneSchodyZRefer() {
		return kontrastneSchodyZRefer;
	}

	/**
	 * Set the value of KontrastneSchodyZRefer
	 * 
	 * @param v
	 *            new value
	 */
	public void setKontrastneSchodyZRefer(String v) {

		if (!ObjectUtils.equals(this.kontrastneSchodyZRefer, v)) {
			this.kontrastneSchodyZRefer = v;
			setModified(true);
		}

	}

	/**
	 * Get the ZvyrazneniePrekazokZRefer
	 * 
	 * @return String
	 */
	public String getZvyrazneniePrekazokZRefer() {
		return zvyrazneniePrekazokZRefer;
	}

	/**
	 * Set the value of ZvyrazneniePrekazokZRefer
	 * 
	 * @param v
	 *            new value
	 */
	public void setZvyrazneniePrekazokZRefer(String v) {

		if (!ObjectUtils.equals(this.zvyrazneniePrekazokZRefer, v)) {
			this.zvyrazneniePrekazokZRefer = v;
			setModified(true);
		}

	}

	/**
	 * Get the PodlahoveIndikatoryNastup
	 * 
	 * @return String
	 */
	public String getPodlahoveIndikatoryNastup() {
		return podlahoveIndikatoryNastup;
	}

	/**
	 * Set the value of PodlahoveIndikatoryNastup
	 * 
	 * @param v
	 *            new value
	 */
	public void setPodlahoveIndikatoryNastup(String v) {

		if (!ObjectUtils.equals(this.podlahoveIndikatoryNastup, v)) {
			this.podlahoveIndikatoryNastup = v;
			setModified(true);
		}

	}

	/**
	 * Get the BarieryNaKontroluClNastupistia
	 * 
	 * @return String
	 */
	public String getBarieryNaKontroluClNastupistia() {
		return barieryNaKontroluClNastupistia;
	}

	/**
	 * Set the value of BarieryNaKontroluClNastupistia
	 * 
	 * @param v
	 *            new value
	 */
	public void setBarieryNaKontroluClNastupistia(String v) {

		if (!ObjectUtils.equals(this.barieryNaKontroluClNastupistia, v)) {
			this.barieryNaKontroluClNastupistia = v;
			setModified(true);
		}

	}

	/**
	 * Get the BarieryNaKontroluClVozik
	 * 
	 * @return String
	 */
	public String getBarieryNaKontroluClVozik() {
		return barieryNaKontroluClVozik;
	}

	/**
	 * Set the value of BarieryNaKontroluClVozik
	 * 
	 * @param v
	 *            new value
	 */
	public void setBarieryNaKontroluClVozik(String v) {

		if (!ObjectUtils.equals(this.barieryNaKontroluClVozik, v)) {
			this.barieryNaKontroluClVozik = v;
			setModified(true);
		}

	}

	/**
	 * Get the DoplnInfOPristupnosti
	 * 
	 * @return String
	 */
	public String getDoplnInfOPristupnosti() {
		return doplnInfOPristupnosti;
	}

	/**
	 * Set the value of DoplnInfOPristupnosti
	 * 
	 * @param v
	 *            new value
	 */
	public void setDoplnInfOPristupnosti(String v) {

		if (!ObjectUtils.equals(this.doplnInfOPristupnosti, v)) {
			this.doplnInfOPristupnosti = v;
			setModified(true);
		}

	}

	/**
	 * Get the UrovnovyPristupVozik
	 * 
	 * @return String
	 */
	public String getUrovnovyPristupVozik() {
		return urovnovyPristupVozik;
	}

	/**
	 * Set the value of UrovnovyPristupVozik
	 * 
	 * @param v
	 *            new value
	 */
	public void setUrovnovyPristupVozik(String v) {

		if (!ObjectUtils.equals(this.urovnovyPristupVozik, v)) {
			this.urovnovyPristupVozik = v;
			setModified(true);
		}

	}

	/**
	 * Get the PomocneZarNastupVystup
	 * 
	 * @return String
	 */
	public String getPomocneZarNastupVystup() {
		return pomocneZarNastupVystup;
	}

	/**
	 * Set the value of PomocneZarNastupVystup
	 * 
	 * @param v
	 *            new value
	 */
	public void setPomocneZarNastupVystup(String v) {

		if (!ObjectUtils.equals(this.pomocneZarNastupVystup, v)) {
			this.pomocneZarNastupVystup = v;
			setModified(true);
		}

	}

	/**
	 * Get the DoplnInfOPristupnostiPomZar
	 * 
	 * @return String
	 */
	public String getDoplnInfOPristupnostiPomZar() {
		return doplnInfOPristupnostiPomZar;
	}

	/**
	 * Set the value of DoplnInfOPristupnostiPomZar
	 * 
	 * @param v
	 *            new value
	 */
	public void setDoplnInfOPristupnostiPomZar(String v) {

		if (!ObjectUtils.equals(this.doplnInfOPristupnostiPomZar, v)) {
			this.doplnInfOPristupnostiPomZar = v;
			setModified(true);
		}

	}

	/**
	 * Get the PomocPriPristupe
	 * 
	 * @return String
	 */
	public String getPomocPriPristupe() {
		return pomocPriPristupe;
	}

	/**
	 * Set the value of PomocPriPristupe
	 * 
	 * @param v
	 *            new value
	 */
	public void setPomocPriPristupe(String v) {

		if (!ObjectUtils.equals(this.pomocPriPristupe, v)) {
			this.pomocPriPristupe = v;
			setModified(true);
		}

	}

	/**
	 * Get the PodmienkyPomoci
	 * 
	 * @return String
	 */
	public String getPodmienkyPomoci() {
		return podmienkyPomoci;
	}

	/**
	 * Set the value of PodmienkyPomoci
	 * 
	 * @param v
	 *            new value
	 */
	public void setPodmienkyPomoci(String v) {

		if (!ObjectUtils.equals(this.podmienkyPomoci, v)) {
			this.podmienkyPomoci = v;
			setModified(true);
		}

	}

	/**
	 * Get the PomocBezOznamenia
	 * 
	 * @return String
	 */
	public String getPomocBezOznamenia() {
		return pomocBezOznamenia;
	}

	/**
	 * Set the value of PomocBezOznamenia
	 * 
	 * @param v
	 *            new value
	 */
	public void setPomocBezOznamenia(String v) {

		if (!ObjectUtils.equals(this.pomocBezOznamenia, v)) {
			this.pomocBezOznamenia = v;
			setModified(true);
		}

	}

	/**
	 * Get the MoznostNadZssk
	 * 
	 * @return String
	 */
	public String getMoznostNadZssk() {
		return moznostNadZssk;
	}

	/**
	 * Set the value of MoznostNadZssk
	 * 
	 * @param v
	 *            new value
	 */
	public void setMoznostNadZssk(String v) {

		if (!ObjectUtils.equals(this.moznostNadZssk, v)) {
			this.moznostNadZssk = v;
			setModified(true);
		}

	}

	/**
	 * Get the PodmienkyNadZssk
	 * 
	 * @return String
	 */
	public String getPodmienkyNadZssk() {
		return podmienkyNadZssk;
	}

	/**
	 * Set the value of PodmienkyNadZssk
	 * 
	 * @param v
	 *            new value
	 */
	public void setPodmienkyNadZssk(String v) {

		if (!ObjectUtils.equals(this.podmienkyNadZssk, v)) {
			this.podmienkyNadZssk = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdDopravnyBod
	 * 
	 * @return Integer
	 */
	public Integer getIdDopravnyBod() {
		return idDopravnyBod;
	}

	/**
	 * Set the value of IdDopravnyBod
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdDopravnyBod(Integer v) {

		if (!ObjectUtils.equals(this.idDopravnyBod, v)) {
			this.idDopravnyBod = v;
			setModified(true);
		}

	}

	private static List fieldNames = null;

	/**
	 * Generate a list of field names.
	 * 
	 * @return a list of field names
	 */
	public static synchronized List getFieldNames() {
		if (fieldNames == null) {
			fieldNames = new ArrayList();
			fieldNames.add("HistId");
			fieldNames.add("PlatnostOd");
			fieldNames.add("PlatnostDo");
			fieldNames.add("CasVytvorenia");
			fieldNames.add("CasZmeny");
			fieldNames.add("IdZmena");
			fieldNames.add("Zmaz");
			fieldNames.add("NastupistePrmId");
			fieldNames.add("NastupisteCislo");
			fieldNames.add("PrisupBezSchodZRefer");
			fieldNames.add("HmatovaCestaZRefer");
			fieldNames.add("KontrastneSchodyZRefer");
			fieldNames.add("ZvyrazneniePrekazokZRefer");
			fieldNames.add("PodlahoveIndikatoryNastup");
			fieldNames.add("BarieryNaKontroluClNastupistia");
			fieldNames.add("BarieryNaKontroluClVozik");
			fieldNames.add("DoplnInfOPristupnosti");
			fieldNames.add("UrovnovyPristupVozik");
			fieldNames.add("PomocneZarNastupVystup");
			fieldNames.add("DoplnInfOPristupnostiPomZar");
			fieldNames.add("PomocPriPristupe");
			fieldNames.add("PodmienkyPomoci");
			fieldNames.add("PomocBezOznamenia");
			fieldNames.add("MoznostNadZssk");
			fieldNames.add("PodmienkyNadZssk");
			fieldNames.add("IdDopravnyBod");
			fieldNames = Collections.unmodifiableList(fieldNames);
		}
		return fieldNames;
	}

	/**
	 * Retrieves a field from the object by field (Java) name passed in as a String.
	 * 
	 * @param name
	 *            field name
	 * @return value
	 */
	public Object getByName(String name) {
		if (name.equals("HistId")) {
			return getHistId();
		}
		if (name.equals("PlatnostOd")) {
			return getPlatnostOd();
		}
		if (name.equals("PlatnostDo")) {
			return getPlatnostDo();
		}
		if (name.equals("CasVytvorenia")) {
			return getCasVytvorenia();
		}
		if (name.equals("CasZmeny")) {
			return getCasZmeny();
		}
		if (name.equals("IdZmena")) {
			return getIdZmena();
		}
		if (name.equals("Zmaz")) {
			return getZmaz();
		}
		if (name.equals("NastupistePrmId")) {
			return getNastupistePrmId();
		}
		if (name.equals("NastupisteCislo")) {
			return getNastupisteCislo();
		}
		if (name.equals("PrisupBezSchodZRefer")) {
			return getPrisupBezSchodZRefer();
		}
		if (name.equals("HmatovaCestaZRefer")) {
			return getHmatovaCestaZRefer();
		}
		if (name.equals("KontrastneSchodyZRefer")) {
			return getKontrastneSchodyZRefer();
		}
		if (name.equals("ZvyrazneniePrekazokZRefer")) {
			return getZvyrazneniePrekazokZRefer();
		}
		if (name.equals("PodlahoveIndikatoryNastup")) {
			return getPodlahoveIndikatoryNastup();
		}
		if (name.equals("BarieryNaKontroluClNastupistia")) {
			return getBarieryNaKontroluClNastupistia();
		}
		if (name.equals("BarieryNaKontroluClVozik")) {
			return getBarieryNaKontroluClVozik();
		}
		if (name.equals("DoplnInfOPristupnosti")) {
			return getDoplnInfOPristupnosti();
		}
		if (name.equals("UrovnovyPristupVozik")) {
			return getUrovnovyPristupVozik();
		}
		if (name.equals("PomocneZarNastupVystup")) {
			return getPomocneZarNastupVystup();
		}
		if (name.equals("DoplnInfOPristupnostiPomZar")) {
			return getDoplnInfOPristupnostiPomZar();
		}
		if (name.equals("PomocPriPristupe")) {
			return getPomocPriPristupe();
		}
		if (name.equals("PodmienkyPomoci")) {
			return getPodmienkyPomoci();
		}
		if (name.equals("PomocBezOznamenia")) {
			return getPomocBezOznamenia();
		}
		if (name.equals("MoznostNadZssk")) {
			return getMoznostNadZssk();
		}
		if (name.equals("PodmienkyNadZssk")) {
			return getPodmienkyNadZssk();
		}
		if (name.equals("IdDopravnyBod")) {
			return getIdDopravnyBod();
		}
		return null;
	}

	/**
	 * Set a field in the object by field (Java) name.
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (name.equals("HistId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHistId((Integer) value);
			return true;
		}
		if (name.equals("PlatnostOd")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostOd((Date) value);
			return true;
		}
		if (name.equals("PlatnostDo")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostDo((Date) value);
			return true;
		}
		if (name.equals("CasVytvorenia")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasVytvorenia((Date) value);
			return true;
		}
		if (name.equals("CasZmeny")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasZmeny((Date) value);
			return true;
		}
		if (name.equals("IdZmena")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdZmena((Integer) value);
			return true;
		}
		if (name.equals("Zmaz")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setZmaz((String) value);
			return true;
		}
		if (name.equals("NastupistePrmId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setNastupistePrmId((Integer) value);
			return true;
		}
		if (name.equals("NastupisteCislo")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setNastupisteCislo((String) value);
			return true;
		}
		if (name.equals("PrisupBezSchodZRefer")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPrisupBezSchodZRefer((String) value);
			return true;
		}
		if (name.equals("HmatovaCestaZRefer")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHmatovaCestaZRefer((String) value);
			return true;
		}
		if (name.equals("KontrastneSchodyZRefer")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setKontrastneSchodyZRefer((String) value);
			return true;
		}
		if (name.equals("ZvyrazneniePrekazokZRefer")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setZvyrazneniePrekazokZRefer((String) value);
			return true;
		}
		if (name.equals("PodlahoveIndikatoryNastup")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPodlahoveIndikatoryNastup((String) value);
			return true;
		}
		if (name.equals("BarieryNaKontroluClNastupistia")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setBarieryNaKontroluClNastupistia((String) value);
			return true;
		}
		if (name.equals("BarieryNaKontroluClVozik")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setBarieryNaKontroluClVozik((String) value);
			return true;
		}
		if (name.equals("DoplnInfOPristupnosti")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setDoplnInfOPristupnosti((String) value);
			return true;
		}
		if (name.equals("UrovnovyPristupVozik")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setUrovnovyPristupVozik((String) value);
			return true;
		}
		if (name.equals("PomocneZarNastupVystup")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPomocneZarNastupVystup((String) value);
			return true;
		}
		if (name.equals("DoplnInfOPristupnostiPomZar")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setDoplnInfOPristupnostiPomZar((String) value);
			return true;
		}
		if (name.equals("PomocPriPristupe")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPomocPriPristupe((String) value);
			return true;
		}
		if (name.equals("PodmienkyPomoci")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPodmienkyPomoci((String) value);
			return true;
		}
		if (name.equals("PomocBezOznamenia")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPomocBezOznamenia((String) value);
			return true;
		}
		if (name.equals("MoznostNadZssk")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setMoznostNadZssk((String) value);
			return true;
		}
		if (name.equals("PodmienkyNadZssk")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPodmienkyNadZssk((String) value);
			return true;
		}
		if (name.equals("IdDopravnyBod")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdDopravnyBod((Integer) value);
			return true;
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by name passed in as a String. The String must be one of the static Strings defined in this Class' Peer.
	 * 
	 * @param name
	 *            peer name
	 * @return value
	 */
	public Object getByPeerName(String name) {
		if (name.equals(TNastupistePrmPeer.HIST_ID)) {
			return getHistId();
		}
		if (name.equals(TNastupistePrmPeer.PLATNOST_OD)) {
			return getPlatnostOd();
		}
		if (name.equals(TNastupistePrmPeer.PLATNOST_DO)) {
			return getPlatnostDo();
		}
		if (name.equals(TNastupistePrmPeer.CAS_VYTVORENIA)) {
			return getCasVytvorenia();
		}
		if (name.equals(TNastupistePrmPeer.CAS_ZMENY)) {
			return getCasZmeny();
		}
		if (name.equals(TNastupistePrmPeer.ID_ZMENA)) {
			return getIdZmena();
		}
		if (name.equals(TNastupistePrmPeer.ZMAZ)) {
			return getZmaz();
		}
		if (name.equals(TNastupistePrmPeer.NASTUPISTE_PRM_ID)) {
			return getNastupistePrmId();
		}
		if (name.equals(TNastupistePrmPeer.NASTUPISTE_CISLO)) {
			return getNastupisteCislo();
		}
		if (name.equals(TNastupistePrmPeer.PRISUP_BEZ_SCHOD_Z_REFER)) {
			return getPrisupBezSchodZRefer();
		}
		if (name.equals(TNastupistePrmPeer.HMATOVA_CESTA_Z_REFER)) {
			return getHmatovaCestaZRefer();
		}
		if (name.equals(TNastupistePrmPeer.KONTRASTNE_SCHODY_Z_REFER)) {
			return getKontrastneSchodyZRefer();
		}
		if (name.equals(TNastupistePrmPeer.ZVYRAZNENIE_PREKAZOK_Z_REFER)) {
			return getZvyrazneniePrekazokZRefer();
		}
		if (name.equals(TNastupistePrmPeer.PODLAHOVE_INDIKATORY_NASTUP)) {
			return getPodlahoveIndikatoryNastup();
		}
		if (name.equals(TNastupistePrmPeer.BARIERY_NA_KONTROLU_CL_NASTUPISTIA)) {
			return getBarieryNaKontroluClNastupistia();
		}
		if (name.equals(TNastupistePrmPeer.BARIERY_NA_KONTROLU_CL_VOZIK)) {
			return getBarieryNaKontroluClVozik();
		}
		if (name.equals(TNastupistePrmPeer.DOPLN_INF_O_PRISTUPNOSTI)) {
			return getDoplnInfOPristupnosti();
		}
		if (name.equals(TNastupistePrmPeer.UROVNOVY_PRISTUP_VOZIK)) {
			return getUrovnovyPristupVozik();
		}
		if (name.equals(TNastupistePrmPeer.POMOCNE_ZAR_NASTUP_VYSTUP)) {
			return getPomocneZarNastupVystup();
		}
		if (name.equals(TNastupistePrmPeer.DOPLN_INF_O_PRISTUPNOSTI_POM_ZAR)) {
			return getDoplnInfOPristupnostiPomZar();
		}
		if (name.equals(TNastupistePrmPeer.POMOC_PRI_PRISTUPE)) {
			return getPomocPriPristupe();
		}
		if (name.equals(TNastupistePrmPeer.PODMIENKY_POMOCI)) {
			return getPodmienkyPomoci();
		}
		if (name.equals(TNastupistePrmPeer.POMOC_BEZ_OZNAMENIA)) {
			return getPomocBezOznamenia();
		}
		if (name.equals(TNastupistePrmPeer.MOZNOST_NAD_ZSSK)) {
			return getMoznostNadZssk();
		}
		if (name.equals(TNastupistePrmPeer.PODMIENKY_NAD_ZSSK)) {
			return getPodmienkyNadZssk();
		}
		if (name.equals(TNastupistePrmPeer.ID_DOPRAVNY_BOD)) {
			return getIdDopravnyBod();
		}
		return null;
	}

	/**
	 * Set field values by Peer Field Name
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPeerName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (TNastupistePrmPeer.HIST_ID.equals(name)) {
			return setByName("HistId", value);
		}
		if (TNastupistePrmPeer.PLATNOST_OD.equals(name)) {
			return setByName("PlatnostOd", value);
		}
		if (TNastupistePrmPeer.PLATNOST_DO.equals(name)) {
			return setByName("PlatnostDo", value);
		}
		if (TNastupistePrmPeer.CAS_VYTVORENIA.equals(name)) {
			return setByName("CasVytvorenia", value);
		}
		if (TNastupistePrmPeer.CAS_ZMENY.equals(name)) {
			return setByName("CasZmeny", value);
		}
		if (TNastupistePrmPeer.ID_ZMENA.equals(name)) {
			return setByName("IdZmena", value);
		}
		if (TNastupistePrmPeer.ZMAZ.equals(name)) {
			return setByName("Zmaz", value);
		}
		if (TNastupistePrmPeer.NASTUPISTE_PRM_ID.equals(name)) {
			return setByName("NastupistePrmId", value);
		}
		if (TNastupistePrmPeer.NASTUPISTE_CISLO.equals(name)) {
			return setByName("NastupisteCislo", value);
		}
		if (TNastupistePrmPeer.PRISUP_BEZ_SCHOD_Z_REFER.equals(name)) {
			return setByName("PrisupBezSchodZRefer", value);
		}
		if (TNastupistePrmPeer.HMATOVA_CESTA_Z_REFER.equals(name)) {
			return setByName("HmatovaCestaZRefer", value);
		}
		if (TNastupistePrmPeer.KONTRASTNE_SCHODY_Z_REFER.equals(name)) {
			return setByName("KontrastneSchodyZRefer", value);
		}
		if (TNastupistePrmPeer.ZVYRAZNENIE_PREKAZOK_Z_REFER.equals(name)) {
			return setByName("ZvyrazneniePrekazokZRefer", value);
		}
		if (TNastupistePrmPeer.PODLAHOVE_INDIKATORY_NASTUP.equals(name)) {
			return setByName("PodlahoveIndikatoryNastup", value);
		}
		if (TNastupistePrmPeer.BARIERY_NA_KONTROLU_CL_NASTUPISTIA.equals(name)) {
			return setByName("BarieryNaKontroluClNastupistia", value);
		}
		if (TNastupistePrmPeer.BARIERY_NA_KONTROLU_CL_VOZIK.equals(name)) {
			return setByName("BarieryNaKontroluClVozik", value);
		}
		if (TNastupistePrmPeer.DOPLN_INF_O_PRISTUPNOSTI.equals(name)) {
			return setByName("DoplnInfOPristupnosti", value);
		}
		if (TNastupistePrmPeer.UROVNOVY_PRISTUP_VOZIK.equals(name)) {
			return setByName("UrovnovyPristupVozik", value);
		}
		if (TNastupistePrmPeer.POMOCNE_ZAR_NASTUP_VYSTUP.equals(name)) {
			return setByName("PomocneZarNastupVystup", value);
		}
		if (TNastupistePrmPeer.DOPLN_INF_O_PRISTUPNOSTI_POM_ZAR.equals(name)) {
			return setByName("DoplnInfOPristupnostiPomZar", value);
		}
		if (TNastupistePrmPeer.POMOC_PRI_PRISTUPE.equals(name)) {
			return setByName("PomocPriPristupe", value);
		}
		if (TNastupistePrmPeer.PODMIENKY_POMOCI.equals(name)) {
			return setByName("PodmienkyPomoci", value);
		}
		if (TNastupistePrmPeer.POMOC_BEZ_OZNAMENIA.equals(name)) {
			return setByName("PomocBezOznamenia", value);
		}
		if (TNastupistePrmPeer.MOZNOST_NAD_ZSSK.equals(name)) {
			return setByName("MoznostNadZssk", value);
		}
		if (TNastupistePrmPeer.PODMIENKY_NAD_ZSSK.equals(name)) {
			return setByName("PodmienkyNadZssk", value);
		}
		if (TNastupistePrmPeer.ID_DOPRAVNY_BOD.equals(name)) {
			return setByName("IdDopravnyBod", value);
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema. Zero-based.
	 * 
	 * @param pos
	 *            position in xml schema
	 * @return value
	 */
	public Object getByPosition(int pos) {
		if (pos == 0) {
			return getHistId();
		}
		if (pos == 1) {
			return getPlatnostOd();
		}
		if (pos == 2) {
			return getPlatnostDo();
		}
		if (pos == 3) {
			return getCasVytvorenia();
		}
		if (pos == 4) {
			return getCasZmeny();
		}
		if (pos == 5) {
			return getIdZmena();
		}
		if (pos == 6) {
			return getZmaz();
		}
		if (pos == 7) {
			return getNastupistePrmId();
		}
		if (pos == 8) {
			return getNastupisteCislo();
		}
		if (pos == 9) {
			return getPrisupBezSchodZRefer();
		}
		if (pos == 10) {
			return getHmatovaCestaZRefer();
		}
		if (pos == 11) {
			return getKontrastneSchodyZRefer();
		}
		if (pos == 12) {
			return getZvyrazneniePrekazokZRefer();
		}
		if (pos == 13) {
			return getPodlahoveIndikatoryNastup();
		}
		if (pos == 14) {
			return getBarieryNaKontroluClNastupistia();
		}
		if (pos == 15) {
			return getBarieryNaKontroluClVozik();
		}
		if (pos == 16) {
			return getDoplnInfOPristupnosti();
		}
		if (pos == 17) {
			return getUrovnovyPristupVozik();
		}
		if (pos == 18) {
			return getPomocneZarNastupVystup();
		}
		if (pos == 19) {
			return getDoplnInfOPristupnostiPomZar();
		}
		if (pos == 20) {
			return getPomocPriPristupe();
		}
		if (pos == 21) {
			return getPodmienkyPomoci();
		}
		if (pos == 22) {
			return getPomocBezOznamenia();
		}
		if (pos == 23) {
			return getMoznostNadZssk();
		}
		if (pos == 24) {
			return getPodmienkyNadZssk();
		}
		if (pos == 25) {
			return getIdDopravnyBod();
		}
		return null;
	}

	/**
	 * Set field values by its position (zero based) in the XML schema.
	 * 
	 * @param position
	 *            The field position
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid position / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPosition(int position, Object value) throws TorqueException, IllegalArgumentException {
		if (position == 0) {
			return setByName("HistId", value);
		}
		if (position == 1) {
			return setByName("PlatnostOd", value);
		}
		if (position == 2) {
			return setByName("PlatnostDo", value);
		}
		if (position == 3) {
			return setByName("CasVytvorenia", value);
		}
		if (position == 4) {
			return setByName("CasZmeny", value);
		}
		if (position == 5) {
			return setByName("IdZmena", value);
		}
		if (position == 6) {
			return setByName("Zmaz", value);
		}
		if (position == 7) {
			return setByName("NastupistePrmId", value);
		}
		if (position == 8) {
			return setByName("NastupisteCislo", value);
		}
		if (position == 9) {
			return setByName("PrisupBezSchodZRefer", value);
		}
		if (position == 10) {
			return setByName("HmatovaCestaZRefer", value);
		}
		if (position == 11) {
			return setByName("KontrastneSchodyZRefer", value);
		}
		if (position == 12) {
			return setByName("ZvyrazneniePrekazokZRefer", value);
		}
		if (position == 13) {
			return setByName("PodlahoveIndikatoryNastup", value);
		}
		if (position == 14) {
			return setByName("BarieryNaKontroluClNastupistia", value);
		}
		if (position == 15) {
			return setByName("BarieryNaKontroluClVozik", value);
		}
		if (position == 16) {
			return setByName("DoplnInfOPristupnosti", value);
		}
		if (position == 17) {
			return setByName("UrovnovyPristupVozik", value);
		}
		if (position == 18) {
			return setByName("PomocneZarNastupVystup", value);
		}
		if (position == 19) {
			return setByName("DoplnInfOPristupnostiPomZar", value);
		}
		if (position == 20) {
			return setByName("PomocPriPristupe", value);
		}
		if (position == 21) {
			return setByName("PodmienkyPomoci", value);
		}
		if (position == 22) {
			return setByName("PomocBezOznamenia", value);
		}
		if (position == 23) {
			return setByName("MoznostNadZssk", value);
		}
		if (position == 24) {
			return setByName("PodmienkyNadZssk", value);
		}
		if (position == 25) {
			return setByName("IdDopravnyBod", value);
		}
		return false;
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed.
	 * 
	 * @throws Exception
	 */
	public void save() throws Exception {
		save(TNastupistePrmPeer.DATABASE_NAME);
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. Note: this code is here because the method body is auto-generated
	 * conditionally and therefore needs to be in this file instead of in the super class, BaseObject.
	 * 
	 * @param dbName
	 * @throws TorqueException
	 */
	public void save(String dbName) throws TorqueException {
		Connection con = null;
		try {
			con = Transaction.begin(dbName);
			save(con);
			Transaction.commit(con);
		} catch (TorqueException e) {
			Transaction.safeRollback(con);
			throw e;
		}
	}

	/**
	 * flag to prevent endless save loop, if this object is referenced by another object which falls in this transaction.
	 */
	private boolean alreadyInSave = false;

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. This method is meant to be used as part of a transaction, otherwise
	 * use the save() method and the connection details will be handled internally
	 * 
	 * @param con
	 * @throws TorqueException
	 */
	public void save(Connection con) throws TorqueException {
		if (!alreadyInSave) {
			alreadyInSave = true;

			// If this object has been modified, then save it to the database.
			if (isModified()) {
				if (isNew()) {
					TNastupistePrmPeer.doInsert((TNastupistePrm) this, con);
					setNew(false);
				} else {
					TNastupistePrmPeer.doUpdate((TNastupistePrm) this, con);
				}
			}

			alreadyInSave = false;
		}
	}

	/**
	 * Set the PrimaryKey using ObjectKey.
	 * 
	 * @param key
	 *            histId ObjectKey
	 */
	public void setPrimaryKey(ObjectKey key)

	{
		setHistId(new Integer(((NumberKey) key).intValue()));
	}

	/**
	 * Set the PrimaryKey using a String.
	 * 
	 * @param key
	 */
	public void setPrimaryKey(String key) {
		setHistId(new Integer(key));
	}

	/**
	 * returns an id that differentiates this object from others of its class.
	 */
	public ObjectKey getPrimaryKey() {
		return SimpleKey.keyFor(getHistId());
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. It then fills all the association collections and sets the related objects to
	 * isNew=true.
	 */
	public TNastupistePrm copy() throws TorqueException {
		return copy(true);
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. If the parameter deepcopy is true, it then fills all the association collections and
	 * sets the related objects to isNew=true.
	 * 
	 * @param deepcopy
	 *            whether to copy the associated objects.
	 */
	public TNastupistePrm copy(boolean deepcopy) throws TorqueException {
		return copyInto(new TNastupistePrm(), deepcopy);
	}

	/**
	 * Fills the copyObj with the contents of this object. The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 */
	protected TNastupistePrm copyInto(TNastupistePrm copyObj) throws TorqueException {
		return copyInto(copyObj, true);
	}

	/**
	 * Fills the copyObj with the contents of this object. If deepcopy is true, The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 * @param deepcopy
	 *            whether the associated objects should be copied.
	 */
	protected TNastupistePrm copyInto(TNastupistePrm copyObj, boolean deepcopy) throws TorqueException {
		copyObj.setHistId(histId);
		copyObj.setPlatnostOd(platnostOd);
		copyObj.setPlatnostDo(platnostDo);
		copyObj.setCasVytvorenia(casVytvorenia);
		copyObj.setCasZmeny(casZmeny);
		copyObj.setIdZmena(idZmena);
		copyObj.setZmaz(zmaz);
		copyObj.setNastupistePrmId(nastupistePrmId);
		copyObj.setNastupisteCislo(nastupisteCislo);
		copyObj.setPrisupBezSchodZRefer(prisupBezSchodZRefer);
		copyObj.setHmatovaCestaZRefer(hmatovaCestaZRefer);
		copyObj.setKontrastneSchodyZRefer(kontrastneSchodyZRefer);
		copyObj.setZvyrazneniePrekazokZRefer(zvyrazneniePrekazokZRefer);
		copyObj.setPodlahoveIndikatoryNastup(podlahoveIndikatoryNastup);
		copyObj.setBarieryNaKontroluClNastupistia(barieryNaKontroluClNastupistia);
		copyObj.setBarieryNaKontroluClVozik(barieryNaKontroluClVozik);
		copyObj.setDoplnInfOPristupnosti(doplnInfOPristupnosti);
		copyObj.setUrovnovyPristupVozik(urovnovyPristupVozik);
		copyObj.setPomocneZarNastupVystup(pomocneZarNastupVystup);
		copyObj.setDoplnInfOPristupnostiPomZar(doplnInfOPristupnostiPomZar);
		copyObj.setPomocPriPristupe(pomocPriPristupe);
		copyObj.setPodmienkyPomoci(podmienkyPomoci);
		copyObj.setPomocBezOznamenia(pomocBezOznamenia);
		copyObj.setMoznostNadZssk(moznostNadZssk);
		copyObj.setPodmienkyNadZssk(podmienkyNadZssk);
		copyObj.setIdDopravnyBod(idDopravnyBod);

		copyObj.setHistId((Integer) null);

		if (deepcopy) {
		}
		return copyObj;
	}

	/**
	 * returns a peer instance associated with this om. Since Peer classes are not to have any instance attributes, this method returns the same instance for all member of this
	 * class. The method could therefore be static, but this would prevent one from overriding the behavior.
	 */
	public TNastupistePrmPeer getPeer() {
		return peer;
	}

	/**
	 * Retrieves the TableMap object related to this Table data without compiler warnings of using getPeer().getTableMap().
	 * 
	 * @return The associated TableMap object.
	 */
	public TableMap getTableMap() throws TorqueException {
		return TNastupistePrmPeer.getTableMap();
	}

	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("TNastupistePrm:\n");
		str.append("HistId = ").append(getHistId()).append("\n");
		str.append("PlatnostOd = ").append(getPlatnostOd()).append("\n");
		str.append("PlatnostDo = ").append(getPlatnostDo()).append("\n");
		str.append("CasVytvorenia = ").append(getCasVytvorenia()).append("\n");
		str.append("CasZmeny = ").append(getCasZmeny()).append("\n");
		str.append("IdZmena = ").append(getIdZmena()).append("\n");
		str.append("Zmaz = ").append(getZmaz()).append("\n");
		str.append("NastupistePrmId = ").append(getNastupistePrmId()).append("\n");
		str.append("NastupisteCislo = ").append(getNastupisteCislo()).append("\n");
		str.append("PrisupBezSchodZRefer = ").append(getPrisupBezSchodZRefer()).append("\n");
		str.append("HmatovaCestaZRefer = ").append(getHmatovaCestaZRefer()).append("\n");
		str.append("KontrastneSchodyZRefer = ").append(getKontrastneSchodyZRefer()).append("\n");
		str.append("ZvyrazneniePrekazokZRefer = ").append(getZvyrazneniePrekazokZRefer()).append("\n");
		str.append("PodlahoveIndikatoryNastup = ").append(getPodlahoveIndikatoryNastup()).append("\n");
		str.append("BarieryNaKontroluClNastupistia = ").append(getBarieryNaKontroluClNastupistia()).append("\n");
		str.append("BarieryNaKontroluClVozik = ").append(getBarieryNaKontroluClVozik()).append("\n");
		str.append("DoplnInfOPristupnosti = ").append(getDoplnInfOPristupnosti()).append("\n");
		str.append("UrovnovyPristupVozik = ").append(getUrovnovyPristupVozik()).append("\n");
		str.append("PomocneZarNastupVystup = ").append(getPomocneZarNastupVystup()).append("\n");
		str.append("DoplnInfOPristupnostiPomZar = ").append(getDoplnInfOPristupnostiPomZar()).append("\n");
		str.append("PomocPriPristupe = ").append(getPomocPriPristupe()).append("\n");
		str.append("PodmienkyPomoci = ").append(getPodmienkyPomoci()).append("\n");
		str.append("PomocBezOznamenia = ").append(getPomocBezOznamenia()).append("\n");
		str.append("MoznostNadZssk = ").append(getMoznostNadZssk()).append("\n");
		str.append("PodmienkyNadZssk = ").append(getPodmienkyNadZssk()).append("\n");
		str.append("IdDopravnyBod = ").append(getIdDopravnyBod()).append("\n");
		return (str.toString());
	}
}
