package sk.ditec.dao.master;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 * 
 * [Fri Jul 25 14:44:46 CEST 2025]
 * 
 * You should not use this class directly. It should not even be extended all references should be to TDispecerskyOkruh
 */
public abstract class BaseTDispecerskyOkruh extends BaseObject {
	/** Serial version */
	private static final long serialVersionUID = 1753447486539L;

	/** The Peer class */
	private static final TDispecerskyOkruhPeer peer = new TDispecerskyOkruhPeer();

	/** The value for the histId field */
	private Integer histId;

	/** The value for the platnostOd field */
	private Date platnostOd;

	/** The value for the platnostDo field */
	private Date platnostDo;

	/** The value for the casVytvorenia field */
	private Date casVytvorenia;

	/** The value for the casZmeny field */
	private Date casZmeny;

	/** The value for the idZmena field */
	private Integer idZmena;

	/** The value for the zmaz field */
	private String zmaz;

	/** The value for the dispecerskyOkruhId field */
	private Integer dispecerskyOkruhId;

	/** The value for the idObvodRiadeniaDopravy field */
	private Integer idObvodRiadeniaDopravy;

	/** The value for the cislo field */
	private String cislo;

	/** The value for the skratkaDispecera field */
	private String skratkaDispecera;

	/** The value for the dispecer field */
	private String dispecer;

	/** The value for the telefonZts field */
	private String telefonZts;

	/** The value for the telefonVts field */
	private String telefonVts;

	/** The value for the telefonMobil field */
	private String telefonMobil;

	/** The value for the email field */
	private String email;

	/**
	 * Get the HistId
	 * 
	 * @return Integer
	 */
	public Integer getHistId() {
		return histId;
	}

	/**
	 * Set the value of HistId
	 * 
	 * @param v
	 *            new value
	 */
	public void setHistId(Integer v) {

		if (!ObjectUtils.equals(this.histId, v)) {
			this.histId = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostOd
	 * 
	 * @return Date
	 */
	public Date getPlatnostOd() {
		return platnostOd;
	}

	/**
	 * Set the value of PlatnostOd
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostOd(Date v) {

		if (!ObjectUtils.equals(this.platnostOd, v)) {
			this.platnostOd = v;
			setModified(true);
		}

	}

	/**
	 * Get the PlatnostDo
	 * 
	 * @return Date
	 */
	public Date getPlatnostDo() {
		return platnostDo;
	}

	/**
	 * Set the value of PlatnostDo
	 * 
	 * @param v
	 *            new value
	 */
	public void setPlatnostDo(Date v) {

		if (!ObjectUtils.equals(this.platnostDo, v)) {
			this.platnostDo = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasVytvorenia
	 * 
	 * @return Date
	 */
	public Date getCasVytvorenia() {
		return casVytvorenia;
	}

	/**
	 * Set the value of CasVytvorenia
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasVytvorenia(Date v) {

		if (!ObjectUtils.equals(this.casVytvorenia, v)) {
			this.casVytvorenia = v;
			setModified(true);
		}

	}

	/**
	 * Get the CasZmeny
	 * 
	 * @return Date
	 */
	public Date getCasZmeny() {
		return casZmeny;
	}

	/**
	 * Set the value of CasZmeny
	 * 
	 * @param v
	 *            new value
	 */
	public void setCasZmeny(Date v) {

		if (!ObjectUtils.equals(this.casZmeny, v)) {
			this.casZmeny = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdZmena
	 * 
	 * @return Integer
	 */
	public Integer getIdZmena() {
		return idZmena;
	}

	/**
	 * Set the value of IdZmena
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdZmena(Integer v) {

		if (!ObjectUtils.equals(this.idZmena, v)) {
			this.idZmena = v;
			setModified(true);
		}

	}

	/**
	 * Get the Zmaz
	 * 
	 * @return String
	 */
	public String getZmaz() {
		return zmaz;
	}

	/**
	 * Set the value of Zmaz
	 * 
	 * @param v
	 *            new value
	 */
	public void setZmaz(String v) {

		if (!ObjectUtils.equals(this.zmaz, v)) {
			this.zmaz = v;
			setModified(true);
		}

	}

	/**
	 * Get the DispecerskyOkruhId
	 * 
	 * @return Integer
	 */
	public Integer getDispecerskyOkruhId() {
		return dispecerskyOkruhId;
	}

	/**
	 * Set the value of DispecerskyOkruhId
	 * 
	 * @param v
	 *            new value
	 */
	public void setDispecerskyOkruhId(Integer v) {

		if (!ObjectUtils.equals(this.dispecerskyOkruhId, v)) {
			this.dispecerskyOkruhId = v;
			setModified(true);
		}

	}

	/**
	 * Get the IdObvodRiadeniaDopravy
	 * 
	 * @return Integer
	 */
	public Integer getIdObvodRiadeniaDopravy() {
		return idObvodRiadeniaDopravy;
	}

	/**
	 * Set the value of IdObvodRiadeniaDopravy
	 * 
	 * @param v
	 *            new value
	 */
	public void setIdObvodRiadeniaDopravy(Integer v) {

		if (!ObjectUtils.equals(this.idObvodRiadeniaDopravy, v)) {
			this.idObvodRiadeniaDopravy = v;
			setModified(true);
		}

	}

	/**
	 * Get the Cislo
	 * 
	 * @return String
	 */
	public String getCislo() {
		return cislo;
	}

	/**
	 * Set the value of Cislo
	 * 
	 * @param v
	 *            new value
	 */
	public void setCislo(String v) {

		if (!ObjectUtils.equals(this.cislo, v)) {
			this.cislo = v;
			setModified(true);
		}

	}

	/**
	 * Get the SkratkaDispecera
	 * 
	 * @return String
	 */
	public String getSkratkaDispecera() {
		return skratkaDispecera;
	}

	/**
	 * Set the value of SkratkaDispecera
	 * 
	 * @param v
	 *            new value
	 */
	public void setSkratkaDispecera(String v) {

		if (!ObjectUtils.equals(this.skratkaDispecera, v)) {
			this.skratkaDispecera = v;
			setModified(true);
		}

	}

	/**
	 * Get the Dispecer
	 * 
	 * @return String
	 */
	public String getDispecer() {
		return dispecer;
	}

	/**
	 * Set the value of Dispecer
	 * 
	 * @param v
	 *            new value
	 */
	public void setDispecer(String v) {

		if (!ObjectUtils.equals(this.dispecer, v)) {
			this.dispecer = v;
			setModified(true);
		}

	}

	/**
	 * Get the TelefonZts
	 * 
	 * @return String
	 */
	public String getTelefonZts() {
		return telefonZts;
	}

	/**
	 * Set the value of TelefonZts
	 * 
	 * @param v
	 *            new value
	 */
	public void setTelefonZts(String v) {

		if (!ObjectUtils.equals(this.telefonZts, v)) {
			this.telefonZts = v;
			setModified(true);
		}

	}

	/**
	 * Get the TelefonVts
	 * 
	 * @return String
	 */
	public String getTelefonVts() {
		return telefonVts;
	}

	/**
	 * Set the value of TelefonVts
	 * 
	 * @param v
	 *            new value
	 */
	public void setTelefonVts(String v) {

		if (!ObjectUtils.equals(this.telefonVts, v)) {
			this.telefonVts = v;
			setModified(true);
		}

	}

	/**
	 * Get the TelefonMobil
	 * 
	 * @return String
	 */
	public String getTelefonMobil() {
		return telefonMobil;
	}

	/**
	 * Set the value of TelefonMobil
	 * 
	 * @param v
	 *            new value
	 */
	public void setTelefonMobil(String v) {

		if (!ObjectUtils.equals(this.telefonMobil, v)) {
			this.telefonMobil = v;
			setModified(true);
		}

	}

	/**
	 * Get the Email
	 * 
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * Set the value of Email
	 * 
	 * @param v
	 *            new value
	 */
	public void setEmail(String v) {

		if (!ObjectUtils.equals(this.email, v)) {
			this.email = v;
			setModified(true);
		}

	}

	private static List fieldNames = null;

	/**
	 * Generate a list of field names.
	 * 
	 * @return a list of field names
	 */
	public static synchronized List getFieldNames() {
		if (fieldNames == null) {
			fieldNames = new ArrayList();
			fieldNames.add("HistId");
			fieldNames.add("PlatnostOd");
			fieldNames.add("PlatnostDo");
			fieldNames.add("CasVytvorenia");
			fieldNames.add("CasZmeny");
			fieldNames.add("IdZmena");
			fieldNames.add("Zmaz");
			fieldNames.add("DispecerskyOkruhId");
			fieldNames.add("IdObvodRiadeniaDopravy");
			fieldNames.add("Cislo");
			fieldNames.add("SkratkaDispecera");
			fieldNames.add("Dispecer");
			fieldNames.add("TelefonZts");
			fieldNames.add("TelefonVts");
			fieldNames.add("TelefonMobil");
			fieldNames.add("Email");
			fieldNames = Collections.unmodifiableList(fieldNames);
		}
		return fieldNames;
	}

	/**
	 * Retrieves a field from the object by field (Java) name passed in as a String.
	 * 
	 * @param name
	 *            field name
	 * @return value
	 */
	public Object getByName(String name) {
		if (name.equals("HistId")) {
			return getHistId();
		}
		if (name.equals("PlatnostOd")) {
			return getPlatnostOd();
		}
		if (name.equals("PlatnostDo")) {
			return getPlatnostDo();
		}
		if (name.equals("CasVytvorenia")) {
			return getCasVytvorenia();
		}
		if (name.equals("CasZmeny")) {
			return getCasZmeny();
		}
		if (name.equals("IdZmena")) {
			return getIdZmena();
		}
		if (name.equals("Zmaz")) {
			return getZmaz();
		}
		if (name.equals("DispecerskyOkruhId")) {
			return getDispecerskyOkruhId();
		}
		if (name.equals("IdObvodRiadeniaDopravy")) {
			return getIdObvodRiadeniaDopravy();
		}
		if (name.equals("Cislo")) {
			return getCislo();
		}
		if (name.equals("SkratkaDispecera")) {
			return getSkratkaDispecera();
		}
		if (name.equals("Dispecer")) {
			return getDispecer();
		}
		if (name.equals("TelefonZts")) {
			return getTelefonZts();
		}
		if (name.equals("TelefonVts")) {
			return getTelefonVts();
		}
		if (name.equals("TelefonMobil")) {
			return getTelefonMobil();
		}
		if (name.equals("Email")) {
			return getEmail();
		}
		return null;
	}

	/**
	 * Set a field in the object by field (Java) name.
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (name.equals("HistId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setHistId((Integer) value);
			return true;
		}
		if (name.equals("PlatnostOd")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostOd((Date) value);
			return true;
		}
		if (name.equals("PlatnostDo")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setPlatnostDo((Date) value);
			return true;
		}
		if (name.equals("CasVytvorenia")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasVytvorenia((Date) value);
			return true;
		}
		if (name.equals("CasZmeny")) {
			// Object fields can be null
			if (value != null && !Date.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCasZmeny((Date) value);
			return true;
		}
		if (name.equals("IdZmena")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdZmena((Integer) value);
			return true;
		}
		if (name.equals("Zmaz")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setZmaz((String) value);
			return true;
		}
		if (name.equals("DispecerskyOkruhId")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setDispecerskyOkruhId((Integer) value);
			return true;
		}
		if (name.equals("IdObvodRiadeniaDopravy")) {
			// Object fields can be null
			if (value != null && !Integer.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setIdObvodRiadeniaDopravy((Integer) value);
			return true;
		}
		if (name.equals("Cislo")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setCislo((String) value);
			return true;
		}
		if (name.equals("SkratkaDispecera")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setSkratkaDispecera((String) value);
			return true;
		}
		if (name.equals("Dispecer")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setDispecer((String) value);
			return true;
		}
		if (name.equals("TelefonZts")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setTelefonZts((String) value);
			return true;
		}
		if (name.equals("TelefonVts")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setTelefonVts((String) value);
			return true;
		}
		if (name.equals("TelefonMobil")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setTelefonMobil((String) value);
			return true;
		}
		if (name.equals("Email")) {
			// Object fields can be null
			if (value != null && !String.class.isInstance(value)) {
				throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
			}
			setEmail((String) value);
			return true;
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by name passed in as a String. The String must be one of the static Strings defined in this Class' Peer.
	 * 
	 * @param name
	 *            peer name
	 * @return value
	 */
	public Object getByPeerName(String name) {
		if (name.equals(TDispecerskyOkruhPeer.HIST_ID)) {
			return getHistId();
		}
		if (name.equals(TDispecerskyOkruhPeer.PLATNOST_OD)) {
			return getPlatnostOd();
		}
		if (name.equals(TDispecerskyOkruhPeer.PLATNOST_DO)) {
			return getPlatnostDo();
		}
		if (name.equals(TDispecerskyOkruhPeer.CAS_VYTVORENIA)) {
			return getCasVytvorenia();
		}
		if (name.equals(TDispecerskyOkruhPeer.CAS_ZMENY)) {
			return getCasZmeny();
		}
		if (name.equals(TDispecerskyOkruhPeer.ID_ZMENA)) {
			return getIdZmena();
		}
		if (name.equals(TDispecerskyOkruhPeer.ZMAZ)) {
			return getZmaz();
		}
		if (name.equals(TDispecerskyOkruhPeer.DISPECERSKY_OKRUH_ID)) {
			return getDispecerskyOkruhId();
		}
		if (name.equals(TDispecerskyOkruhPeer.ID_OBVOD_RIADENIA_DOPRAVY)) {
			return getIdObvodRiadeniaDopravy();
		}
		if (name.equals(TDispecerskyOkruhPeer.CISLO)) {
			return getCislo();
		}
		if (name.equals(TDispecerskyOkruhPeer.SKRATKA_DISPECERA)) {
			return getSkratkaDispecera();
		}
		if (name.equals(TDispecerskyOkruhPeer.DISPECER)) {
			return getDispecer();
		}
		if (name.equals(TDispecerskyOkruhPeer.TELEFON_ZTS)) {
			return getTelefonZts();
		}
		if (name.equals(TDispecerskyOkruhPeer.TELEFON_VTS)) {
			return getTelefonVts();
		}
		if (name.equals(TDispecerskyOkruhPeer.TELEFON_MOBIL)) {
			return getTelefonMobil();
		}
		if (name.equals(TDispecerskyOkruhPeer.EMAIL)) {
			return getEmail();
		}
		return null;
	}

	/**
	 * Set field values by Peer Field Name
	 * 
	 * @param name
	 *            field name
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid name / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPeerName(String name, Object value) throws TorqueException, IllegalArgumentException {
		if (TDispecerskyOkruhPeer.HIST_ID.equals(name)) {
			return setByName("HistId", value);
		}
		if (TDispecerskyOkruhPeer.PLATNOST_OD.equals(name)) {
			return setByName("PlatnostOd", value);
		}
		if (TDispecerskyOkruhPeer.PLATNOST_DO.equals(name)) {
			return setByName("PlatnostDo", value);
		}
		if (TDispecerskyOkruhPeer.CAS_VYTVORENIA.equals(name)) {
			return setByName("CasVytvorenia", value);
		}
		if (TDispecerskyOkruhPeer.CAS_ZMENY.equals(name)) {
			return setByName("CasZmeny", value);
		}
		if (TDispecerskyOkruhPeer.ID_ZMENA.equals(name)) {
			return setByName("IdZmena", value);
		}
		if (TDispecerskyOkruhPeer.ZMAZ.equals(name)) {
			return setByName("Zmaz", value);
		}
		if (TDispecerskyOkruhPeer.DISPECERSKY_OKRUH_ID.equals(name)) {
			return setByName("DispecerskyOkruhId", value);
		}
		if (TDispecerskyOkruhPeer.ID_OBVOD_RIADENIA_DOPRAVY.equals(name)) {
			return setByName("IdObvodRiadeniaDopravy", value);
		}
		if (TDispecerskyOkruhPeer.CISLO.equals(name)) {
			return setByName("Cislo", value);
		}
		if (TDispecerskyOkruhPeer.SKRATKA_DISPECERA.equals(name)) {
			return setByName("SkratkaDispecera", value);
		}
		if (TDispecerskyOkruhPeer.DISPECER.equals(name)) {
			return setByName("Dispecer", value);
		}
		if (TDispecerskyOkruhPeer.TELEFON_ZTS.equals(name)) {
			return setByName("TelefonZts", value);
		}
		if (TDispecerskyOkruhPeer.TELEFON_VTS.equals(name)) {
			return setByName("TelefonVts", value);
		}
		if (TDispecerskyOkruhPeer.TELEFON_MOBIL.equals(name)) {
			return setByName("TelefonMobil", value);
		}
		if (TDispecerskyOkruhPeer.EMAIL.equals(name)) {
			return setByName("Email", value);
		}
		return false;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema. Zero-based.
	 * 
	 * @param pos
	 *            position in xml schema
	 * @return value
	 */
	public Object getByPosition(int pos) {
		if (pos == 0) {
			return getHistId();
		}
		if (pos == 1) {
			return getPlatnostOd();
		}
		if (pos == 2) {
			return getPlatnostDo();
		}
		if (pos == 3) {
			return getCasVytvorenia();
		}
		if (pos == 4) {
			return getCasZmeny();
		}
		if (pos == 5) {
			return getIdZmena();
		}
		if (pos == 6) {
			return getZmaz();
		}
		if (pos == 7) {
			return getDispecerskyOkruhId();
		}
		if (pos == 8) {
			return getIdObvodRiadeniaDopravy();
		}
		if (pos == 9) {
			return getCislo();
		}
		if (pos == 10) {
			return getSkratkaDispecera();
		}
		if (pos == 11) {
			return getDispecer();
		}
		if (pos == 12) {
			return getTelefonZts();
		}
		if (pos == 13) {
			return getTelefonVts();
		}
		if (pos == 14) {
			return getTelefonMobil();
		}
		if (pos == 15) {
			return getEmail();
		}
		return null;
	}

	/**
	 * Set field values by its position (zero based) in the XML schema.
	 * 
	 * @param position
	 *            The field position
	 * @param value
	 *            field value
	 * @return True if value was set, false if not (invalid position / protected field).
	 * @throws IllegalArgumentException
	 *             if object type of value does not match field object type.
	 * @throws TorqueException
	 *             If a problem occures with the set[Field] method.
	 */
	public boolean setByPosition(int position, Object value) throws TorqueException, IllegalArgumentException {
		if (position == 0) {
			return setByName("HistId", value);
		}
		if (position == 1) {
			return setByName("PlatnostOd", value);
		}
		if (position == 2) {
			return setByName("PlatnostDo", value);
		}
		if (position == 3) {
			return setByName("CasVytvorenia", value);
		}
		if (position == 4) {
			return setByName("CasZmeny", value);
		}
		if (position == 5) {
			return setByName("IdZmena", value);
		}
		if (position == 6) {
			return setByName("Zmaz", value);
		}
		if (position == 7) {
			return setByName("DispecerskyOkruhId", value);
		}
		if (position == 8) {
			return setByName("IdObvodRiadeniaDopravy", value);
		}
		if (position == 9) {
			return setByName("Cislo", value);
		}
		if (position == 10) {
			return setByName("SkratkaDispecera", value);
		}
		if (position == 11) {
			return setByName("Dispecer", value);
		}
		if (position == 12) {
			return setByName("TelefonZts", value);
		}
		if (position == 13) {
			return setByName("TelefonVts", value);
		}
		if (position == 14) {
			return setByName("TelefonMobil", value);
		}
		if (position == 15) {
			return setByName("Email", value);
		}
		return false;
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed.
	 * 
	 * @throws Exception
	 */
	public void save() throws Exception {
		save(TDispecerskyOkruhPeer.DATABASE_NAME);
	}

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. Note: this code is here because the method body is auto-generated
	 * conditionally and therefore needs to be in this file instead of in the super class, BaseObject.
	 * 
	 * @param dbName
	 * @throws TorqueException
	 */
	public void save(String dbName) throws TorqueException {
		Connection con = null;
		try {
			con = Transaction.begin(dbName);
			save(con);
			Transaction.commit(con);
		} catch (TorqueException e) {
			Transaction.safeRollback(con);
			throw e;
		}
	}

	/**
	 * flag to prevent endless save loop, if this object is referenced by another object which falls in this transaction.
	 */
	private boolean alreadyInSave = false;

	/**
	 * Stores the object in the database. If the object is new, it inserts it; otherwise an update is performed. This method is meant to be used as part of a transaction, otherwise
	 * use the save() method and the connection details will be handled internally
	 * 
	 * @param con
	 * @throws TorqueException
	 */
	public void save(Connection con) throws TorqueException {
		if (!alreadyInSave) {
			alreadyInSave = true;

			// If this object has been modified, then save it to the database.
			if (isModified()) {
				if (isNew()) {
					TDispecerskyOkruhPeer.doInsert((TDispecerskyOkruh) this, con);
					setNew(false);
				} else {
					TDispecerskyOkruhPeer.doUpdate((TDispecerskyOkruh) this, con);
				}
			}

			alreadyInSave = false;
		}
	}

	/**
	 * Set the PrimaryKey using ObjectKey.
	 * 
	 * @param key
	 *            histId ObjectKey
	 */
	public void setPrimaryKey(ObjectKey key)

	{
		setHistId(new Integer(((NumberKey) key).intValue()));
	}

	/**
	 * Set the PrimaryKey using a String.
	 * 
	 * @param key
	 */
	public void setPrimaryKey(String key) {
		setHistId(new Integer(key));
	}

	/**
	 * returns an id that differentiates this object from others of its class.
	 */
	public ObjectKey getPrimaryKey() {
		return SimpleKey.keyFor(getHistId());
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. It then fills all the association collections and sets the related objects to
	 * isNew=true.
	 */
	public TDispecerskyOkruh copy() throws TorqueException {
		return copy(true);
	}

	/**
	 * Makes a copy of this object. It creates a new object filling in the simple attributes. If the parameter deepcopy is true, it then fills all the association collections and
	 * sets the related objects to isNew=true.
	 * 
	 * @param deepcopy
	 *            whether to copy the associated objects.
	 */
	public TDispecerskyOkruh copy(boolean deepcopy) throws TorqueException {
		return copyInto(new TDispecerskyOkruh(), deepcopy);
	}

	/**
	 * Fills the copyObj with the contents of this object. The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 */
	protected TDispecerskyOkruh copyInto(TDispecerskyOkruh copyObj) throws TorqueException {
		return copyInto(copyObj, true);
	}

	/**
	 * Fills the copyObj with the contents of this object. If deepcopy is true, The associated objects are also copied and treated as new objects.
	 * 
	 * @param copyObj
	 *            the object to fill.
	 * @param deepcopy
	 *            whether the associated objects should be copied.
	 */
	protected TDispecerskyOkruh copyInto(TDispecerskyOkruh copyObj, boolean deepcopy) throws TorqueException {
		copyObj.setHistId(histId);
		copyObj.setPlatnostOd(platnostOd);
		copyObj.setPlatnostDo(platnostDo);
		copyObj.setCasVytvorenia(casVytvorenia);
		copyObj.setCasZmeny(casZmeny);
		copyObj.setIdZmena(idZmena);
		copyObj.setZmaz(zmaz);
		copyObj.setDispecerskyOkruhId(dispecerskyOkruhId);
		copyObj.setIdObvodRiadeniaDopravy(idObvodRiadeniaDopravy);
		copyObj.setCislo(cislo);
		copyObj.setSkratkaDispecera(skratkaDispecera);
		copyObj.setDispecer(dispecer);
		copyObj.setTelefonZts(telefonZts);
		copyObj.setTelefonVts(telefonVts);
		copyObj.setTelefonMobil(telefonMobil);
		copyObj.setEmail(email);

		copyObj.setHistId((Integer) null);

		if (deepcopy) {
		}
		return copyObj;
	}

	/**
	 * returns a peer instance associated with this om. Since Peer classes are not to have any instance attributes, this method returns the same instance for all member of this
	 * class. The method could therefore be static, but this would prevent one from overriding the behavior.
	 */
	public TDispecerskyOkruhPeer getPeer() {
		return peer;
	}

	/**
	 * Retrieves the TableMap object related to this Table data without compiler warnings of using getPeer().getTableMap().
	 * 
	 * @return The associated TableMap object.
	 */
	public TableMap getTableMap() throws TorqueException {
		return TDispecerskyOkruhPeer.getTableMap();
	}

	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("TDispecerskyOkruh:\n");
		str.append("HistId = ").append(getHistId()).append("\n");
		str.append("PlatnostOd = ").append(getPlatnostOd()).append("\n");
		str.append("PlatnostDo = ").append(getPlatnostDo()).append("\n");
		str.append("CasVytvorenia = ").append(getCasVytvorenia()).append("\n");
		str.append("CasZmeny = ").append(getCasZmeny()).append("\n");
		str.append("IdZmena = ").append(getIdZmena()).append("\n");
		str.append("Zmaz = ").append(getZmaz()).append("\n");
		str.append("DispecerskyOkruhId = ").append(getDispecerskyOkruhId()).append("\n");
		str.append("IdObvodRiadeniaDopravy = ").append(getIdObvodRiadeniaDopravy()).append("\n");
		str.append("Cislo = ").append(getCislo()).append("\n");
		str.append("SkratkaDispecera = ").append(getSkratkaDispecera()).append("\n");
		str.append("Dispecer = ").append(getDispecer()).append("\n");
		str.append("TelefonZts = ").append(getTelefonZts()).append("\n");
		str.append("TelefonVts = ").append(getTelefonVts()).append("\n");
		str.append("TelefonMobil = ").append(getTelefonMobil()).append("\n");
		str.append("Email = ").append(getEmail()).append("\n");
		return (str.toString());
	}
}
