Insert into CUD.CUD_PLUGIN_CLASS_NAME (PLUGIN_CLASS_NAME_ID,CLASS_NAME,POPIS,ID_TRANSAKCIA_ZAPISANE) values (7,'CudPluginStavebnaDlzkaVociDUClass','Kontroluje stavebn˙ dæûku voËi tabulke definiËnÈ ˙seky',1);
Insert into CUD.CUD_PLUGIN_CLASS_NAME (PLUGIN_CLASS_NAME_ID,CLASS_NAME,POPIS,ID_TRANSAKCIA_ZAPISANE) values (8,'CudPluginStavebnaDlzkaClass','Kontroluje stavebn˙ dæûku voËi tej istej tabulke',1);
commit;

Insert into CUD.CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,ID_PLUGIN_CLASS_NAME,TYP,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE,KONSTANTA) values (700,7,'V','TRATOVY_USEK','Traùov˝ ˙sek',1,'F');
Insert into CUD.CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,ID_PLUGIN_CLASS_NAME,TYP,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE,KONSTANTA) values (701,7,'V','STAVEBNA_DLZKA','Stavebn· dÂûka',1,'F');

Insert into CUD.CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,ID_PLUGIN_CLASS_NAME,TYP,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE,KONSTANTA) values (800,8,'V','KM_OD','Km Od [km]',1,'F');
Insert into CUD.CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,ID_PLUGIN_CLASS_NAME,TYP,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE,KONSTANTA) values (801,8,'V','KM_DO','Km Do [km]',1,'F');
Insert into CUD.CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,ID_PLUGIN_CLASS_NAME,TYP,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE,KONSTANTA) values (802,8,'V','STAVEBNA_DLZKA','Stavebn· dÂûka [m]',1,'F');
Insert into CUD.CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,ID_PLUGIN_CLASS_NAME,TYP,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE,KONSTANTA) values (803,8,'V','MHK','Abnorm·lne hektometre [m]',1,'F');
commit;