-- tato cast je ok
Insert into CUD.CUD_PLUGIN_CLASS_NAME (PLUGIN_CLASS_NAME_ID,CLASS_NAME,POPIS,ID_TRANSAKCIA_ZAPISANE) values (9,'CudPluginEmailClass','Kontroluje email adries',1);
commit;

Insert into CUD.CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,ID_PLUGIN_CLASS_NAME,TYP,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE,KONSTANTA) values (900,9,'V','EMAIL','Email',1,'F');
commit;

-- NENASADZOVAT!!!! tato cast nie je dobre, treba ju zmazat, zatial nasadene len na kistest a kist
ALTER TABLE cud_wf_def ADD id_ciselnik_stlpec NUMBER(10);
ALTER TABLE cud_wf_def ADD CONSTRAINT cud_wf_def_fk3 FOREIGN KEY(id_ciselnik_stlpec) REFERENCES cud_ciselnik_stlpec(ciselnik_stlpec_id);
-- NENASADZOVAT!!!!


-- tato cast je ok
CREATE TABLE CUD_WF_DEF_CISELNIK_STLPEC (
    WF_DEF_CISELNIK_STLPEC_ID   NUMBER(10) NOT NULL,
    ID_WF_DEF                   NUMBER(10) NOT NULL,
    ID_CISELNIK_STLPEC          NUMBER(10) NOT NULL,
    ID_TRANSAKCIA_ZAPISANE      NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE       NUMBER(20),
    CONSTRAINT CUD_WF_DEF_CISELNIK_STLPEC_PK PRIMARY KEY (WF_DEF_CISELNIK_STLPEC_ID)
);

ALTER TABLE CUD_WF_DEF_CISELNIK_STLPEC ADD CONSTRAINT CUD_WF_DEF_CISELNIK_STLPEC_FK1 FOREIGN KEY (ID_WF_DEF) REFERENCES CUD_WF_DEF (WF_DEF_ID);
ALTER TABLE CUD_WF_DEF_CISELNIK_STLPEC ADD CONSTRAINT CUD_WF_DEF_CISELNIK_STLPEC_FK2 FOREIGN KEY (ID_CISELNIK_STLPEC) REFERENCES CUD_CISELNIK_STLPEC (CISELNIK_STLPEC_ID);

CREATE SEQUENCE CUD_WF_DEF_CISELNIK_STLPEC_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;


-- toto maze vytvoreny atribut na kistest a kist.
ALTER TABLE cud_wf_def DROP COLUMN ID_CISELNIK_STLPEC;