ALTER TABLE T_UN_A_KEMLER_KOD ADD TRIEDA NVARCHAR2(3);
ALTER TABLE T_UN_A_KEMLER_KOD ADD ID_PACKING_GROUP NUMBER(10);
ALTER TABLE T_UN_A_KEMLER_KOD ADD ZAKAZANA_PREPRAVA NVARCHAR2(1);
ALTER TABLE T_UN_A_KEMLER_KOD ADD POZNAMKA NVARCHAR2(255);
