CREATE TABLE "CRD_SPRACOVANIE" 
   (	"CRD_SPRACOVANIE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DATUM_VOLANIA" TIMESTAMP (6) NOT NULL ENABLE, 
	"KOD_SPRACOVANIA" VARCHAR2(20 BYTE), 
	"POSLEDNE_USPESNE_SPRACOVANIE" TIMESTAMP (6), 
	 CONSTRAINT "CRD_SPRACOVANIE_PK" PRIMARY KEY ("CRD_SPRACOVANIE_ID") );
 
  
CREATE TABLE "CRD_SPRACOVANIE_ZMENY" 
   (	"CRD_SPRACOVANIE_ZMENY_ID" NUMBER(10,0) NOT NULL ENABLE, 
    "ID_ZMENA" NUMBER(10,0) NOT NULL ENABLE, 
	"DATUM_VOLANIA" TIMESTAMP (6) NOT NULL ENABLE, 
	"CHYBOVA_SPRAVA" VARCHAR2(500 BYTE), 
	"CHYBA" VARCHAR2(1 BYTE), 
	 CONSTRAINT "CRD_SPRACOVANIE_ZMENY_PK" PRIMARY KEY ("CRD_SPRACOVANIE_ZMENY_ID") );
 
  	 
	 
  CREATE TABLE CRD_SPRAC_TABULIEK 
(
 	"CRD_SPRAC_TABULIEK_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_CRD_SPRACOVANIE" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_CISELNIK" NUMBER(10,0) NOT NULL ENABLE, 
	"DATE_FILTER_FOR_DELETED" DATE NOT NULL ENABLE,  
	"REPLICATE_FROM_DATE" DATE NOT NULL ENABLE, 
	"REPLICATE_ALL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NAVRATOVY_KOD" NUMBER(*,0), 
	"POPIS_SPRACOVANIA" VARCHAR2(500 BYTE), 
	"VSTUPNE_XML" CLOB, 
	"VYSTUPNE_XML" CLOB, 
	"ZMENOVE_XML_VSTUP" CLOB, 
	"ZMENOVE_XML_VYSTUP" CLOB, 
 CONSTRAINT CRD_SPRAC_TABULIEK_PK PRIMARY KEY 
  (
    CRD_SPRAC_TABULIEK_ID 
  )
);


 CREATE TABLE "CRD_NENAJDENE_ZAZNAMY" 
   (	"CRD_NENAJDENE_ZAZNAMY_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_CRD_SPRAC_TABULIEK" NUMBER(10,0) NOT NULL ENABLE, 
	"POPIS" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"CHYBOVA_SPRAVA" VARCHAR2(500 BYTE), 
	"CHYBA" VARCHAR2(1 BYTE), 
	"VAROVANIE" VARCHAR2(1 BYTE), 
	 CONSTRAINT "CRD_NENAJDENE_ZAZNAMY_PK" PRIMARY KEY ("CRD_NENAJDENE_ZAZNAMY_ID") );
	 
	  CREATE TABLE "CUD_PARAMETRE" 
   (	"PARAMETRE_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"PARAMETRE_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PARAMETRE_VALUE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	 )

CREATE SEQUENCE CUD_PARAMETRE_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CRD_SPRACOVANIE_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CRD_SPRAC_TABULIEK_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CRD_NENAJDENE_ZAZNAMY_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CRD_SPRACOVANIE_ZMENY_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;

create or replace TRIGGER INSERT_PK_CRD_SPRACOVANIE_ID before INSERT ON CRD_SPRACOVANIE FOR EACH ROW
BEGIN
    IF inserting THEN
        IF :NEW.CRD_SPRACOVANIE_ID IS NULL THEN
            SELECT CRD_SPRACOVANIE_SEQ.nextval
            INTO :NEW.CRD_SPRACOVANIE_ID
            FROM dual;
        END IF;
    END IF;
END;

create or replace TRIGGER INSERT_PK_CRD_SPRAC_TABULIEK_ID before INSERT ON CRD_SPRAC_TABULIEK FOR EACH ROW
BEGIN
    IF inserting THEN
        IF :NEW.CRD_SPRAC_TABULIEK_ID IS NULL THEN
            SELECT CRD_SPRAC_TABULIEK_SEQ.nextval
            INTO :NEW.CRD_SPRAC_TABULIEK_ID
            FROM dual;
        END IF;
    END IF;
END;

create or replace TRIGGER INSERT_PK_CRD_NENAJDENE_ZAZNAMY_ID before INSERT ON CRD_NENAJDENE_ZAZNAMY FOR EACH ROW
BEGIN
    IF inserting THEN
        IF :NEW.CRD_NENAJDENE_ZAZNAMY_ID IS NULL THEN
            SELECT CRD_NENAJDENE_ZAZNAMY_SEQ.nextval
            INTO :NEW.CRD_NENAJDENE_ZAZNAMY_ID
            FROM dual;
        END IF;
    END IF;
END;

create or replace TRIGGER CRD_SPRACOVANIE_ZMENY_ID before INSERT ON CRD_SPRACOVANIE_ZMENY FOR EACH ROW
BEGIN
    IF inserting THEN
        IF :NEW.CRD_SPRACOVANIE_ZMENY_ID IS NULL THEN
            SELECT CRD_SPRACOVANIE_ZMENY_SEQ.nextval
            INTO :NEW.CRD_SPRACOVANIE_ZMENY_ID
            FROM dual;
        END IF;
    END IF;
END;

