CREATE OR REPLACE TRIGGER INSERT_PK_CUD_ZMENA_STAV_HIST_ID before INSERT ON CUD_ZMENA_STAV_HIST FOR EACH ROW
BEGIN
    IF inserting THEN
        IF :NEW.ZMENA_STAV_HIST_ID IS NULL THEN
            SELECT CUD_ZMENA_STAV_HIST_seq.nextval
            INTO :NEW.ZMENA_STAV_HIST_ID
            FROM dual;
        END IF;
    END IF;
END;
/
CREATE OR REPLACE TRIGGER INSERT_PK_CUD_ZMENA_STLPEC_ID before INSERT ON CUD_ZMENA_STLPEC FOR EACH ROW
BEGIN
    IF inserting THEN
        IF :NEW.ZMENA_STLPEC_ID IS NULL THEN
            SELECT CUD_ZMENA_STLPEC_seq.nextval
            INTO :NEW.ZMENA_STLPEC_ID
            FROM dual;
        END IF;
    END IF;
END;
/
CREATE OR REPLACE TRIGGER INSERT_PK_CUD_WF_TODO_ID before INSERT ON CUD_WF_TODO FOR EACH ROW
BEGIN
    IF inserting THEN
        IF :NEW.WF_TODO_ID IS NULL THEN
            SELECT CUD_WF_TODO_seq.nextval
            INTO :NEW.WF_TODO_ID
            FROM dual;
        END IF;
    END IF;
END;
