Insert into CUD.CUD_PLUGIN_CLASS_NAME (PLUGIN_CLASS_NAME_ID,CLASS_NAME,POPIS,ID_TRANSAKCIA_ZAPISANE) values (1,'CudPluginDlzkaUsekuClass','Kontroluje celkov˝ s˙Ëet usekov',1);
Insert into CUD.CUD_PLUGIN_CLASS_NAME (PLUGIN_CLASS_NAME_ID,CLASS_NAME,POPIS,ID_TRANSAKCIA_ZAPISANE) values (2,'CudPluginSubsidiarnaLokalitaClass','Kontroluje jedineËnosù susidi·rnej lokality',1);
Insert into CUD.CUD_PLUGIN_CLASS_NAME (PLUGIN_CLASS_NAME_ID,CLASS_NAME,POPIS,ID_TRANSAKCIA_ZAPISANE) values (3,'CudPluginLokalitaDbClass','Kontrola atrib˙tov nadradenej prim·rnej lokality alebo subsidiarnej lokality', 1);
Insert into CUD.CUD_PLUGIN_CLASS_NAME (PLUGIN_CLASS_NAME_ID,CLASS_NAME,POPIS,ID_TRANSAKCIA_ZAPISANE) values (4,'CudPluginJedinecnostClass','Kontroluje jedineËnosù atrib˙tu v r·mci tabuæky',1);
Insert into CUD.CUD_PLUGIN_CLASS_NAME (PLUGIN_CLASS_NAME_ID,CLASS_NAME,POPIS,ID_TRANSAKCIA_ZAPISANE) values (5,'CudPluginCelociselneZaokruhlenieClass','Kontrola, Ëi desatinnÈ Ëislo po matematickom zaokruhleni sa rovn· celÈmu ËÌslu',1);
Insert into CUD.CUD_PLUGIN_CLASS_NAME (PLUGIN_CLASS_NAME_ID,CLASS_NAME,POPIS,ID_TRANSAKCIA_ZAPISANE) values (6,'CudPluginCisloDbClass','Kontrola ËÌsla DB',1);
commit;

Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (1,'D',null,'ZDROJ','Aktrib˙t, ktorÈho hodnota sa ma kontrolovaù',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (2,'D',null,'LOOKUP','Aktrib˙t, ktorÈho hodnota sa ma doplniù',1);

Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (100,'V',1,'DLZKA','Kontrolovan· hodnota atrib˙tu (sum): DÂûka [km, m]',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (101,'V',1,'DLZKA_CASTI_DU_Z','Kontrolovan· hodnota atrib˙tu: DÂûka Ëasti definiËnÈho ˙seku Z',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (102,'V',1,'DLZKA_CASTI_TU','Kontrolovan· hodnota atrib˙tu: DÂûka Ëasti traùovÈho ˙seku',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (103,'V',1,'DLZKA_CASTI_DU_DO','Kontrolovan· hodnota atrib˙tu: DÂûka Ëasti definiËnÈho ˙seku Do',1);

Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (200,'V',2,'CISLO','CelÈ ËÌslo (dopravneho bodu, koæaje, a podobne)',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (201,'V',2,'NADRADENA_PRIMARNA','Nadraden· prim·rna lokalita alebo dopravn˝ bod',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (202,'V',2,'CRD_ZAC','CRD od',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (203,'V',2,'CRD_KON','CRD do',1);

Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (300,'V',3,'SUBSIDIARY_TYPE','Typ subsidi·rnej lokality',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (301,'V',3,'CISLO','»Ìslo dopravnÈho bodu',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (302,'V',3,'NADRADENA_PRIMARNA','Nadraden· prim·rna lokalita',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (304,'V',3,'COMPANY','VlastnÌk bodu',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (305,'V',3,'CRD_ZAC','CRD od',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (306,'V',3,'CRD_KON','CRD do',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (307,'V',3,'OTVORENY_PRE_OD','Otvoren˝ pre OD',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (308,'V',3,'OTVORENY_PRE_ND','Otvoren˝ pre ND',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (309,'V',3,'OTVORENY_PRE_OD_ZAC','Otvoren˝ pre OD od',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (310,'V',3,'OTVORENY_PRE_OD_KON','Otvoren˝ pre OD do',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (311,'V',3,'OTVORENY_PRE_ND_ZAC','Otvoren˝ pre ND od',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (312,'V',3,'OTVORENY_PRE_ND_KON','Otvoren˝ pre ND do',1);

Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (400,'V',4,'ATRIBUT','Kontrolovan˝ atrib˙t',1);

Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (500,'V',5,'CISLO_DESATINNE','DesatinnÈ ËÌslo',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (501,'V',5,'CISLO_CELE','CelÈ ËÌslo',1);

Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (600,'V',6,'CISLO','»Ìslo dopravnÈho bodu',1);
Insert into CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID,TYP,ID_PLUGIN_CLASS_NAME,NAZOV_ALIASU,POPIS,ID_TRANSAKCIA_ZAPISANE) values (601,'V',6,'SUBSIDIARY_TYPE','Typ subsidi·rnej lokality',1);
commit;
