CREATE TABLE CUD_CISELNIK (
    CISELNIK_ID             NUMBER(10) NOT NULL,
    TABULKA                 NVARCHAR2(100) NOT NULL,
    NAZOV                   NVARCHAR2(200) NOT NULL,
    POPIS                   NVARCHAR2(2000),
    PRINT_CLASS             NVARCHAR2(200),
    PRINT_ZAHLAVIE          NVARCHAR2(200) NOT NULL,
    AKTIVNY                 NVARCHAR2(1) NOT NULL,
    PREDPIS                 NVARCHAR2(50),
    PRILOHA_KAPITOLA        NVARCHAR2(50),
    HLAVNY                  NVARCHAR2(1),
    TYP                     NVARCHAR2(4) NOT NULL,
    KATEGORIA               NVARCHAR2(8) NOT NULL,
    CAS_ZMENY               TIMESTAMP (6),
    ID_UCET                 NUMBER(10),
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE   NUMBER(20),
    CONSTRAINT CUD_CISELNIK_PK PRIMARY KEY (CISELNIK_ID)
);
COMMENT ON COLUMN CUD_CISELNIK.TYP is 'values = { TECH, INY }';
COMMENT ON COLUMN CUD_CISELNIK.KATEGORIA is 'values = { ZAKLADNY, VOZIDLO, TAFTSI, INFRA, LOKALITA }';

CREATE TABLE CUD_CISELNIK_STLPEC (
    CISELNIK_STLPEC_ID      NUMBER(10) NOT NULL,
    ID_CISELNIK             NUMBER(10) NOT NULL,
    NAZOV                   NVARCHAR2(200) NOT NULL,
    NADPIS                  NVARCHAR2(200) NOT NULL,
    TYP                     NVARCHAR2(3) NOT NULL,
    PORADIE                 NUMBER(2) NOT NULL,
    DLZKA                   NUMBER(4) NOT NULL,
    DECIMALS                NUMBER(10),
    DB_TYP                  NVARCHAR2(20) NOT NULL,
    POVINNY                 NVARCHAR2(1) NOT NULL,
    JEDINECNY               NVARCHAR2(1) NOT NULL,
    AKTIVNY                 NVARCHAR2(1) NOT NULL,
    FK1_ID_CISELNIK         NUMBER(10),
    FK1_PK_NAZOV            NVARCHAR2(200),
    FK1_FK_NAZOV            NVARCHAR2(200),
    POPIS                   NVARCHAR2(2000),
    CAS_ZMENY               TIMESTAMP (6),
    ID_UCET                 NUMBER(10),
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE   NUMBER(20),
    CONSTRAINT CUD_CISELNIK_STLPEC_PK PRIMARY KEY (CISELNIK_STLPEC_ID)
);
COMMENT ON COLUMN CUD_CISELNIK_STLPEC.TYP is 'values = { HK, PK, FK, AT }';
COMMENT ON COLUMN CUD_CISELNIK_STLPEC.DB_TYP is 'values = { String, Integer, Double, Date, Boolean }';

CREATE TABLE CUD_CISELNIK_GUI (
    CISELNIK_GUI_ID         NUMBER(10) NOT NULL,
    ID_CISELNIK             NUMBER(10) NOT NULL,
    STAV                    NVARCHAR2(5) NOT NULL,
    PLATNOST_OD             TIMESTAMP(6),
    PLATNOST_DO             TIMESTAMP(6),
    CAS_PUBLIKOVANIA        TIMESTAMP(6),
    POPIS                   NVARCHAR2(2000),
    CAS_ZMENY               TIMESTAMP (6),
    ID_UCET                 NUMBER(10),
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE   NUMBER(20),
    CONSTRAINT CUD_CISELNIK_GUI_PK PRIMARY KEY (CISELNIK_GUI_ID)
);
COMMENT ON COLUMN CUD_CISELNIK_GUI.STAV is 'values = { DRAFT, PUB, ZMAZ }';

CREATE TABLE CUD_CISELNIK_STLPEC_GUI (
    CISELNIK_STLPEC_GUI_ID  NUMBER(10) NOT NULL,
    ID_CISELNIK_GUI         NUMBER(10) NOT NULL,
    ID_CISELNIK_STLPEC      NUMBER(10) NOT NULL,
    NADPIS                  NVARCHAR2(200) NOT NULL,
    PORADIE                 NUMBER(3) NOT NULL,
    DLZKA                   NUMBER(4) NOT NULL,
    DECIMALS                NUMBER(10),
    DB_TYP                  NVARCHAR2(20) NOT NULL,
    ZMENA                   NVARCHAR2(1) NOT NULL,
    POVINNY                 NVARCHAR2(1) NOT NULL,
    ZAROVNANIE              NVARCHAR2(1),
    FK1_FK_NAZOV            NVARCHAR2(200),
    FK2_ID_CISELNIK         NUMBER(10),
    FK2_PK_NAZOV            NVARCHAR2(200),
    FK2_FK_NAZOV            NVARCHAR2(200),
    LIST_ZOBRAZENIE         NVARCHAR2(1) NOT NULL,
    LIST_SIRKA              NUMBER(4),
    LIST_SIRKA_CHANGE       NVARCHAR2(1) NOT NULL,
    FORM_ZOBRAZENIE         NVARCHAR2(1) NOT NULL,
    FORM_SIRKA              NUMBER(4),
    POPUP_ZOBRAZENIE        NVARCHAR2(1) NOT NULL,
    POPUP_SIRKA             NUMBER(4),
    POPUP_SIRKA_CHANGE      NVARCHAR2(1) NOT NULL,
    LOOKUP_ZOBRAZENIE       NVARCHAR2(1) NOT NULL,
    EDIT_CONTROL            NVARCHAR2(20),
    REG_EXP                 NVARCHAR2(500),
    POPIS                   NVARCHAR2(2000),
    CAS_ZMENY               TIMESTAMP (6),
    ID_UCET                 NUMBER(10),
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE   NUMBER(20),
    CONSTRAINT CUD_CISELNIK_STLPEC_GUI_PK PRIMARY KEY (CISELNIK_STLPEC_GUI_ID)
);

CREATE TABLE CUD_WF_DEF (
    WF_DEF_ID               NUMBER(10) NOT NULL,
    ID_CISELNIK             NUMBER(10) NOT NULL,
    ID_WF_DEF_NASL          NUMBER(10),
    NAZOV                   NVARCHAR2(100) NOT NULL,
    TYP                     NVARCHAR2(2) NOT NULL,
    ZODPOVEDNOST            NVARCHAR2(1),
    EMAIL_LIST              NVARCHAR2(2000),
    EMAIL_TEXT              NVARCHAR2(2000),
    EMAIL_SUBJECT           NVARCHAR2(100),
    EMAIL_SEND              NVARCHAR2(1) NOT NULL,
    HODINY                  NUMBER(3),
    ID_SKUPINA              NUMBER(10) NOT NULL,
    SKUPINA_NAZOV           NVARCHAR2(100) NOT NULL,
    CAS_ZMENY               TIMESTAMP (6),
    ID_UCET                 NUMBER(10),
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE   NUMBER(20),
    CONSTRAINT CUD_WF_DEF_PK PRIMARY KEY (WF_DEF_ID)
);
COMMENT ON COLUMN CUD_WF_DEF.TYP is 'values = { IN, SC, OV, ES }';

CREATE TABLE CUD_ZMENA (
    ZMENA_ID                NUMBER(10) NOT NULL,
    ID_CISELNIK             NUMBER(10) NOT NULL,
    ROW_ID                  NUMBER(10),
    OPERACIA                NVARCHAR2(1) NOT NULL,
    STAV                    NVARCHAR2(3) NOT NULL,
    PLATNOST_OD             TIMESTAMP (6),
    PLATNOST_DO             TIMESTAMP (6),
    CAS_SCHVALENIA_GR       TIMESTAMP (6),
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    CONSTRAINT CUD_ZMENA_PK PRIMARY KEY (ZMENA_ID)
);
COMMENT ON COLUMN CUD_ZMENA.STAV is 'values = { VPO, SCH, ZAM, PAU, SAU }';

CREATE TABLE CUD_ZMENA_STLPEC (
    ZMENA_STLPEC_ID         NUMBER(10) NOT NULL,
    ID_CISELNIK             NUMBER(10) NOT NULL,
    ID_ZMENA                NUMBER(10) NOT NULL,
    ID_CISELNIK_STLPEC      NUMBER(10) NOT NULL,
    OLD_VALUE               NVARCHAR2(2000),
    NEW_VALUE               NVARCHAR2(2000),
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    CONSTRAINT CUD_ZMENA_STLPEC_PK PRIMARY KEY (ZMENA_STLPEC_ID)
);

CREATE TABLE CUD_WF_TODO (
    WF_TODO_ID              NUMBER(10) NOT NULL,
    ID_CISELNIK             NUMBER(10) NOT NULL,
    ID_ZMENA                NUMBER(10) NOT NULL,
    ID_WF_DEF               NUMBER(10) NOT NULL,
    POTVRDENY               NVARCHAR2(1),
    POZNAMKA                NVARCHAR2(2000),
    ID_UCET                 NUMBER(10) NOT NULL,
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    CONSTRAINT CUD_WF_TODO_PK PRIMARY KEY (WF_TODO_ID)
);

CREATE TABLE CUD_ZMENA_STAV_HIST (
    ZMENA_STAV_HIST_ID      NUMBER(10) NOT NULL,
    ID_CISELNIK             NUMBER(10) NOT NULL,
    ID_ZMENA                NUMBER(10) NOT NULL,
    STAV                    NVARCHAR2(3) NOT NULL,
    CAS_VYTVORENIA          TIMESTAMP(6) NOT NULL,
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    CONSTRAINT CUD_ZMENA_STAV_HIST_PK PRIMARY KEY (ZMENA_STAV_HIST_ID)
);
COMMENT ON COLUMN CUD_ZMENA_STAV_HIST.STAV is 'values = { VPO, SCH, ZAM, PAU, SAU }';

CREATE TABLE CUD_PLUGIN (
    PLUGIN_ID                   NUMBER(10) NOT NULL,
    ID_CISELNIK                 NUMBER(10) NOT NULL,
    ID_PLUGIN_CLASS_NAME        NUMBER(10),
    TYP                         NVARCHAR2(1) NOT NULL,
    PLATNOST_OD                 TIMESTAMP (6) NOT NULL,
    PLATNOST_DO                 TIMESTAMP (6),
    CAS_ZMENY                   TIMESTAMP (6) NOT NULL,
    ID_UCET                     NUMBER(10) NOT NULL,
    ID_TRANSAKCIA_ZAPISANE      NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE       NUMBER(20),
    CONSTRAINT CUD_PLUGIN_PK PRIMARY KEY (PLUGIN_ID)
);
COMMENT ON COLUMN CUD_PLUGIN.TYP is 'values = { V - validacny, D - doplnenie, Z - zobrazenie }';

CREATE TABLE CUD_PLUGIN_STLPEC (
    PLUGIN_STLPEC_ID          NUMBER(10) NOT NULL,
    ID_PLUGIN                 NUMBER(10) NOT NULL,
    ID_CISELNIK_STLPEC        NUMBER(10) NOT NULL,
    ID_PLUGIN_ALIAS           NUMBER(10),
    ID_TRANSAKCIA_ZAPISANE    NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE     NUMBER(20),
    CONSTRAINT CUD_PLUGIN_STLPEC_PK PRIMARY KEY (PLUGIN_STLPEC_ID)
);

CREATE TABLE CUD_PLUGIN_ALIAS (
    PLUGIN_ALIAS_ID             NUMBER(10) NOT NULL,
    ID_PLUGIN_CLASS_NAME        NUMBER(10),
    TYP                         NVARCHAR2(1),
    NAZOV_ALIASU                NVARCHAR2(200) NOT NULL,
    POPIS                       NVARCHAR2(2000) NOT NULL,
    ID_TRANSAKCIA_ZAPISANE      NUMBER(20) NOT NULL,
    CONSTRAINT CUD_PLUGIN_ALIAS_PK PRIMARY KEY (PLUGIN_ALIAS_ID)
);
COMMENT ON COLUMN CUD_PLUGIN_ALIAS.TYP is 'values = { V - validacny, D - doplnenie, Z - zobrazenie }';

CREATE TABLE CUD_PLUGIN_CLASS_NAME (
    PLUGIN_CLASS_NAME_ID        NUMBER(10) NOT NULL,
    CLASS_NAME                  NVARCHAR2(200) NOT NULL,
    POPIS                       NVARCHAR2(2000) NOT NULL,
    ID_TRANSAKCIA_ZAPISANE      NUMBER(20) NOT NULL,
    CONSTRAINT CUD_PLUGIN_CLASS_NAME_PK PRIMARY KEY (PLUGIN_CLASS_NAME_ID)
);

CREATE TABLE CUD_PLUGIN_KONTROLA (
    PLUGIN_KONTROLA_ID        NUMBER(10) NOT NULL,
    ID_CISELNIK               NUMBER(10) NOT NULL,
    PLATNOST_OD               TIMESTAMP(6) NOT NULL,
    CAS_KONTROLA_ZAC          TIMESTAMP(6),
    CAS_KONTROLA_KON          TIMESTAMP(6),
    STAV                      NVARCHAR2(1)  NOT NULL,
    CAS_ZMENY                 TIMESTAMP(6) NOT NULL,
    ID_UCET                   NUMBER(10) NOT NULL,
    ID_TRANSAKCIA_ZAPISANE    NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE     NUMBER(20),
    CONSTRAINT CUD_PLUGIN_KONTROLA_PK PRIMARY KEY (PLUGIN_KONTROLA_ID)
);
COMMENT ON COLUMN CUD_PLUGIN_KONTROLA.STAV is 'values = { K - Kontrola, E - Kontrola s chybou }';

CREATE TABLE CUD_PLUGIN_KONTROLA_ROW (
    PLUGIN_KONTROLA_ROW_ID    NUMBER(10) NOT NULL,
    ID_PLUGIN_KONTROLA        NUMBER(10) NOT NULL,
    ID_PLUGIN                 NUMBER(10) NOT NULL,
    ROW_ID                    NUMBER(10) NOT NULL,
    KONTROLA_USPESNA          NVARCHAR2(1) NOT NULL,
    POPIS                     NVARCHAR2(2000),
    ID_TRANSAKCIA_ZAPISANE    NUMBER(20) NOT NULL,
    CONSTRAINT CUD_PLUGIN_KONTROLA_ROW_PK PRIMARY KEY (PLUGIN_KONTROLA_ROW_ID)
);

CREATE TABLE CUD_PREKLAD (
    PREKLAD_ID              NUMBER(10) NOT NULL,
    ID_PREKLAD_JAZYK        NUMBER(10) NOT NULL,
    ID_PREKLAD_STLPEC       NUMBER(10) NOT NULL,
    ZAZNAM_ID               NUMBER(10) NOT NULL,
    PREKLAD                 BLOB NOT NULL,
    CAS_ZMENY               TIMESTAMP (6),
    ID_UCET                 NUMBER(10),
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE   NUMBER(20),
    CONSTRAINT CUD_PREKLAD_PK PRIMARY KEY (PREKLAD_ID)
);

CREATE TABLE CUD_PREKLAD_TABULKA (
    PREKLAD_TABULKA_ID      NUMBER(10) NOT NULL,
    NAZOV_DB                NVARCHAR2(200) NOT NULL,
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    CONSTRAINT CUD_PREKLAD_TABULKA_PK PRIMARY KEY (PREKLAD_TABULKA_ID)
);

CREATE TABLE CUD_PREKLAD_STLPEC (
    PREKLAD_STLPEC_ID       NUMBER(10) NOT NULL,
    ID_PREKLAD_TABULKA      NUMBER(10) NOT NULL,
    NAZOV_DB                NVARCHAR2(200) NOT NULL,
    NADPIS                  NVARCHAR2(200) NOT NULL,
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    CONSTRAINT CUD_PREKLAD_STLPEC_PK PRIMARY KEY (PREKLAD_STLPEC_ID)
);

CREATE TABLE CUD_PREKLAD_JAZYK (
    PREKLAD_JAZYK_ID        NUMBER(10) NOT NULL,
    KOD                     NVARCHAR2(3) NOT NULL,
    NAZOV_SK                NVARCHAR2(200) NOT NULL,
    NAZOV_EN                NVARCHAR2(200) NOT NULL,
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    CONSTRAINT CUD_PREKLAD_JAZYK_PK PRIMARY KEY (PREKLAD_JAZYK_ID)
);

CREATE TABLE CUD_UZAMKNUTIE (
    UZAMKNUTIE_ID           NUMBER(10) NOT NULL,
    ID_CISELNIK             NUMBER(10) NOT NULL,
    ROW_ID                  NUMBER(10) NOT NULL,
    CAS_ZMENY               TIMESTAMP (6),
    ID_UCET                 NUMBER(10),
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE   NUMBER(20),
    CONSTRAINT CUD_UZAMKNUTIE_PK PRIMARY KEY (UZAMKNUTIE_ID)
);

CREATE TABLE CUD_OBJEKT (
    OBJEKT_ID                   NUMBER(10) NOT NULL,
    NAZOV                       NVARCHAR2(200) NOT NULL,
    PLATNY                      NVARCHAR2(1) NOT NULL,
    SYSTEMOVY                   NVARCHAR2(1) NOT NULL,
    SYSTEMOVY_KANAL             NVARCHAR2(10),
    SYSTEMOVY_VSETKY_CISELNIKY  NVARCHAR2(1),
    SYSTEMOVY_EXPORT_FORMAT     NVARCHAR2(1),
    CAS_ZMENY                   TIMESTAMP (6),
    ID_UCET                     NUMBER(10),
    ID_TRANSAKCIA_ZAPISANE      NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE       NUMBER(20),
    CONSTRAINT CUD_OBJEKT_PK PRIMARY KEY (OBJEKT_ID)
);
COMMENT ON COLUMN CUD_OBJEKT.SYSTEMOVY_EXPORT_FORMAT is 'values = { 1 - xml, 2 - excel }';
COMMENT ON COLUMN CUD_OBJEKT.SYSTEMOVY_KANAL is 'values = { OBM, CRD }';

CREATE TABLE CUD_OBJEKT_CISELNIK (
    OBJEKT_CISELNIK_ID      NUMBER(10) NOT NULL,
    ID_OBJEKT               NUMBER(10) NOT NULL,
    ID_CISELNIK             NUMBER(10) NOT NULL,
    VSETKY                  NVARCHAR2(1) NOT NULL,
    PLATNY                  NVARCHAR2(1) NOT NULL,
    CAS_ZMENY               TIMESTAMP (6),
    ID_UCET                 NUMBER(10),
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE   NUMBER(20),
    CONSTRAINT CUD_OBJEKT_CISELNIK_PK PRIMARY KEY (OBJEKT_CISELNIK_ID)
);

CREATE TABLE CUD_OBJEKT_STLPEC (
    OBJEKT_STLPEC_ID          NUMBER(10) NOT NULL,
    ID_OBJEKT_CISELNIK        NUMBER(10) NOT NULL,
    ID_CISELNIK_STLPEC        NUMBER(10) NOT NULL,
    ZMENA                     NVARCHAR2(1) NOT NULL,
    HODNOTA                   NVARCHAR2(255),
    CAS_ZMENY                 TIMESTAMP (6),
    ID_UCET                   NUMBER(10),
    ID_TRANSAKCIA_ZAPISANE    NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE     NUMBER(20),
    CONSTRAINT CUD_OBJEKT_STLPEC_PK PRIMARY KEY (OBJEKT_STLPEC_ID)
);

CREATE TABLE CUD_ODBERATEL (
    ODBERATEL_ID            NUMBER(10) NOT NULL,
    ID_HIST_DOPRAVCA        NUMBER(10),
    NAZOV                   NVARCHAR2(255) NOT NULL,
    OBM_UCET_NAZOV          NVARCHAR2(50),
    ROLA_KOD                NVARCHAR2(3),
    ROLA_NAZOV              NVARCHAR2(200),
    EXPORT_TYP              NVARCHAR2(3),
    EXPORT_CESTA            NVARCHAR2(255),
    AKTIVNY                 NVARCHAR2(1) NOT NULL,
    INTERNY                 NVARCHAR2(1) NOT NULL,
    CAS_ZMENY               TIMESTAMP (6),
    ID_UCET                 NUMBER(10),
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE   NUMBER(20),
    CONSTRAINT CUD_ODBERATEL_PK PRIMARY KEY (ODBERATEL_ID)
);
COMMENT ON COLUMN CUD_ODBERATEL.EXPORT_TYP is 'values = { DIR - adresar, URI - url adresa }';

CREATE TABLE CUD_ODBERATEL_OBJEKT (
    ODBERATEL_OBJEKT_ID         NUMBER(10) NOT NULL,
    ID_ODBERATEL                NUMBER(10) NOT NULL,
    ID_OBJEKT                   NUMBER(10),
    PLATNOST_OD                 TIMESTAMP(6) NOT NULL,
    PLATNOST_DO                 TIMESTAMP(6),
    TYP_PRISTUPU                NVARCHAR2(1) NOT NULL,
    OPAKOVANIE                  NVARCHAR2(1),
    EXPORT_DOVOD                NVARCHAR2(1),
    EXPORT_ROZSAH               NVARCHAR2(1),
    EXPORT_FORMAT               NVARCHAR2(1),
    EXPORT_TYP                  NVARCHAR2(3),
    EXPORT_CESTA                NVARCHAR2(255),
    VSETKY_CISELNIKY            NVARCHAR2(1) NOT NULL,
    CAS_POSL_EXPORTU_ZMENA      TIMESTAMP(6),
    CAS_POSL_EXPORTU            TIMESTAMP(6),
    CAS_POSL_EXPORTU_PLAN       TIMESTAMP(6),
    CAS_ZMENY                   TIMESTAMP (6),
    ID_UCET                     NUMBER(10),
    ID_TRANSAKCIA_ZAPISANE      NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE       NUMBER(20),
    CONSTRAINT CUD_ODBERATEL_OBJEKT_PK PRIMARY KEY (ODBERATEL_OBJEKT_ID)
);
COMMENT ON COLUMN CUD_ODBERATEL_OBJEKT.TYP_PRISTUPU is 'values = { 1 - web servis, 2 - export, 3 - zmena }';
COMMENT ON COLUMN CUD_ODBERATEL_OBJEKT.OPAKOVANIE is 'values = { 1 - denne, 2 - tyzdenne,  3 - mesacne, 4 - 3mesacne, 5 - pri zmene }';
COMMENT ON COLUMN CUD_ODBERATEL_OBJEKT.EXPORT_DOVOD is 'values = { 1 - zmena, 2 - obdobie }';
COMMENT ON COLUMN CUD_ODBERATEL_OBJEKT.EXPORT_ROZSAH is 'values = { 1 - vsetky, 2 - zmenene }';
COMMENT ON COLUMN CUD_ODBERATEL_OBJEKT.EXPORT_FORMAT is 'values = { 1 - xml, 2 - excel }';
COMMENT ON COLUMN CUD_ODBERATEL_OBJEKT.EXPORT_TYP is 'values = { ADR - adresar, URI - url adresa }';


CREATE TABLE CUD_SEND (
    SEND_ID                   NUMBER(10) NOT NULL,
    ID_ODBERATEL_OBJEKT       NUMBER(10) NOT NULL,
    CAS_VYTVORENIA            TIMESTAMP(6) NOT NULL,
    SPRAVA_UUID               NVARCHAR2(36),
    SPRAVA_TYP                NVARCHAR2(4),
    ID_TRANSAKCIA_ZAPISANE    NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE     NUMBER(20),
    CONSTRAINT CUD_SEND_PK PRIMARY KEY (SEND_ID)
);

CREATE TABLE CUD_SEND_SUBOR (
    SEND_SUBOR_ID           NUMBER(10) NOT NULL,
    ID_SEND                 NUMBER(10) NOT NULL,
    ID_CISELNIK             NUMBER(10),
    ROW_ID_EXT              NUMBER(10),
    NAZOV_SUBORU            NVARCHAR2(200) NOT NULL,
    SUBOR                   BLOB,
    PORADOVE_CISLO          NUMBER(3),
    POCET_POKUSOV           NUMBER(2) NOT NULL,
    CAS_VYTVORENIA          TIMESTAMP(6) NOT NULL,
    CAS_ODOSLANIA           TIMESTAMP(6),
    NAVRAT_KOD              NVARCHAR2(4),
    NAVRAT_TEXT             NVARCHAR2(225),
    ERROR_SPRAVA            NVARCHAR2(500),
    ERROR_CAS               TIMESTAMP(6),
    ODPOVED_UUID            NVARCHAR2(36),
    ODPOVED_TYP             NVARCHAR2(4),
    ODPOVED_SUBOR           BLOB,
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    ID_TRANSAKCIA_ZRUSENE   NUMBER(20),
    CONSTRAINT CUD_SEND_SUBOR_PK PRIMARY KEY (SEND_SUBOR_ID)
);

CREATE TABLE CUD_IMPORT (
  IMPORT_ID               NUMBER(10, 0) NOT NULL,
  ID_CISELNIK             NUMBER(10),
  CISELNIK_TABULKA        VARCHAR2(100 BYTE),
  STAV                    VARCHAR2(1 BYTE)  NOT NULL,
  CAS_VYTVORENIA          TIMESTAMP(6) NOT NULL,
  CAS_KONTROLA_ZAC        TIMESTAMP(6),
  CAS_KONTROLA_KON        TIMESTAMP(6),
  CAS_IMPORT_ZAC          TIMESTAMP(6),
  CAS_IMPORT_KON          TIMESTAMP(6),
  CAS_ZMENY               TIMESTAMP(6),
  ID_UCET                 NUMBER(10, 0),
  ID_TRANSAKCIA_ZAPISANE  NUMBER(20, 0) NOT NULL,
  ID_TRANSAKCIA_ZRUSENE   NUMBER(20, 0),
  CONSTRAINT CUD_IMPORT_PK PRIMARY KEY ( IMPORT_ID )
);
COMMENT ON COLUMN CUD_IMPORT.STAV is 'values = { V, K, I, E }';

CREATE TABLE CUD_IMPORT_PRILOHA (
  IMPORT_PRILOHA_ID       NUMBER(10, 0) NOT NULL,
  ID_IMPORT               NUMBER(10, 0) NOT NULL,
  FILE_NAME               VARCHAR2(100 BYTE) NOT NULL,
  PRILOHA                 BLOB NOT NULL,
  ID_TRANSAKCIA_ZAPISANE  NUMBER(20, 0) NOT NULL,
  CONSTRAINT CUD_IMPORT_PRILOHA_PK PRIMARY KEY ( IMPORT_PRILOHA_ID )
);

CREATE TABLE CUD_IMPORT_ZMENA (
    IMPORT_ZMENA_ID         NUMBER(10) NOT NULL,
    ID_IMPORT               NUMBER(10, 0) NOT NULL,
    ROW_ID                  NUMBER(10),
    XLS_ROW_ID              NUMBER(10) NOT NULL,
    OPERACIA                NVARCHAR2(1),
    PLATNOST_OD             TIMESTAMP(6),
    CAS_SCHVALENIA_GR       TIMESTAMP(6),
    POZNAMKA                NVARCHAR2(2000),
    SPRACOVANY              NVARCHAR2(1) NOT NULL,
    OBNOVA                  NVARCHAR2(1) NOT NULL,
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    CONSTRAINT CUD_IMPORT_ZMENA_PK PRIMARY KEY (IMPORT_ZMENA_ID)
);

CREATE TABLE CUD_IMPORT_ZMENA_STLPEC (
    IMPORT_ZMENA_STLPEC_ID          NUMBER(10) NOT NULL,
    ID_IMPORT                       NUMBER(10) NOT NULL,
    ID_IMPORT_ZMENA                 NUMBER(10) NOT NULL,
    ID_CISELNIK_STLPEC              NUMBER(10),
    ID_IMPORT_ZMENA_STLPEC_PRILOHA  NUMBER(10),
    CISELNIK_STLPEC_NAZOV           NVARCHAR2(200) NOT NULL,
    OLD_VALUE                       NVARCHAR2(2000),
    NEW_VALUE                       NVARCHAR2(2000),
    ID_TRANSAKCIA_ZAPISANE          NUMBER(20) NOT NULL,
    CONSTRAINT CUD_IMPORT_ZMENA_STLPEC_PK PRIMARY KEY (IMPORT_ZMENA_STLPEC_ID)
);

CREATE TABLE CUD_IMPORT_ZMENA_STLPEC_PRILOHA (
    IMPORT_ZMENA_STLPEC_PRILOHA_ID       NUMBER(10) NOT NULL,
    ID_IMPORT               NUMBER(10) NOT NULL,
    ID_IMPORT_ZMENA         NUMBER(10) NOT NULL,
    OLD_VALUE_PRILOHA               BLOB,
    NEW_VALUE_PRILOHA               BLOB,
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    CONSTRAINT CUD_IMPORT_ZMENA_STLPEC_PRILOHA_PK PRIMARY KEY (IMPORT_ZMENA_STLPEC_PRILOHA_ID)
);

CREATE TABLE CUD_IMPORT_MSG (
    IMPORT_MSG_ID           NUMBER(10) NOT NULL,
    ID_IMPORT               NUMBER(10) NOT NULL,
    ID_IMPORT_ZMENA         NUMBER(10),
    TYP                     NVARCHAR2(1) NOT NULL,
    MSG                     NVARCHAR2(2000) NOT NULL,
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20) NOT NULL,
    CONSTRAINT CUD_IMPORT_MSG_PK PRIMARY KEY (IMPORT_MSG_ID)
);
COMMENT ON COLUMN CUD_IMPORT_MSG.TYP is 'values = { E, W }';


CREATE TABLE CUD_ZMENA_ESKALACIA (
  ZMENA_ESKALACIA_ID       NUMBER(10) NOT NULL,
  ID_CISELNIK              NUMBER(10) NOT NULL,
  ID_ZMENA                 NUMBER(10) NOT NULL,
  CAS_VYTVORENIA           TIMESTAMP(6) NOT NULL,
  ID_TRANSAKCIA_ZAPISANE   NUMBER(20) NOT NULL,
  CONSTRAINT CUD_ZMENA_ESKALACIA_PK PRIMARY KEY ( ZMENA_ESKALACIA_ID )
);




CREATE UNIQUE INDEX CUD_CISELNIK_DUNQ1 ON CUD_CISELNIK(TABULKA, ID_TRANSAKCIA_ZRUSENE);
CREATE UNIQUE INDEX CUD_CISELNIK_DUNQ2 ON CUD_CISELNIK(NAZOV, ID_TRANSAKCIA_ZRUSENE);
CREATE UNIQUE INDEX CUD_CISELNIK_STLPEC_DUNQ1 ON CUD_CISELNIK_STLPEC(ID_CISELNIK, NAZOV, ID_TRANSAKCIA_ZRUSENE);
CREATE UNIQUE INDEX CUD_OBJEKT_DUNQ1 ON CUD_OBJEKT(NAZOV, ID_TRANSAKCIA_ZRUSENE);
CREATE UNIQUE INDEX CUD_PREKLAD_DUNQ1 ON CUD_PREKLAD(ID_PREKLAD_JAZYK, ID_PREKLAD_STLPEC, ZAZNAM_ID, ID_TRANSAKCIA_ZRUSENE);
CREATE UNIQUE INDEX CUD_UZAMKNUTIE_DUNQ1 ON CUD_UZAMKNUTIE ( ID_CISELNIK, ROW_ID, ID_TRANSAKCIA_ZRUSENE);

CREATE INDEX CUD_ZMENA_IDX ON CUD_ZMENA(ID_CISELNIK);
CREATE INDEX CUD_ZMENA_STLPEC_IDX ON CUD_ZMENA_STLPEC(ID_CISELNIK);
CREATE INDEX CUD_WF_TODO_IDX ON CUD_WF_TODO(ID_CISELNIK);
CREATE INDEX CUD_ZMENA_STAV_HIST_IDX ON CUD_ZMENA_STAV_HIST(ID_CISELNIK);
CREATE INDEX CUD_SEND_SUBOR_IDX ON CUD_SEND_SUBOR(ID_CISELNIK);
CREATE INDEX CUD_IMPORT_ZMENA_IDX ON CUD_IMPORT_ZMENA(ID_IMPORT);
CREATE INDEX CUD_IMPORT_ZMENA_STLPEC_IDX ON CUD_IMPORT_ZMENA_STLPEC(ID_IMPORT);
CREATE INDEX CUD_IMPORT_ZMENA_STLPEC_PRILOHA_IDX ON CUD_IMPORT_ZMENA_STLPEC_PRILOHA(ID_IMPORT);
CREATE INDEX CUD_IMPORT_MSG_IDX ON CUD_IMPORT_MSG(ID_IMPORT);
CREATE INDEX CUD_ZMENA_ESKALACIA_IDX ON CUD_ZMENA_ESKALACIA(ID_CISELNIK);
CREATE INDEX CUD_PLUGIN_KONTROLA_IDX ON CUD_PLUGIN_KONTROLA(ID_CISELNIK);
CREATE INDEX CUD_PLUGIN_KONTROLA_ROW_IDX ON CUD_PLUGIN_KONTROLA_ROW(ID_PLUGIN_KONTROLA);
CREATE INDEX CUD_PREKLAD_IDX ON CUD_PREKLAD(ID_PREKLAD_JAZYK);
CREATE INDEX CUD_UZAMKNUTIE_IDX ON CUD_UZAMKNUTIE(ID_CISELNIK);



ALTER TABLE CUD_CISELNIK_STLPEC ADD CONSTRAINT CUD_CISELNIK_STLPEC_FK1 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_CISELNIK_GUI ADD CONSTRAINT CUD_CISELNIK_GUI_FK1 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_CISELNIK_STLPEC_GUI ADD CONSTRAINT CUD_CISELNIK_STLPEC_GUI_FK1 FOREIGN KEY (ID_CISELNIK_GUI) REFERENCES CUD_CISELNIK_GUI (CISELNIK_GUI_ID);
ALTER TABLE CUD_CISELNIK_STLPEC_GUI ADD CONSTRAINT CUD_CISELNIK_STLPEC_GUI_FK2 FOREIGN KEY (ID_CISELNIK_STLPEC) REFERENCES CUD_CISELNIK_STLPEC (CISELNIK_STLPEC_ID);
ALTER TABLE CUD_WF_DEF ADD CONSTRAINT CUD_WF_DEF_FK1 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_WF_DEF ADD CONSTRAINT CUD_WF_DEF_FK2 FOREIGN KEY (ID_WF_DEF_NASL) REFERENCES CUD_WF_DEF (WF_DEF_ID);
ALTER TABLE CUD_ZMENA ADD CONSTRAINT CUD_ZMENA_FK1 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_ZMENA_STLPEC ADD CONSTRAINT CUD_ZMENA_STLPEC_FK1 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_ZMENA_STLPEC ADD CONSTRAINT CUD_ZMENA_STLPEC_FK2 FOREIGN KEY (ID_ZMENA) REFERENCES CUD_ZMENA (ZMENA_ID);
ALTER TABLE CUD_ZMENA_STLPEC ADD CONSTRAINT CUD_ZMENA_STLPEC_FK3 FOREIGN KEY (ID_CISELNIK_STLPEC) REFERENCES CUD_CISELNIK_STLPEC (CISELNIK_STLPEC_ID);
ALTER TABLE CUD_WF_TODO ADD CONSTRAINT CUD_WF_TODO_FK1 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_WF_TODO ADD CONSTRAINT CUD_WF_TODO_FK2 FOREIGN KEY (ID_ZMENA) REFERENCES CUD_ZMENA (ZMENA_ID);
ALTER TABLE CUD_ZMENA_STAV_HIST ADD CONSTRAINT CUD_ZMENA_STAV_HIST_FK1 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_ZMENA_STAV_HIST ADD CONSTRAINT CUD_ZMENA_STAV_HIST_FK2 FOREIGN KEY (ID_ZMENA) REFERENCES CUD_ZMENA (ZMENA_ID);
ALTER TABLE CUD_PLUGIN ADD CONSTRAINT CUD_PLUGIN_FK1 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_PLUGIN ADD CONSTRAINT CUD_PLUGIN_FK2 FOREIGN KEY (ID_PLUGIN_CLASS_NAME) REFERENCES CUD_PLUGIN_CLASS_NAME (PLUGIN_CLASS_NAME_ID);
ALTER TABLE CUD_PLUGIN_STLPEC ADD CONSTRAINT CUD_PLUGIN_STLPEC_FK1 FOREIGN KEY (ID_PLUGIN) REFERENCES CUD_PLUGIN (PLUGIN_ID);
ALTER TABLE CUD_PLUGIN_STLPEC ADD CONSTRAINT CUD_PLUGIN_STLPEC_FK3 FOREIGN KEY (ID_CISELNIK_STLPEC) REFERENCES CUD_CISELNIK_STLPEC (CISELNIK_STLPEC_ID);
ALTER TABLE CUD_PLUGIN_STLPEC ADD CONSTRAINT CUD_PLUGIN_STLPEC_FK4 FOREIGN KEY (ID_PLUGIN_ALIAS) REFERENCES CUD_PLUGIN_ALIAS (PLUGIN_ALIAS_ID);
ALTER TABLE CUD_PLUGIN_KONTROLA ADD CONSTRAINT CUD_PLUGIN_KONTROLA_FK1 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_PLUGIN_KONTROLA_ROW ADD CONSTRAINT CUD_PLUGIN_KONTROLA_ROW_FK1 FOREIGN KEY (ID_PLUGIN_KONTROLA) REFERENCES CUD_PLUGIN_KONTROLA (PLUGIN_KONTROLA_ID);
ALTER TABLE CUD_PLUGIN_KONTROLA_ROW ADD CONSTRAINT CUD_PLUGIN_KONTROLA_ROW_FK2 FOREIGN KEY (ID_PLUGIN) REFERENCES CUD_PLUGIN (PLUGIN_ID);
ALTER TABLE CUD_UZAMKNUTIE ADD CONSTRAINT CUD_UZAMKNUTIE_FK1 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_OBJEKT_CISELNIK ADD CONSTRAINT CUD_OBJEKT_CISELNIK_FK1 FOREIGN KEY (ID_OBJEKT) REFERENCES CUD_OBJEKT (OBJEKT_ID);
ALTER TABLE CUD_OBJEKT_CISELNIK ADD CONSTRAINT CUD_OBJEKT_CISELNIK_FK2 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_OBJEKT_STLPEC ADD CONSTRAINT CUD_OBJEKT_STLPEC_FK1 FOREIGN KEY (ID_OBJEKT_CISELNIK) REFERENCES CUD_OBJEKT_CISELNIK (OBJEKT_CISELNIK_ID);
ALTER TABLE CUD_OBJEKT_STLPEC ADD CONSTRAINT CUD_OBJEKT_STLPEC_FK2 FOREIGN KEY (ID_CISELNIK_STLPEC) REFERENCES CUD_CISELNIK_STLPEC (CISELNIK_STLPEC_ID);
ALTER TABLE CUD_ODBERATEL ADD CONSTRAINT CUD_ODBERATEL_FK1 FOREIGN KEY (ID_HIST_DOPRAVCA) REFERENCES T_DOPRAVCA (HIST_ID);
ALTER TABLE CUD_ODBERATEL_OBJEKT ADD CONSTRAINT CUD_ODBERATEL_OBJEKT_FK1 FOREIGN KEY (ID_ODBERATEL) REFERENCES CUD_ODBERATEL (ODBERATEL_ID);
ALTER TABLE CUD_ODBERATEL_OBJEKT ADD CONSTRAINT CUD_ODBERATEL_OBJEKT_FK2 FOREIGN KEY (ID_OBJEKT) REFERENCES CUD_OBJEKT (OBJEKT_ID);
ALTER TABLE CUD_SEND ADD CONSTRAINT CUD_SEND_FK1 FOREIGN KEY (ID_ODBERATEL_OBJEKT) REFERENCES CUD_ODBERATEL_OBJEKT (ODBERATEL_OBJEKT_ID);
ALTER TABLE CUD_SEND_SUBOR ADD CONSTRAINT CUD_SEND_SUBOR_FK1 FOREIGN KEY (ID_SEND) REFERENCES CUD_SEND (SEND_ID);
ALTER TABLE CUD_SEND_SUBOR ADD CONSTRAINT CUD_SEND_SUBOR_FK2 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_IMPORT ADD CONSTRAINT CUD_IMPORT_FK1 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_IMPORT_PRILOHA ADD CONSTRAINT CUD_IMPORT_PRILOHA_FK1 FOREIGN KEY (ID_IMPORT) REFERENCES CUD_IMPORT (IMPORT_ID);
ALTER TABLE CUD_IMPORT_ZMENA ADD CONSTRAINT CUD_IMPORT_ZMENA_FK1 FOREIGN KEY (ID_IMPORT) REFERENCES CUD_IMPORT (IMPORT_ID);
ALTER TABLE CUD_IMPORT_ZMENA_STLPEC ADD CONSTRAINT CUD_IMPORT_ZMENA_STLPEC_FK1 FOREIGN KEY (ID_IMPORT) REFERENCES CUD_IMPORT (IMPORT_ID);
ALTER TABLE CUD_IMPORT_ZMENA_STLPEC ADD CONSTRAINT CUD_IMPORT_ZMENA_STLPEC_FK2 FOREIGN KEY (ID_IMPORT_ZMENA) REFERENCES CUD_IMPORT_ZMENA (IMPORT_ZMENA_ID);
ALTER TABLE CUD_IMPORT_ZMENA_STLPEC ADD CONSTRAINT CUD_IMPORT_ZMENA_STLPEC_FK3 FOREIGN KEY (ID_CISELNIK_STLPEC) REFERENCES CUD_CISELNIK_STLPEC (CISELNIK_STLPEC_ID);
ALTER TABLE CUD_IMPORT_ZMENA_STLPEC ADD CONSTRAINT CUD_IMPORT_ZMENA_STLPEC_FK4 FOREIGN KEY (ID_IMPORT_ZMENA_STLPEC_PRILOHA) REFERENCES CUD_IMPORT_ZMENA_STLPEC_PRILOHA (IMPORT_ZMENA_STLPEC_PRILOHA_ID);
ALTER TABLE CUD_IMPORT_ZMENA_STLPEC_PRILOHA ADD CONSTRAINT CUD_IMPORT_ZMENA_STLPEC_PRILOHA_FK1 FOREIGN KEY (ID_IMPORT) REFERENCES CUD_IMPORT (IMPORT_ID);
ALTER TABLE CUD_IMPORT_ZMENA_STLPEC_PRILOHA ADD CONSTRAINT CUD_IMPORT_ZMENA_STLPEC_PRILOHA_FK2 FOREIGN KEY (ID_IMPORT_ZMENA) REFERENCES CUD_IMPORT_ZMENA (IMPORT_ZMENA_ID);
ALTER TABLE CUD_IMPORT_MSG ADD CONSTRAINT CUD_IMPORT_MSG_FK1 FOREIGN KEY (ID_IMPORT) REFERENCES CUD_IMPORT (IMPORT_ID);
ALTER TABLE CUD_IMPORT_MSG ADD CONSTRAINT CUD_IMPORT_MSG_FK2 FOREIGN KEY (ID_IMPORT_ZMENA) REFERENCES CUD_IMPORT_ZMENA (IMPORT_ZMENA_ID);
ALTER TABLE CUD_ZMENA_ESKALACIA ADD CONSTRAINT CUD_ZMENA_ESKALACIA_FK1 FOREIGN KEY (ID_CISELNIK) REFERENCES CUD_CISELNIK (CISELNIK_ID);
ALTER TABLE CUD_PREKLAD ADD CONSTRAINT CUD_PREKLAD_FK1 FOREIGN KEY (ID_PREKLAD_JAZYK) REFERENCES CUD_PREKLAD_JAZYK (PREKLAD_JAZYK_ID);
ALTER TABLE CUD_PREKLAD ADD CONSTRAINT CUD_PREKLAD_FK2 FOREIGN KEY (ID_PREKLAD_STLPEC) REFERENCES CUD_PREKLAD_STLPEC (PREKLAD_STLPEC_ID);
ALTER TABLE CUD_PREKLAD_STLPEC ADD CONSTRAINT CUD_PREKLAD_STLPEC_FK1 FOREIGN KEY (ID_PREKLAD_TABULKA) REFERENCES CUD_PREKLAD_TABULKA (PREKLAD_TABULKA_ID);



CREATE SEQUENCE CUD_CISELNIK_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_CISELNIK_STLPEC_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_CISELNIK_GUI_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_CISELNIK_STLPEC_GUI_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_WF_DEF_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_ZMENA_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_ZMENA_STLPEC_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_WF_TODO_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_ZMENA_STAV_HIST_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_PLUGIN_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_PLUGIN_STLPEC_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_PLUGIN_KONTROLA_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_PLUGIN_KONTROLA_ROW_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_PREKLAD_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_UZAMKNUTIE_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_OBJEKT_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_OBJEKT_CISELNIK_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_OBJEKT_STLPEC_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_ODBERATEL_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_ODBERATEL_OBJEKT_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_SEND_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_SEND_SUBOR_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_IMPORT_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_IMPORT_PRILOHA_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_IMPORT_ZMENA_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_IMPORT_ZMENA_STLPEC_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_IMPORT_ZMENA_STLPEC_PRILOHA_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_IMPORT_MSG_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE CUD_ZMENA_ESKALACIA_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;

