CREATE TABLE SYS_CONFIG (
    CONFIG_ID               NUMBER(10),
    CONFIG_GROUP            NVARCHAR2(30),
    CONFIG_ITEM             NVARCHAR2(100),
    VALUESTR                NVARCHAR2(2000),
    ID_TRANSAKCIA_ZAPISANE  NUMBER(20),
    ID_TRANSAKCIA_ZRUSENE   NUMBER(20),
    CONSTRAINT SYS_CONFIG_PK PRIMARY KEY (CONFIG_ID)
);

CREATE TABLE SYS_PROCESS (
    PROCESS_ID    NUMBER(10) NOT NULL,
    PROCESS_NAME  VARCHAR2(50) NOT NULL,
    PROC_CLASS    VARCHAR2(255) NOT NULL,
    PROCESS_AT    VARCHAR2(100),
    MODUL         VARCHAR2(50),
    INACTIVE_TIME NUMBER(10),
    DESTROY_TIME  NUMBER(10),
    PROCESS_DESC  VARCHAR2(2000),
    AUTOSTART     VARCHAR2(50),
    LOG_NAME      VARCHAR2(500),
    NONSTOP       VARCHAR2(1)
);

CREATE TABLE SYS_PROCESS_PARAM (
    PROC_ID    VARCHAR2(50) NOT NULL,
    PROC_PARAM VARCHAR2(50) NOT NULL,
    PROC_VALUE VARCHAR2(255) NOT NULL
);

CREATE TABLE SYS_TRANSAKCIA (
    TRANSAKCIA_ID     NUMBER(20) NOT NULL,
    ID_UCET           NUMBER(10) NOT NULL,
    ZACIATOK          TIMESTAMP(6) NOT NULL,
    KONIEC            TIMESTAMP(6),
    STAV_TRANSAKCIE   NVARCHAR2(1) NOT NULL,
    ID_OPRAVNENIE     NUMBER(10),
    CONSTRAINT SYS_TRANSAKCIA_PK PRIMARY KEY (TRANSAKCIA_ID)
);

CREATE TABLE SYS_USER_STAT (
    USER_STAT_ID    NUMBER(10) NOT NULL,
    USER_IP         NVARCHAR2(100) NOT NULL,
    USER_HOST       NVARCHAR2(200) NOT NULL,
    USER_ACCOUNT    NVARCHAR2(100) NOT NULL,
    USER_DATE       TIMESTAMP(6) NOT NULL,
    USER_X_FOR      NVARCHAR2(200),
    USER_X_SERVER   NVARCHAR2(200),
    USER_X_HOST     NVARCHAR2(200),
    CONSTRAINT SYS_USER_STAT_PK PRIMARY KEY (USER_STAT_ID)
);

CREATE TABLE comm_log (
  log_id          NUMBER(10) NOT NULL,
  ucet            NVARCHAR2(50),
  app             NVARCHAR2(20),
  soap_action     NVARCHAR2(50),
  request_dt      TIMESTAMP(6),
  response_dt     TIMESTAMP(6),
  dist_test       NVARCHAR2(1),
  dist_dev        NVARCHAR2(1),
  stav            NVARCHAR2(1),
  poznamka        NVARCHAR2(2000),
  msg_id          NUMBER(16),
  request         CLOB,
  response        CLOB,
  vlk_id          NVARCHAR2(18),
  trvanie         NVARCHAR2(10),
  ws              NVARCHAR2(100),
  CONSTRAINT comm_log_pk PRIMARY KEY (log_id)
);



CREATE SEQUENCE SYS_TRANSAKCIA_SEQ INCREMENT BY 1 START WITH 100 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SYS_USER_STAT_SEQ INCREMENT BY 1 START WITH 100 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE COMM_LOG_SEQ INCREMENT BY 1 START WITH 100 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE NOCACHE NOORDER;

INSERT INTO SYS_TRANSAKCIA (TRANSAKCIA_ID, ID_UCET, ZACIATOK, KONIEC, STAV_TRANSAKCIE, ID_OPRAVNENIE) VALUES (SYS_TRANSAKCIA_SEQ.nextval, 1, to_date('2010 05 06', 'YYYY MM DD'), to_date('2010 05 06', 'YYYY MM DD'), 'U', 99);

Insert into SYS_CONFIG (CONFIG_ID,CONFIG_GROUP,CONFIG_ITEM,VALUESTR,ID_TRANSAKCIA_ZAPISANE,ID_TRANSAKCIA_ZRUSENE) values ('2','framework','auth.wsdl','http://wmneo/auth/AuthModWS?wsdl','1',null);
Insert into SYS_CONFIG (CONFIG_ID,CONFIG_GROUP,CONFIG_ITEM,VALUESTR,ID_TRANSAKCIA_ZAPISANE,ID_TRANSAKCIA_ZRUSENE) values ('3','framework','notif.wsdl','http://wmneo/pis_adm/NotifWS?wsdl','1',null);
Insert into SYS_CONFIG (CONFIG_ID,CONFIG_GROUP,CONFIG_ITEM,VALUESTR,ID_TRANSAKCIA_ZAPISANE,ID_TRANSAKCIA_ZRUSENE) values ('200','kmd','error.mail.body',null,'1',null);
Insert into SYS_CONFIG (CONFIG_ID,CONFIG_GROUP,CONFIG_ITEM,VALUESTR,ID_TRANSAKCIA_ZAPISANE,ID_TRANSAKCIA_ZRUSENE) values ('201','kmd','error.mail.list','zember@ditec.sk;zember@ditec.sk; zember@ditec.sk','1',null);
commit;
