DROP SEQUENCE COMM_LOG_SEQ;
DROP SEQUENCE SYS_TRANSAKCIA_SEQ;
DROP SEQUENCE SYS_USER_STAT_SEQ;

DROP TABLE COMM_LOG cascade constraints;
DROP TABLE SYS_CONFIG cascade constraints;
DROP TABLE SYS_PROCESS cascade constraints;
DROP TABLE SYS_PROCESS_PARAM cascade constraints;
DROP TABLE SYS_TRANSAKCIA cascade constraints;
DROP TABLE SYS_USER_STAT cascade constraints;

PURGE TABLE COMM_LOG;
PURGE TABLE SYS_CONFIG;
PURGE TABLE SYS_PROCESS;
PURGE TABLE SYS_PROCESS_PARAM;
PURGE TABLE SYS_TRANSAKCIA;
PURGE TABLE SYS_USER_STAT;
